:feelpp: Feel++
= feelpp_remotedata(1)
Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: feelpp_remotedata
:man-linkstyle: pass:[blue R < >]


== NAME

{manmanual} - manage remotedata for {feelpp}


== SYNOPSIS

{manmanual} is a simple application which can download data, upload data and print remote data listing.


== DESCRIPTION



== OPTIONS

=== Options

{manmanual} requires some options.

.Table of command-line {manmanual} options
|===                                                                                                                                                                              
| Name | Description | Default value

| upload | specify the remote server and the location of uploaded files on remote server |                                                                                              
| download | specify remote data to download |
| data a|

* with upload mode : datas path (file or dir) to upload,
* with download mode : the path of downloaded datas
|
| contents | specify data contents to print in the terminal |
|===  

== EXAMPLES

=== Download mode

* Download file from an url

[source,shell]
----
feelpp_remotedata --download https://raw.githubusercontent.com/feelpp/feelpp/develop/README.adoc
----

* Download file/folder from Github

[source,shell]
----
feelpp_remotedata --download "github:{repo:feelpp,path:README.adoc}"
----

* Download file/folder from Girder

[source,shell]
----
feelpp_remotedata --download "girder:{file:5b1f8707b0e9570499f66bd0}"
----

* Download into a specific directory

[source,shell]
----
feelpp_remotedata --download "girder:{file:5b1f8707b0e9570499f66bd0}" --data $HOME/mydir
----

=== Upload mode

* Upload file/folder on Girder

[source,shell]
----
feelpp_remotedata --download "girder:{folder:<a folder id>}" --data $HOME/mydata
----


=== Contents mode

* With Girder

[source,shell]
----
feelpp_remotedata --contents "girder:{folder:5ac72871b0e9574027047894}"
feelpp_remotedata --contents "girder:{file:5b1f8707b0e9570499f66bd0}"
feelpp_remotedata --contents "girder:{folder:[5ac72871b0e9574027047894,5ad4b75db0e9574027047d70],file:5b1f8707b0e9570499f66bd0}"
----




== COPYING

Copyright \(C) 2017 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

