:feelpp: Feel++
= feelpp_crb_onlinerun(1)
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>; Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: feelpp_crb_onlinerun
:man-linkstyle: pass:[blue R < >]


== NAME

{manmanual} - a tool to execute {feelpp} CRB online codes


== SYNOPSIS

{manmanual} is a simple application which can load a {feelpp} CRB online code, generate a parameter sampling and execute the online code for each point of the parameter sampling.
{manmanual} can generate the finite element representation for visualisation purposes in e.g. Paraview.


== DESCRIPTION



== OPTIONS

=== Options

{manmanual} requires some options.

.Table of command-line {manmanual} options
|===                                                                                                                                                                              
| Name | Description | Default value

| plugin.dir | directory where the plugin(online library) are stored | <{feelpp} install prefix>/lib
| crbmodel.name | name of the online code | N/A
| crbmodel.db.id | id of crbmodel (called by the `name` arg) registered | N/A
| crbmodel.db.last | name of the online code (use last created(=1) or modified(=2))  | 2
| crbmodel.db.root_directory | root directory of the CRB DB | `${repository}/crbdb`
|===

Some CRB DB are stored on GitHub at link:http://www.github.com/feelpp/crbdb[].

== EXAMPLES

Evaluate output from one parameter::
----
feelpp_mor_onlinerun --crbmodel.name heat3d --parameter 110 140 124 193.3 34000 29300 62000 0.23
----

Evaluate outputs from a sampling::
----
feelpp_mor_onlinerun --crbmodel.name heat3d --sampling.size=64
----

Evaluate outputs and export finite element solution for each parameter::
----
feelpp_mor_onlinerun --crbmodel.name heat3d --sampling.size=64 --crb.load-elements-database=1
----



== SEE ALSO

*{feelpp} Book:* http://book.feelpp.org

== COPYING

Copyright \(C) 2017 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

