= Model order reduction Offline / Online applications

For this example, we use the case `thermalfin_2d`.

== Offline basis generation

Build the 2d model :

[source,bash]
----
mpiexec -n 1 feelpp_mor_toolbox_heat_offline --config-file ./src/feelpp/mor/apps/thermalfin/thermal-fin_2d.cfg
----

Some options, that can be set un the cfg file :

* `toomboxmor.name`: name of the basis generated, this name need to be used in the online application.
* `crb.output-index`: index of the output ised to generate the basis, `0` for compliant case compliant, `1` for the first in json (in alphabetical order), etc.

Example of output: error on output for different size of basis.

[source,bash]
----
stats on field over size of RB
    N                      min                      max                     mean                    stdev
    1             4.099061e-02             4.150085e-01             1.298491e-01             1.322375e-02
    2             1.708096e-02             3.864504e-01             1.124733e-01             1.210746e-02
    3             1.297177e-02             2.232052e-01             6.922406e-02             4.515022e-03
    4             1.281115e-02             1.883887e-01             5.541298e-02             3.044681e-03
    5             7.997071e-03             5.581980e-02             2.910149e-02             2.009136e-04
    6             8.872246e-03             6.055751e-02             2.554539e-02             2.943605e-04
    7             9.369505e-03             6.035874e-02             2.488778e-02             2.998957e-04
    8             7.451146e-03             5.739285e-02             2.172427e-02             2.448318e-04
    9             5.566216e-03             4.419973e-02             1.566300e-02             1.331442e-04
   10             1.947147e-03             2.454690e-02             1.046096e-02             3.545864e-05
stats on output o1 over size of RB
    N                      min                      max                     mean                    stdev
    1             3.962279e-03             5.272746e-01             1.477502e-01             2.682294e-02
    2             1.758302e-02             4.951480e-01             1.526740e-01             2.050461e-02
    3             1.153670e-02             2.338150e-01             7.548131e-02             5.111251e-03
    4             1.461290e-02             2.243271e-01             7.726441e-02             4.410684e-03
    5             7.290856e-03             5.174318e-02             3.095027e-02             2.453592e-04
    6             3.098532e-03             5.769210e-02             2.723897e-02             3.276623e-04
    7             6.068928e-03             6.094063e-02             2.811905e-02             3.199083e-04
    8             4.956817e-03             3.883156e-02             1.960122e-02             1.509491e-04
    9             7.964150e-05             1.242065e-02             4.560343e-03             1.574464e-05
   10             3.104699e-04             5.670884e-03             2.544157e-03             2.496097e-06
----



== Online run of the model

[source,bash]
----
feelpp_mor_onlinerun --crbmodel.name toolbox_heat_thermal-fin_2d --plugin.dir /usr/lib/x86_64-linux-gnu
----

Some options:

* `crbmodel.name`: name of the model to run, used in the offline generation
* `sampling.size`: number of sampling points
* `--rb-dim`: reduced basis dimension used (`-1` use the max dim)


Example of output: run on the case `thermal_fin_2d` with the reduced basis :

[source,bash]
----
+--------------+--------------+--------------+--------------+--------------+--------------+
| Bi           | k_1          | k_2          | k_3          | k_4          | output       |
+==============+==============+==============+==============+==============+==============+
| 2.777267e-01 | 3.653380e-01 | 9.054149e+00 | 8.340662e+00 | 2.787092e+00 | 1.558875e-01 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 4.402479e-01 | 7.196269e+00 | 2.217984e+00 | 9.677249e+00 | 5.190842e+00 | 9.663407e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 7.282815e-01 | 6.122700e+00 | 6.897754e+00 | 2.061301e+00 | 7.430149e+00 | 6.898085e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 7.845586e-01 | 9.978705e+00 | 5.678513e+00 | 3.560614e-01 | 6.814422e+00 | 6.454170e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 2.330269e-01 | 4.138574e+00 | 2.823535e+00 | 5.808864e-01 | 2.270569e-01 | 1.603281e-01 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 9.460945e-01 | 4.208168e+00 | 5.472882e+00 | 6.295506e-01 | 5.444294e+00 | 5.959327e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 2.075473e-01 | 7.852283e+00 | 4.390368e+00 | 3.021325e+00 | 6.192945e+00 | 1.616768e-01 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 8.396724e-01 | 8.618846e+00 | 8.996676e+00 | 6.147079e-01 | 8.296094e+00 | 6.177158e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 6.194166e-01 | 3.331893e+00 | 7.826606e+00 | 3.091920e+00 | 8.729408e+00 | 7.931198e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
| 9.603544e-01 | 9.375056e-01 | 8.750702e+00 | 5.282057e+00 | 9.418556e+00 | 6.287971e-02 |
+--------------+--------------+--------------+--------------+--------------+--------------+
----
