# -*- Mode: python -*-
###  SConscript --- core lib

#  Author(s): Christophe Prud'homme <christophe.prudhomme@epfl.ch>
#       Date: 2006-05-25
#
#  Copyright (C) 2006 EPFL
#
# Distributed under the GPL(GNU Public License):
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#

Import('env')

SOURCES=['vectorpetsc.cpp',
         'vectorepetra.cpp',
         'solverumfpack.cpp',
         'solverlinearpetsc.cpp',
         'solvernonlinearpetsc.cpp',
         'solvereigen.cpp',
         'solvereigenslepc.cpp',
         'backendgmm.cpp',
         'backend_adaptive_reuse_pc.cpp',
         'backendpetsc.cpp',
         ]

if env['static']:
    env.StaticLibrary('lifealg', source=SOURCES)

if env['shared']:
    env.SharedLibrary('lifealg', source=SOURCES,LIBS=['lifecore',env['umfpack_libs']],LIBPATH=['../lifecore'])

