# -*- Mode: python -*-
###  SConscript ---

#  Author(s): Christophe Prud'homme <christophe.prudhomme@epfl.ch>
#       Date: 2006-05-25
#
#  Copyright (C) 2006 EPFL
#
# Distributed under the GPL(GNU Public License):
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#
from version import *
Import('env')
copyenv=env.Copy()

LifeBuildId = LifeGetBuildId( env )

if env['nobuildid']:
    copyenv.Replace(CPPDEFINES=['PACKAGE=\"'+LifeBuildId['package']+'\"',
                                'LIFE_PREFIX=\"'+env['prefix']+'\"',
                                'LIFE_DATADIR=\"'+env['prefix']+'/share/'+LifeBuildId['package']+'\"',
                                'LIFE_BUILDID='+'0LL',
                                'LIFE_REVISION='+'0',
                                'LIFE_VERSION='+'0LL',
                                'LIFE_VERSION_MAJOR='+'0',
                                'LIFE_VERSION_MINOR='+'0',
                                'LIFE_VERSION_MICRO='+'0',
                                'LIFE_VERSION_STRING=\"0.0.0\"'
                                ])
else:
    copyenv.Replace(CPPDEFINES=['PACKAGE=\"'+LifeBuildId['package']+'\"',
                                'LIFE_PREFIX=\"'+env['prefix']+'\"',
                                'LIFE_DATADIR=\"'+env['prefix']+'/share/'+LifeBuildId['package']+'\"',
                                'LIFE_BUILDID='+str(LifeBuildId['build_id'])+'LL',
                                'LIFE_REVISION='+str(LifeBuildId['revision']),
                                'LIFE_VERSION='+str(LifeBuildId['version'])+'LL',
                                'LIFE_VERSION_MAJOR='+str(LifeBuildId['version_major']),
                                'LIFE_VERSION_MINOR='+str(LifeBuildId['version_minor']),
                                'LIFE_VERSION_MICRO='+str(LifeBuildId['version_micro']),
                                'LIFE_VERSION_STRING=\"'+LifeBuildId['version_string']+'\"'
                                ])


copyenv.StaticLibrary('lifeinfo', source='lifecore/info.cpp')

lifepc="""
prefix=""" + str(env['prefix']) + """
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Life
Description: A finite and spectral element library in 1D, 2D and 3D
Version: """ + make_version(env) + """
URL: http://www.lifev.org
Libs: -L${libdir}"""+ make_str(env['LIBS'], '-l') + """
Libs.private: -lm
Cflags: """ + make_str(env['CPPPATH'], '-I')

FILE = open('life.pc',"w")
FILE.writelines(lifepc)
FILE.close();
