# -*- Mode: python -*-
###  SConscript --- core lib

#  Author(s): Christophe Prud'homme <christophe.prudhomme@epfl.ch>
#       Date: 2006-05-25
#
#  Copyright (C) 2006 EPFL
#
# Distributed under the GPL(GNU Public License):
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#

Import('env')

SOURCES=['about.cpp',
         'debug.cpp',
         'typeinfo.cpp',
         'smartassert.cpp',

         'application.cpp',
         'applicationserial.cpp',
         'applicationmpi.cpp',
         'applicationpetsc.cpp',
         'applicationepetra.cpp',

         'pslogger.cpp',
         ]

if env['static']:
    env.StaticLibrary('lifecore', source=SOURCES,LIBS='lifeinfo',LIBPATH='..')

if env['shared']:
    env.SharedLibrary('lifecore',
                      source=SOURCES,
                      LIBS=['lifeinfo',
                            'boost_program_options',
                            'boost_filesystem',
                            'boost_date_time',
                            'qd',
                            env['LIBS']
                            ],
                      LIBPATH=['.', '..'])

