[[change-log]]
= Change Log


[[v0.104.0-2018-04-22]]
== https://github.com/feelpp/feelpp/tree/v0.104.0[v0.104.0] (2018-04-22)


https://github.com/feelpp/feelpp/compare/v0.103.2...v0.104.0[Full
Changelog]

*Closed issues:*

* make quickstart checker less verbose
https://github.com/feelpp/feelpp/issues/1145[#1145]
* update toolbox examples
https://github.com/feelpp/feelpp/issues/1144[#1144]
* Missing link on Feel++ book on how to Compile Boost C++ library
https://github.com/feelpp/feelpp/issues/1141[#1141]
* failed to compile feelpp/omc
https://github.com/feelpp/feelpp/issues/1138[#1138]
* SER should assemble the model after each EIM offline step
https://github.com/feelpp/feelpp/issues/1130[#1130]
* How to save several objects using export-scene-macro.py
https://github.com/feelpp/feelpp/issues/1129[#1129]
* Support changing json files from command line
https://github.com/feelpp/feelpp/issues/1122[#1122]
* CRB load the database in the constructor
https://github.com/feelpp/feelpp/issues/1120[#1120]
* Add feelpp_fmi_runfmu
https://github.com/feelpp/feelpp/issues/1119[#1119]
* Add test for FMU model
https://github.com/feelpp/feelpp/issues/1118[#1118]
* Document Feel++ Tosca Files V1
https://github.com/feelpp/feelpp/issues/1112[#1112]
* Framework OpenModelica Feel++
https://github.com/feelpp/feelpp/issues/1109[#1109]
* latest toolboxes FTBS on Debian/Testing
https://github.com/feelpp/feelpp/issues/1107[#1107]
* Check fail in DataMap constructor for sequential build in //
https://github.com/feelpp/feelpp/issues/1106[#1106]
* Question on CRB https://github.com/feelpp/feelpp/issues/1101[#1101]
* Wrong results for unsteady MixedElasticity solved with static
condensation in parallel
https://github.com/feelpp/feelpp/issues/1098[#1098]
* Wrong results for unsteady MixedPoisson with static condensation
solved in parallel https://github.com/feelpp/feelpp/issues/1097[#1097]
* latest dev version FTBS on Debian/Testing: gflags error
https://github.com/feelpp/feelpp/issues/1095[#1095]
* Problem with using python3 on atlas
https://github.com/feelpp/feelpp/issues/1086[#1086]
* OpenModelica cmake detection
https://github.com/feelpp/feelpp/issues/1085[#1085]
* Instantiate Mesh<> https://github.com/feelpp/feelpp/issues/1084[#1084]
* FTBS in feature/rb-uid-db
https://github.com/feelpp/feelpp/issues/1077[#1077]
* latest feelpp FTBS during cmake stage
https://github.com/feelpp/feelpp/issues/1076[#1076]
* Singularity images fail to build
https://github.com/feelpp/feelpp/issues/1075[#1075]
* Change existing code to deal with function space on range
https://github.com/feelpp/feelpp/issues/1074[#1074]
* FTBS Feature/Deim https://github.com/feelpp/feelpp/issues/1073[#1073]
* feelpp_test_productspaces fails with petsc error
https://github.com/feelpp/feelpp/issues/1072[#1072]
* Support PETSc 3.8 https://github.com/feelpp/feelpp/issues/1068[#1068]
* feelpp_mesh_partitioner does not work for med meshes
https://github.com/feelpp/feelpp/issues/1063[#1063]
* ModelCrbBase does not have any output method
https://github.com/feelpp/feelpp/issues/1062[#1062]
* Deadlock in DEIM using linftyNorm for vectors
https://github.com/feelpp/feelpp/issues/1058[#1058]
* Allow to have multiple physics by material
https://github.com/feelpp/feelpp/issues/1052[#1052]
* DEIM : add options to store Tensors during greedy
https://github.com/feelpp/feelpp/issues/1048[#1048]
* DEIM : add option to store solutions on disk (NL problems)
https://github.com/feelpp/feelpp/issues/1047[#1047]
* Bug with expansion https://github.com/feelpp/feelpp/issues/1041[#1041]
* Problem with unsteady MixedElasticity in the new version (with SC)
https://github.com/feelpp/feelpp/issues/1038[#1038]
* Update submodule via cmake only after a clone.
https://github.com/feelpp/feelpp/issues/1036[#1036]
* Allow comments in feelpp_add_application TESTS
https://github.com/feelpp/feelpp/issues/1035[#1035]
* Checker should say whether the results have been really checked or not
https://github.com/feelpp/feelpp/issues/1034[#1034]
* Add many testcases for a given application
https://github.com/feelpp/feelpp/issues/1033[#1033]
* Avoid to reload on disk the cfg files
https://github.com/feelpp/feelpp/issues/1032[#1032]
* GMSH install fails due to change of versioning system
https://github.com/feelpp/feelpp/issues/1031[#1031]
* Factorize cmake submodule clone/update
https://github.com/feelpp/feelpp/issues/1030[#1030]
* Add Checker testcase for quickstart Stokes
https://github.com/feelpp/feelpp/issues/1029[#1029]
* Fix exporter error for MixedPoisson with P>=3
https://github.com/feelpp/feelpp/issues/1027[#1027]
* Add helper alias class for Eigen data structures
https://github.com/feelpp/feelpp/issues/1023[#1023]
* Add polynomial traits polymomial_order and is_linear_polynomial
https://github.com/feelpp/feelpp/issues/1022[#1022]
* update and improve compile time context
https://github.com/feelpp/feelpp/issues/1021[#1021]
* add casting function for class enum
https://github.com/feelpp/feelpp/issues/1020[#1020]
* Toolboxes with Newton solver are broken
https://github.com/feelpp/feelpp/issues/1019[#1019]
* NLopt is not working anymore
https://github.com/feelpp/feelpp/issues/1018[#1018]
* Problems in fixed point for CRB
https://github.com/feelpp/feelpp/issues/1016[#1016]
* Bump up version of Eigen3
https://github.com/feelpp/feelpp/issues/1013[#1013]
* DEIM: matrix B non invertible
https://github.com/feelpp/feelpp/issues/1012[#1012]
* support leaks sanitizer suppression file in Debug mode
https://github.com/feelpp/feelpp/issues/1008[#1008]
* fix address issues and memory leaks
https://github.com/feelpp/feelpp/issues/1007[#1007]
* Refactor Factory to use std::unique_ptr
https://github.com/feelpp/feelpp/issues/1006[#1006]
* Memory leak in MatrixPetscMPI
https://github.com/feelpp/feelpp/issues/1005[#1005]
* Refactor Gmsh factory to avoid leaks
https://github.com/feelpp/feelpp/issues/1004[#1004]
* Use Address Sanitizer in Debug Mode
https://github.com/feelpp/feelpp/issues/1003[#1003]
* crash in block matrix zero stencil
https://github.com/feelpp/feelpp/issues/1002[#1002]
* support static condensation at runtime
https://github.com/feelpp/feelpp/issues/999[#999]
* Convergence tests broken in benchmarks/hdg
https://github.com/feelpp/feelpp/issues/998[#998]
* make MatrixSparse and Vector support enable_shared__from_this
https://github.com/feelpp/feelpp/issues/996[#996]
* make VectorBlock<> a Vector<>
https://github.com/feelpp/feelpp/issues/995[#995]
* Add Material info into boundary conditions
https://github.com/feelpp/feelpp/issues/992[#992]
* Crash of thermoelectric CRB online application
https://github.com/feelpp/feelpp/issues/991[#991]
* invalid eim expression in CRB thermoelectric application
https://github.com/feelpp/feelpp/issues/990[#990]
* decay numerical type in cst/cst_ref
https://github.com/feelpp/feelpp/issues/989[#989]
* install HDG toolbox applications
https://github.com/feelpp/feelpp/issues/987[#987]
* Implement Checker class to verify numerical results from result
database https://github.com/feelpp/feelpp/issues/986[#986]
* provide Mesh trait such as is_mesh and is_mesh_v
https://github.com/feelpp/feelpp/issues/985[#985]
* add free functions topodim() realdim() on meshes
https://github.com/feelpp/feelpp/issues/984[#984]
* add order() member function to base class FiniteElement
https://github.com/feelpp/feelpp/issues/983[#983]
* add support for polyfit : least square and interpolation
https://github.com/feelpp/feelpp/issues/982[#982]
* add support exp, log, log10 on std::vector
https://github.com/feelpp/feelpp/issues/981[#981]
* Enhance crbonlinerun interface
https://github.com/feelpp/feelpp/issues/978[#978]
* Exporter in a `for` loop
https://github.com/feelpp/feelpp/issues/976[#976]
* Move Singularity builds to a specific buildkite pipeline
https://github.com/feelpp/feelpp/issues/975[#975]
* Effective online phase for DEIM
https://github.com/feelpp/feelpp/issues/974[#974]
* Submesh creation : conservation of elements ID
https://github.com/feelpp/feelpp/issues/973[#973]
* Support hdf5 format to save PETSc vectors
https://github.com/feelpp/feelpp/issues/972[#972]
* How to set entries of algebraic representation in linear forms
https://github.com/feelpp/feelpp/issues/971[#971]
* Provide random integer generator between min and max
https://github.com/feelpp/feelpp/issues/970[#970]
* ship headers for mesh adaptation
https://github.com/feelpp/feelpp/issues/969[#969]
* build mesh from list of elements
https://github.com/feelpp/feelpp/issues/968[#968]
* Add more information in Feel++Config
https://github.com/feelpp/feelpp/issues/967[#967]
* Enable testsuite as separate Feel++ project
https://github.com/feelpp/feelpp/issues/966[#966]
* build and deploy testsuite using buildkite and docker
https://github.com/feelpp/feelpp/issues/965[#965]
* Singularity build fails
https://github.com/feelpp/feelpp/issues/964[#964]
* Generate a unique id in parallel
https://github.com/feelpp/feelpp/issues/963[#963]
* Mesostra Feel++ support
https://github.com/feelpp/feelpp/issues/962[#962]
* Issue with fftw using mpirun on a mesostra compute node
https://github.com/feelpp/feelpp/issues/960[#960]
* Add support for llvm >= 3.9 and clang using gcc6 at unistra
https://github.com/feelpp/feelpp/issues/958[#958]
* Problem with EIM in non linear thermoelectric app
https://github.com/feelpp/feelpp/issues/957[#957]
* Ipopt support broken https://github.com/feelpp/feelpp/issues/956[#956]
* Feel++ contrib system does not scale
https://github.com/feelpp/feelpp/issues/955[#955]
* Support mesh partitioner by markers
https://github.com/feelpp/feelpp/issues/954[#954]
* add support the mongo c++ driver
https://github.com/feelpp/feelpp/issues/953[#953]
* Fix expansion calls https://github.com/feelpp/feelpp/issues/951[#951]
* cleanup warnings in eim and crb about missing override
https://github.com/feelpp/feelpp/issues/950[#950]
* support load/modify last CRB DB online and offline
https://github.com/feelpp/feelpp/issues/946[#946]
* Compilation error with Lambda expression and matrix multiplication
https://github.com/feelpp/feelpp/issues/944[#944]
* Add MongoDB support https://github.com/feelpp/feelpp/issues/941[#941]
* Add feelpp version in docker tags
https://github.com/feelpp/feelpp/issues/938[#938]
* FTBS in Feel++ Toolboxes with ExpressionStringAtMarker
https://github.com/feelpp/feelpp/issues/937[#937]
* make output too verbose (DL_OPEN message)
https://github.com/feelpp/feelpp/issues/936[#936]
* Boost::DLL no available on Debian/Jessie with Boost 1.55
https://github.com/feelpp/feelpp/issues/934[#934]
* Update nlopt interface
https://github.com/feelpp/feelpp/issues/931[#931]
* implement unique ids for CRB DB
https://github.com/feelpp/feelpp/issues/929[#929]
* refactor options for crb,eim scm and pod
https://github.com/feelpp/feelpp/issues/928[#928]
* Support crb_add_library
https://github.com/feelpp/feelpp/issues/927[#927]
* Issue with installation information in info and cmake
https://github.com/feelpp/feelpp/issues/926[#926]
* Add support for DEIM https://github.com/feelpp/feelpp/issues/925[#925]
* toolbox:te https://github.com/feelpp/feelpp/issues/922[#922]
* Support plugin system for CRB application
https://github.com/feelpp/feelpp/issues/913[#913]
* Add support MatrixCondensed and VectorCondensed
https://github.com/feelpp/feelpp/issues/909[#909]
* Add support for cmake flags in dockerization scripts
https://github.com/feelpp/feelpp/issues/907[#907]
* Add FMI support https://github.com/feelpp/feelpp/issues/904[#904]
* Run a minimal exemple in a docker
https://github.com/feelpp/feelpp/issues/902[#902]
* Refactor SER algorithm
https://github.com/feelpp/feelpp/issues/876[#876]
* HDG : support static condensation with dynamic product space
https://github.com/feelpp/feelpp/issues/867[#867]
* Support smart storage/replay of offline eim/deim data
https://github.com/feelpp/feelpp/issues/866[#866]
* Provide static condensation framework
https://github.com/feelpp/feelpp/issues/811[#811]
* Error with exporter.element-spaces=P1 option
https://github.com/feelpp/feelpp/issues/781[#781]
* Make ParameterSpace dynamic
https://github.com/feelpp/feelpp/issues/780[#780]
* Support divergence of matrix fields
https://github.com/feelpp/feelpp/issues/730[#730]
* fast marching crashes in periodic
https://github.com/feelpp/feelpp/issues/681[#681]
* Support MPI synchronization in Vector
https://github.com/feelpp/feelpp/issues/671[#671]
* Ginac expression in myexpression.cpp
https://github.com/feelpp/feelpp/issues/584[#584]
* Information about Resolution/Preconditioner
https://github.com/feelpp/feelpp/issues/576[#576]
* Problem with projection of a component of a product space element
https://github.com/feelpp/feelpp/issues/465[#465]
* CRB construction on a model using EIM in //
https://github.com/feelpp/feelpp/issues/344[#344]
* Use Ginac expressions in CRB framework
https://github.com/feelpp/feelpp/issues/317[#317]
* Support for PETSc fieldsplit preconditioners
https://github.com/feelpp/feelpp/issues/231[#231]
* feelpp_P3P2P3_heatns_natural_convection_cavity_3d_crb
https://github.com/feelpp/feelpp/issues/153[#153]
* error when load an element_type from a database
https://github.com/feelpp/feelpp/issues/40[#40]
* Update CRB framework so that we can infer models properties
https://github.com/feelpp/feelpp/issues/14[#14]

*Merged pull requests:*

* Feature/deim https://github.com/feelpp/feelpp/pull/1135[#1135]
(https://github.com/jbwahl[jbwahl])
* Feature/omc https://github.com/feelpp/feelpp/pull/1134[#1134]
(https://github.com/jbwahl[jbwahl])
* Feature/toolboxes refactoring
https://github.com/feelpp/feelpp/pull/1128[#1128]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/crbblock https://github.com/feelpp/feelpp/pull/1127[#1127]
(https://github.com/romainhild[romainhild])
* Fix Stokes/Stationary conflict
https://github.com/feelpp/feelpp/pull/1126[#1126]
(https://github.com/metivett[metivett])
* Feature/bdf reverse https://github.com/feelpp/feelpp/pull/1123[#1123]
(https://github.com/gdolle[gdolle])
* Feature/ls refactoring
https://github.com/feelpp/feelpp/pull/1113[#1113]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/doftable mpi https://github.com/feelpp/feelpp/pull/1102[#1102]
(https://github.com/vincentchabannes[vincentchabannes])
* add modeloutput class to manage crb output
https://github.com/feelpp/feelpp/pull/1099[#1099]
(https://github.com/romainhild[romainhild])
* Feature/cmake toolboxes detection
https://github.com/feelpp/feelpp/pull/1094[#1094]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/cleanup https://github.com/feelpp/feelpp/pull/1092[#1092]
(https://github.com/prudhomm[prudhomm])
* Add openmodelica header directory #1085
https://github.com/feelpp/feelpp/pull/1090[#1090]
(https://github.com/jbwahl[jbwahl])
* Fix1063 https://github.com/feelpp/feelpp/pull/1089[#1089]
(https://github.com/Trophime[Trophime])
* Feature/crb rbspace https://github.com/feelpp/feelpp/pull/1083[#1083]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/crb uid db https://github.com/feelpp/feelpp/pull/1082[#1082]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/deim https://github.com/feelpp/feelpp/pull/1081[#1081]
(https://github.com/jbwahl[jbwahl])
* Feature/issue1052 https://github.com/feelpp/feelpp/pull/1053[#1053]
(https://github.com/romainhild[romainhild])
* Feature/crb plugin https://github.com/feelpp/feelpp/pull/1050[#1050]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/checker https://github.com/feelpp/feelpp/pull/1046[#1046]
(https://github.com/prudhomm[prudhomm])
* Fix py3k PYTHON_VERSION detection
https://github.com/feelpp/feelpp/pull/1043[#1043]
(https://github.com/jschueller[jschueller])
* fix issue #1041 https://github.com/feelpp/feelpp/pull/1042[#1042]
(https://github.com/romainhild[romainhild])
* fix issue #1016 https://github.com/feelpp/feelpp/pull/1040[#1040]
(https://github.com/romainhild[romainhild])
* Feature/cmake contrib clean
https://github.com/feelpp/feelpp/pull/1017[#1017]
(https://github.com/gdolle[gdolle])
* Feature/functionspace on range
https://github.com/feelpp/feelpp/pull/997[#997]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/mesh memredux https://github.com/feelpp/feelpp/pull/980[#980]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/rb-load https://github.com/feelpp/feelpp/pull/952[#952]
(https://github.com/prudhomm[prudhomm])
* Fix ftbs manual https://github.com/feelpp/feelpp/pull/933[#933]
(https://github.com/Trophime[Trophime])
* Feature/bs rb2 https://github.com/feelpp/feelpp/pull/932[#932]
(https://github.com/romainhild[romainhild])
* Working on SER : https://github.com/feelpp/feelpp/pull/880[#880]
(https://github.com/jbwahl[jbwahl])
* deim https://github.com/feelpp/feelpp/pull/849[#849]
(https://github.com/prudhomm[prudhomm])
* Crb saddle point https://github.com/feelpp/feelpp/pull/845[#845]
(https://github.com/prudhomm[prudhomm])
* Feature/hdg sc https://github.com/feelpp/feelpp/pull/813[#813]
(https://github.com/prudhomm[prudhomm])

[[v0.103.2-2017-05-21]]
== https://github.com/feelpp/feelpp/tree/v0.103.2[v0.103.2] (2017-05-21)


https://github.com/feelpp/feelpp/compare/v0.103.1...v0.103.2[Full
Changelog]

*Closed issues:*

* FTBS from Feel++ tarballs
https://github.com/feelpp/feelpp/issues/903[#903]
* Missing hpddm and others from source archive tarball
https://github.com/feelpp/feelpp/issues/893[#893]

[[v0.103.1-2017-05-18]]
== https://github.com/feelpp/feelpp/tree/v0.103.1[v0.103.1] (2017-05-18)


https://github.com/feelpp/feelpp/compare/v0.103.0...v0.103.1[Full
Changelog]

[[v0.103.0-2017-05-17]]
== https://github.com/feelpp/feelpp/tree/v0.103.0[v0.103.0] (2017-05-17)


https://github.com/feelpp/feelpp/compare/v0.102.0...v0.103.0[Full
Changelog]

*Closed issues:*

* Support parallel adaptive meshing
https://github.com/feelpp/feelpp/issues/898[#898]
* Provide containerization tools for subprojects
https://github.com/feelpp/feelpp/issues/896[#896]
* rpath not properly handled on platform like linux
https://github.com/feelpp/feelpp/issues/895[#895]
* Support manual pages for applications
https://github.com/feelpp/feelpp/issues/889[#889]
* Installation process broken
https://github.com/feelpp/feelpp/issues/887[#887]
* Issue with Neumann BC in Toolbox:TE
https://github.com/feelpp/feelpp/issues/886[#886]
* Support intersection of entity sets
https://github.com/feelpp/feelpp/issues/883[#883]
* install-feelpp-lib can't finish because of mesh_partitioner
https://github.com/feelpp/feelpp/issues/882[#882]
* Building apps on top of feelmodels FTBS using feelpp-toolboxes docker
images https://github.com/feelpp/feelpp/issues/881[#881]
* Provide empty mesh shared and unique ptr construction
https://github.com/feelpp/feelpp/issues/879[#879]
* Support automated github release scripts
https://github.com/feelpp/feelpp/issues/875[#875]
* Add support for Advection-Diffusion-Reaction in quickstart
https://github.com/feelpp/feelpp/issues/873[#873]
* Move back Feel++ book into Feel++
https://github.com/feelpp/feelpp/issues/853[#853]
* Port Feel++ on Finis Terrae @ CESGA
https://github.com/feelpp/feelpp/issues/852[#852]
* Review and fix CRB codes
https://github.com/feelpp/feelpp/issues/843[#843]
* Support two element mesh in parallel (e.g 2 processors)
https://github.com/feelpp/feelpp/issues/822[#822]
* Installation Error https://github.com/feelpp/feelpp/issues/816[#816]
* Support terminal colors
https://github.com/feelpp/feelpp/issues/786[#786]
* Support Altair development environment
https://github.com/feelpp/feelpp/issues/776[#776]
* Use Boost.Log instead of google/glog
https://github.com/feelpp/feelpp/issues/732[#732]
* Replace ordered containers by hashed container in geometric elements
https://github.com/feelpp/feelpp/issues/723[#723]
* Optimize interprocessfaces()
https://github.com/feelpp/feelpp/issues/721[#721]
* Provide a isInterProcess() property for faces
https://github.com/feelpp/feelpp/issues/720[#720]
* Support reading Acusim Raw Mesh formats
https://github.com/feelpp/feelpp/issues/706[#706]
* Fu convergence failure when reconstructing the preconditioner
https://github.com/feelpp/feelpp/issues/628[#628]
* Feel++ Travis Deployment
https://github.com/feelpp/feelpp/issues/624[#624]
* Support SIMPLE preconditioner in Operator Framework for Stokes and
Navier-Stokes https://github.com/feelpp/feelpp/issues/496[#496]
* Markers on submesh https://github.com/feelpp/feelpp/issues/402[#402]
* Evaluate Precompiled Header support in Feel++
https://github.com/feelpp/feelpp/issues/171[#171]

*Merged pull requests:*

* Feature/nlopt https://github.com/feelpp/feelpp/pull/897[#897]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/cmake dependencies
https://github.com/feelpp/feelpp/pull/894[#894]
(https://github.com/vincentchabannes[vincentchabannes])
* Minor changes to cesga port in order to compile PETSc with MKL
https://github.com/feelpp/feelpp/pull/891[#891]
(https://github.com/victorsndvg[victorsndvg])
* Feature/cmake dependencies
https://github.com/feelpp/feelpp/pull/890[#890]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/cmake dependencies
https://github.com/feelpp/feelpp/pull/888[#888]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/MeshStructured https://github.com/feelpp/feelpp/pull/865[#865]
(https://github.com/LANTZT[LANTZT])

[[v0.102.0-2017-04-08]]
== https://github.com/feelpp/feelpp/tree/v0.102.0[v0.102.0] (2017-04-08)


https://github.com/feelpp/feelpp/compare/v0.101.1...v0.102.0[Full
Changelog]

*Closed issues:*

* CMake process fails from scratch at GINAC step
https://github.com/feelpp/feelpp/issues/860[#860]
* Support install rule in feelpp_add_application
https://github.com/feelpp/feelpp/issues/842[#842]
* Add project name in feelpp application
https://github.com/feelpp/feelpp/issues/841[#841]
* Reorganize models into toolboxes
https://github.com/feelpp/feelpp/issues/839[#839]
* Reduce quickstart to Laplacian and Stokes applications
https://github.com/feelpp/feelpp/issues/837[#837]
* Split mesh_partitioner files to reduce memory cost at compilation
https://github.com/feelpp/feelpp/issues/835[#835]
* Support staged compilation and installation
https://github.com/feelpp/feelpp/issues/834[#834]
* update Eigen3 https://github.com/feelpp/feelpp/issues/828[#828]
* Improve interface to Gmsh mesh readers
https://github.com/feelpp/feelpp/issues/826[#826]
* Support nnz() member function in MatrixSparse class
https://github.com/feelpp/feelpp/issues/821[#821]
* FTBS on Debian/Testing with gcc 6.2.0
https://github.com/feelpp/feelpp/issues/818[#818]
* Support GSL https://github.com/feelpp/feelpp/issues/817[#817]
* Bdf - Order > 1 https://github.com/feelpp/feelpp/issues/814[#814]
* FTBS on Debian/Testing with gcc 6.1.1
https://github.com/feelpp/feelpp/issues/812[#812]
* Update eigen3 https://github.com/feelpp/feelpp/issues/809[#809]
* Provide Boost hana support
https://github.com/feelpp/feelpp/issues/808[#808]
* Provide support for bi/linear forms on product of spaces
https://github.com/feelpp/feelpp/issues/807[#807]
* segfault with PtAP in sequential
https://github.com/feelpp/feelpp/issues/806[#806]
* Support mesh scaling to get proper dimension units
https://github.com/feelpp/feelpp/issues/805[#805]
* Support mesh for visualisation in MixedPoisson
https://github.com/feelpp/feelpp/issues/804[#804]
* Support boundary conditions defined in data file
https://github.com/feelpp/feelpp/issues/803[#803]
* Support loading a CSV file
https://github.com/feelpp/feelpp/issues/802[#802]
* CMake / CTest https://github.com/feelpp/feelpp/issues/801[#801]
* Upgrade Eigen in feature/hdg
https://github.com/feelpp/feelpp/issues/799[#799]
* Improve expression Evaluator
https://github.com/feelpp/feelpp/issues/797[#797]
* Support boost 1.61 https://github.com/feelpp/feelpp/issues/794[#794]
* Add support for ipopt
https://github.com/feelpp/feelpp/issues/791[#791]
* Minimal version of Feel++
https://github.com/feelpp/feelpp/issues/790[#790]
* move log files to result directory
https://github.com/feelpp/feelpp/issues/787[#787]
* Remove some files that are obsolete
https://github.com/feelpp/feelpp/issues/773[#773]
* Support visibility attributes
https://github.com/feelpp/feelpp/issues/772[#772]
* cleanup Ginac verbosity
https://github.com/feelpp/feelpp/issues/771[#771]
* Issue with petsc/ublas vector (probably copy) with petsc 3.7
https://github.com/feelpp/feelpp/issues/770[#770]
* Add support for libc++ in linux
https://github.com/feelpp/feelpp/issues/767[#767]
* Expose primal, dual and L2 preconditioners in CRBModel
https://github.com/feelpp/feelpp/issues/766[#766]
* Move physical marker management to MeshBase
https://github.com/feelpp/feelpp/issues/765[#765]
* Support automatic code reformatting according to Feel++ coding rules
https://github.com/feelpp/feelpp/issues/763[#763]
* Support elementswithmarkedfaces
https://github.com/feelpp/feelpp/issues/762[#762]
* CRB / PC https://github.com/feelpp/feelpp/issues/759[#759]
* Support PETSc 3.7 https://github.com/feelpp/feelpp/issues/756[#756]
* Bug in blockns preconditioner when vector is not ghosted
https://github.com/feelpp/feelpp/issues/755[#755]
* Provide the complement of a set of entities
https://github.com/feelpp/feelpp/issues/754[#754]
* Document and improve traits for functionspace and their elements
https://github.com/feelpp/feelpp/issues/753[#753]
* Support concatenation of entity sets
https://github.com/feelpp/feelpp/issues/752[#752]
* Bug in path of ensightgold scalar quantity file
https://github.com/feelpp/feelpp/issues/751[#751]
* Support add scalar quantity in Exporter interface
https://github.com/feelpp/feelpp/issues/750[#750]
* Support buildkite https://github.com/feelpp/feelpp/issues/748[#748]
* brew install duplicated source
https://github.com/feelpp/feelpp/issues/746[#746]
* Supports Eigen::Tensor serialization
https://github.com/feelpp/feelpp/issues/744[#744]
* Fix FindPETSc on HomeBrew/MacosX
https://github.com/feelpp/feelpp/issues/743[#743]
* support for med format for mesh
https://github.com/feelpp/feelpp/issues/735[#735]
* Interpolate a dataset
https://github.com/feelpp/feelpp/issues/733[#733]
* Support for io streams in parallel
https://github.com/feelpp/feelpp/issues/715[#715]
* loadMesh behaviour when msh filename is wrong
https://github.com/feelpp/feelpp/issues/668[#668]
* Cmake installation with install-feelpp
https://github.com/feelpp/feelpp/issues/662[#662]
* Update gflags/glog support
https://github.com/feelpp/feelpp/issues/642[#642]
* Add support for external storage in FunctionSpace::Element
https://github.com/feelpp/feelpp/issues/393[#393]
* Support variable expansion in options
https://github.com/feelpp/feelpp/issues/391[#391]
* Move levelset core to feel++
https://github.com/feelpp/feelpp/issues/390[#390]
* FTBS applications/crb/heat1d with g++ 4.8.2
https://github.com/feelpp/feelpp/issues/267[#267]

*Merged pull requests:*

* Feature/interpreter https://github.com/feelpp/feelpp/pull/872[#872]
(https://github.com/gdolle[gdolle])
* Feature/minor fixes from imft
https://github.com/feelpp/feelpp/pull/871[#871]
(https://github.com/Doyeux[Doyeux])
* Feature/mesh memredux https://github.com/feelpp/feelpp/pull/851[#851]
(https://github.com/vincentchabannes[vincentchabannes])
* Feature/slepc mumps https://github.com/feelpp/feelpp/pull/848[#848]
(https://github.com/romainhild[romainhild])
* feature/meshStructured https://github.com/feelpp/feelpp/pull/847[#847]
(https://github.com/LANTZT[LANTZT])
* Feature/toolboxes https://github.com/feelpp/feelpp/pull/840[#840]
(https://github.com/prudhomm[prudhomm])
* Feature/fix install https://github.com/feelpp/feelpp/pull/838[#838]
(https://github.com/prudhomm[prudhomm])
* Feature/fix clang4 https://github.com/feelpp/feelpp/pull/836[#836]
(https://github.com/prudhomm[prudhomm])
* Feature/optimize mesh https://github.com/feelpp/feelpp/pull/832[#832]
(https://github.com/prudhomm[prudhomm])
* Feature/optimize https://github.com/feelpp/feelpp/pull/830[#830]
(https://github.com/prudhomm[prudhomm])
* Feature/eigen3 https://github.com/feelpp/feelpp/pull/829[#829]
(https://github.com/prudhomm[prudhomm])
* Feature/cmake gflags glog
https://github.com/feelpp/feelpp/pull/825[#825]
(https://github.com/prudhomm[prudhomm])
* Add support for MESH and MED mesh format
https://github.com/feelpp/feelpp/pull/824[#824]
(https://github.com/Trophime[Trophime])
* fixes #809 https://github.com/feelpp/feelpp/pull/810[#810]
(https://github.com/prudhomm[prudhomm])
* Feature/improve evaluator
https://github.com/feelpp/feelpp/pull/798[#798]
(https://github.com/prudhomm[prudhomm])
* Feature/ls https://github.com/feelpp/feelpp/pull/796[#796]
(https://github.com/prudhomm[prudhomm])
* Feature/glog crbjson https://github.com/feelpp/feelpp/pull/795[#795]
(https://github.com/prudhomm[prudhomm])
* Implements Feature/minimal
https://github.com/feelpp/feelpp/pull/792[#792]
(https://github.com/prudhomm[prudhomm])
* Simplifying some aspects of the runtime environment
https://github.com/feelpp/feelpp/pull/788[#788]
(https://github.com/prudhomm[prudhomm])
* Feature/Holo3 https://github.com/feelpp/feelpp/pull/785[#785]
(https://github.com/prudhomm[prudhomm])
* Feature/visibility https://github.com/feelpp/feelpp/pull/783[#783]
(https://github.com/prudhomm[prudhomm])
* Feature/altair https://github.com/feelpp/feelpp/pull/777[#777]
(https://github.com/prudhomm[prudhomm])
* Feature/ls https://github.com/feelpp/feelpp/pull/774[#774]
(https://github.com/prudhomm[prudhomm])
* Feature/elements with marked faces
https://github.com/feelpp/feelpp/pull/768[#768]
(https://github.com/prudhomm[prudhomm])
* Add HDF5 format for CRB database
https://github.com/feelpp/feelpp/pull/758[#758]
(https://github.com/aancel[aancel])
* Feature/petsc37 https://github.com/feelpp/feelpp/pull/757[#757]
(https://github.com/vhuber[vhuber])
* Feature/interpolator https://github.com/feelpp/feelpp/pull/749[#749]
(https://github.com/vhuber[vhuber])
* Feature/crb clean https://github.com/feelpp/feelpp/pull/745[#745]
(https://github.com/prudhomm[prudhomm])
* Feature/hdg https://github.com/feelpp/feelpp/pull/712[#712]
(https://github.com/prudhomm[prudhomm])

* _This Change Log was automatically generated by
https://github.com/skywinder/Github-Changelog-Generator[github_changelog_generator]_
