Feel++: Feel::Repository Class Reference
Feel::Repository Class Reference
Description
@ structure to handle repository of results
Instances and minimal complete definitions
struct Config
struct Owner
Public Member Functions
Repository & cd ()
change directory to current configuration
Config & config ()
get the configuration of the repository
Config const & config () const
get the configuration of the repository
Repository & configure ()
configure the repository directories based on Config
Repository & configure (fs::path const &d)
configure for a given directory
Repository & configure (fs::path const &d, Location const &l)
configure for a given directory
Repository & configure (nl::json const &j)
configure for a json configuration
fs::path directory () const
the result repository absolute directory
fs::path directoryWithoutAppenders () const
the result repository absolute directory without appenders
fs::path const & exprs () const
get the expressions directory The expressions directory contains c++ and plugins associated with the expressions
fs::path const & geo () const
get the geo directory The geo directory contains geo files of Gmsh
fs::path const & globalRoot () const
bool isAbsolute () const
bool isGit () const
bool isGlobal () const
bool isLocal () const
bool isRelative () const
fs::path const & logs () const
get the logs directory The logs directory contains feelpp apps log files
fs::path relativeDirectory () const
the result repository directory relative to root
Repository (Config c)
fs::path const & root () const
std::string userEmail () const
the user email
std::string userName () const
the user name
Member Function Documentation
cd()
Repository & Feel::Repository::cd ()
change directory to current configuration
Returns
Repository& return the current directory
config() [1/2]
Config& Feel::Repository::config ()
get the configuration of the repository
Returns
Config &
config() [2/2]
Config const& Feel::Repository::config () const
get the configuration of the repository
Returns
Config const&
configure() [1/4]
Repository & Feel::Repository::configure ()
configure the repository directories based on Config
References Feel::absolute, directory(), Feel::git, Feel::global, and Feel::relative.
Referenced by configure().
configure() [2/4]
Repository& Feel::Repository::configure (fs::path const & d)
configure for a given directory
Parameters
d directory path
configure() [3/4]
Repository& Feel::Repository::configure (fs::path const & d, Location const & l)
configure for a given directory
Parameters
d directory path
l type of location
configure() [4/4]
Repository& Feel::Repository::configure (nl::json const & j)
configure for a json configuration
Parameters
j json file to configure the repo
References configure(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get().
directory()
fs::path Feel::Repository::directory () const
the result repository absolute directory
Returns
fs::path
Referenced by configure().
directoryWithoutAppenders()
fs::path Feel::Repository::directoryWithoutAppenders () const
the result repository absolute directory without appenders
Returns
fs::path
exprs()
fs::path const& Feel::Repository::exprs () const
get the expressions directory The expressions directory contains c++ and plugins associated with the expressions
Returns
get the exprs directory of the repository
geo()
fs::path const& Feel::Repository::geo () const
get the geo directory The geo directory contains geo files of Gmsh
Returns
get the geo directory of the repository
globalRoot()
fs::path const& Feel::Repository::globalRoot () const
Returns
get the global root repository associated to the global location
isAbsolute()
bool Feel::Repository::isAbsolute () const
Returns
true if repository is absolute, false otherwise
References Feel::absolute.
isGit()
bool Feel::Repository::isGit () const
Returns
true if repository is relative to a git repository, false otherwise
References Feel::git.
isGlobal()
bool Feel::Repository::isGlobal () const
Returns
true if repository is global, false otherwise
References Feel::global.
isLocal()
bool Feel::Repository::isLocal () const
Returns
true if repository is local, false otherwise
References Feel::relative.
isRelative()
bool Feel::Repository::isRelative () const
Returns
true if repository is local, false otherwise
References Feel::relative.
logs()
fs::path const& Feel::Repository::logs () const
get the logs directory The logs directory contains feelpp apps log files
Returns
get the logs directory of the repository
relativeDirectory()
fs::path Feel::Repository::relativeDirectory () const
the result repository directory relative to root
Returns
fs::path
root()
fs::path const& Feel::Repository::root () const
Returns
get the root of the repository where the results will be stored
userEmail()
std::string Feel::Repository::userEmail () const
the user email
Returns
std::string
userName()
std::string Feel::Repository::userName () const
the user name
Returns
std::string