Feel++: Feel::PolynomialSet Class Reference
Feel::PolynomialSet Class Reference
Description
a Set of polynomials
This class represents a set of polynomials \({p_i}_{i=1...N} \) defined in a certain basis given by the template argument. The coefficients of the polynomials in the basis are represented by a matrix whose line represents the polynomials and columns the basis index \(C_{i,j} = \mathcal{R}(p_i)_j \) where \(\mathcal{R}\) is the mapping between the polynomial and its coefficients. We have that the polynomial set is represented as follows:
\[p_i = \sum_j=1^N \mathcal{R}(p_i)_j \phi_j\]
Author
Christophe Prud'homme
See also
Constants
static const uint16_type nDim = Poly::nDim
static const uint16_type nRealDim = Poly::nRealDim
static const uint16_type nOrder = Poly::nOrder
Typedefs
typedef PolynomialSet< Poly, PolySetType > self_type
typedef std::shared_ptr< self_type > self_ptrtype
typedef Poly::value_type value_type
typedef Poly::basis_type basis_type
typedef PolySetType< nRealDim > polyset_type
typedef PolynomialSet< Poly, Scalar > component_type
typedef Polynomial< Poly, PolySetType > polynomial_type
typedef polynomial_type polynomial_view_type
typedef Poly::convex_type convex_type
typedef basis_type::matrix_type matrix_type
typedef basis_type::points_type points_type
using gradient_polynomialset_type = typename mpl::if_< is_scalar_polynomial< polyset_type >, mpl::identity< PolynomialSet< Poly, Vectorial > >, typename mpl::if_< is_vector_polynomial< polyset_type >, mpl::identity< PolynomialSet< Poly, Tensor2 > >, mpl::identity< PolynomialSet< Poly, Tensor3 > > >::type >::type::type
static const bool is_product = Poly::is_product
static const bool is_tensor2symm = polyset_type::is_tensor2 && is_symm_v<polyset_type>
static const bool is_tensor2 = polyset_type::is_tensor2
static const bool is_vectorial = polyset_type::is_vectorial
static const bool is_scalar = polyset_type::is_scalar
static const uint16_type nComponents = polyset_type::nComponents
static const uint16_type nComponents1 = polyset_type::nComponents1
static const uint16_type nComponents2 = polyset_type::nComponents2
static const uint16_type rank = polyset_type::rank
Constructors, destructor
PolynomialSet ()
PolynomialSet (Poly const &p)
PolynomialSet (Poly const &p, matrix_type const &c, bool __as_is=false)
PolynomialSet (matrix_type const &c, bool __as_is=false)
PolynomialSet (PolynomialSet const &p)
virtual ~PolynomialSet ()
Operator overloads
self_type & operator= (self_type const &pset)
component_type operator[] (uint16_type i) const
extract the i-th component of a vectorial polynomial set
component_type operator() (uint16_type i, uint16_type j) const
Accessors
uint16_type degree () const
matrix_type const & coeff () const
basis_type const & basis () const
size_type polynomialDimension () const
size_type polynomialDimensionPerComponent () const
bool isZero () const
virtual std::string familyName () const
the familyName() identifies the finite element
std::string name (std::string sep=".") const
the name of a finite element is a string composed by:
static bool isScalar ()
static bool isVectorial ()
static uint16_type numberOfComponents ()
Mutators
void setCoefficient (matrix_type const &__c, bool __as_is=false)
set the coefficient of the polynomial set in the basis.
Methods
typedef PreCompute precompute_type
class PreCompute
typedef std::shared_ptr< precompute_type > precompute_ptrtype
typedef std::vector< std::map< typename convex_type::permutation_type, precompute_ptrtype > > faces_precompute_type
PolynomialSet< Poly, PolySetType > polynomials (std::vector< int > const &list_p) const
Extract the polynomials whose indices are listed in list_p.
PolynomialSet< Poly, PolySetType > polynomialsUpToDimension (int dim_p) const
Extract the polynomials up to dimension dim.
PolynomialSet< Poly, PolySetType > polynomialsRange (uint16_type dim_bot, uint16_type dim_top) const
Extract the polynomials between dimension dim_bot up to dimension dim_top.
Polynomial< Poly, PolySetType > polynomial (uint16_type i) const
Extract the i -th polynomial.
template<typename AE >
ublas::vector< value_type > evaluate (uint16_type i, ublas::vector_expression< AE > const &__pt) const
evaluate the i-th polynomial at node __pt
template<typename AE >
ublas::matrix< value_type > evaluate (ublas::vector_expression< AE > const &__pt) const
evaluate all polynomials at node __pt
template<typename AE >
matrix_type evaluate (ublas::matrix_expression< AE > const &__pts) const
evaluate all polynomials of the set at a set of nodes
matrix_type const & d (uint16_type i) const
Derivate with respect to the \(\ell\) coordinates at the nodes where the polynomials basis have been constructed.
matrix_type d (uint16_type i, uint16_type j) const
self_type derivate (uint16_type l) const
Derivate with respect to the l-th direction.
template<typename AE >
ublas::vector< matrix_type > derivate (ublas::matrix_expression< AE > const &pts) const
template<typename AE >
matrix_type derivate (uint16_type i, ublas::matrix_expression< AE > const &pts) const
template<typename AE >
ublas::matrix< matrix_type > derivate2 (ublas::matrix_expression< AE > const &pts) const
template<typename AE >
matrix_type derivate (uint16_type i, uint16_type j, ublas::matrix_expression< AE > const &pts) const
gradient_polynomialset_type gradient () const
Gradient of the polynomial set.
gradient_polynomialset_type gradient (rank_t< 0 >) const
gradient_polynomialset_type gradient (rank_t< 1 >) const
uint16_type nbDof () const
void insert (PolynomialSet< Poly, PolySetType > const &p, bool erase=false)
insert the polynomial set p at the end of the set
matrix_type firstMoments ()
compute the first moment value or first-moment of the polynomial set.
precompute_ptrtype preCompute (self_ptrtype p, points_type const &P)
precompute_ptrtype preCompute (points_type const &P)
std::vector< std::map< typename convex_type::permutation_type, precompute_ptrtype > > preComputeOnFaces (self_ptrtype p, points_type const &P)
std::vector< std::map< typename convex_type::permutation_type, precompute_ptrtype > > preComputeOnFaces (self_ptrtype p, std::vector< std::map< uint16_type, points_type > > const &P)
template<typename PAtEdges >
std::vector< std::map< typename convex_type::permutation_type, precompute_ptrtype > > preComputeOnEdges (self_ptrtype gm, PAtEdges const &p)
template<size_type context_v, typename BasisType , typename GeoType , typename ElementType >
std::shared_ptr< Context< context_v, BasisType, GeoType, ElementType > > context (std::shared_ptr< BasisType > b, std::shared_ptr< GeoType > gm, precompute_ptrtype &pc)
template<int contextv, int contextg, typename BasisType , typename GeoType , typename ElementType >
std::shared_ptr< Context< contextv, BasisType, GeoType, ElementType > > ctx (std::shared_ptr< BasisType > const &b, std::shared_ptr< typename GeoType::template Context< contextg, ElementType > > const &gm, precompute_ptrtype pc, ElementType &e)
template<int contextv, typename BasisType , typename GeoType , typename ElementType >
std::shared_ptr< Context< contextv, BasisType, GeoType, ElementType > > ctx (std::shared_ptr< BasisType > const &b, std::shared_ptr< typename GeoType::template Context< contextv, ElementType > > const &gm, precompute_ptrtype pc, ElementType &e)
Member Function Documentation
basis()
basis_type const& Feel::PolynomialSet::basis () const
Returns
the basis associated with the polynomial set
coeff()
matrix_type const& Feel::PolynomialSet::coeff () const
Returns
coefficient of the polynomials of the polynomial set in the basis associated with Poly
Referenced by Feel::PolynomialSet< Poly, PolySetType >::polynomialsRange(), and Feel::PolynomialSet< Poly, PolySetType >::polynomialsUpToDimension().
d()
matrix_type const& Feel::PolynomialSet::d (uint16_type i) const
Derivate with respect to the \(\ell\) coordinates at the nodes where the polynomials basis have been constructed.
We construct the matrix
\begin{eqnarray*} A_{i,j} &= \frac{\partial p_i(x_j)}{\partial x_\ell}\\ &= \sum_{k=1}^N \mathcal{R}(p_i)_k \frac{\partial \phi_k(x_j)}{\partial x_\ell} \end{eqnarray*}
l the derivation index \(\ell\)
__pts a column oriented matrix contained the node coordinates (in the columns).
Returns
the matrix \(A\)
derivatives of Dubiner polynomials the derivatives are computed at the nodes of the lattice
i index of the derivative (0 : x, 1 : y, 2 : z)
degree()
uint16_type Feel::PolynomialSet::degree () const
Returns
the degree of the polynomials in the set
derivate()
self_type Feel::PolynomialSet::derivate (uint16_type l) const
Derivate with respect to the l-th direction.
Returns
the polynomial set associated with the derivation in the l-direction
evaluate() [1/3]
template<typename AE > matrix_type Feel::PolynomialSet::evaluate (ublas::matrix_expression< AE > const & __pts) const
evaluate all polynomials of the set at a set of nodes
Constructs \(A_{i,j} = p_i(x_j) = \sum_{k=1}^N \mathcal{R}(p_i)_k \phi_k(x_j)\)
__pts a column oriented matrix contained the node coordinates (in the columns).
Returns
the matrix \(A\)
evaluate() [2/3]
template<typename AE > ublas::matrix<value_type> Feel::PolynomialSet::evaluate (ublas::vector_expression< AE > const & __pt) const
evaluate all polynomials at node __pt
Returns
a column matrix
evaluate() [3/3]
template<typename AE > ublas::vector<value_type> Feel::PolynomialSet::evaluate (uint16_type i, ublas::vector_expression< AE > const & __pt) const
evaluate the i-th polynomial at node __pt
Warning
this function is not efficient at all, the preferred method is to evaluate at a set of points
familyName()
virtual std::string Feel::PolynomialSet::familyName () const virtual
the familyName() identifies the finite element
Returns
the family name of a finite element
firstMoments()
matrix_type Feel::PolynomialSet::firstMoments ()
compute the first moment value or first-moment of the polynomial set.
Note
the values are not divided by the measure of the domain.
Returns
a column matrix containing the first moment value of the basis functions
gradient()
gradient_polynomialset_type Feel::PolynomialSet::gradient () const
Gradient of the polynomial set.
Computes the gradient of the polynomial set.
isScalar()
static bool Feel::PolynomialSet::isScalar () static
Returns
true if the polynomial set is scalar, false otherwise
isVectorial()
static bool Feel::PolynomialSet::isVectorial () static
Returns
true if the polynomial set is vectorial, false otherwise
isZero()
bool Feel::PolynomialSet::isZero () const
Returns
true if the polynomial set is zero, false otherwise
name()
std::string Feel::PolynomialSet::name (std::string sep = ".") const
the name of a finite element is a string composed by:
a prefix which identifies the family (eg lagrange)
the dimension
the order of the finite element
Parameters
sep separator between family name, dimension and order (by default it is '.')
Returns
the name of the finite element
nbDof()
uint16_type Feel::PolynomialSet::nbDof () const
Returns
the number of degrees of freedom
operator[]()
component_type Feel::PolynomialSet::operator[] (uint16_type i) const
extract the i-th component of a vectorial polynomial set
Returns
the i-th component of the polynomial set
polynomial()
Polynomial<Poly, PolySetType> Feel::PolynomialSet::polynomial (uint16_type i) const
Extract the i -th polynomial.
Parameters
i index of the polynomial to extract
Returns
the polynomial extracted
polynomialDimension()
size_type Feel::PolynomialSet::polynomialDimension () const
Returns
the polynomial dimension
Referenced by Feel::PolynomialSet< Poly, PolySetType >::polynomialsRange().
polynomialDimensionPerComponent()
size_type Feel::PolynomialSet::polynomialDimensionPerComponent () const
Returns
the polynomial dimension per component
polynomials()
PolynomialSet<Poly, PolySetType> Feel::PolynomialSet::polynomials (std::vector< int > const & list_p) const
Extract the polynomials whose indices are listed in list_p.
Parameters
list_p list of indices of polynomials to extract
Returns
the polynomial set extracted
polynomialsRange()
PolynomialSet<Poly, PolySetType> Feel::PolynomialSet::polynomialsRange (uint16_type dim_bot, uint16_type dim_top) const
Extract the polynomials between dimension dim_bot up to dimension dim_top.
Parameters
dim_bot polynomial dimension
dim_top polynomial dimension
Returns
the polynomial set extracted
polynomialsUpToDimension()
PolynomialSet<Poly, PolySetType> Feel::PolynomialSet::polynomialsUpToDimension (int dim_p) const
Extract the polynomials up to dimension dim.
Parameters
dim_p polynomial dimension
Returns
the polynomial set extracted