Feel++: Feel::TimerTable Class Reference
Feel::TimerTable Class Reference
Description
TimerTable is a map of timer.
TimerTable ()
Constructors.
void add (std::string const &msg, std::pair< double, int > const &t, std::string const &uiname="")
Modifiers.
void save (bool display)
Methods.
void saveMD (std::ostream &os)
Save timers in markdown format.
void test ()
Public Member Functions
~TimerTable () override
Destructor.
Public Member Functions inherited from Feel::JournalWatcher
JournalWatcher (std::string const &category="", std::string const &name="", bool connect=JournalManager::journalAutoMode())
Constructors.
JournalWatcher (std::string const &category, bool useDefaultName, bool connect=JournalManager::journalAutoMode())
JournalWatcher (function_update_information_type const &func, std::string const &category="", std::string const &name="", bool useDefaultNameIfEmpty=true, bool connect=JournalManager::journalAutoMode())
JournalWatcher (JournalWatcher const &jw)
Copy constructor.
virtual ~JournalWatcher ()
Default destructor. The (inherited) object is always disconnected from the journal during the destruction.
bool journalIsConnected () const
GettersCheck if the object is connected to the journal.
std::string const & journalWatcherInstanceName () const
Return the full instance name for this watched object. The name is composed with the base name and a suffix index corresponding to the nth call.
nl::json::json_pointer journalSection () const
Return the section into the journal as json_pointer.
nl::json const & informationObject () const
Return the information into property tree.
void journalConnect ()
Setters.
void journalDisconnect ()
Disconnect the derived object from the simulation info manager. The disconnection is safe.
void setInformationObject (nl::json const &informationObject)
set information object
void putInformationObject (nl::json const &informationObject)
put information object
void addInformationObject (nl::json const &informationObject)
add information object
void journalFinalize ()
finalize journal publication
Additional Inherited Members
Public Types inherited from Feel::JournalWatcher
using function_update_information_type = std::function< void(nl::json &)>
using notify_type = nl::json
Protected Member Functions inherited from Feel::JournalWatcher
void applyUpdateInformationObject ()
Protected Methods.
Member Function Documentation
add()
void Feel::TimerTable::add (std::string const & msg, std::pair< double, int > const & t, std::string const & uiname = "")
Modifiers.
Add a timer for the given message
Referenced by TimerTable().
save()
void Feel::TimerTable::save (bool display)
Methods.
Save the timers. If display is true, the timers are printed on the standard output.
saveMD()
void Feel::TimerTable::saveMD (std::ostream & os)
Save timers in markdown format.
Parameters
os output stream
See also
save
Constructor & Destructor Documentation
TimerTable()
Feel::TimerTable::TimerTable ()
Constructors.
Default constructor
References add(), Feel::JournalWatcher::journalFinalize(), Feel::JournalWatcher::JournalWatcher(), and ~TimerTable().