Feel++: Feel::CRBDB Class Reference
Feel::CRBDB Class Reference abstract
Description
brief description
Author
Christophe Prud'homme
See also
Typedefs
using super = CommObject
Constructors, destructor
CRBDB ()=delete
CRBDB (std::string const &name, std::string const &ext, worldcomm_ptr_t const &worldComm=Environment::worldCommPtr())
default constructor
CRBDB (std::string const &name, std::string const &ext, uuids::uuid const &i, worldcomm_ptr_t const &worldComm=Environment::worldCommPtr())
CRBDB (CRBDB const &)=default
copy constructor
virtual ~CRBDB ()
destructor
Operator overloads
CRBDB & operator= (CRBDB const &o)=default
copy operator
Accessors
std::string const & name () const
std::string const & extension () const
return extension
uuids::uuid const & id () const
uuids::uuid id (fs::path p) const
std::string idStr () const
void setId (uuids::uuid const &i)
set UUID
std::string jsonFilename () const
std::string const & dbFilename () const
std::string dbDirectory (bool withSubDir=true) const
void setDBDirectory (std::string const &name, uuids::uuid const &i)
set the DB directory according to a name and a UUID
void setDBDirectory (uuids::uuid const &i)
set the DB directory according to a UUID
std::string const & dbSubDirectory () const
std::string dbRelativePath () const
virtual fs::path dbLocalPath () const
virtual fs::path lookForDB () const
po::variables_map const & vm () const
bool isDBLoaded () const
Mutators
void setName (std::string const &name)
set the name of the model for the DB
void setDBFilename (std::string const &filename)
set the name of the model for the DB
void setDBDirectory (std::string const &directory)
set DB directory
void addDBSubDirectory (std::string const &subdirectory)
add a subdirectory to the database directory
void setDBSubDirectory (std::string const &directory)
set DB sub directory
Methods
class boost::serialization::access
BOOST_SERIALIZATION_SPLIT_MEMBER() private std::string M_ext
uuids::uuid M_uuid
std::string M_dbfilename
std::string M_dbDirectory
std::string M_dbSubDirectory
bool M_isloaded
virtual void saveDB ()
save the CRB database
virtual bool loadDB ()
load the CRB database
virtual void loadDB (std::string const &filename, crb::load l)=0
fs::path db (std::string const &) const
virtual void loadDBFromId (std::string const &id, crb::load l=crb::load::rb, std::string const &root=Environment::rootRepository())
fs::path dbFromId (std::string const &id, std::string const &root=Environment::rootRepository()) const
virtual void loadDBLast (crb::last last=crb::last::modified, crb::load l=crb::load::rb, std::string const &root=Environment::rootRepository())
fs::path dbLast (crb::last last=crb::last::modified, std::string const &root=Environment::rootRepository()) const
void setIsLoaded (bool isloaded)
template<class Archive >
void save (Archive &ar, const unsigned int version) const
template<class Archive >
void load (Archive &ar, const unsigned int version)
Additional Inherited Members
Public Member Functions inherited from Feel::CommObject
WorldComm const & comm () const
CommObject (CommObject &&)=default
CommObject (CommObject const &)=default
CommObject (worldcomm_ptr_t &w)
CommObject (worldcomm_ptr_t const &w)
bool hasWorldComm () const
returns true if worldcomm is allocated, false othewise
CommObject & operator= (CommObject &&)=default
CommObject & operator= (CommObject const &)=default
virtual void setWorldComm (worldcomm_ptr_t const &w)
virtual void setWorldComm (worldcomm_t &w)
worldcomm_ptr_t & subWorldCommSeqPtr ()
worldcomm_ptr_t const & subWorldCommSeqPtr () const
WorldComm & worldComm ()
WorldComm const & worldComm () const
worldcomm_ptr_t & worldCommPtr ()
worldcomm_ptr_t const & worldCommPtr () const
Member Function Documentation
db()
fs::path Feel::CRBDB::db (std::string const &) const
Returns
path to file f and check json extension
dbDirectory()
std::string Feel::CRBDB::dbDirectory (bool withSubDir = true) const
Returns
prefix directory
dbFilename()
std::string const& Feel::CRBDB::dbFilename () const
Returns
the DB filename
dbFromId()
fs::path Feel::CRBDB::dbFromId (std::string const & id, std::string const & root = Environment::rootRepository()) const
Returns
fs::path from DB id check existence of json metadata file
Parameters
id db id
root root repository for CRB DB
dbLast()
fs::path Feel::CRBDB::dbLast (crb::last last = crb::last::modified, std::string const & root = Environment::rootRepository()) const
Returns
fs::path from DB last check existence of json metadata file
Parameters
last what last file type
root root repository for CRB DB
dbLocalPath()
virtual fs::path Feel::CRBDB::dbLocalPath () const virtual
Returns
the db local path
Referenced by Feel::CRB< TruthModelType >::WNmuSize().
dbRelativePath()
std::string Feel::CRBDB::dbRelativePath () const
Returns
relative path
dbSubDirectory()
std::string const& Feel::CRBDB::dbSubDirectory () const
Returns
sub directory
id() [1/2]
uuids::uuid const& Feel::CRBDB::id () const
Returns
the uuid of the CRBDB
id() [2/2]
uuids::uuid Feel::CRBDB::id (fs::path p) const
Returns
the uuid from a path to the json file
idStr()
std::string Feel::CRBDB::idStr () const
Returns
the string representation of the uuid
isDBLoaded()
bool Feel::CRBDB::isDBLoaded () const
Returns
true if the DB has been loaded, false otherwise
jsonFilename()
std::string Feel::CRBDB::jsonFilename () const
Returns
the DB filename
Referenced by Feel::CRB< TruthModelType >::WNmuSize().
lookForDB()
virtual fs::path Feel::CRBDB::lookForDB () const virtual
Returns
path to database, empty path if not found
name()
std::string const& Feel::CRBDB::name () const
Returns
name
Referenced by Feel::CRBElementsDB< truth_model_type >::CRBElementsDB().
setDBFilename()
void Feel::CRBDB::setDBFilename (std::string const & filename)
set the name of the model for the DB
this->setDBFilename("heat.crbdb");
Referenced by Feel::CRBElementsDB< truth_model_type >::CRBElementsDB().
setName()
void Feel::CRBDB::setName (std::string const & name)
set the name of the model for the DB
this->setName("heat");
vm()
po::variables_map const& Feel::CRBDB::vm () const
Returns
variables_map