Feel++: Feel::Gmsh Class Reference
Feel::Gmsh Class Reference
Description
Gmsh Mesh Generator.
The Gmsh class helps with the generation of meshes using the program gmsh. Typically one would generate a .geo std::string for example and pass it to generate() along with the prefix name of the .geo and .msh files to create/generate.
std::ostringstream ostr;
std::string fname;
ostr << "h=" << 0.1 << ";\n"
<< "Point(1) = {0,0,0,h};\n"
<< "Point(2) = {1,0,0,h};\n"
<< "Point(3) = {1,1,0,h};\n"
<< "Point(4) = {0,1,0,h};\n"
<< "Line(1) = {1,2};\n"
<< "Line(2) = {2,3};\n"
<< "Line(3) = {3,4};\n"
<< "Line(4) = {4,1};\n"
<< "Line Loop(4) = {1,2,3,4};\n"
<< "Plane Surface(5) = {4};\n"
<< "Physical Line(10) = {1,3};\n"
<< "Physical Line(20) = {2,4};\n"
<< "Physical Surface(6) = {5};\n";
Gmsh gmsh;
// generate the \c .geo file using \c ostr and
// call gmsh to generate the \c msh file from the \c .geo file
fname = gmsh.generate("triangle", ostr.str());
// fname can now be passed to \c ImporterGmsh for example
mesh_type mesh;
ImporterGmsh<mesh_type> import(fname);
mesh->accept(import);
Author
Christophe Prud'homme
See also
http://www.geuz.org/gmsh/
Constructors, destructor
Gmsh (int nDim=1, int nOrder=GMSH_ORDER_ONE, worldcomm_ptr_t const &worldComm=Environment::worldCommPtr())
Gmsh (Gmsh const &__g)
virtual ~Gmsh ()
Operator overloads
Gmsh & operator= (Gmsh const &__g)
assignment operator
static std::shared_ptr< Gmsh > New (po::variables_map const &vm)
static std::shared_ptr< Gmsh > New (std::string const &shape, uint16_type d=2, uint16_type o=1, std::string const &ct="simplex", worldcomm_ptr_t const &worldComm=Environment::worldCommPtr())
Accessors
int dimension () const
GMSH_ORDER order () const
get the order of the elements of the mesh
std::string version () const
GMSH_FORMAT format () const
std::pair< std::string, std::string > geo () const
get the geometry
bool isASCIIFormat () const
bool isBinaryFormat () const
std::string prefix () const
PeriodicEntities const & periodic () const
std::vector< std::pair< double, double > > const & boundingBox () const
double xmin () const
double xmax () const
double ymin () const
double ymax () const
double zmin () const
double zmax () const
double const & h () const
std::string const & description () const
double geoParameter (std::string const &_name)
Get the value of a GMSH geometry parameter. If the parameter does not match any parameter, the function throws an out_of_range exception.
std::map< std::string, std::string > const & geoParameters () const
Get all GMSH geometry parameters.
std::map< std::string, std::string > & geoParameters ()
bool addMidPoint () const
add the mid point of the domain
bool usePhysicalNames () const
int numberOfPartitions () const
bool mshFileByPartition () const
GMSH_PARTITIONER partitioner () const
double shear () const
get the shear
bool recombine () const
return true if recombine, false otherwise
int structuredMesh () const
int refinementLevels () const
std::string const & gModelName () const
Mutators
Gmsh & setDimension (int dim)
set the dimension
Gmsh & ref ()
the gmsh generator to generate a reference domain
Gmsh & h (double _h)
set the characteristic length
void setVerbosity (int val)
set Gmsh verbosity
void setOrder (int o)
set the order of the elements of the mesh it can be either GMSH_ORDER_ONE (order 1/linear) or GMSH_ORDER_TWO(order 2/quadratic)
void setVersion (std::string version, GMSH_FORMAT format=GMSH_FORMAT_ASCII)
set the file format version in ascii or binary format
void setInMemory (bool in)
if in is true, read in-memory geo files
void setGModelName (std::string const &name)
void setFileFormat (GMSH_FORMAT format)
set file format: ascii or binary
void setGeo (std::pair< std::string, std::string > const &g)
set the gmsh geo
void setDescription (std::string const &desc)
set the description of the geometry
void setSubStructuring (bool substruct)
bool subStructuring () const
void setPrefix (std::string const &name)
set the prefix of the Gmsh files
virtual void setX (std::pair< double, double > const &x)
virtual void setY (std::pair< double, double > const &y)
virtual void setZ (std::pair< double, double > const &z)
virtual void setReferenceDomain ()
the gmsh generator to generate a reference domain
virtual void setCharacteristicLength (double _h)
set the characteristic length to h
virtual void setNx (double _nx)
set number of subdivison in x-direction
virtual void setNy (double _ny)
set number of subdivison in y-direction
virtual void setNz (double _nz)
set number of subdivison in z-direction
void setAddMidPoint (bool add)
if add is true, set M_addmidpoint to true, false otherwise
void setGeoParameter (std::string const &_name, double _value)
set a geo parameter.
void addGeoParameters (std::map< std::string, std::string > const &geomap)
Add geo parameters from a map of parameters.
void usePhysicalNames (bool option)
Set the use of physical names to describe the boundaries of the domain: if option is set to true then the generator will generate a PhysicalNames Section and replace numerical id by strings for the Physical boundaries.
void setWorldComm (WorldComm &_worldcomm)
set the communicator
void setWorldComm (worldcomm_ptr_t const &_worldcomm)
set the communicator
void setNumberOfPartitions (int n)
set the number of partitions
void setMshFileByPartition (bool p)
set save msh file by partitions
void setStructuredMesh (int s)
void setRefinementLevels (int levels)
void setPartitioner (GMSH_PARTITIONER const &p)
set the partitioner
void setShear (double _shear)
shear the domain
void setRecombine (bool _recombine)
recombine simplices into quads
void setPeriodic (PeriodicEntities const &p)
Methods
int M_dimension
mesh dimension
int M_order
mesh order
std::string M_version
GMSH_FORMAT M_format
std::string M_name
std::string M_desc
std::map< std::string, std::string > M_geoParamMap
bool M_in_memory
std::vector< std::pair< double, double > > M_I
bounding box
double M_h
characteristic length
double M_nx
number of discretization in X direction
double M_ny
number of discretization in Y direction
double M_nz
number of discretization in Z direction
bool M_addmidpoint
mid point
bool M_usePhysicalNames
add physical names to msh files
GMSH_PARTITIONER M_partitioner
partitioner type
int M_partitions
number of partitions
bool M_partition_file
save msh file by partition
double M_shear
shear
bool M_recombine
recombine simplices into hypercubes
int M_structured
int M_refine_levels
number of refinement levels
bool M_substructuring
PeriodicEntities M_periodic
std::pair< std::string, std::string > M_geo
std::string M_gmodelName
std::string generate (std::string const &name) const
generate a Gmsh msh file from name
boost::tuple< std::string, bool > generate (std::string const &name, std::string const &geo, bool const forceRebuild=false, bool const parametric=false, bool const modifGeo=true, std::string const &outputDirectory="") const
std::string refine (std::string const &name, int level=1, bool const parametric=false) const
refine the mesh uniformly by splitting
std::string preamble () const
std::string getDescriptionFromFile (std::string const &file) const
void rebuildPartitionMsh (std::string const &nameMshInput, std::string const &nameMshOutput) const
load mesh and generate a new partion of this mesh
std::map< std::string, std::string > retrieveGeoParameters (std::string const &geo) const
Extract all parameters from a geo gmsh geometry description and store them into a map.
static std::map< std::string, std::string > gpstr2map (std::string const &geopars)
Create a map from a list of geometry parameters string and separated by a character :.
virtual std::string getDescription () const
sublass must provide the geo description
bool generateGeo (std::string const &name, std::string const &geo, bool const modifGeo=true, std::string const &outputFilename="") const
Public Types
enum DomainType { GMSH_REFERENCE_DOMAIN = 0, GMSH_REAL_DOMAIN }
using super = CommObject
Additional Inherited Members
Public Member Functions inherited from Feel::CommObject
WorldComm const & comm () const
CommObject (CommObject &&)=default
CommObject (CommObject const &)=default
CommObject (worldcomm_ptr_t &w)
CommObject (worldcomm_ptr_t const &w)
bool hasWorldComm () const
returns true if worldcomm is allocated, false othewise
CommObject & operator= (CommObject &&)=default
CommObject & operator= (CommObject const &)=default
worldcomm_ptr_t & subWorldCommSeqPtr ()
worldcomm_ptr_t const & subWorldCommSeqPtr () const
WorldComm & worldComm ()
WorldComm const & worldComm () const
worldcomm_ptr_t & worldCommPtr ()
worldcomm_ptr_t const & worldCommPtr () const
Member Function Documentation
addGeoParameters()
void Feel::Gmsh::addGeoParameters (std::map< std::string, std::string > const & geomap)
Add geo parameters from a map of parameters.
Parameters
geomap A map containing the geo parameters (param,value).
boundingBox()
std::vector<std::pair<double,double> > const& Feel::Gmsh::boundingBox () const
Returns
bounding box
description()
std::string const& Feel::Gmsh::description () const
Returns
the geometry description
dimension()
int Feel::Gmsh::dimension () const
Returns
mesh dimension
Referenced by setNx(), and setReferenceDomain().
format()
GMSH_FORMAT Feel::Gmsh::format () const
Returns
file format
generate()
boost::tuple<std::string,bool> Feel::Gmsh::generate (std::string const & name, std::string const & geo, bool const forceRebuild = false, bool const parametric = false, bool const modifGeo = true, std::string const & outputDirectory = "") const
Parameters
name filename prefix to create the geo and msh file from geo
geo gmsh geometry description
forceRebuild if true, rebuild the mesh even if geofile is unchanged if false, rebuild only if geo file has changed. Useful if generateGeo has been called outside or if gmsh lybrary has changed.
parametric :
modifGeo : if true variable in geofile can be modified
outputDirectory : output directory of geo and msh file. If empty then it s generated on current path.
Returns
the name of the mesh file generate by gmsh (with the .msh extension)
generateGeo()
bool Feel::Gmsh::generateGeo (std::string const & name, std::string const & geo, bool const modifGeo = true, std::string const & outputFilename = "") const protected
Parameters
name filename prefix to create the geo
geo gmsh geometry description
Returns
returns whether geo file has changed or not. Usually called inside generate, but may be used to just generate the geo file. Note: if you use it alone, generate will call this routine again, hence generate needs to know whether to regenerate the mesh or not
geo()
std::pair<std::string,std::string> Feel::Gmsh::geo () const
get the geometry
Returns
the gmsh geo description
geoParameter()
double Feel::Gmsh::geoParameter (std::string const & _name)
Get the value of a GMSH geometry parameter. If the parameter does not match any parameter, the function throws an out_of_range exception.
Parameters
_name Geo parameter name.
Returns
Return the geo parameter value.
References M_h.
geoParameters()
std::map<std::string, std::string> const& Feel::Gmsh::geoParameters () const
Get all GMSH geometry parameters.
Returns
Return a map containing the geo gmsh geometry parameters as {par,value}.
getDescriptionFromFile()
std::string Feel::Gmsh::getDescriptionFromFile (std::string const & file) const
Returns
the content of the geo file file in a std::string
gpstr2map()
static std::map<std::string, std::string> Feel::Gmsh::gpstr2map (std::string const & geopars) static
Create a map from a list of geometry parameters string and separated by a character :.
Parameters
geopars List of parameters as key=value. Each new parameter is separated by a char :.
Returns
Return a map of GMSH geometry parameters and their values. If the string is empty, it returns an empty map.
h() [1/2]
double const& Feel::Gmsh::h () const
Returns
characteristic length
h() [2/2]
Gmsh& Feel::Gmsh::h (double _h)
set the characteristic length
Parameters
h the characteristic length
Returns
the mesh generator
isASCIIFormat()
bool Feel::Gmsh::isASCIIFormat () const
Returns
true if gmsh format is ascii
isBinaryFormat()
bool Feel::Gmsh::isBinaryFormat () const
Returns
true if gmsh format is binary
mshFileByPartition()
bool Feel::Gmsh::mshFileByPartition () const
Returns
true if save msh file by partitions, false otherwise
numberOfPartitions()
int Feel::Gmsh::numberOfPartitions () const
Returns
the nnumber of partitions
operator=()
Gmsh& Feel::Gmsh::operator= (Gmsh const & __g)
assignment operator
Parameters
__g another Gmsh object instance
Returns
the newly generated Gmsh object
order()
GMSH_ORDER Feel::Gmsh::order () const
get the order of the elements of the mesh
Returns
the order of the elements of the mesh
partitioner()
GMSH_PARTITIONER Feel::Gmsh::partitioner () const
Returns
the partitioner
preamble()
std::string Feel::Gmsh::preamble () const
Returns
the preamble for gmsh geometries
prefix()
std::string Feel::Gmsh::prefix () const
Returns
the name of the file
ref()
Gmsh& Feel::Gmsh::ref ()
the gmsh generator to generate a reference domain
Returns
the mesh generator
Gmsh gmsh;
gmsh = gmsh.ref();
refine()
std::string Feel::Gmsh::refine (std::string const & name, int level = 1, bool const parametric = false) const
refine the mesh uniformly by splitting
Parameters
name name of the gmsh mesh file
Parameters
level the number of refinements
retrieveGeoParameters()
std::map<std::string, std::string> Feel::Gmsh::retrieveGeoParameters (std::string const & geo) const
Extract all parameters from a geo gmsh geometry description and store them into a map.
Parameters
geo Gmsh geometry description.
Returns
Geo parameter map containing each parameter and its value.
setGeo()
void Feel::Gmsh::setGeo (std::pair< std::string, std::string > const & g)
set the gmsh geo
Parameters
g gmsh geo
References version().
setGeoParameter()
void Feel::Gmsh::setGeoParameter (std::string const & _name, double _value)
set a geo parameter.
Parameters
_name Geo parameter name.
_value Geo parameter value.
Returns
Return the current Gmsh object.
References M_nx.
setOrder()
void Feel::Gmsh::setOrder (int o)
set the order of the elements of the mesh it can be either GMSH_ORDER_ONE (order 1/linear) or GMSH_ORDER_TWO(order 2/quadratic)
Parameters
o order of the elements
setVerbosity()
void Feel::Gmsh::setVerbosity (int val)
set Gmsh verbosity
Parameters
val the verbosity level
usePhysicalNames()
bool Feel::Gmsh::usePhysicalNames () const
Returns
true if use the physical name, 'false' otherwise
version()
std::string Feel::Gmsh::version () const
Returns
the file format version
Referenced by setGeo().