Feel++: Feel::Event::SignalHandler Class Reference
Feel::Event::SignalHandler Class Reference
Description
Enable signals & slots to inherited objects. Add new functionnalities to connect objects between each others. Class that inherite from SignalHandler will have to possibility to create new signal.
:Note: Function template is a design choice. We want to simplify event creation in userland and also minimize polymorphism complexity.
:Info: This class is used to generate benchmark database.
template<typename... Args>
using sig_type = boost::signals2::signal< Args... >
Typedefs.
template<typename... Args>
using sig_shared_ptr_type = std::shared_ptr< sig_type< Args... > >
template<typename... Args>
using sig_weak_ptr_type = std::shared_ptr< sig_type< Args... > >
using sig_map_type = std::map< std::string, boost::any >
template<typename... Args>
using sig_map_entry_type = std::pair< std::string, sig_shared_ptr_type< Args... > >
using slothdlr_base_type = SlotHandler
using connection_type = boost::signals2::connection
using link_type = std::tuple< std::string, std::reference_wrapper< slothdlr_base_type const >, std::string >
using link_map_type = std::map< link_type, std::vector< connection_type > >
const boost::any & signal (const std::string &name)
Getters.
template<typename SlotType , typename... Args>
decltype(auto) signal (const std::string &name)
Get a signal by name. Otherwise, prefer using createSignal return type directly.
const sig_map_type & signals () const
Get a signal by name. Use dynamic cast to get real signal type. Otherwise, prefer using createSignal return type directly.
template<typename SlotType , typename... SignalArgs, typename SlotHdlr >
connection_type signalConnect (const std::string &signame, SlotHdlr &slothdlr, const std::string &slotname, SigConnectFlags flags=DEFAULT)
Connect a slot to a signal.
template<typename SlotType , typename... SignalArgs, typename SlotHdlr >
void signalDisconnect (const std::string &signame, SlotHdlr &slothdlr, const std::string &slotname, SigConnectFlags flags=DEFAULT)
Disconnect a slot from the signal.
void signalShow () const
Print a list of signal. Display stored signal from the map.
template<typename SlotType , typename... Args>
static decltype(auto) signalStatic (const std::string &name)
Get a static signal by name. Otherwise, prefer using createSignal return type directly.
static const sig_map_type & signalsStatic ()
Get a static signal by name. Use dynamic cast to get real signal type. Otherwise, prefer using createSignal return type directly.
template<typename SlotType , typename... SignalArgs, typename SlotHdlr >
static const connection_type signalStaticConnect (const std::string &signame, SlotHdlr &slothdlr, const std::string &slotname, SigConnectFlags flags=DEFAULT)
Connect a slot to a static signal.
template<typename SlotType , typename... SignalArgs, typename SlotHdlr >
static void signalStaticDisconnect (const std::string &signame, SlotHdlr &slothdlr, const std::string &slotname, SigConnectFlags flags=DEFAULT)
Disconnect a slot from a static signal.
static void signalStaticShow ()
Print a list of static signal. Display stored signal from the static map.
Public Member Functions
void signalDelete (const std::string &name)
Delete a signal.
template<typename... Args>
const sig_shared_ptr_type< Args... > & signalNew (const std::string &name)
Create a new signal.
Static Public Member Functions
static void signalStaticDelete (const std::string &name)
Delete a signal.
template<typename... Args>
static const sig_shared_ptr_type< Args... > & signalStaticNew (const std::string &name)
Create a new static signal.
Member Function Documentation
signal() [1/2]
const boost::any& Feel::Event::SignalHandler::signal (const std::string & name)
Getters.
Get a signal by name. Use dynamic cast to get real signal type. Otherwise, prefer using createSignal return type directly.
Returns
a signal as any type. A dynamic_cast has to be performed afterward to retrieve real signal type!
Referenced by signalConnect(), and signalDisconnect().
signal() [2/2]
template<typename SlotType , typename... Args> decltype(auto) Feel::Event::SignalHandler::signal (const std::string & name)
Get a signal by name. Otherwise, prefer using createSignal return type directly.
Returns
the real signal type. The slot type has to be passed as a template argument.
signalConnect()
template<typename SlotType , typename... SignalArgs, typename SlotHdlr > connection_type Feel::Event::SignalHandler::signalConnect (const std::string & signame, SlotHdlr & slothdlr, const std::string & slotname, SigConnectFlags flags = DEFAULT)
Connect a slot to a signal.
Template Parameters
SlotType Slot type.
SignalArgs Signal optional argument types.
SlotHdlr Slot handler type.
Parameters
signame Signal name.
slothdlr Slot handler.
slotname Slot name. The first argument is the slot type. The signal can only connect to a slot that have the same type!
References signal().
signalDisconnect()
template<typename SlotType , typename... SignalArgs, typename SlotHdlr > void Feel::Event::SignalHandler::signalDisconnect (const std::string & signame, SlotHdlr & slothdlr, const std::string & slotname, SigConnectFlags flags = DEFAULT)
Disconnect a slot from the signal.
Template Parameters
SlotType Slot type.
SignalArgs Signal optional argument types.
SlotHdlr Slot handler type.
Parameters
signame Signal name.
slothdlr Slot handler.
slotname Slot name. The first argument is the slot type. The signal can only connect to a slot that have the same type!
References signal().
signalNew()
template<typename... Args> const sig_shared_ptr_type< Args... >& Feel::Event::SignalHandler::signalNew (const std::string & name)
Create a new signal.
Template Parameters
Args optional signal arguments (see sig_type).
signalStatic()
template<typename SlotType , typename... Args> static decltype(auto) Feel::Event::SignalHandler::signalStatic (const std::string & name) static
Get a static signal by name. Otherwise, prefer using createSignal return type directly.
Returns
the real signal type. The slot type has to be passed as a template argument.
Referenced by signalStaticConnect(), and signalStaticDisconnect().
signalStaticConnect()
template<typename SlotType , typename... SignalArgs, typename SlotHdlr > static const connection_type Feel::Event::SignalHandler::signalStaticConnect (const std::string & signame, SlotHdlr & slothdlr, const std::string & slotname, SigConnectFlags flags = DEFAULT) static
Connect a slot to a static signal.
Template Parameters
SlotType Slot type.
SignalArgs Signal optional argument types.
SlotHdlr Slot handler type.
Parameters
signame Signal name.
slothdlr Slot handler.
slotname Slot name. The first argument is the slot type. The signal can only connect to a slot that have the same type!
References signalStatic().
signalStaticDisconnect()
template<typename SlotType , typename... SignalArgs, typename SlotHdlr > static void Feel::Event::SignalHandler::signalStaticDisconnect (const std::string & signame, SlotHdlr & slothdlr, const std::string & slotname, SigConnectFlags flags = DEFAULT) static
Disconnect a slot from a static signal.
Template Parameters
SlotType Slot type.
SignalArgs Signal optional argument types.
SlotHdlr Slot handler type.
Parameters
signame Signal name.
slothdlr Slot handler.
slotname Slot name. The first argument is the slot type. The signal can only connect to a slot that have the same type! Note: All connections are closed!
References signalStatic().
signalStaticNew()
template<typename... Args> static const sig_shared_ptr_type< Args... >& Feel::Event::SignalHandler::signalStaticNew (const std::string & name) static
Create a new static signal.
Template Parameters
Args optional signal arguments (see sig_type).
Member Typedef Documentation
sig_type
template<typename... Args> using Feel::Event::SignalHandler::sig_type = boost::signals2::signal< Args... >
Typedefs.
Feel++ signal type.
Template Parameters
Args Signal arguments The first argument is the Slot type, second is the event to apply to all notification.