Feel++: Feel::ParameterSpace< P >::Sampling Class Reference
Feel::ParameterSpace< P >::Sampling Class Reference
Description
template<uint16_type P = invalid_uint16_type_value>
class Feel::ParameterSpace< P >::Sampling
Parameter space sampling class.
Friends
class boost::serialization::access
Public Types
typedef std::shared_ptr< element_type > element_ptrtype
typedef parameterspace_type::Element element_type
typedef std::shared_ptr< parameterspace_type > parameterspace_ptrtype
typedef ParameterSpace< Dimension > parameterspace_type
typedef std::shared_ptr< sampling_type > sampling_ptrtype
typedef Sampling sampling_type
Public Member Functions
void addElement (element_type const &mu)
create add an element to a sampling
std::vector< int > closestSamplingFromFile (std::string const &file_name="list_of_parameters_taken")
build the closest sampling with parameters given from the file look in the supersampling closest parameters
sampling_ptrtype complement () const
if supersampling is != 0, Returns the complement
void distributeOnAllProcessors (int N, std::string const &file_name)
void equidistribute (int N, bool all_procs_have_same_sampling=true, std::string const &file_name="")
create a sampling with equidistributed elements
void equidistributeProduct (std::vector< size_type > const &N, bool all_procs_have_same_sampling=true, std::string const &file_name="")
create a sampling with equidistributed elements
void generateElementsProduct (std::vector< std::vector< double > > const &components)
void generateElementsProduct (std::vector< std::vector< std::vector< double > > > const &vector_components)
size_type indexInSuperSampling (size_type index) const
given a local index, returns the index in the super sampling
element_type lastElement ()
return the last element in the sampling
void logEquidistribute (int N, bool all_procs_have_same_sampling=true, std::string const &file_name="")
create a sampling with log-equidistributed elements
void logEquidistributeProduct (std::vector< size_type > const &N, bool all_procs_have_same_sampling=true, std::string const &file_name="")
create a sampling with log-equidistributed elements
boost::tuple< element_type, size_type > max (bool check=true) const
Returns the maximum element in the sampling and its index.
boost::tuple< element_type, size_type > min (bool check=true) const
Returns the minimum element in the sampling and its index.
void mixEquiLogEquidistributeProduct (std::vector< int > const &Nlogequi, std::vector< int > const &Nequi)
create a sampling with log-equidistributed and equidistributed elements
int nbElements () const
return number of elements in the sampling
parameterspace_ptrtype const & parameterSpace () const
Retuns the parameter space.
void push_back (element_type const &mu, size_type index=invalid_v< size_type >)
add new parameter mu in sampling and store index in super sampling
void randomInDirections (int N, std::vector< bool > const &Nd, bool all_procs_have_same_sampling=true, std::string const &file_name="")
create a sampling with random elements
void randomize (int N, bool all_procs_have_same_sampling=true, std::string const &file_name="", bool apply_log=false)
create a sampling with random elements
double readFromFile (std::string const &file_name="list_of_parameters_taken")
read the sampling from a file
void sample (size_type N, std::string const &samplingMode, bool all_procs_have_same_sampling=true, std::string const &filename="")
create a sampling with global number of samples
void sample (std::vector< size_type > const &N, std::string const &samplingMode, bool all_procs_have_same_sampling=true, std::string const &filename="")
create a sampling with number of samples in each direction
Sampling (parameterspace_ptrtype const &space, int N=0, sampling_ptrtype const &supersampling=sampling_ptrtype())
void sampling (size_type N, std::string const &samplingMode)
void saveJson (std::string const &filename, bool addParameterSpaceInfo=true)
save sampling data in json
sampling_ptrtype searchNearestNeighbors (element_type const &mu, size_type M, std::vector< int > &index_vector, bool broadcast=true)
Returns the M closest points to mu in sampling.
void setElements (std::vector< element_type > const &V)
create a sampling with elements given by the user
void setSuperSampling (sampling_ptrtype const &super)
set the super sampling
sampling_ptrtype const & superSampling () const
\breif Returns the supersampling (might be null)
void updatePropertyTree (boost::property_tree::ptree &ptree, bool addParameterSpaceInfo=true)
update sampling description in property_tree data structure
void writeOnFile (std::string const &file_name="list_of_parameters_taken")
write the sampling in a file
Member Function Documentation
addElement()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::addElement (element_type const & mu)
create add an element to a sampling
Parameters
mu : element_type
closestSamplingFromFile()
template<uint16_type P = invalid_uint16_type_value> std::vector<int> Feel::ParameterSpace< P >::Sampling::closestSamplingFromFile (std::string const & file_name = "list_of_parameters_taken")
build the closest sampling with parameters given from the file look in the supersampling closest parameters
Parameters
file_name : give the real parameters we want return the index vector of parameters in the supersampling
equidistribute()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::equidistribute (int N, bool all_procs_have_same_sampling = true, std::string const & file_name = "")
create a sampling with equidistributed elements
Parameters
N the number of samples
all_procs_have_same_sampling (boolean)
file_name : file name where the sampling is written
equidistributeProduct()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::equidistributeProduct (std::vector< size_type > const & N, bool all_procs_have_same_sampling = true, std::string const & file_name = "")
create a sampling with equidistributed elements
Parameters
N : vector containing the number of samples on each direction
indexInSuperSampling()
template<uint16_type P = invalid_uint16_type_value> size_type Feel::ParameterSpace< P >::Sampling::indexInSuperSampling (size_type index) const
given a local index, returns the index in the super sampling
Parameters
index index in the local sampling
Returns
the index in the super sampling
logEquidistribute()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::logEquidistribute (int N, bool all_procs_have_same_sampling = true, std::string const & file_name = "")
create a sampling with log-equidistributed elements
Parameters
N the number of samples
all_procs_have_same_sampling (boolean)
file_name : file name where the sampling is written
logEquidistributeProduct()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::logEquidistributeProduct (std::vector< size_type > const & N, bool all_procs_have_same_sampling = true, std::string const & file_name = "")
create a sampling with log-equidistributed elements
Parameters
N : vector containing the number of samples on each direction if N[direction] < 1 then we take minimum value for this direction
mixEquiLogEquidistributeProduct()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::mixEquiLogEquidistributeProduct (std::vector< int > const & Nlogequi, std::vector< int > const & Nequi)
create a sampling with log-equidistributed and equidistributed elements
Parameters
Nlogequi : vector containing the number of log-equidistributed samples on each direction
Nequi : vector containing the number of equidistributed samples on each direction
randomInDirections()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::randomInDirections (int N, std::vector< bool > const & Nd, bool all_procs_have_same_sampling = true, std::string const & file_name = "")
create a sampling with random elements
Parameters
N : vector of bool for the direction to sample
randomize()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::randomize (int N, bool all_procs_have_same_sampling = true, std::string const & file_name = "", bool apply_log = false)
create a sampling with random elements
Parameters
N the number of samples
all_procs_have_same_sampling (boolean)
file_name : file name where the sampling is written
readFromFile()
template<uint16_type P = invalid_uint16_type_value> double Feel::ParameterSpace< P >::Sampling::readFromFile (std::string const & file_name = "list_of_parameters_taken")
read the sampling from a file
Parameters
file_name : name of the file to read in the file we expect : mu_0= [ value0 , value1 , ... ] mu_1= [ value0 , value1 , ... ] return the size of the sampling
References Feel::ParameterSpace< P >::max(), and Feel::ParameterSpace< P >::min().
sample() [1/2]
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::sample (size_type N, std::string const & samplingMode, bool all_procs_have_same_sampling = true, std::string const & filename = "")
create a sampling with global number of samples
Parameters
N the number of samples
samplingMode : random, log-random, log-equidistribute, equidistribute
all_procs_have_same_sampling (boolean)
filename : file name where the sampling is written
References Feel::readFromFile().
sample() [2/2]
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::sample (std::vector< size_type > const & N, std::string const & samplingMode, bool all_procs_have_same_sampling = true, std::string const & filename = "")
create a sampling with number of samples in each direction
Parameters
N the number of samples in each direction
samplingMode : random, log-random, log-equidistribute, equidistribute
all_procs_have_same_sampling (boolean)
filename : file name where the sampling is written
saveJson()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::saveJson (std::string const & filename, bool addParameterSpaceInfo = true)
save sampling data in json
Parameters
output filename
searchNearestNeighbors()
template<uint16_type P> std::shared_ptr< typename ParameterSpace< P >::Sampling > Feel::ParameterSpace< P >::Sampling::searchNearestNeighbors (element_type const & mu, size_type M, std::vector< int > & index_vector, bool broadcast = true)
Returns the M closest points to mu in sampling.
Parameters
mu the point in parameter whom we want to find the neighbors
M the number of neighbors to find
Returns
vector of neighbors and index of them in the sampling
setElements()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::setElements (std::vector< element_type > const & V)
create a sampling with elements given by the user
Parameters
V : vector of element_type
updatePropertyTree()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::updatePropertyTree (boost::property_tree::ptree & ptree, bool addParameterSpaceInfo = true)
update sampling description in property_tree data structure
Parameters
ptree to update
writeOnFile()
template<uint16_type P = invalid_uint16_type_value> void Feel::ParameterSpace< P >::Sampling::writeOnFile (std::string const & file_name = "list_of_parameters_taken")
write the sampling in a file
Parameters
file_name : name of the file to read in the file we write : mu_0= [ value0 , value1 , ... ] mu_1= [ value0 , value1 , ... ]