Feel++: Feel::Geo0D< Dim, T, IndexT > Class Template Reference
Feel::Geo0D< Dim, T, IndexT > Class Template Reference
Basis Geometrical Entities Geo0D and GeoND.
Description
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type>
class Feel::Geo0D< Dim, T, IndexT >
Zero dimensional entity.
Friends
class boost::serialization::access
Public Types
using index_type = typename super::index_type
using marker_type = Marker< flag_type >
typedef matrix_node< value_type >::type matrix_node_type
using meshbase_type = MeshBase< index_type >
using node_type = typename node< T, Dim >::type
typedef node< T, 2 >::type parametric_node_type
typedef Geo0D< Dim, T, IndexT > self_type
using size_type = typename super::size_type
typedef T value_type
Public Types inherited from Feel::GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type >
typedef Simplex< 0, 1, Dim > super
typedef GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type > GeoShape
typedef GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type > self_type
typedef double value_type
using index_type = uint32_type
using size_type = index_type
typedef super::topological_face_type face_type
typedef face_type GeoBShape
typedef Simplex< 0, 1, Dim > ::edge_permutation_type edge_permutation_type
typedef Simplex< 0, 1, Dim > ::face_permutation_type face_permutation_type
typedef Simplex< 0, 1, Dim > convex_type
using reference_convex_type = Reference< Simplex< 0, 1, Dim >, nDim, nOrder, nRealDim, TT >
using marker_type = Marker< flag_type >
Public Types inherited from Feel::Simplex< 0, 1, Dim >
typedef mpl::if_< mpl::greater_equal< mpl::int_< nDim >, mpl::int_< 2 > >, mpl::identity< line_permutations >, mpl::identity< no_permutation > >::type::type edge_permutation_type
typedef mpl::at< map_entity_to_point_t, mpl::int_< nDim > >::type edge_to_point_t
typedef mpl::at< v_edges_t, mpl::int_< real_dimension > >::type edge_type
typedef mpl::at< elements_t, mpl::int_< nDim > >::type element_type
typedef mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 3 > >, mpl::identity< triangular_faces_type >, mpl::identity< no_permutation > >::type::type face_permutation_type
typedef mpl::at< map_entity_to_point_t, mpl::int_< nDim > >::type face_to_edge_t
typedef mpl::at< map_entity_to_point_t, mpl::int_< nDim > >::type face_to_point_t
typedef topological_face_type GeoBShape
typedef mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 2 > >, mpl::identity< mpl::vector< edge_permutation_type, vertex_permutation_type, vertex_permutation_type > >, typename mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 3 > >, mpl::identity< mpl::vector< face_permutation_type, edge_permutation_type, vertex_permutation_type > >, mpl::identity< mpl::vector< vertex_permutation_type, vertex_permutation_type, vertex_permutation_type > > >::type >::type::type permutation_by_subentity_type
typedef mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 2 > >, mpl::identity< edge_permutation_type >, typename mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 3 > >, mpl::identity< face_permutation_type >, mpl::identity< no_permutation > >::type >::type::type permutation_type
using PermutationSubEntity = typename mpl::at_c< permutation_by_subentity_type, N-1 >::type
using shape = Simplex< shape_dim, O, R >
using shape_t = Simplex< shape_dim, O, R >
typedef mpl::at< typename faces_t< real_dimension >::type, mpl::int_< nDim > >::type topological_face_type
typedef no_permutation vertex_permutation_type
Public Member Functions
matrix_node_type G () const
int gDim () const
Geo0D ()
default constructor
Geo0D (Geo0D &&G)
Geo0D (Geo0D const &G)
copy/move constructors
Geo0D (index_type id, bool boundary=false, bool is_vertex=false)
constructor where I give the id and declare if Geo0D object is on a boundary
Geo0D (index_type id, const node_type *__x, bool boundary=false, bool is_vertex=false, bool isView=false)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Geo0D (index_type id, self_type const &__x, bool boundary=false, bool is_vertex=false, bool isView=false)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
template<typename TheNodeType >
Geo0D (index_type id, TheNodeType const &__x, bool boundary=false, bool is_vertex=false, typename std::enable_if<!is_ptr_or_shared_ptr< TheNodeType >::value >::type *=nullptr)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Geo0D (index_type id, value_type x, value_type y, value_type z, bool boundary=false, bool is_vertex=false)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Geo0D (node_type const &__x)
the point coordinate
template<typename AE >
Geo0D (ublas::vector_expression< AE > const &__expr)
the point coordinate expression
Geo0D (value_type x, value_type y, value_type z)
give the point coordinate
int gTag () const
bool isParametric () const
bool isPeriodic () const
bool isVertex () const
index_type masterId () const
the master id is different from the id in the context of periodic boundary conditions on the slave side
self_type const * masterVertex () const
value_type measure () const override
meshbase_type const * mesh () const
node_type const & node () const
value_type & operator() (int i)
value_type operator() (int i) const
template<typename AE >
Geo0D & operator+= (ublas::vector_expression< AE > const &expr)
bool operator< (Geo0D const &e) const
bool operator< (index_type __i) const
Geo0D & operator= (Geo0D &&G)
Geo0D & operator= (Geo0D const &G)
assignement operators
template<typename AE >
Geo0D & operator= (ublas::vector_expression< AE > const &expr)
bool operator== (Geo0D const &geo0d) const
value_type & operator[] (int i)
value_type operator[] (int i) const
parametric_node_type const & parametricCoordinates () const
void setAsVertex (bool v)
set the point as a vertex or not using v
void setMasterId (index_type id)
void setMasterVertex (self_type const *m)
void setMesh (meshbase_type const *m)
set the mesh to which this geometric entity belongs to
void setNode (node_type const &__n)
set the node coordinates
void setParametricCoordinates (int gdim, int gtag, parametric_node_type const &x)
set the parametric coordinates of the node (if it is on an point, edge or surface geometric entity)
void setParametricCoordinates (int gdim, int gtag, value_type u, value_type v)
set the parametric coordinates of the node (if it is on an point, edge or surface geometric entity)
void setPoint (uint16_type const, self_type const &p)
set the point coordinates.
void setPointCoordG (int i, ublas::vector< double > const &p)
void setTags (std::vector< int > const &tags) override
set the tags associated to the points
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
show the information about the Geo0D
std::vector< int > tags () const
self_type & translate (node_type const &trans)
translate the point by trans
value_type u () const
value_type v () const
matrix_node_type vertices () const
~Geo0D () override
Destructor.
Public Member Functions inherited from Feel::GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type >
self_type & addElement (size_type e, int id_in_element=0)
add a new element to which the point belongs
size_type numberOfElements () const
std::set< std::pair< size_type, uint16_type > > const & elements () const
std::set< std::pair< size_type, uint16_type > > & elements ()
self_type & addElementGhost (rank_type proc, size_type e)
add a new ghost element to which the point belongs
rank_type numberOfProcGhost () const
std::map< rank_type, std::set< size_type > > const & elementsGhost () const
bool isSubEntityOfGhostElement (rank_type p) const
void clearElementsGhost ()
std::map< uint16_type, marker_type > const & markers () const
return all markers
void setMarkers (std::map< uint16_type, marker_type > const &markers)
set all markers
bool hasMarkerType (uint16_type k) const
return true if has marker type id k
bool hasMarker (uint16_type k) const
return true if has marker type id k
bool hasMarker () const
marker_type const & marker (uint16_type k) const
return marker with type id k
marker_type const & marker () const
void setMarker (uint16_type k, flag_type v)
set marker type id k with flag v
void setMarker (uint16_type k, TT const &vs)
set marker type id k with flag v
void setMarker (flag_type v)
void setMarker (TT const &vs)
void addMarker (uint16_type k, flag_type v)
add flag v to the marker type id k
void addMarker (uint16_type k, TT const &vs)
add flags vs to the marker type id k
void addMarker (flag_type v)
void addMarker (TT const &vs)
bool hasMarker2 () const
marker_type const & marker2 () const
void setMarker2 (flag_type v)
bool hasMarker3 () const
marker_type const & marker3 () const
void setMarker3 (flag_type v)
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)=default
GeoEntity (GeoEntity &&__me)
GeoEntity & operator= (GeoEntity const &__me)=default
GeoEntity & operator= (GeoEntity &&__me)
~GeoEntity () override
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const noexcept
constexpr uint16_type refDim () const
the dimension of the reference shape
constexpr uint16_type nPoints () const
number of points on the reference shape
constexpr uint16_type nVertices () const
number of vertices on the reference shape
constexpr uint16_type nEdges () const
number of edges on the reference shape
constexpr uint16_type nFaces () const
number of faces on the reference shape
constexpr uint16_type nTopologicalFaces () const
number of topological faces on the reference shape
constexpr uint16_type nGeometricFaces () const
number of faces on the reference shape
constexpr uint16_type nNormals () const
number of normals on the reference shape
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const noexcept
Tells if item is on the boundary.
uint16_type boundaryEntityDimension () const noexcept
maximum dimension of the entity of the element touching the boundary
bool isGhostCell () const noexcept
rank_type processId () const noexcept
void setProcessId (rank_type pid) noexcept
set the processor id of the entity &
rank_type pidInPartition () const noexcept
void setProcessIdInPartition (rank_type pid) noexcept
set the processor id of the entity &
rank_type partitionId () const noexcept
rank_type numberOfPartitions () const noexcept
rank_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< rank_type > const & neighborPartitionIds () const
std::vector< rank_type > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
clear the neighbor partition ids container
FEELPP_DEPRECATED void setIdInOthersPartitions (rank_type pid, size_type id)
set id in a partition pid of the entity
void setIdInOtherPartitions (rank_type pid, size_type id)
void setIdInOtherPartitions (std::map< rank_type, size_type > const &iop)
set (partition,id) in other partitions of the entity
void setIdInOtherPartitions (std::map< rank_type, size_type > &&iop)
set (partition,id) in other partitions of the entity
size_type idInOthersPartitions (rank_type pid) const
std::map< rank_type, size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
clear id in others partitions container
bool active () const
virtual value_type measure () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
set the boundary flag
FEELPP_DEPRECATED void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
set the number of partition the element is linked to
void setNeighborPartitionIds (std::vector< rank_type > const &npids)
void addNeighborPartitionId (rank_type p)
Public Member Functions inherited from Feel::Simplex< 0, 1, Dim >
uint16_type dimension () const
Simplex & operator= (Simplex &&)=default
Simplex & operator= (Simplex const &)=default
Simplex (Simplex &&)=default
Simplex (Simplex const &)=default
uint16_type topologicalDimension () const
Public Member Functions inherited from Feel::Convex< Dim, Order, RDim >
Convex ()
default constructor
Convex (Convex const &)
copy constructor
virtual ~Convex ()
destructor
Convex & operator= (Convex const &o)=default
copy operator
Static Public Attributes
static const bool is_simplex = true
static const uint16_type nDim = Dim
Static Public Attributes inherited from Feel::GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Static Public Attributes inherited from Feel::Simplex< 0, 1, Dim >
static const size_type Geometry
static const bool is_hypercube
static const bool is_simplex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerVolume
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const int numEdges
static const int numFaces
static const int numGeometricFaces
static const uint16_type numNormals
static const uint16_type numPoints
static const int numTopologicalFaces
static const int numVertices
static const int numVolumes
static const uint16_type real_dimension
static constexpr int Shape
static constexpr int shape_v
static const uint16_type topological_dimension
Static Public Attributes inherited from Feel::Convex< Dim, Order, RDim >
static const uint16_type nDim = Dim
static const uint16_type nOrder = Order
static const uint16_type nRealDim = RDim
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type >
static uint16_type eToP (uint16_type const __localEdge, uint16_type const __point)
eToP(i,j) = localId of jth point on ith local edge
static uint16_type fToP (uint16_type const __localFace, uint16_type const __point)
fToP(i,j) = localId of jth point on ith local edge
static uint16_type fToE (uint16_type const __localFace, uint16_type const __edge)
fToE(i,j) = localId of jth edge on ith local face
Static Public Member Functions inherited from Feel::Simplex< 0, 1, Dim >
static uint16_type e2p (uint16_type e, uint16_type p)
Given an edge e in the element and the local index p (0 or 1) of a point in the edge e ,.
static uint16_type f2e (uint16_type f, uint16_type e)
Given a face f in the element and the local index e of an edge in the face f,.
static uint16_type f2eLoc (uint16_type f, uint16_type e)
Given a face f in the element and the global index e of an edge in the face f,.
static uint16_type f2p (uint16_type f, uint16_type p)
Given a face f in the element and the local index p of a point in the face f ,.
static constexpr int getShape ()
handle a shape
static std::string name ()
static uint16_type nPointsOnEdge ()
Returns the number of points per edge.
static uint16_type nPointsOnFace ()
Returns the number of points per face.
static uint16_type nPointsOnVertex ()
Returns the number of points per vertex.
static uint16_type nPointsOnVolume ()
Returns the number of points per volume.
static constexpr int numberOfEdges ()
static constexpr int numberOfGeometricFaces ()
static constexpr int numberOfTopologicalFaces ()
static constexpr int numberOfVertices ()
static constexpr int numberOfVolumes ()
static int polyDims (int n)
static std::string type ()
Member Function Documentation
G()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> matrix_node_type Feel::Geo0D< Dim, T, IndexT >::G () const
Returns
the node data structure
Referenced by Feel::Geo0D< 3 >::operator=(), and Feel::Geo0D< 3 >::vertices().
gDim()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> int Feel::Geo0D< Dim, T, IndexT >::gDim () const
Returns
the geometric dimension of the entity the point belongs to
gTag()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> int Feel::Geo0D< Dim, T, IndexT >::gTag () const
Returns
the geometric dimension of the entity the point belongs to
isParametric()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> bool Feel::Geo0D< Dim, T, IndexT >::isParametric () const
Returns
true if the point has parametric coordinates
isPeriodic()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> bool Feel::Geo0D< Dim, T, IndexT >::isPeriodic () const
Returns
true if the entity is periodic, false otherwise
isVertex()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> bool Feel::Geo0D< Dim, T, IndexT >::isVertex () const
Returns
true if point is a vertex, false otherwise
Attention
DO NOT USE YET, returns always false
masterId()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> index_type Feel::Geo0D< Dim, T, IndexT >::masterId () const
the master id is different from the id in the context of periodic boundary conditions on the slave side
Returns
the master id
measure()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> value_type Feel::Geo0D< Dim, T, IndexT >::measure () const override
Returns
the measure of a point
mesh()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> meshbase_type const* Feel::Geo0D< Dim, T, IndexT >::mesh () const
Returns
the mesh to which this geometric entity belongs to
node()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> node_type const& Feel::Geo0D< Dim, T, IndexT >::node () const
Returns
the node data structure
Referenced by Feel::Sphere::closestPoint(), Feel::Sphere::surfaceCoords(), and Feel::Sphere::unitNormal().
operator==()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> bool Feel::Geo0D< Dim, T, IndexT >::operator== (Geo0D< Dim, T, IndexT > const & geo0d) const
Returns
true if points are equal, false otherwise
parametricCoordinates()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> parametric_node_type const& Feel::Geo0D< Dim, T, IndexT >::parametricCoordinates () const
Returns
the parametric coordinates
Referenced by Feel::Geo0D< 3 >::u(), and Feel::Geo0D< 3 >::v().
setNode()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> void Feel::Geo0D< Dim, T, IndexT >::setNode (node_type const & __n)
set the node coordinates
Parameters
__n the node coordinates
setPoint()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> void Feel::Geo0D< Dim, T, IndexT >::setPoint (uint16_type const , self_type const & p)
set the point coordinates.
This will typically be called when creating faces (points) in 1D.
setTags()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> void Feel::Geo0D< Dim, T, IndexT >::setTags (std::vector< int > const & tags) override virtual
set the tags associated to the points
tags[0] physical region
tags[1] elementary region
tags[2] particular region
Reimplemented from Feel::GeoEntity< Simplex< 0, 1, Dim >, double, uint32_type >.
showMe()
template<uint16_type Dim, typename T , typename IndexT > std::ostream & Feel::Geo0D< Dim, T, IndexT >::showMe (bool verbose = false, std::ostream & c = std::cout) const
show the information about the Geo0D
Parameters
verbose true if verbose mode, false otherwise
c the output stream to use
Returns
the output stream
u()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> value_type Feel::Geo0D< Dim, T, IndexT >::u () const
Returns
the first parametric coordinates
Referenced by Feel::Geo0D< 3 >::setParametricCoordinates().
v()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> value_type Feel::Geo0D< Dim, T, IndexT >::v () const
Returns
the first parametric coordinates
Referenced by Feel::Geo0D< 3 >::setAsVertex(), and Feel::Geo0D< 3 >::setParametricCoordinates().
vertices()
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> matrix_node_type Feel::Geo0D< Dim, T, IndexT >::vertices () const
Returns
the node data structure
Referenced by Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::id().
Constructor & Destructor Documentation
Geo0D() [1/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> Feel::Geo0D< Dim, T, IndexT >::Geo0D ()
default constructor
Geo0D() [2/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> Feel::Geo0D< Dim, T, IndexT >::Geo0D (index_type id, bool boundary = false, bool is_vertex = false) explicit
constructor where I give the id and declare if Geo0D object is on a boundary
Parameters
id identifier of the Geo0D
boundary true if on the boundary, false otherwise
is_vertex true if the point is a vertex
Returns
Geo0D() [3/9]
template<uint16_type Dim, typename T , typename IndexT > Feel::Geo0D< Dim, T, IndexT >::Geo0D (index_type id, value_type x, value_type y, value_type z, bool boundary = false, bool is_vertex = false) explicit
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Parameters
id identifier of the node
x x-coordinate of the node
y y-coordinate of the node
z z-coordinate of the node
boundary true if on the boundary, false otherwise
is_vertex true if the point is a vertex
Geo0D() [4/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> Feel::Geo0D< Dim, T, IndexT >::Geo0D (value_type x, value_type y, value_type z)
give the point coordinate
Parameters
x x-coordinate of the node
y y-coordinate of the node
z z-coordinate of the node
Geo0D() [5/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> template<typename TheNodeType > Feel::Geo0D< Dim, T, IndexT >::Geo0D (index_type id, TheNodeType const & __x, bool boundary = false, bool is_vertex = false, typename std::enable_if<!is_ptr_or_shared_ptr< TheNodeType >::value >::type * = nullptr)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Parameters
id identifier
__x node coordinate
boundary true if on the boundary, false otherwise
is_vertex true if the point is a vertex
Geo0D() [6/9]
template<uint16_type Dim, typename T , typename IndexT > Feel::Geo0D< Dim, T, IndexT >::Geo0D (index_type id, const node_type * __x, bool boundary = false, bool is_vertex = false, bool isView = false)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Parameters
id identifier
__x node coordinate (shared_ptr)
boundary true if on the boundary, false otherwise
is_vertex true if the point is a vertex
Geo0D() [7/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> Feel::Geo0D< Dim, T, IndexT >::Geo0D (index_type id, self_type const & __x, bool boundary = false, bool is_vertex = false, bool isView = false)
constructor where I give the id, the point coordinate and I declare if the Geo0D object is on a boundary
Parameters
id identifier
__x another Geo0D object
boundary true if on the boundary, false otherwise
is_vertex true if the point is a vertex
isView true if the node is shared
Geo0D() [8/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> Feel::Geo0D< Dim, T, IndexT >::Geo0D (node_type const & __x)
the point coordinate
Parameters
__x node coordinate
Geo0D() [9/9]
template<uint16_type Dim, typename T = double, typename IndexT = uint32_type> template<typename AE > Feel::Geo0D< Dim, T, IndexT >::Geo0D (ublas::vector_expression< AE > const & __expr)
the point coordinate expression
Parameters
__expr expression for the coordinates