Feel++: Feel::Partitioner< MeshType > Class Template Reference
Feel::Partitioner< MeshType > Class Template Reference abstract
Description
template<typename MeshType>
class Feel::Partitioner< MeshType >
partitioner class
The Partitioner class provides a uniform interface for partitioning algorithms.
It takes a reference to a MeshBase object as input, which it will partition into a number of subdomains.
Public Types
using clone_ptrtype = std::unique_ptr< partitioner_type >
using element_type = typename mesh_type::element_type
using face_type = typename mesh_type::face_type
using mesh_ptrtype = std::shared_ptr< mesh_type >
using mesh_type = decay_type< MeshType >
using partitioner_type = Partitioner< mesh_type >
using point_type = typename mesh_type::point_type
using range_element_type = elements_reference_wrapper_t< mesh_type >
Public Member Functions
virtual void attachWeights (std::vector< double > const &weights)
Attach weights that can be used for partitioning.
virtual clone_ptrtype clone () const =0
Creates a new partitioner of this type and returns it in an std::unique_ptr.
void partition (mesh_ptrtype mesh)
Partition the Mesh into Environment::numberOfProcessors() parts.
void partition (mesh_ptrtype mesh, rank_type n, std::vector< range_element_type > const &partitionByRange=std::vector< range_element_type >())
Partition the Mesh into n parts.
Partitioner ()
Constructor.
void repartition (mesh_ptrtype mesh)
Repartitions the Mesh into Environment::numberOfProcessors() parts.
void repartition (mesh_ptrtype mesh, rank_type n)
Repartitions the Mesh into n parts.
virtual ~Partitioner ()=default
Destructor.
Static Public Member Functions
static void setNodeProcessorIds (mesh_ptrtype mesh)
This function is called after partitioning to set the processor IDs for the nodes.
Protected Member Functions
virtual void partitionImpl (mesh_ptrtype mesh, rank_type n, std::vector< range_element_type > const &partitionByRange=std::vector< range_element_type >())=0
This is the actual partitioning method which must be overloaded in derived classes.
virtual void repartitionImpl (mesh_ptrtype mesh, rank_type n)
This is the actual re-partitioning method which can be overloaded in derived classes.
void singlePartition (mesh_ptrtype mesh)
Trivially "partitions" the mesh for one processor.
Protected Attributes
std::vector< double > M_weights
The weights that might be used for partitioning.
Static Protected Attributes
static const dof_id_type communication_blocksize = 1000000
The blocksize to use when doing blocked parallel communication.
Member Function Documentation
attachWeights()
template<typename MeshType > virtual void Feel::Partitioner< MeshType >::attachWeights (std::vector< double > const & weights) virtual
Attach weights that can be used for partitioning.
This ErrorVector should be exactly the same on every processor and should have mesh->max_elem_id() entries.
clone()
template<typename MeshType > virtual clone_ptrtype Feel::Partitioner< MeshType >::clone () const pure virtual
Creates a new partitioner of this type and returns it in an std::unique_ptr.
This is used when copying meshes, and must be overloaded in the derived classes.
Implemented in Feel::PartitionerMetis< MeshType >, and Feel::PartitionerLinear< MeshType >.
partition() [1/2]
template<typename MeshType > void Feel::Partitioner< MeshType >::partition (mesh_ptrtype mesh)
Partition the Mesh into Environment::numberOfProcessors() parts.
The partitioner currently does not modify the subdomain_id of each element. This number is reserved for things like material properties, etc.
References Feel::Environment::numberOfProcessors().
partition() [2/2]
template<typename MeshType > void Feel::Partitioner< MeshType >::partition (mesh_ptrtype mesh, rank_type n, std::vector< range_element_type > const & partitionByRange = std::vector<range_element_type>())
Partition the Mesh into n parts.
The partitioner currently does not modify the marker1 but rather marker3 of each element. marker1 is reserved for things like material properties, etc.
Referenced by Feel::partitionMesh().
partitionImpl()
template<typename MeshType > virtual void Feel::Partitioner< MeshType >::partitionImpl (mesh_ptrtype mesh, rank_type n, std::vector< range_element_type > const & partitionByRange = std::vector< range_element_type >()) protected pure virtual
This is the actual partitioning method which must be overloaded in derived classes.
It is called via the public partition() method above by the user.
Implemented in Feel::PartitionerMetis< MeshType >.
Referenced by Feel::Partitioner< MeshType >::repartitionImpl().
repartition() [1/2]
template<typename MeshType > void Feel::Partitioner< MeshType >::repartition (mesh_ptrtype mesh)
Repartitions the Mesh into Environment::numberOfProcessors() parts.
This is required since some partitoning algorithms can repartition more efficiently than computing a new partitioning from scratch.
References Feel::Environment::numberOfProcessors().
repartition() [2/2]
template<typename MeshType > void Feel::Partitioner< MeshType >::repartition (mesh_ptrtype mesh, rank_type n)
Repartitions the Mesh into n parts.
This is required since some partitoning algorithms can repartition more efficiently than computing a new partitioning from scratch. The default behavior is to simply call this->partition(mesh,n)
repartitionImpl()
template<typename MeshType > virtual void Feel::Partitioner< MeshType >::repartitionImpl (mesh_ptrtype mesh, rank_type n) protected virtual
This is the actual re-partitioning method which can be overloaded in derived classes.
Note that the default behavior is to simply call the partition function.
References Feel::Partitioner< MeshType >::partitionImpl().
setNodeProcessorIds()
template<typename MeshType > void Feel::Partitioner< MeshType >::setNodeProcessorIds (mesh_ptrtype mesh) static
This function is called after partitioning to set the processor IDs for the nodes.
By definition, a Node's processor ID is the minimum processor ID for all of the elements which share the node.
singlePartition()
template<typename MeshType > void Feel::Partitioner< MeshType >::singlePartition (mesh_ptrtype mesh) protected
Trivially "partitions" the mesh for one processor.
Simply loops through the elements and assigns all of them to processor 0. Is is provided as a separate function so that derived classes may use it without reimplementing it.
References Feel::elements(), and Feel::faces().
Member Data Documentation
communication_blocksize
template<typename MeshType > const dof_id_type Feel::Partitioner< MeshType >::communication_blocksize = 1000000 static protected
The blocksize to use when doing blocked parallel communication.
This limits the maximum vector size which can be used in a single communication step.
Constructor & Destructor Documentation
~Partitioner()
template<typename MeshType > virtual Feel::Partitioner< MeshType >::~Partitioner () virtual default
Destructor.
Virtual so that we can derive from this class.