Feel++: Feel::Info Class Reference
Feel::Info Class Reference
information provider for versioning and installation directories
Public Member Functions
Info (Info const &)=delete
Info & operator= (Info const &)=delete
Static Public Member Functions
static char const * buildId ()
Build id is the Feel compilation date/time (e.g 2005/12/07 - 18:18:09)
static fs::path casesdir ()
casesdir directory
static fs::path datadir ()
datadir directory
static GitMetadata gitMetadata ()
get git metadata
static fs::path libdir ()
libdir directory
static fs::path plugindir ()
plugindir directory
static fs::path prefix ()
prefix directory
static fs::path relativeCasesdir ()
relative casesdir directory
static fs::path relativeDatadir ()
relative datadir directory
static fs::path relativeLibdir ()
relative libdir directory
static fs::path relativePlugindir ()
relative plugindir directory
static char const * revision ()
Revision number (Subversion revision).
static unsigned long long version ()
Returns the encoded number of FEEL's version, see the FEELPP_VERSION macro.
static unsigned int versionMajor ()
Returns the major number of FEEL's version, e.g.
static unsigned int versionMicro ()
Returns the micro number of FEEL's version, e.g.
static unsigned int versionMinor ()
Returns the minor number of FEEL's version, e.g.
static char const * versionString ()
Returns the FEEL version as string, e.g.
Detailed Description
information provider for versioning and installation directories
Author
Christophe Prud'homme
Member Function Documentation
buildId()
char const * Feel::Info::buildId () static
Build id is the Feel compilation date/time (e.g 2005/12/07 - 18:18:09)
This is a unique id for each release. It permits Feel to check if a more recent version of itself exist. Format: year/month/day hour:minutes:seconds
casesdir()
fs::path Feel::Info::casesdir () static
casesdir directory
the directory where cases are installed
References prefix().
Referenced by relativeCasesdir().
datadir()
fs::path Feel::Info::datadir () static
datadir directory
The directory for installing idiosyncratic read-only architecture-independent data files for this program
Referenced by relativeDatadir().
libdir()
fs::path Feel::Info::libdir () static
libdir directory
The directory where libraries are installed
References prefix().
Referenced by relativeLibdir().
plugindir()
fs::path Feel::Info::plugindir () static
plugindir directory
The directory where plugins are installed
References prefix().
Referenced by relativePlugindir().
prefix()
fs::path Feel::Info::prefix () static
prefix directory
A prefix used in constructing the default values of the variables listed below. The default value of prefix should be /usr/local. When building the complete GNU system, the prefix will be empty and /usr will be a symbolic link to /.
Referenced by casesdir(), libdir(), plugindir(), relativeCasesdir(), relativeDatadir(), relativeLibdir(), and relativePlugindir().
relativeLibdir()
fs::path Feel::Info::relativeLibdir () static
relative libdir directory
Returns
fs::path relative path to libdir
References libdir(), and prefix().
version()
unsigned long long Feel::Info::version () static
Returns the encoded number of FEEL's version, see the FEELPP_VERSION macro.
In contrary to that macro this function returns the number of the actually installed FEEL version, not the number of the FEEL version that was installed when the program was compiled.
Returns
the version number, encoded in a single unsigned long long
Since
0.7
versionMajor()
unsigned int Feel::Info::versionMajor () static
Returns the major number of FEEL's version, e.g.
0 for FEEL 0.7
Returns
the major version number
Since
0.7
versionMicro()
unsigned int Feel::Info::versionMicro () static
Returns the micro number of FEEL's version, e.g.
0 for FEEL 0.7.0
Returns
the extra information
Since
0.7
versionMinor()
unsigned int Feel::Info::versionMinor () static
Returns the minor number of FEEL's version, e.g.
7 for FEEL 0.7.0
Returns
the minor version number
Since
0.7
versionString()
char const * Feel::Info::versionString () static
Returns the FEEL version as string, e.g.
"0.7.0".
Returns
the FEEL version. You can keep the string forever
Since
0.7