Feel++: Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim > Class Template Reference
Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim > Class Template Reference
Description
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange>
template<size_type context_v, typename ElementType, int SubEntityCoDim = 1>
class Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >
Context for the geometric mapping depend on a node in the reference element
Accessors
gm_ptrtype const & geometricMapping () const
uint16_type N () const
uint16_type P () const
element_type const & element () const
element_type const & element_c () const
bool isOnFace () const
bool isOnSubEntity () const
uint16_type nPoints () const
uint16_type nComputedPoints () const
in the case of linear transformation, the jacobian is constant and we don't have to compute the information at all points, only at one
matrix_node_t_type const & xRefs () const
ublas::matrix_column< matrix_node_t_type const > xRef (int q) const
matrix_type const & xReal () const
ublas::matrix_column< matrix_type const > xReal (int q) const
template<typename GeoMapT = gm_type>
value_type J (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
Get the jacobian of the transformation at the q -th point.
template<typename GeoMapT = gm_type>
value_type J (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
matrix_type const & G () const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & B (int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
Get the inverse of the transformation at the i -th point.
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & B (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & B (int c1, int c2, int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & B (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & localBasis (int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & localBasis (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type::ColXpr const & basisN (int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type::ColXpr const & basisN (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & localBasis (int c1, int c2, int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & localBasis (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & basisN (int c1, int c2, int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & basisN (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_nn_type const & projectorTangent (int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_nn_type const & projectorTangent (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & projectorTangent (int c1, int c2, int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & projectorTangent (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & K (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_matrix_np_type const & K (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & K (int c1, int c2, int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
vector_eigen_matrix_np_type const & K (std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & K (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
hessian_type const & hessian (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
hessian_type const & hessian (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
boost::multi_array< value_type, 4 > const & B3 () const
the tensor of rank 4 for the transformation of 2nd order derivatives from the reference element to the real element.
node_t_type barycenterRef () const
node_t_type barycenterReal () const
bool isOnConvexSurface () const
tell whether the point is on the surface of the convex
node_t_type const & refNormal (int) const
template<typename GeoMapT = gm_type>
value_type normalNorm (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
get the norm_2 of normal of the real element
template<typename GeoMapT = gm_type>
value_type normalNorm (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & normal (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
get the normal of the real element
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & normal (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
vector_eigen_vector_n_type const & unitNormal (std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & unitNormal (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & unitNormal (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & unitNormal (int n, int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & unitNormal (int n, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & tangent (std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & tangent (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
scaled tangent at point
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & tangent (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & unitTangent (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & unitTangent (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
eigen_vector_n_type const & unitTangent (int c1, int c2, int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> *=nullptr) const
template<typename GeoMapT = gm_type>
value_type const & unitTangent (int c1, int c2, int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> *=nullptr) const
size_type id () const
get the id of the element
uint16_type faceId () const
bool elementIsAFace () const
Marker1 marker (uint16_type k) const
get the marker of the element
Marker1 marker () const
get the marker of the element
Marker1 marker2 () const
get the marker2 of the element
Marker1 marker3 () const
get the marker3 of the element
Marker1 entityMarker (uint16_type k=1) const
get the marker of the face of the element
size_type id1 () const
get the id of the first element containing the element
uint16_type idIn1 () const
get the local id of the element in the first element containing the element
size_type id2 () const
get the id of the second element containing the element
uint16_type idIn2 () const
get the local id of the element in the second element containing the element
value_type radiusEstimate () const
get an estimate of the radius of the current element
value_type h () const
value_type hMin () const
value_type hFace () const
Get max length of the edge of the face of the element.
value_type meas () const
value_type measurePointElementNeighbors () const
value_type measFace () const
permutation_type permutation () const
precompute_ptrtype const & pc () const
std::vector< std::map< permutation_type, precompute_ptrtype > > const & pcFaces () const
size_type dynamicContext () const
Mutators
class boost::serialization::access
void setPc (precompute_ptrtype const &__pc)
set some precomputed data on the reference element
void setPcFaces (std::vector< std::map< permutation_type, precompute_ptrtype >> const &__pcfaces)
void edgeTangent (int edgeId, ublas::vector< value_type > &t, bool scaled=false) const
void faceNormal (int faceId, ublas::vector< value_type > &n, bool scaled=false) const
template<typename EltType , typename NeighborGeoType >
bool updateFromNeighborMatchingFace (EltType const &elt, uint16_type face_in_elt, std::shared_ptr< NeighborGeoType > const &gmc)
update the geomap through a neighbor matching face.
Public Types
using eigen_matrix_nn_type = eigen_matrix_type< NDim, NDim, value_type >
using eigen_matrix_np_type = eigen_matrix_type< NDim, PDim, value_type >
using eigen_matrix_nx_type = eigen_matrix_type< NDim, Eigen::Dynamic, value_type >
using eigen_matrix_pp_type = eigen_matrix_type< PDim, PDim, value_type >
using eigen_matrix_px_type = eigen_matrix_type< PDim, Eigen::Dynamic, value_type >
using eigen_matrix_xn_type = eigen_matrix_type< Eigen::Dynamic, NDim, value_type >
using eigen_matrix_xp_type = eigen_matrix_type< Eigen::Dynamic, PDim, value_type >
typedef ElementType element_type
typedef std::shared_ptr< gm_type > gm_ptrtype
typedef mpl::if_< mpl::equal_to< mpl::int_< PDim >, mpl::int_< NDim > >, mpl::identity< GeoMap< Dim, Order, NDim, T, Entity, PP > >, typename mpl::if_< mpl::and_< mpl::greater_equal< mpl::int_< NDim >, mpl::int_< 1 > >, mpl::equal_to< mpl::int_< PDim >, mpl::int_< NDim - 1 > > >, mpl::identity< typename GeoMap< NDim, Order, NDim, T, Entity, PP >::face_gm_type >, typename mpl::if_< mpl::and_< mpl::equal_to< mpl::int_< NDim >, mpl::int_< 3 > >, mpl::equal_to< mpl::int_< PDim >, mpl::int_< NDim - 2 > > >, mpl::identity< typename GeoMap< NDim, Order, NDim, T, Entity, PP >::edge_gm_type >, mpl::identity< boost::none_t > >::type >::type >::type::type gm_type
typedef std::shared_ptr< gmc_type > gmc_ptrtype
typedef Context< contextv, ElementType, SubEntityCoDim > gmc_type
using hessian_type = tensor3_fixed_size_t< NDim, PDim, PDim, value_type >
typedef normals_type::const_iterator normal_const_iterator
typedef node_t_type normal_type
typedef ublas::vector< normal_type > normals_type
typedef element_type::template PermutationSubEntity< SubEntityCoDim > permutation_type
typedef gm_type::precompute_ptrtype precompute_ptrtype
typedef tangents_type::const_iterator tangent_const_iterator
typedef node_t_type tangent_type
typedef ublas::vector< tangent_type > tangents_type
using using_vectices_t = mpl::int_< 0 >
typedef gm_type::value_type value_type
using vector_eigen_matrix_nn_type = vector_eigen_matrix_type< NDim, NDim, value_type >
using vector_eigen_matrix_np_type = vector_eigen_matrix_type< NDim, PDim, value_type >
using vector_eigen_matrix_pp_type = vector_eigen_matrix_type< PDim, PDim, value_type >
using vector_hessian_type = vector_tensor3_fixed_size_t< NDim, PDim, PDim, value_type >
Public Member Functions
gmc_ptrtype clone ()
clone the context
Context (Context &&)=default
Context (Context const &)=default
Context (gm_ptrtype __gm, element_type const &__e, precompute_ptrtype &__pc, uint16_type __f, using_vectices_t)
Context (gm_ptrtype __gm, element_type const &__e, precompute_ptrtype const &__pc=precompute_ptrtype(), uint16_type __f=invalid_uint16_type_value, size_type dynctx=0)
Context (gm_ptrtype __gm, element_type const &__e, std::vector< std::map< permutation_type, precompute_ptrtype > > &__pc, uint16_type __f, size_type dynctx=0)
Context (gmc_ptrtype &p)
template<size_type CTX = context>
bool resizeGradient ()
void setElement (element_type const &__e)
template<size_type CTX = context>
void update (element_type const &__e, precompute_ptrtype const &__pc, uint16_type __f=invalid_uint16_type_value, bool updatePc=true)
template<size_type CTX = context>
void update (element_type const &__e, uint16_type __f, permutation_type __perm, bool __updateJacobianCtx=true)
template<size_type CTX = context>
void update (element_type const &__e, uint16_type __f, precompute_ptrtype pc, using_vectices_t)
template<size_type CTX = context>
void update (element_type const &__e, uint16_type __f, using_vectices_t)
update information on this context
template<size_type CTX = context>
void update (element_type const &__e, uint16_type __f=invalid_uint16_type_value, bool updatePC=true)
update information on this context
template<size_type CTX = context>
void updateGradient (int q)
template<size_type CTX = context>
void updateOnFace (uint16_type __f, bool updatePC=true)
update geomap data only on face, element has not been changed
Static Public Attributes
static const bool condition = ((PDim == NDim) || ((NDim >= 1) && (PDim == NDim - 1)))
static const size_type context = context_v
static const size_type contextv = context_v
static const bool is_linear = (trans == fem::LINEAR)
static const uint16_type NDim = ElementType::nRealDim
static const uint16_type nDim = NDim
static const uint16_type PDim = ElementType::nDim
static const int subEntityCoDim = SubEntityCoDim
static const fem::transformation_type trans = geometric_mapping_type::trans
Member Function Documentation
B()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_matrix_np_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::B (int i, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Get the inverse of the transformation at the i -th point.
Parameters
i the index of point where the pseudo-inverse is requested
Returns
the pseudo inverse of the transformation
B3()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> boost::multi_array<value_type, 4> const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::B3 () const
the tensor of rank 4 for the transformation of 2nd order derivatives from the reference element to the real element.
The tensor has the shape \([N,N,P,P]\).
Returns
the tensor of rank 4
barycenterReal()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> node_t_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::barycenterReal () const
Returns
the barycenter of the geometric nodes
barycenterRef()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> node_t_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::barycenterRef () const
Returns
the barycenter of the reference nodes
dynamicContext()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> size_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::dynamicContext () const
Returns
the dynamic context associated to the geomap
element()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> element_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::element () const
Returns
the real element to which this context is associated
elementIsAFace()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::elementIsAFace () const
Returns
true if the element is a face, false otherwise
entityMarker()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> Marker1 Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::entityMarker (uint16_type k = 1) const
get the marker of the face of the element
Returns
the marker of the face of the element
G()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> matrix_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::G () const
Returns
the matrix associated with the geometric nodes
geometricMapping()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> gm_ptrtype const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::geometricMapping () const
Returns
the geometric mapping associated with the context
References Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::nComputedPoints().
h()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::h () const
Returns
the max length of the edges of the element
hFace()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::hFace () const
Get max length of the edge of the face of the element.
Returns
the max length of the edge of the face of the element
hMin()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::hMin () const
Returns
the min length of the edges of the element
id()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> size_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::id () const
get the id of the element
Returns
the id of the element
id1()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> size_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::id1 () const
get the id of the first element containing the element
Returns
the id of the first element containing the element
id2()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> size_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::id2 () const
get the id of the second element containing the element
Returns
the id of the second element containing the element
idIn1()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::idIn1 () const
get the local id of the element in the first element containing the element
Returns
the local id of element in the first element containing the element
idIn2()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::idIn2 () const
get the local id of the element in the second element containing the element
Returns
the local id of element in the second element containing the element
isOnConvexSurface()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::isOnConvexSurface () const
tell whether the point is on the surface of the convex
Returns
true if the point is on the surface, false otherwise
isOnFace()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::isOnFace () const
Returns
true if geomap assocated to a face, false otherwise
isOnSubEntity()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::isOnSubEntity () const
Returns
true if geomap assocated to a face, edge or point, false otherwise
Referenced by Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::clone().
J()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::J (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Get the jacobian of the transformation at the q -th point.
Parameters
q index of the point where the jacobian is requested
Returns
the jacobian of the transformation
marker() [1/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> Marker1 Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::marker () const
get the marker of the element
Returns
the marker of the element
marker() [2/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> Marker1 Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::marker (uint16_type k) const
get the marker of the element
Returns
the marker of the element
marker2()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> Marker1 Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::marker2 () const
get the marker2 of the element
Returns
the marker2 of the element
marker3()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> Marker1 Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::marker3 () const
get the marker3 of the element
Returns
the marker3 of the element
N()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::N () const
Returns
the dimension of the space of the real element
References Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::nComputedPoints().
nComputedPoints()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::nComputedPoints () const
in the case of linear transformation, the jacobian is constant and we don't have to compute the information at all points, only at one
Returns
the number of points at which the geometric mapping is really computed.
Referenced by Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::geometricMapping(), Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::N(), and Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::P().
normal()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::normal (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
get the normal of the real element
Returns
the normal of the real element
normalNorm()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::normalNorm (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
get the norm_2 of normal of the real element
Returns
the norm_2 of the normal of the real element
nPoints()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::nPoints () const
Returns
the number of points to transfer from reference to real element
P()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> uint16_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::P () const
Returns
the dimension of the space of the reference element
References Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::nComputedPoints().
pc()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> precompute_ptrtype const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::pc () const
Returns
the precompute type
pcFaces()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> std::vector<std::map<permutation_type, precompute_ptrtype> > const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::pcFaces () const
Returns
the precompute type for the faces
permutation()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> permutation_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::permutation () const
Returns
the permutation associated with the face
radiusEstimate()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> value_type Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::radiusEstimate () const
get an estimate of the radius of the current element
Returns
the radius estimate of the current element
tangent() [1/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::tangent (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
scaled tangent at point
Parameters
q index of the point at which the tangent is evaluated
Returns
the scaled tamgent at the point
tangent() [2/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::tangent (std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Returns
the scaled tangent to the current face
unitNormal() [1/3]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::unitNormal (int q, std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Returns
the unit_normal at point q
unitNormal() [2/3]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::unitNormal (int q, std::enable_if_t<!is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Returns
the unit_normal at point q
unitNormal() [3/3]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename GeoMapT = gm_type> vector_eigen_vector_n_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::unitNormal (std::enable_if_t< is_linear_polynomial_v< GeoMapT >> * = nullptr) const
Returns
the unit normal of the real element
update() [1/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<size_type CTX = context> void Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::update (element_type const & __e, uint16_type __f, using_vectices_t)
update information on this context
update the coordinate of the real points
update the pseudo-inverse of the gradient of the transformation
compute \(K(x_{\mathrm{ref}}) = G \nabla_{\mathrm{ref}} \phi(x_{\mathrm{ref}}) \) where \(G \) is the matrix representing the geometric nodes nDof x dim
compute \(B(x_{\mathrm{ref}}) = K (K^T K)^{-1} \) where \(G \) is the matrix representing the geometric nodes nDof x dim update geometric only using vertices information
Referenced by Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::clone().
update() [2/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<size_type CTX = context> void Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::update (element_type const & __e, uint16_type __f = invalid_uint16_type_value, bool updatePC = true)
update information on this context
update the coordinate of the real points
update the pseudo-inverse of the gradient of the transformation
compute \(K(x_{\mathrm{ref}}) = G \nabla_{\mathrm{ref}} \phi(x_{\mathrm{ref}}) \) where \(G \) is the matrix representing the geometric nodes nDof x dim
compute \(B(x_{\mathrm{ref}}) = K (K^T K)^{-1} \) where \(G \) is the matrix representing the geometric nodes nDof x dim
updateFromNeighborMatchingFace()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> template<typename EltType , typename NeighborGeoType > bool Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::updateFromNeighborMatchingFace (EltType const & elt, uint16_type face_in_elt, std::shared_ptr< NeighborGeoType > const & gmc)
update the geomap through a neighbor matching face.
Matching means that the points coordinates from both geomap are the same up to a permutation. We compute here the permutation that ensures this and update the geomap accordingly
Returns
true if the permutation has been found and the geomap updated, false otherwise.
xReal() [1/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> matrix_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::xReal () const
Returns
the node in the real element
xReal() [2/2]
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> ublas::matrix_column<matrix_type const> Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::xReal (int q) const
Returns
the node in the real element
xRef()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> ublas::matrix_column<matrix_node_t_type const> Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::xRef (int q) const
Returns
the q-th point in the reference convex
xRefs()
template<uint16_type Dim, uint16_type Order, uint16_type RealDim, typename T = double, template< uint16_type, uint16_type, uint16_type > class Entity = Simplex, template< uint16_type, template< uint16_type RDim > class PolySetType, typename ContinuityType, template< class, uint16_type, class > class Pts, uint16_type > class PP = Lagrange> template<size_type context_v, typename ElementType , int SubEntityCoDim = 1> matrix_node_t_type const& Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::Context< context_v, ElementType, SubEntityCoDim >::xRefs () const
Returns
the set of points in the reference convex