Feel++: Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage > Class Template Reference
Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage > Class Template Reference
Feelpp » Mesh
Description
template<uint16_type Dim, typename GEOSHAPE, typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false>
class Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >
class for 1D elements
In the 2D case, we store the size_types of the adjacent 2D elements and their relative position.
Friends
class boost::serialization::access
Public Types
typedef super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef std::array< point_type *, numLocalVertices >::const_iterator face_const_iterator
typedef std::array< point_type *, numLocalVertices >::iterator face_iterator
typedef super::face_permutation_type face_permutation_type
typedef GEOSHAPE GeoShape
using index_type = typename super::index_type
typedef super::node_type node_type
typedef super::permutation_type permutation_type
typedef super::point_type point_type
typedef GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage > self_type
using size_type = typename super::size_type
typedef GeoND< Dim, GEOSHAPE, T, IndexT, typename mpl::if_< mpl::bool_< PointTypeIsSubFaceOf >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage > >, T, IndexT > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, T, IndexT > > >::type::type, UseMeasuresStorage > super
typedef SubFace super2
typedef super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoND< Dim, GEOSHAPE, double, uint32_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, false >
typedef super::edge_permutation_type edge_permutation_type
typedef self_type element_type
typedef super::face_permutation_type face_permutation_type
typedef super::face_type face_type
typedef GEOSHAPE GeoShape
typedef GetGm< 1 >::ptrtype gm1_ptrtype
typedef GetGm< 1 >::type gm1_type
typedef GetGm< nOrder >::ptrtype gm_ptrtype
typedef GetGm< nOrder >::type gm_type
using index_type = uint32_type
typedef matrix_node< value_type >::type matrix_node_type
typedef node< value_type >::type node_type
typedef mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 1 > >, mpl::identity< vertex_permutation_type >, typename mpl::if_< mpl::equal_to< mpl::int_< nDim >, mpl::int_< 2 > >, mpl::identity< edge_permutation_type >, mpl::identity< face_permutation_type > >::type >::type::type permutation_type
typedef std::vector< point_type * >::const_iterator point_const_iterator
typedef std::vector< point_type * >::iterator point_iterator
using point_type = PointType
typedef mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type PointType
typedef GetImMeasure< 1 >::type quad_meas1_type
typedef GetImMeasure< nOrder >::type quad_meas_type
typedef gm1_type::super::reference_convex_type reference_convex1_type
typedef gm_type::super::reference_convex_type reference_convex_type
typedef GeoND< Dim, GEOSHAPE, value_type, index_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, UseMeasuresStorage > self_type
using size_type = index_type
typedef double value_type
typedef super::vertex_permutation_type vertex_permutation_type
Public Types inherited from Feel::GeoEntity< GEOSHAPE, double >
typedef GEOSHAPE super
typedef GeoEntity< GEOSHAPE, double, uint32_type > GeoShape
typedef GeoEntity< GEOSHAPE, double, uint32_type > self_type
typedef double value_type
using index_type = uint32_type
using size_type = index_type
typedef super::topological_face_type face_type
typedef face_type GeoBShape
typedef GEOSHAPE ::edge_permutation_type edge_permutation_type
typedef GEOSHAPE ::face_permutation_type face_permutation_type
typedef GEOSHAPE convex_type
using reference_convex_type = Reference< GEOSHAPE, nDim, nOrder, nRealDim, TT >
using marker_type = Marker< flag_type >
Public Types inherited from Feel::SubFaceOfNone< 0 >
typedef boost::tuple< size_type, size_type, uint16_type > element_connectivity_type
using index_type = uint32_type
using size_type = index_type
Public Member Functions
BOOST_MPL_ASSERT_MSG ((condition), INVALID_ELEMENT_REAL_DIMENSION,(mpl::int_< Dim >, mpl::int_< nRealDim >, GEOSHAPE))
uint16_type boundaryEntityDimension () const
point_type const & edge (uint16_type i) const
point_type & face (uint16_type i)
point_type const & face (uint16_type i) const
vertex_permutation_type facePermutation (uint16_type) const
point_type * facePtr (uint16_type i)
point_type const * facePtr (uint16_type i) const
std::pair< face_iterator, face_iterator > faces ()
std::pair< face_const_iterator, face_const_iterator > faces () const
std::vector< size_type > facesId () const
GeoElement1D (GeoElement1D &&g)
GeoElement1D (GeoElement1D const &g)=default
copy consttructor
GeoElement1D (size_type id=0)
default constructor, make it explicit to avoid implict inversion to size_type
bool hasFace (uint16_type i) const
size_type id () const
bool isGhostCell () const
bool isGhostFace () const
bool isInterProcessDomain () const
bool isOnBoundary () const
uint8_type map (uint8_type k_1) const
MeshBase const * mesh () const
GeoElement1D & operator= (GeoElement1D &&g)
GeoElement1D & operator= (GeoElement1D const &g)=default
copy operator
rank_type partition1 () const
rank_type partition2 () const
edge_permutation_type permutation (uint16_type) const
vertex_permutation_type permutation (uint16_type, mpl::int_< 1 >) const override
rank_type processId () const
void setFace (uint16_type const i, point_type const &p)
Inserts a point as face of the edge geometric element.
void setMap (uint8_type k_1, uint8_type k_2)
~GeoElement1D () override
destructor
Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, double, uint32_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, false >
void applyDisplacement (int i, ublas::vector< double > const &u)
FEELPP_DEPRECATED void applyDisplacementG (int i, ublas::vector< double > const &u)
node_type barycenter () const
point_iterator beginPoint ()
point_const_iterator beginPoint () const
GeoND< Dim, GEOSHAPE, double, uint32_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, UseMeasuresStorage >::value_type computeFaceMeasureImpl (QuadType const &thequad, std::shared_ptr< CtxFaceType > &ctxf, uint16_type f) const
point_iterator endPoint ()
point_const_iterator endPoint () const
void exchangePoints (const uint16_type otn[numPoints])
Exchange Points.
node_type faceBarycenter (uint16_type f) const
FEELPP_DEPRECATED matrix_node_type faceBarycenters () const
value_type faceMeasure (uint16_type f) const
Eigen::Matrix< value_type, numTopologicalFaces, 1 > faceMeasures () const
uint16_type faceToOppositePoint (uint16_type const _localFace, uint16_type const _point) const
faceToOppositePoint(i,j) = localId of jth opposite point to ith local face
matrix_node_type G () const
matrix of geometric nodes retrieve the matrix of geometric nodes (Dim x NumPoints) the matrix is column oriented, the column i contains the coordinate of the i-th geometric node of the element
GeoND ()
default constructor
GeoND (GeoND &&e)
GeoND (GeoND const &e)=default
GeoND (size_type id)
constructor from an id
gm_ptrtype gm () const
return the geometric mapping if a mesh was set
gm1_ptrtype gm1 () const
return the geometric mapping if a mesh was set
value_type h () const
get the max length of the edges of the element
size_type hasNeighbor (uint16_type n) const
bool hasPoints () const
bool hasPointWithMarker () const
value_type hEdge (uint16_type f) const
value_type hFace (uint16_type f) const
get the max length of the edge in the local face f
value_type hMin () const
get the minimum edge length in the element
bool isAnticlockwiseOriented () const
Determines if the local numbering of a 2D element is oriented anticlockwise.
bool isNeighbor (self_type const &G) const
bool isValid () const
check if an element is valid: check points are != nullptr
value_type measure () const override
MeshBase const * mesh () const
size_type neighbor (uint16_type n) const
Neighbors are stored as pointers and some of them can be null pointers if the corresponding face is on the boundary.
uint16_type nNeighbors () const
the number of neighbors is equal to the number of faces.
uint16_type nOppositePointsPerFace () const
get the number of opposite points per face
node_type normal (uint16_type f) const
matrix_node_type normals () const
uint16_type nPoints () const
size_type numberOfPointElementNeighbors () const
GeoND & operator= (GeoND &&e)
GeoND & operator= (GeoND const &)=default
permutation_type permutation (uint16_type) const
point_type & point (uint16_type i)
It returns the reference to an point object (possibly derived from Geo0D)
point_type const & point (uint16_type i) const
It returns the reference to an point object (possibly derived from Geo0D)
std::set< size_type > pointElementNeighborIds () const
point_type * pointPtr (uint16_type i)
It returns the pointer to an point object (possibly derived from Geo0D)
point_type const * pointPtr (uint16_type i) const
It returns the pointer to an point object (possibly derived from Geo0D)
std::vector< point_type * > & points ()
std::vector< point_type * > const & points () const
point_type & reversepoint (uint16_type const i)
The ith point (starting from the end)
point_type const & reversepoint (uint16_type const i) const
The ith point (starting from the end)
void setCommonData (GeoNDCommon< self_type > *commonData)
set common data
void setMeasurePointElementNeighbors (value_type meas)
void setNeighbor (uint16_type n, size_type neigh_id)
set the n -th neighbor with neigh
void setPoint (uint16_type i, point_type &p)
Inserts a point.
FEELPP_DEPRECATED void setPointCoordG (int i, ublas::vector< double > const &u)
std::ostream & showMe (bool verbose=false, std::ostream &c=std::cout) const
show information about the geoND
void swapPoints (const uint16_type &pt1, const uint16_type &pt2)
Swap Points.
void update ()
void updateG (TheNodesType &G, std::enable_if_t< is_eigen_matrix_v< TheNodesType > > *=nullptr) const
update G with all points of the element
void updateVertices (TheNodesType &G, std::enable_if_t< is_eigen_matrix_v< TheNodesType > > *=nullptr) const
update G with all vertices of the element
void updateWithCtx (QuadType const &thequad, std::shared_ptr< CtxType > &ctx, std::shared_ptr< CtxFaceType > &ctxf) const
void updateWithCtx1 (quad_meas1_type const &thequad, std::shared_ptr< CtxType > &ctx, std::shared_ptr< CtxFaceType > &ctxf) const
matrix_node_type vertices () const
matrix of vertices geometric nodes retrieve the matrix of geometric nodes (Dim x NumPoints) the matrix is column oriented, the column i contains the coordinate of the i-th geometric node of the element
~GeoND () override
destructor, make it virtual for derived classes
Public Member Functions inherited from Feel::GeoEntity< GEOSHAPE, double >
self_type & addElement (size_type e, int id_in_element=0)
add a new element to which the point belongs
size_type numberOfElements () const
std::set< std::pair< size_type, uint16_type > > const & elements () const
std::set< std::pair< size_type, uint16_type > > & elements ()
self_type & addElementGhost (rank_type proc, size_type e)
add a new ghost element to which the point belongs
rank_type numberOfProcGhost () const
std::map< rank_type, std::set< size_type > > const & elementsGhost () const
bool isSubEntityOfGhostElement (rank_type p) const
void clearElementsGhost ()
virtual void setTags (std::vector< int > const &tags)
set the tags associated to the points
std::map< uint16_type, marker_type > const & markers () const
return all markers
void setMarkers (std::map< uint16_type, marker_type > const &markers)
set all markers
bool hasMarkerType (uint16_type k) const
return true if has marker type id k
bool hasMarker (uint16_type k) const
return true if has marker type id k
bool hasMarker () const
marker_type const & marker (uint16_type k) const
return marker with type id k
marker_type const & marker () const
void setMarker (uint16_type k, flag_type v)
set marker type id k with flag v
void setMarker (uint16_type k, TT const &vs)
set marker type id k with flag v
void setMarker (flag_type v)
void setMarker (TT const &vs)
void addMarker (uint16_type k, flag_type v)
add flag v to the marker type id k
void addMarker (uint16_type k, TT const &vs)
add flags vs to the marker type id k
void addMarker (flag_type v)
void addMarker (TT const &vs)
bool hasMarker2 () const
marker_type const & marker2 () const
void setMarker2 (flag_type v)
bool hasMarker3 () const
marker_type const & marker3 () const
void setMarker3 (flag_type v)
GeoEntity ()
GeoEntity (size_type i, size_type geometry=Geometry, size_type shape=Shape, size_type context=MESH_ENTITY_INTERNAL)
GeoEntity (GeoEntity const &__me)=default
GeoEntity (GeoEntity &&__me)
GeoEntity & operator= (GeoEntity const &__me)=default
GeoEntity & operator= (GeoEntity &&__me)
~GeoEntity () override
bool operator== (GeoEntity const &e) const
bool operator< (GeoEntity const &e) const
bool operator< (size_type __i) const
size_type id () const noexcept
constexpr uint16_type refDim () const
the dimension of the reference shape
constexpr uint16_type nPoints () const
number of points on the reference shape
constexpr uint16_type nVertices () const
number of vertices on the reference shape
constexpr uint16_type nEdges () const
number of edges on the reference shape
constexpr uint16_type nFaces () const
number of faces on the reference shape
constexpr uint16_type nTopologicalFaces () const
number of topological faces on the reference shape
constexpr uint16_type nGeometricFaces () const
number of faces on the reference shape
constexpr uint16_type nNormals () const
number of normals on the reference shape
bool hasShape (size_type __shape) const
bool isAVolume () const
bool isASurface () const
bool isALine () const
bool isAPoint () const
bool isAPointShape () const
bool isALineShape () const
bool isATriangleShape () const
bool isAQuadrangleShape () const
bool isATetrahedraShape () const
bool isAHexahedraShape () const
bool isLinear () const
bool isBilinear () const
bool isQuadratic () const
bool isInternal () const
bool isOnBoundary () const noexcept
Tells if item is on the boundary.
uint16_type boundaryEntityDimension () const noexcept
maximum dimension of the entity of the element touching the boundary
bool isGhostCell () const noexcept
rank_type processId () const noexcept
void setProcessId (rank_type pid) noexcept
set the processor id of the entity &
rank_type pidInPartition () const noexcept
void setProcessIdInPartition (rank_type pid) noexcept
set the processor id of the entity &
rank_type partitionId () const noexcept
rank_type numberOfPartitions () const noexcept
rank_type numberOfNeighborPartitions () const
bool isLinkedToOtherPartitions () const
std::vector< rank_type > const & neighborPartitionIds () const
std::vector< rank_type > & neighborPartitionIds ()
void clearNeighborPartitionIds ()
clear the neighbor partition ids container
FEELPP_DEPRECATED void setIdInOthersPartitions (rank_type pid, size_type id)
set id in a partition pid of the entity
void setIdInOtherPartitions (rank_type pid, size_type id)
void setIdInOtherPartitions (std::map< rank_type, size_type > const &iop)
set (partition,id) in other partitions of the entity
void setIdInOtherPartitions (std::map< rank_type, size_type > &&iop)
set (partition,id) in other partitions of the entity
size_type idInOthersPartitions (rank_type pid) const
std::map< rank_type, size_type > const & idInOthersPartitions () const
void clearIdInOthersPartitions ()
clear id in others partitions container
bool active () const
void setId (size_type id)
void setOnBoundary (bool b, uint16_type ent_d=invalid_uint16_type_value)
set the boundary flag
FEELPP_DEPRECATED void setNumberOfPartitions (uint16_type np)
void setNumberOfNeighborPartitions (uint16_type nep)
set the number of partition the element is linked to
void setNeighborPartitionIds (std::vector< rank_type > const &npids)
void addNeighborPartitionId (rank_type p)
Public Member Functions inherited from Feel::SubFaceOfNone< 0 >
boost::none_t element (uint16_type) const
bool isGhostFace (rank_type) const
bool isInterProcessDomain (rank_type) const
SubFaceOfNone & operator= (SubFaceOfNone &&)=default
SubFaceOfNone & operator= (SubFaceOfNone const &)=default
rank_type partition1 (rank_type) const
rank_type partition2 (rank_type) const
SubFaceOfNone (SFO const &)
SubFaceOfNone (SubFaceOfNone &&)=default
SubFaceOfNone (SubFaceOfNone const &)
Static Public Attributes
static const bool condition = (Dim==nRealDim)
static const uint16_type nDim = super::nDim
static const uint16_type nOrder = super::nOrder
static const uint16_type nRealDim = super::nRealDim
static const uint16_type numLocalEdges = super::numEdges
static const uint16_type numLocalFaces = super::numLocalVertices
static const uint16_type numLocalVertices = super::numLocalVertices
Static Public Attributes inherited from Feel::GeoND< Dim, GEOSHAPE, double, uint32_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, false >
static constexpr uint16_type meas_quad_order
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const int numEdges
static const int numFaces
static const uint16_type numLocalEdges
static const uint16_type numLocalPoints
static const uint16_type numLocalVertices
static const uint16_type numNeighbors
static const uint16_type numPoints
static const int numTopologicalFaces
static const uint16_type numVertices
static const size_type Shape
Static Public Attributes inherited from Feel::GeoEntity< GEOSHAPE, double >
static const size_type Shape
static const size_type Geometry
static const uint16_type nDim
static const uint16_type nOrder
static const uint16_type nRealDim
static const uint16_type numVertices
static const uint16_type numFaces
static const uint16_type numGeometricFaces
static const uint16_type numTopologicalFaces
static const uint16_type numEdges
static const uint16_type numNormals
static const uint16_type numPoints
static const uint16_type nbPtsPerVertex
static const uint16_type nbPtsPerEdge
static const uint16_type nbPtsPerFace
static const uint16_type nbPtsPerVolume
static const bool is_simplex
static const bool is_hypercube
Static Public Attributes inherited from Feel::SubFaceOfNone< 0 >
static const uint16_type nDim
Additional Inherited Members
Static Public Member Functions inherited from Feel::GeoND< Dim, GEOSHAPE, double, uint32_type, mpl::if_< mpl::bool_< false >, mpl::identity< GeoElement0D< Dim, SubFaceOf< GeoElement1D< Dim, GEOSHAPE, SubFaceOfNone< 0 >, double, uint32_type, false, false > >, double, uint32_type > >, mpl::identity< GeoElement0D< Dim, SubFaceOfNone< 0 >, double, uint32_type > > >::type::type, false >
static uint16_type fToP (uint16_type const _localFace, uint16_type const _point)
Get the local id of the point in the element.
static quad_meas_type imMeasure ()
static quad_meas1_type imMeasureOrder1 ()
Static Public Member Functions inherited from Feel::GeoEntity< GEOSHAPE, double >
static uint16_type eToP (uint16_type const __localEdge, uint16_type const __point)
eToP(i,j) = localId of jth point on ith local edge
static uint16_type fToP (uint16_type const __localFace, uint16_type const __point)
fToP(i,j) = localId of jth point on ith local edge
static uint16_type fToE (uint16_type const __localFace, uint16_type const __edge)
fToE(i,j) = localId of jth edge on ith local face
Member Function Documentation
boundaryEntityDimension()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> uint16_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::boundaryEntityDimension () const
Returns
maximum dimension of the sub-entity touching the boundary of the element
facePermutation()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> vertex_permutation_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::facePermutation (uint16_type) const
See also
edgePermutation(), permutation()
References Feel::GeoEntity< GEOSHAPE, double >::processId().
faces() [1/2]
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> std::pair<face_iterator,face_iterator> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::faces ()
Returns
the iterator pair (begin,end) of faces
faces() [2/2]
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> std::pair<face_const_iterator,face_const_iterator> Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::faces () const
Returns
the iterator pair (begin,end) of faces
References Feel::GeoND< Dim, GEOSHAPE, T, IndexT, POINTTYPE, UseMeasuresStorage >::mesh().
hasFace()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::hasFace (uint16_type i) const
Returns
true if GeoElement1D is connected to a face
id()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> size_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::id () const
Returns
true if on the boundary, false otherwise
References Feel::Geo0D< Dim, T, IndexT >::vertices().
Referenced by Feel::GeoElement2D< Dim, GEOSHAPE, SubFace, T, IndexT, UseMeasuresStorage >::boundaryEntityDimension().
isGhostCell()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::isGhostCell () const
Returns
true if ghost cell, false otherwise
isInterProcessDomain()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::isInterProcessDomain () const
Returns
true if interprocess domain face, false otherwise
isOnBoundary()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> bool Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::isOnBoundary () const
Returns
true if on the boundary, false otherwise
partition1()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> rank_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::partition1 () const
Returns
process id
partition2()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> rank_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::partition2 () const
Returns
process id
processId()
template<uint16_type Dim, typename GEOSHAPE , typename SubFace = SubFaceOfNone<0>, typename T = double, typename IndexT = uint32_type, bool PointTypeIsSubFaceOf = false, bool UseMeasuresStorage = false> rank_type Feel::GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage >::processId () const
Returns
process id