#+NAME: Feel++ Consortium
#+EMAIL: feelpp-users@feelpp.org
#+OPTIONS: LaTeX:t

* Installation
** Requirements

 - G++ (>=4.5)
 - Boost (>=1.46)
 - PETSc (>=3.1)
 - Gmsh

** Options

 - SLEPc (>=3.1), Library to solve standard and generalized eigenvalue problems.
   Note that the version of SLEPc installed depends on the version of PETSc
   (they have should the same release number),
 - ANN (>=1.1.2) Approximate Nearest Neighbor
 - GLPK (>= 4.45) GNU Linear Programming ToolKit

** Building Feel++

Note that in-source builds of Feel++ are not possible.

*** Out source build

#+BEGIN_SRC shell
mkdir opt
cd opt
cmake <top level feel directory>
make
make install
#+END_SRC

At the end of the process, you have
 - the Feel++ libraries and its dependencies compiled
 - a quickstart example solving $- \Delta u = f$ in $[0,1]^2$ with $u=g$ on $\partial \Omega$
   located in the quickstart/ directory

More details are available in Feel++ manual and Feel++ website (http://www.feelpp.org)

* Running Feel++ examples

** Environment variables

If Feel++ was installed in a directory other than
#+BEGIN_SRC shell
/opt/local
/usr/local
/usr
#+END_SRC
then you need to set the environment variable =FEELPP_DIR= to ensure that next
=cmake= commands find the required components to compile the Feel++ examples

For example, if Feel++ was installed in =/opt/feelpp=, then set
#+BEGIN_SRC shell
# using sh type shells
export FEELPP_DIR=/opt/feelpp
# using csh type shells
setenv FEELPP_DIR /opt/feelpp
#+END_SRC


** Compiling Feel++ examples

The Feel++ examples are in =FEELPP_DIR/share/doc/feel/examples= organized in
sub-directories following the layout in the Feel++ source code in =doc/manual=.
A =CMakeLists.txt= is available to compile the examples.

#+BEGIN_SRC shell
mkdir <feelpp examples build dir>
cd <feelpp examples build dir>
cmake $FEELPP_DIR/share/doc/feel/examples
#+END_SRC

Once the =cmake= process is done, type for example
#+BEGIN_SRC shell
make tutorial
#+END_SRC
to build all the Feel++ tutorial examples from the manual.


