var namespacenlohmann =
[
    [ "detail", "namespacenlohmann_1_1detail.html", "namespacenlohmann_1_1detail" ],
    [ "detail2", null, [
      [ "begin_tag", "structnlohmann_1_1detail2_1_1begin__tag.html", null ],
      [ "end_tag", "structnlohmann_1_1detail2_1_1end__tag.html", null ],
      [ "would_call_std_begin", "structnlohmann_1_1detail2_1_1would__call__std__begin.html", null ],
      [ "would_call_std_end", "structnlohmann_1_1detail2_1_1would__call__std__end.html", null ]
    ] ],
    [ "adl_serializer", "structnlohmann_1_1adl__serializer.html", "structnlohmann_1_1adl__serializer" ],
    [ "adl_serializer< boost::filesystem::path >", "structnlohmann_1_1adl__serializer_3_01boost_1_1filesystem_1_1path_01_4.html", null ],
    [ "adl_serializer< py::bool_ >", "structnlohmann_1_1adl__serializer_3_01py_1_1bool___01_4.html", null ],
    [ "adl_serializer< py::detail::item_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1item__accessor_01_4.html", null ],
    [ "adl_serializer< py::detail::list_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1list__accessor_01_4.html", null ],
    [ "adl_serializer< py::detail::obj_attr_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1obj__attr__accessor_01_4.html", null ],
    [ "adl_serializer< py::detail::sequence_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1sequence__accessor_01_4.html", null ],
    [ "adl_serializer< py::detail::str_attr_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1str__attr__accessor_01_4.html", null ],
    [ "adl_serializer< py::detail::tuple_accessor >", "structnlohmann_1_1adl__serializer_3_01py_1_1detail_1_1tuple__accessor_01_4.html", null ],
    [ "adl_serializer< py::dict >", "structnlohmann_1_1adl__serializer_3_01py_1_1dict_01_4.html", null ],
    [ "adl_serializer< py::float_ >", "structnlohmann_1_1adl__serializer_3_01py_1_1float___01_4.html", null ],
    [ "adl_serializer< py::handle >", "structnlohmann_1_1adl__serializer_3_01py_1_1handle_01_4.html", null ],
    [ "adl_serializer< py::int_ >", "structnlohmann_1_1adl__serializer_3_01py_1_1int___01_4.html", null ],
    [ "adl_serializer< py::list >", "structnlohmann_1_1adl__serializer_3_01py_1_1list_01_4.html", null ],
    [ "adl_serializer< py::object >", "structnlohmann_1_1adl__serializer_3_01py_1_1object_01_4.html", null ],
    [ "adl_serializer< py::str >", "structnlohmann_1_1adl__serializer_3_01py_1_1str_01_4.html", null ],
    [ "adl_serializer< py::tuple >", "structnlohmann_1_1adl__serializer_3_01py_1_1tuple_01_4.html", null ],
    [ "basic_json", "classnlohmann_1_1basic__json.html", "classnlohmann_1_1basic__json" ],
    [ "byte_container_with_subtype", "classnlohmann_1_1byte__container__with__subtype.html", "classnlohmann_1_1byte__container__with__subtype" ],
    [ "json_pointer", "classnlohmann_1_1json__pointer.html", "classnlohmann_1_1json__pointer" ],
    [ "json_sax", "structnlohmann_1_1json__sax.html", "structnlohmann_1_1json__sax" ],
    [ "ordered_map", "structnlohmann_1_1ordered__map.html", null ],
    [ "would_call_std_begin", "structnlohmann_1_1would__call__std__begin.html", null ],
    [ "would_call_std_end", "structnlohmann_1_1would__call__std__end.html", null ],
    [ "json", "namespacenlohmann.html#a2bfd99e845a2e5cd90aeaf1b1431f474", null ],
    [ "ordered_json", "namespacenlohmann.html#ad53cef358adfa7f07cea23eb1e28b9ea", null ],
    [ "to_string", "namespacenlohmann.html#ad567589424d944bc2c8082d0541f0fdf", null ]
];