Feel++: Feel Namespace Reference
Feel Namespace Reference
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*-
Namespaces
detail
Policy for Scalar polynomials or polynomial set of dimension Dim.
math
Class that contains methods for computing Jacobi elliptic functions related to complex analysis.
Classes
struct _Q
struct _QBase
class AboutData
This class is used to store information about a program.
class AboutPerson
This structure is used to store information about a person or developer.
class ADBinaryAdd
class ADBinaryAdd< ADCst< double >, R >
class ADBinaryAdd< ADCst< float >, R >
class ADBinaryAdd< ADCst< int >, R >
class ADBinaryAdd< ADCst< long double >, R >
class ADBinaryAdd< ADCst< long int >, R >
class ADBinaryAdd< L, ADCst< double > >
class ADBinaryAdd< L, ADCst< float > >
class ADBinaryAdd< L, ADCst< int > >
class ADBinaryAdd< L, ADCst< long double > >
class ADBinaryAdd< L, ADCst< long int > >
class ADBinaryDivide
class ADBinaryDivide< ADCst< double >, R >
class ADBinaryDivide< ADCst< float >, R >
class ADBinaryDivide< ADCst< int >, R >
class ADBinaryDivide< ADCst< long double >, R >
class ADBinaryDivide< ADCst< long int >, R >
class ADBinaryDivide< L, ADCst< double > >
class ADBinaryDivide< L, ADCst< float > >
class ADBinaryDivide< L, ADCst< int > >
class ADBinaryDivide< L, ADCst< long double > >
class ADBinaryDivide< L, ADCst< long int > >
class ADBinaryEqual
class ADBinaryEqual< ADCst< double >, R >
class ADBinaryEqual< ADCst< float >, R >
class ADBinaryEqual< ADCst< int >, R >
class ADBinaryEqual< ADCst< long double >, R >
class ADBinaryEqual< ADCst< long int >, R >
class ADBinaryEqual< L, ADCst< double > >
class ADBinaryEqual< L, ADCst< float > >
class ADBinaryEqual< L, ADCst< int > >
class ADBinaryEqual< L, ADCst< long double > >
class ADBinaryEqual< L, ADCst< long int > >
class ADBinaryGreater
class ADBinaryGreater< ADCst< double >, R >
class ADBinaryGreater< ADCst< float >, R >
class ADBinaryGreater< ADCst< int >, R >
class ADBinaryGreater< ADCst< long double >, R >
class ADBinaryGreater< ADCst< long int >, R >
class ADBinaryGreater< L, ADCst< double > >
class ADBinaryGreater< L, ADCst< float > >
class ADBinaryGreater< L, ADCst< int > >
class ADBinaryGreater< L, ADCst< long double > >
class ADBinaryGreater< L, ADCst< long int > >
class ADBinaryGreaterOrEqual
class ADBinaryGreaterOrEqual< ADCst< double >, R >
class ADBinaryGreaterOrEqual< ADCst< float >, R >
class ADBinaryGreaterOrEqual< ADCst< int >, R >
class ADBinaryGreaterOrEqual< ADCst< long double >, R >
class ADBinaryGreaterOrEqual< ADCst< long int >, R >
class ADBinaryGreaterOrEqual< L, ADCst< double > >
class ADBinaryGreaterOrEqual< L, ADCst< float > >
class ADBinaryGreaterOrEqual< L, ADCst< int > >
class ADBinaryGreaterOrEqual< L, ADCst< long double > >
class ADBinaryGreaterOrEqual< L, ADCst< long int > >
class ADBinaryLess
class ADBinaryLess< ADCst< double >, R >
class ADBinaryLess< ADCst< float >, R >
class ADBinaryLess< ADCst< int >, R >
class ADBinaryLess< ADCst< long double >, R >
class ADBinaryLess< ADCst< long int >, R >
class ADBinaryLess< L, ADCst< double > >
class ADBinaryLess< L, ADCst< float > >
class ADBinaryLess< L, ADCst< int > >
class ADBinaryLess< L, ADCst< long double > >
class ADBinaryLess< L, ADCst< long int > >
class ADBinaryLessOrEqual
class ADBinaryLessOrEqual< ADCst< double >, R >
class ADBinaryLessOrEqual< ADCst< float >, R >
class ADBinaryLessOrEqual< ADCst< int >, R >
class ADBinaryLessOrEqual< ADCst< long double >, R >
class ADBinaryLessOrEqual< ADCst< long int >, R >
class ADBinaryLessOrEqual< L, ADCst< double > >
class ADBinaryLessOrEqual< L, ADCst< float > >
class ADBinaryLessOrEqual< L, ADCst< int > >
class ADBinaryLessOrEqual< L, ADCst< long double > >
class ADBinaryLessOrEqual< L, ADCst< long int > >
class ADBinaryMultiply
class ADBinaryMultiply< ADCst< double >, R >
class ADBinaryMultiply< ADCst< float >, R >
class ADBinaryMultiply< ADCst< int >, R >
class ADBinaryMultiply< ADCst< long double >, R >
class ADBinaryMultiply< ADCst< long int >, R >
class ADBinaryMultiply< L, ADCst< double > >
class ADBinaryMultiply< L, ADCst< float > >
class ADBinaryMultiply< L, ADCst< int > >
class ADBinaryMultiply< L, ADCst< long double > >
class ADBinaryMultiply< L, ADCst< long int > >
class ADBinaryNotEqual
class ADBinaryNotEqual< ADCst< double >, R >
class ADBinaryNotEqual< ADCst< float >, R >
class ADBinaryNotEqual< ADCst< int >, R >
class ADBinaryNotEqual< ADCst< long double >, R >
class ADBinaryNotEqual< ADCst< long int >, R >
class ADBinaryNotEqual< L, ADCst< double > >
class ADBinaryNotEqual< L, ADCst< float > >
class ADBinaryNotEqual< L, ADCst< int > >
class ADBinaryNotEqual< L, ADCst< long double > >
class ADBinaryNotEqual< L, ADCst< long int > >
class ADBinaryPow
class ADBinaryPow< ADCst< typename R::value_type >, R >
class ADBinaryPow< L, ADCst< int > >
class ADBinaryPow< L, ADCst< typename L::value_type > >
class ADBinarySubtract
class ADBinarySubtract< ADCst< double >, R >
class ADBinarySubtract< ADCst< float >, R >
class ADBinarySubtract< ADCst< int >, R >
class ADBinarySubtract< ADCst< long double >, R >
class ADBinarySubtract< ADCst< long int >, R >
class ADBinarySubtract< L, ADCst< double > >
class ADBinarySubtract< L, ADCst< float > >
class ADBinarySubtract< L, ADCst< int > >
class ADBinarySubtract< L, ADCst< long double > >
class ADBinarySubtract< L, ADCst< long int > >
class ADCst
struct AddBasisByBlock
class ADExpr
brief description
class AdFuncAbs
class ADFuncCos
class AdFuncExp
class AdFuncLog
class AdFuncLog10
class ADFuncSin
class ADFuncSqrt
class ADFuncTan
class ADOfstream
class ADType< T, Nvar, 0, Var >
class ADType< T, Nvar, 1, Var >
class ADUnaryMinus
class ADUnaryPlus
struct ADVariable
class AdvReact
Advection-Reaction solver.
class Air
Air material.
class Aitken
Aitken relaxation method for fixed point iterations.
class Application
provides information about the Application
class ApplicationXML
XML application.
struct AssembleInitialGuessVInCompositeCase
struct AssembleMassMatrixInCompositeCase
struct Assert
class AssertContext
contains details about a failed assertion
class Backend
base class for all linear algebra backends
class BackendBase
class BackendEigen
class BareEdge
The Edge basis class It contains the attributes common to all Edges In particular, it contains the two size_type's (first and second) of the points at the two ends of the edge.
class BareFace
The base Face class.
class BareItemsHandler
Bare Items Handler.
class BarePoint
The Point basis class It contains the attributes common to all Points In particular, it contains the one size_type's (first) of the point.
struct bases
struct bases_list
class Basis
Base class for basis.
struct basis_type
class BasisFunctions
base class for basis functions
class Bdf
Backward differencing formula time discretization.
struct BFGSInvHessian
delta[k] = x[k+1] - x[k]
gamma[k] = grad f(x[k+1]) - grad f(x[k])
H[0] = I
BFGS : zeta[k] = delta[k] - H[k] gamma[k]
DFP : zeta[k] = H[k] gamma[k]
tau[k] = gamma[k]^T zeta[k]
rho[k] = 1 / gamma[k]^T delta[k]
BFGS : H[k+1] = H[k] + rho[k](zeta[k] delta[k]^T + delta[k] zeta[k]^T)
class BilinearFormBase
Base class for Bilinear Forms handle algebraic representation and multithreading.
class BiotSavartRB
class BlockBilinearForm
forward declarations of BlockBilinearForm and blocform2()
class BlockLinearForm
forward declarations of BlockLinearForm and blockform1()
class BlocksBaseGraphCSR
class BlocksBaseSparseMatrix
class BlocksBaseVector
class BlocksSparseMatrix
class BlocksStencilPattern
class BlocksVector
struct boost_param_params_461preconditioner
struct boost_param_params_564eigs
struct boost_param_params_926bdf
struct boost_param_result_461preconditioner
struct boost_param_result_564eigs
struct boost_param_result_640veigs
struct boost_param_result_788newmark
struct boost_param_result_926bdf
class BoundaryAdapted
BoundaryAdapted Basis on simplex.
struct BoundaryAdaptedTag
struct BoundaryAdaptedTraits
class BoundaryConditions
Defines boundary conditions dictionary.
class BoundingBox
bounding box for a matrix of points
struct BuildRbMatrixByRow
class CastIron
Cast iron material.
class Checker
Checker class.
struct CheckerConvergenceFailed
struct CheckerExactFailed
struct cmpBareItem
struct cmpBareItem< BareEdge >
< The actual comparison operator
struct cmpBareItem< BareFace >
struct cmpBareItem< BarePoint >
< The actual comparison operator
class CNAB2
class CNAB2x2
class CommObject
struct compute_aitken_return
struct compute_eigs_return_type
struct compute_opInterpolation_return
struct compute_opLagrangeP1_return
struct compute_opLinear_return
struct compute_prec_return
struct Condenser
struct ConfigureKSP
ConfigureKSP.
class ConfigurePC
ConfigurePC.
class ConfigurePCASM
ConfigureASM.
struct ConfigurePCBase
ConfigurePCBase.
class ConfigurePCFieldSplit
ConfigurePCFieldSplit.
class ConfigurePCGAMG
ConfigurePCGAMG.
class ConfigurePCGASM
ConfigureGASM.
class ConfigurePCHYPRE_AMS
ConfigurePCHYPRE_AMS.
class ConfigurePCHYPRE_BOOMERAMG
ConfigurePCHYPRE_BOOMERAMG.
class ConfigurePCILU
ConfigurePCILU.
class ConfigurePCLSC
ConfigurePCLSC.
class ConfigurePCLU
ConfigurePCLU.
class ConfigurePCMGLevels
ConfigurePCMGLevels.
class ConfigurePCML
ConfigurePCML.
class ConfigurePCPCD
ConfigurePCPCD.
class ConfigurePCPMM
ConfigurePCPMM.
class ConfigurePCRedundant
ConfigurePCRedundant.
class ConfigurePCSOR
ConfigurePCSOR.
class ConfigureSubPC
ConfigureSubPC.
class ConstrainedPolynomialSet
struct cont_type
struct ContextGeometricBase
struct ContextOn
Context for 'on' operation on sparse matrices.
struct continuity_type
class Continuous
describe continuous functions
class Convex
Convex base class.
struct convex_type
class ConvexBase
class core_data
class CRB
Certifed Reduced Basis class.
class CRBAero
class CRBApp
Certified Reduced Basis application.
class CRBBase
class CRBBlock
class CRBDB
brief description
class CRBElementsDB
class CRBMatrixInfo
class CRBModel
Certified Reduced Basis Model class.
class CRBModelAero
struct CRBModelBase
class CRBModelBlock
class CRBModelDB
class CRBModelSaddlePoint
class CRBModelTrilinear
Certified Reduced Basis Model trilinear class.
class CRBPlugin
Generic Plugin for CRB applications.
class CRBPluginAPI
Interface for CRB plugins.
class CRBPluginBase
class CRBResults
data structure holding the results of a RB online code
class CRBSaddlePoint
Certfified Reduced BAsis for Saddle Point Problems.
class CRBSaddlePointPlugin
Generic Plugin for CRB SaddlePoint applications.
class CRBSCM
SCM algorithm.
class CRBSolutions
class CRBTrilinear
class CRBTrilinearPlugin
Generic Plugin for CRB Trilinear applications.
class CRBUpperBounds
class CreateSubmeshTool
class CrouzeixRaviart
class CSRGraphMetis
This utility class provides a convenient implementation for building the compressed-row-storage graph required for the METIS/ParMETIS graph partitioning schemes.
class CSSolver
class CurveParametrization
class CvgStudy
class DataMap
data layout in a multi-processor environnement
class DEIM
class DEIMBase
Base class for DEIM algorithm.
class DEIMModel
Class inherited from DEIMBase It contains the model This class is still generic and support either matrices or vectors.
struct diff_order
struct dim
struct dimension_t
struct DimFromShape
class DirScalingMatrix
implements the directional Scaling Matrix for directionally-scaled trust region
class Discontinuous
class DiscontinuousInterfaces
describes discontinuous interfaces and provide dof creation
class DistanceToMesh
class DistToCurve
class Dof
class that represents a degree of freedom
class DofComposite
Compositing of degree of freedom table.
class DofFromBoundary
Local Dof contribution from boundary dof.
class DofFromEdge
Local Dof contribution from edge dof.
class DofFromElement
local dof contribution from an element
class DofFromMortar
local dof contribution from a mortar element
class DofFromPeriodic
local contribution from periodic dof
class DofTable
Local-to-global Degree of Freedom table.
class DofTableBase
struct DofTableInfos
struct domain_value_type
class DualBasis
basis of a space P' dual of some space P
class Dubiner
Dubiner polynomial orthonormal basis.
struct DubinerTag
struct DubinerTraits
class dummy_data
dummy data type
class EIM
Empirical interpolation of a function to obtain an affine decomposition.
class EimDefinitionBase
class EIMFunction
class EIMFunctionBase
class EIMFunctionFeSpaceDb
struct EimFunctionNoSolve
class EimFunctionNoSolveBase
class ElemFineToCoarse
create bijection map between fine and coarse elem based indexing grid
class Entity
class Entity< SHAPE_HEXA, T >
class Entity< SHAPE_LINE, T >
class Entity< SHAPE_POINT, T >
class Entity< SHAPE_QUAD, T >
class Entity< SHAPE_TETRA, T >
class Entity< SHAPE_TRIANGLE, T >
class Environment
Initialize, finalize, and query the Feel++ environment.
class equalities
define the equalities type
struct expansion_type
struct ExpansionByBlock
struct ExportBasisFunctionsByBlock
class Exporter
export Feel generated data to some file formats
class ExporterEnsight
exporter to Ensight format
class ExporterEnsightGold
exporter to EnsightGold format
class ExporterExodus
exporter to Exodus format
class ExporterGmsh
Exporter to GMSH format.
class ExporterGnuplot
Exporter to GNUPLOT format.
class ExporterQuick
simple interface to exporter
class ExprBase
Base class for expression.
class ExpressionStringAtMarker
Boundary condition at marker is an epression string.
class ExtenderFromInterface
struct FaceDof
Describe a Dof on a Face.
class Factory
Implements a generic object Factory.
class FactoryClone
Implements a generic cloning object Factory.
struct FactoryDefaultError
class FastMarching
struct FastMarchingDofStatus
class FeelppDatabase
class FeelppDatabaseFieldInfo
struct Field
class Fields
class FilterFromVtk
class FilterFromVtk3D
class FiniteElement
Finite element following Ciarlet framework.
class FluidMechanics
a fluid mechanics class parametrized by an approximation space and a model type
class FMU
Functional Mockup Unit class.
class FmuModel2
class FmuModelBase
class FsFunctional
class FsFunctionalLinear
class FsFunctionalLinearComposite
class FsFunctionalLinearFree
class Functional
represents a linear functional
class functional
defines the functional type
class FunctionalSet
Set of functionals.
class FunctionSpace
class FunctionSpaceBase
base class for FunctionSpace
class FunctionSpaceDefinitionBase
class Gauss
Gauss quadrature points.
class GaussLobatto
Gauss quadrature points.
class Geo0D
class GeoElement0D
Class for Points and Vertices.
class GeoElement1D
class for 1D elements
class GeoElement2D
Class for 2D elements.
class GeoElement3D
Class for 3D elements.
class GeoEntity
base class for all geometric entities
class GeoMap
Structure for the geometrical mapping.
class GeoMapInverse
handles the geometric inversion for a given (supposedly quite large) set of points
struct GeomapInverse
class GeometricSpace
struct GeometricSpaceBase
class GeoND
Base class for Multi-dimensional basis Geometrical Entities.
class GeoNDCommon
Common data shared in a collection of multi-dimensional geometrical entity.
class GeoNDMeasuresStorage
class GeoNDNoMeasuresStorage
struct get_real_type
struct get_real_type< double >
struct get_real_type< std::complex< double > >
struct GetComponent
Get the component type out the available types.
struct getOptionIfAvalaible
struct GinacExprManagerDefaultFileNameDeleterImpl
class GinacExprManagerDefaultFileNameImpl
struct GinacExprManagerDeleterImpl
class GinacExprManagerImpl
class Gmsh
Gmsh Mesh Generator.
class GmshEllipsoidDomain
n-Ellipsoid Domain description for gmsh mesh generation.
class GmshHypercubeDomain
Tensorized Domain description for gmsh mesh generation.
class GmshOrdering
class GmshSimplexDomain
Simplex Domain description for gmsh mesh generation.
class GraphCSR
Graph representation of the Compressed Sparse Row format.
struct GT_Lagrange
struct GT_QK
class H1PolynomialSet
H1 conforming polynomialset base class.
class Hbf2Feelpp
create bijection map between HBF indexing and Feel++ indexing
class Hbf2FeelppStruc
class HbfFineToCoarse
create bijection map between fine and coarse hbf based indexing grid
class HCurlPolynomialSet
HCurl conforming polynomialset base class.
class HDivPolynomialSet
HDiv conforming polynomialset base class.
class Hermite
class Hypercube
class HypercubeBase
class IM
class IMBase
base class for integration method
class IMExact
exact integration method
class IMGeneral
integration method interface class
struct IMGeneric
struct IMMaxOrder
class Importer
class ImporterAcusimRawMesh
Reader for Acusim Raw Mesh Format from Acusim (C) Altair.
class ImporterCSV
class ImporterGmsh
gmsh importer class
class IMSimplex
economical quadratures for simplices
struct IMTetrahedra
struct IMTetrahedra< 0, T >
struct IMTetrahedra< 1, T >
struct IMTetrahedra< 2, T >
struct IMTetrahedra< 3, T >
struct IMTetrahedra< 4, T >
struct IMTetrahedra< 5, T >
struct IMTetrahedra< 6, T >
class IndexSplit
class inequalities
define the inequalities type
class Info
information provider for versioning and installation directories
struct InitEnergtMatrixByBlock
struct IntegrationDegree
order policy that computes integrals of polynomials up to degree N.
struct InterpolationConforming
struct InterpolationCurl
struct InterpolationDiv
struct InterpolationExpr
struct InterpolationGradient
struct InterpolationNonConforming
class InterpolationTypeBase
class InterpolationTypeBaseBase
class Interpolator
Given an un-ordered dataset, provide a representation for the interpolant Options are available for the extrapolation Given a two column file 'x - y', we compute the interpolation of that cloud. We provide the first order derivative of the interpolant as well.
class InterpolatorAkima
The Akima's interpolation differs with the Cspline by the first order derivative imposed at nodes http://www.iue.tuwien.ac.at/phd/rottinger/node60.html TODO: interpolate a(x-xi)**3 + ... instead of ax**3.
class InterpolatorP0
class InterpolatorP1
class InterpolatorSpline
Interpolate with a*x**3 + b*x**2 + c*x + d TODO: interpolate a(x-xi)**3 + ... instead of ax**3 (only to generate a easiest to inverse linear system)
struct is_0d
struct is_0d_real
struct is_1d
struct is_1d_real
struct is_2d
struct is_2d_real
struct is_3d
struct is_3d_real
struct is_convex
struct is_cube
struct is_edge
struct is_face
struct is_filter
struct is_filter< boost::tuple< T... > >
struct is_geoelement
Checks whether T is a GeoElement<n>D type.
struct is_geoelement< GeoElement0D< Dim, SubFace, T, IndexT > >
struct is_geoelement< GeoElement1D< Dim, GEOSHAPE, SubFace, T, IndexT, PointTypeIsSubFaceOf, UseMeasuresStorage > >
struct is_geoelement< GeoElement2D< Dim, GEOSHAPE, SubFace, T, IndexT, UseMeasuresStorage > >
struct is_geoelement< GeoElement3D< Dim, GEOSHAPE, T, IndexT, UseMeasuresStorage > >
class is_h1_conforming
type traits for H1 conforming polynomialset
struct is_hypercube
struct is_iterable
struct is_iterable< T, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end())> >
struct is_iterable_of
struct is_iterable_of< T, V, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), std::is_same< decltype(*std::declval< T >().begin()), V > > >
class is_l2_conforming
type traits for L2 conforming polynomialset
struct is_linear_polynomial
struct is_mortar
struct is_point
struct is_ptr_or_shared_ptr
struct is_reference_convex
Checks whether T is a Reference convex type.
struct is_reference_convex< Reference< Hypercube< Dim, Order, RDim >, Dim, Order, RDim, T > >
struct is_reference_convex< Reference< Simplex< Dim, Order, RDim >, Dim, Order, RDim, T > >
struct is_scalar_polynomial
struct is_segment
struct is_shared_ptr
struct is_shared_ptr< std::shared_ptr< T > >
struct is_simplex
struct is_square
struct is_std_vector
struct is_std_vector< std::vector< T > >
struct is_symm
if T derives from a Tensor2SymmBase then is_symm is mpl::bool_<true>, mpl::bool_<false> otherwise
struct is_tensor2_polynomial
struct is_tetrahedron
struct is_topological_face
struct is_triangle
struct is_vector_polynomial
struct isP0Continuous
class Iteration
brief description
class Jacobi
1D Jacobi polynomial
struct JacobiDegree
degree policy that defines the integration method that used jacobi polynomials of degree N.
class JournalFeed
class JournalManager
JournalManager that manage the journal system handles all journalWatchers.
class JournalWatcher
class KDTree
KDTree class.
class L2PolynomialSet
L2 conforming polynomialset base class.
class Lagrange
class Legendre
Legendre polynomial orthonormal basis.
struct LegendreTag
struct LegendreTraits
class LevelSetRedistanciation
class LevelSetRedistanciationFM
class LevelSetRedistanciationHJ
struct Line
struct ListReturnTypes
struct local_interpolant
struct local_interpolants
class LocalDof
class LocalDofSet
class Localization
struct LocalSolver
class LU
LU Decomposition.
class Material
Material base class.
class MaterialLib
Material library.
struct matrix_node
matrix node definition
class MatrixBlock
block of matrices
class MatrixBlockBase
class MatrixCondensed
Matrix to represent statically condensed matrices.
class MatrixEigenDense
interface to eigen sparse matrix
class MatrixEigenSparse
interface to eigen sparse matrix
class MatrixShell
matrices that define its action against a vector
class MatrixShellSparse
Allow all sparse matrices to be shell matrices.
class MatrixSparse
Generic sparse matrix.
class MatrixTriplet
brief description
class MatrixUBlas
interface to ublas sparse matrix
class MatrixValue
interface to matrix
class MDEIM
class MemoryUsage
class to query for memory usage
class Mesh
unifying mesh class
class Mesh0D
0D mesh class
class Mesh1D
1D mesh class
class Mesh2D
2D mesh class
class Mesh3D
3D mesh class
struct mesh_type
class MeshAdaptation
class MeshBase
base mesh class
struct meshes
class MeshHighOrder
struct MeshMarkerName
class MeshMover
Move mesh according to a given map.
class MeshPartitionSet
class MeshStructured
Structured mesh class.
class MeshSupport
Description of a mesh support.
class MeshSupportBase
Description of a mesh support.
class MeshTraits
Traits for meshes.
struct MinNewEntryForAllReduce
struct model_type
class ModelBoundaryCondition
class ModelBoundaryConditions
class ModelCrbBase
class ModelCrbBaseBase
class ModelExpression
class ModelExpressionScalar
struct ModelFunction
class ModelFunctions
class ModelIndexes
class ModelInitialCondition
class ModelInitialConditions
class ModelInitialConditionTimeSet
class ModelMarkers
struct ModelMaterial
class ModelMaterials
a set of materials key: mesh marker name -> name of the materials - can be different
class ModelModel
class ModelModels
class ModelOutput
class containing an output
class ModelOutputs
class containing all outputs in the model
struct ModelParameter
class ModelParameters
class for Model Parameters
class ModelPointPosition
class ModelPostprocess
class ModelPostprocessCheckerMeasure
class ModelPostprocessExports
class ModelPostprocessNorm
store informations require by the postprocessing Norm
class ModelPostprocessPointPosition
class ModelPostprocessQuantities
class ModelPostprocessSave
class ModelPostprocessStatistics
store informations require by the postprocessing Statistics
class ModelProperties
class MongoConfig
class Mortar
brief description
struct mortar_type
struct mortars
class MultiScaleQuadrature
quadrature points by rectangle approximation for multi scale approach
class MultiScaleQuadrature< Hypercube< 1, 1 >, Integration_Degree, T >
Multi Scale Quadrature on the segment [-1,1].
class MultiScaleQuadrature< Hypercube< 2, 1 >, Integration_Degree, T >
Multi Scale Quadrature on the quadrangle [-1,1]x[-1,1].
class MultiScaleQuadrature< Simplex< 0, 1 >, Integration_Degree, T >
class Nedelec
class NedelecPolynomialSet
class NedelecPolynomialSet< 2, O, NedelecKind::NED1, T, TheTAG >
class NedelecPolynomialSet< 3, O, NedelecKind::NED1, T, TheTAG >
class NedelecPolynomialSet< N, O, NedelecKind::NED2, T, TheTAG >
class Newmark
Newmark discretization.
struct node
node definition
class NoMortar
struct noop
class NoPeriodicity
NoPeriodicity class holder.
struct norm_inf_adaptor
struct Normalized
Policy for orthogonal polynomial set which can be normalized or not.
class NullSpace
class OMModel
class Operator
Operator between function spaces.
class OperatorBase
Base class for Operators.
class OperatorCompose
implement \(f \circ g \) operator
class OperatorDiag
Diagonal of an operator.
class OperatorInterpolation
Global interpolation operator.
class OperatorInverse
Operator class to model an inverse operator.
class OperatorLagrangeP1
class OperatorLinear
Linear Operator between function spaces, represented by a matrix.
class OperatorLinearComposite
class OperatorLinearFree
Linear Operator Free between function spaces, represented by a matrix but this matrix is not automatically assembled.
class OperatorLinearParametrized
An interface for linear parametrized operators.
class OperatorMatrix
class OperatorPCD
class OperatorPCDBase
class OperatorScale
Scaling Operator class.
class OperatorSteklovPc
OperatorSteklovPc made easy.
class OperatorTrace
OperatorTrace made easy.
class OpusApp
Certified Reduced Basis application.
struct order
struct Order
class OrthogonalPolynomialSet
a set of orthogonal polynomials over a convex
class OrthogonalPolynomialSet< Dim, Order, PolySetType, T, Hypercube >
class OrthogonalPolynomialSet< Dim, Order, PolySetType, T, Simplex >
struct OrthonormalizeBasisByBlock
class Oseen
class OseenDefaults
Oseen Default Data.
class Output
output class to describe code outputs
class Output_impl
class Parameter
parameter class to describe code inputs
class Parameter_impl
class parameter_map
class ParameterDefinitionBase
class ParameterSpace
Parameter space class.
class Partitioner
partitioner class
class PartitionerLinear
split mesh into equal size parts associated to each processor
class PartitionerMetis
Metis partitioner.
class Periodic
Periodic class holder.
class PeriodicEntities
struct PeriodicEntity
struct Periodicity
struct periodicity_type
class PFemApp
Parametrized Finite Element Method Application.
class POD
POD class.
struct points_type
class PointSet
Class of all PointSet on a Convex.
class PointSetBase
base class for point sets, to be used eg with SFINAE
class PointSetElectrostatic
class PointSetEquiSpaced
class PointSetFekete
Fekete point set class for simplices and simplex products.
class PointSetFeketeSimplex
class PointSetGaussLobatto
class PointSetInterpolation
Good interpolation point sets on a convex.
class PointSetMapped
class PointSetQuadrature
Quadrature point set base class.
class PointSetToMesh
transform a point set to a mesh data structure using a Delaunay
class PointSetWarpBlend
class PolicyCreationUsingNew
class PolicyFeelTimeDefault
class Polynomial
polynomial class
struct polynomial_order
class PolynomialSet
a Set of polynomials
struct PreAssembleMassMatrixInCompositeCase
class Preconditioner
base class for preconditioner
class PreconditionerAS
class PreconditionerBlockMS
class PreconditionerBlockNS
class PreconditionerPetsc
Petsc preconditioner class.
class Principal
Principal modified functions.
class problem
Optimization problem specifications.
struct product_space_tag
class ProductSpace
struct ProductSpaceBase
class ProductSpaces
class ProductSpaces2
class mixing dynamic and compile-time space product
struct ProductSpacesBase
class Projector
Projection made easy.
class PsLogger
Writes output of the system command ps to a logfile.
class QuadMapped
mapping class for point sets depending on convex permutations
class QuadPtLocalization
struct Rank0
struct Rank1
struct RankCurl
struct RankDown
struct RankDown2
struct RankSame
struct RankUp
Get the next rank.
struct RankUp2
class RaviartThomas
class RaviartThomasPolynomialSet
struct real_dimension_t
class RealToReference
class ReducedBasisSpace
Reduced Basis Space class.
class Reference
Reference convex.
class Reference< Hypercube< Dim, Order, RDim >, Dim, Order, RDim, T >
class Reference< Simplex< Dim, Order, RDim >, Dim, Order, RDim, T >
struct Region
struct RegionMarker
class for RegionMarker
struct RegionMarker2
class for RegionMarker2
struct RegionMarker3
class for RegionMarker3
struct RegionProcess
class for RegionProcess
class RegionTree
implements a region-tree for point search in a set of boxes
class Reinitializer
class ReinitializerFM
class ReinitializerFMS
Fast Marching algorithm.
class ReinitializerHJ
class Remesh
Class that handles remeshing in sequential and parallel.
struct RemoteData
class which manage downloads from an url or github and download/upload with the Girder database by using the libcurl
struct remove_shared_ptr
struct remove_shared_ptr< std::shared_ptr< T > >
struct remove_std_vector
struct remove_std_vector< std::vector< T > >
struct ReturnSelect
struct Scalar
Policy for Scalar polynomials or polynomial set of dimension Dim.
class ScalarBase
class SER
struct SerializeByBlock
class Simget
Simulation Object.
class Simplex
simplex of dimension Dim
class SimplexBase
class SimplexEikonalSolver
class Singleton
implement the Singleton pattern
class SNumericalTraits
class SNumericalTraits< double, float >
class SNumericalTraits< double, int >
class SNumericalTraits< double, long >
class SNumericalTraits< double, std::complex< float > >
class SNumericalTraits< float, double >
class SNumericalTraits< float, int >
class SNumericalTraits< float, long >
class SNumericalTraits< int, double >
class SNumericalTraits< int, float >
class SNumericalTraits< long, double >
class SNumericalTraits< long, float >
class SNumericalTraits< std::complex< float >, double >
class SNumericalTraits< T, T >
class SolidMechanics
class SolverBase
This virtual class provide a generic interface for all FMI solvers.
class SolverConstrained
class SolverEigen
base class for eigen solvers
class SolverLinear
This class provides a uniform interface for linear solvers.
class SolverNonLinear
Non linear solver base interface.
class SolverUMFPACK
Interface for the UMFPACK Solver.
class SolverUnconstrained
class SOrth
class Sphere
This class defines a sphere.
class StaticCondensation
class Stencil
class StencilManagerImpl
struct stencilQuadSet
struct stencilQuadSetBase
define the quadrature order use with non standard stencil
struct stencilRangeMap0Type
struct stencilRangeMap1Type
struct stencilRangeMap2Type
struct stencilRangeMapTypeBase
struct stencilrangetype
struct StorageUBlas
Storage Policy using ublas for numerical type T.
class StructuredGrid
class to represent a Structured Grid
class SubFaceOf
struct SubFaceOfBase
class SubFaceOfNone
class SubMeshData
data structure storing sub mesh data
class Surface
This class defines a surface.
class SVD
Singular Value Decomposition of a rectangular matrix.
class Symbols
class System
System of PDE associated to a function space.
class SystemExplicit
describes an explicit system
class SystemImplicit
describes an implicit system
class SystemImplicitLinear
brief description
class SystemImplicitNonLinear
Describes nonlinear implicit systems.
struct Tag
struct Tensor2
Policy for rank 2 tensor polynomials or polynomial sets of dimension Dim.
class Tensor2Base
struct Tensor2Symm
Policy for symmetric rank 2 tensor polynomials or polynomial sets of dimension Dim.
struct Tensor2SymmBase
struct Tensor3
Policy for rank 2 tensor polynomials or polynomial sets of dimension Dim.
class TensorisedBoundaryAdapted
TensorisedBoundaryAdapted Basis on simplex products.
struct Tetrahedron
class TimerData
TimerData is the value for the TimerTable map.
class TimerMap
timers map
struct TimerPair
class TimerTable
TimerTable is a map of timer.
class TimerTool
class TimerToolBase
class TimerToolNull
class TimeSet
struct TimeStepInfo
class that stores time step information:
class TransImage
struct Triangle
class TSBase
class TSBaseMetadata
class TwoSpacesMap
This class provides a correspondancy map between two spaces and particularly between a sequential space Xs defined on a submesh of the parallel space Xp.
struct type_identity
struct type_traits
class TypeInfo
wrapper for std::type_info
struct UpdateInformationObject
struct value_type
class Vector
Numeric vector.
class VectorBlock
block of vector
class VectorBlockBase
class VectorCondensed
Vector to represent statically condensed matrices.
class VectorEigen
interface to vector
struct Vectorial
Policy for Vectorial polynomials or polynomial sets of dimension Dim.
class VectorialBase
class VectorPetsc
class VectorPetscMPI
class VectorPetscMPIRange
class VectorUblas
interface to vector
class VectorValue
interface to vector
class VisitableBase
class VisitableCatchAllDefault
class Visitor
class VisitorBase
The base class of any Acyclic Visitor.
class VisitorBaseImpl
Implements non-strict visitation (you can implement only part of the Visit functions)
class VisitorBaseImpl< mpl::list< Head >, R >
class VisitorBaseImpl< mpl::list< Head, Tail >, R >
class VisitorCyclic
class VisitorList
struct void_basis
class vtkBaseInsituPipeline
class WorldComm
Provides interface to MPI Communicators.
class WorldsComm
a set of worlds communicator
class xmlParser
Typedefs
template<typename MeshType >
using alledges_t = edges_reference_wrapper_t< MeshType >
template<typename MeshType >
using allelements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using allfaces_t = faces_reference_wrapper_t< MeshType >
template<typename Key , int N, int P, typename T = double>
using allocator_matrix_t = Eigen::aligned_allocator< std::pair< const Key, eigen_matrix_type< N, P, T > > >
template<typename MeshType >
using allpoints_t = points_reference_wrapper_t< MeshType >
template<typename T = double, typename SizeT = uint32_type>
using backend_ptr_t = std::shared_ptr< Backend< T, SizeT > >
typedef std::shared_ptr< backend_type > backend_ptrtype
typedef Backend< double, uint32_type > backend_type
template<typename PS >
using blockform1_t = BlockLinearForm< PS >
template<typename PS >
using blockform2_t = BlockBilinearForm< PS >
typedef boost_param_params_461preconditioner< int > boost_param_parameters_461preconditioner
typedef boost_param_params_564eigs< int > boost_param_parameters_564eigs
typedef boost_param_params_926bdf< int > boost_param_parameters_926bdf
using BoundaryConditionFactory = Singleton< BoundaryConditions >
template<typename MeshType >
using boundaryedges_t = edges_reference_wrapper_t< MeshType >
template<typename MeshType >
using boundaryelements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using boundaryfaces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using boundarypoints_t = points_reference_wrapper_t< MeshType >
typedef std::shared_ptr< c_backend_type > c_backend_ptrtype
typedef Backend< std::complex< double > > c_backend_type
template<size_type Contextv, size_type Value>
using clear_value = mpl::size_t< Contextv &(~Value)>
typedef complex128_type complex128_t
typedef std::complex< float64_t > complex128_type
typedef std::complex< double > complex64_type
typedef std::complex< double > complex_type
using Component = ComponentType
template<typename IteratorType , typename ... Args>
using concatenate_t = ext_entities_from_iterator_t< IteratorType >
template<typename T >
using condensed_matrix_ptr_t = std::shared_ptr< condensed_matrix_t< T > >
template<typename T >
using condensed_matrix_t = MatrixCondensed< T >
template<typename T >
using condensed_vector_ptr_t = std::shared_ptr< condensed_vector_t< T > >
template<typename T >
using condensed_vector_t = VectorCondensed< T >
using conforming_t = mpl::bool_< true >
using Context = meta::Context< size_type >
using crbpluginapi_create_ft = boost::function< crbpluginapi_create_t >
using crbpluginapi_create_t = std::shared_ptr< CRBPluginAPI >()
typedef ublas::compressed_matrix< double, ublas::column_major, 0, ublas::unbounded_array< int >, ublas::unbounded_array< double > > csc_matrix_type
typedef ublas::compressed_matrix< double, ublas::row_major, 0, ublas::unbounded_array< int >, ublas::unbounded_array< double > > csr_matrix_type
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationCurl<nonconforming_t>>
using Curl_ptr_t = std::shared_ptr< Curl_t< DomainSpaceType, ImageSpaceType, IteratorRange, InterpType > >
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationCurl<nonconforming_t>>
using Curl_t = OperatorInterpolation< DomainSpaceType, ImageSpaceType, range_t< IteratorRange >, InterpType >
using cycles_t = Feel::uint64_type
typedef std::shared_ptr< d_sparse_matrix_type > d_sparse_matrix_ptrtype
typedef MatrixSparse< double > d_sparse_matrix_type
using d_tensor_eigen_ublas_type = Eigen::TensorMap< Eigen::Tensor< const double, 2 > >
template<typename SizeT = uint32_type>
using datamap_ptr_t = datamap_ptrtype< SizeT >
template<typename SizeT = uint32_type>
using datamap_ptrtype = std::shared_ptr< datamap_t< SizeT > >
template<typename SizeT = uint32_type>
using datamap_t = DataMap< SizeT >
template<typename T >
using decay_type = std::decay_t< remove_shared_ptr_type< std::decay_t< T > >>
using default_t = mpl::bool_< false >
template<int Order, typename MeshType >
using dh_ptrtype = std::shared_ptr< dh_type< Order, MeshType > >
template<typename MeshType , int Order>
using Dh_ptrtype = std::shared_ptr< dh_type< Order, MeshType > >
template<int Order, typename MeshType >
using dh_type = FunctionSpace< MeshType, bases< RaviartThomas< Order > >, Periodicity< NoPeriodicity > >
template<typename MeshType , int Order>
using Dh_type = FunctionSpace< MeshType, bases< RaviartThomas< Order > >, Periodicity< NoPeriodicity > >
typedef uint16_type dim_type
dimension type
using dimpair_t = Eigen::IndexPair< int >
dimension array for Eigen::Tensor
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationDiv<nonconforming_t>>
using Div_ptr_t = std::shared_ptr< Div_t< DomainSpaceType, ImageSpaceType, IteratorRange, InterpType > >
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationDiv<nonconforming_t>>
using Div_t = OperatorInterpolation< DomainSpaceType, ImageSpaceType, range_t< IteratorRange >, InterpType >
using dof_id_type = index_type
dof id type
template<typename SpaceT , bool same_mesh = true>
using dyn_product_space_element_ptr_t = typename ProductSpace< SpaceT, same_mesh >::element_ptrtype
template<typename SpaceT , bool same_mesh = true>
using dyn_product_space_element_t = typename ProductSpace< SpaceT, same_mesh >::element_type
template<typename SpaceT , bool same_mesh = true>
using dyn_product_space_ptr_t = std::shared_ptr< ProductSpace< SpaceT, same_mesh > >
template<typename SpaceT , bool same_mesh = true>
using dyn_product_space_t = ProductSpace< SpaceT, same_mesh >
template<typename SpaceT , typename... SpaceList>
using dyn_product_spaces_element_ptr_t = typename ProductSpaces2< SpaceT, SpaceList... >::element_ptrtype
template<typename SpaceT , typename... SpaceList>
using dyn_product_spaces_element_t = typename ProductSpaces2< SpaceT, SpaceList... >::element_type
template<typename SpaceT , typename... SpaceList>
using dyn_product_spaces_ptr_t = std::shared_ptr< ProductSpaces2< SpaceT, SpaceList... > >
template<typename SpaceT , typename... SpaceList>
using dyn_product_spaces_t = ProductSpaces2< SpaceT, SpaceList... >
template<typename MeshType >
using edges_reference_wrapper_t = boost::tuple< mpl::size_t< MESH_EDGES >, typename MeshTraits< MeshType >::edge_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::edge_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::edges_reference_wrapper_ptrtype >
template<int N = Eigen::Dynamic, int P = Eigen::Dynamic, typename T = double>
using eigen_matrix_type = Eigen::Matrix< T, N, P >
template<typename T = double>
using eigen_matrix_xx_col_type = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor >
template<int Dim, typename T = double>
using eigen_vector_type = Eigen::Matrix< T, Dim, 1 >
template<typename SpaceT , typename = std::enable_if_t<is_functionspace_v<SpaceT>>>
using element_ptr_t = typename SpaceT::element_ptrtype
get the element shared ptr type of a functionspace
template<typename SpaceT , typename = std::enable_if_t<is_functionspace_v<SpaceT>>>
using element_t = typename SpaceT::element_type
get the element type of a functionspace
template<typename MeshType >
using elements_pid_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using elements_reference_wrapper_t = boost::tuple< mpl::size_t< MESH_ELEMENTS >, typename MeshTraits< MeshType >::element_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::element_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::elements_reference_wrapper_ptrtype >
template<typename MeshType >
using elements_wrapper_ptr_t = typename MeshTraits< MeshType >::elements_reference_wrapper_ptr_type
template<typename MeshType >
using elements_wrapper_t = typename MeshTraits< MeshType >::elements_reference_wrapper_type
template<int M, int N, typename value_type = double>
using em_fixed_size_cmatrix_t = Eigen::Map< const Eigen::Matrix< value_type, M, N > >
template<int M, int N, typename value_type = double>
using em_fixed_size_matrix_t = Eigen::Map< Eigen::Matrix< value_type, M, N > >
template<typename T = double>
using em_matrix_col_type = Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor > >
Eigen type to map matrix_node<>::type.
template<typename T = double>
using em_matrix_row_type = Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor > >
Eigen type to map matrix_type (row major)
template<typename T = double>
using em_node_type = Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, 1 > >
Eigen type to map node_type.
using entity_process_t = EntityProcessType
template<typename RangeType >
using entity_range_t = typename boost::unwrap_reference< typename boost::tuples::template element< 1, range_t< RangeType > >::type::value_type >::type
template<typename SizeT = uint32_type>
using EntityDof = FaceDof< SizeT >
template<typename MeshType >
using ext_edges_t = edges_reference_wrapper_t< MeshType >
template<typename MeshType >
using ext_elements_t = elements_reference_wrapper_t< MeshType >
template<typename IteratorType >
using ext_entities_from_iterator_t = boost::tuple< filter_enum_t< IteratorType >, typename std::vector< boost::reference_wrapper< filter_entity_t< IteratorType > const > >::const_iterator, typename std::vector< boost::reference_wrapper< filter_entity_t< IteratorType > const > >::const_iterator, std::shared_ptr< std::vector< boost::reference_wrapper< filter_entity_t< IteratorType > const > > > >
template<typename MeshType >
using ext_faces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using faces_pid_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using faces_reference_wrapper_t = boost::tuple< mpl::size_t< MESH_FACES >, typename MeshTraits< MeshType >::face_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::face_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::faces_reference_wrapper_ptrtype >
template<typename IteratorType >
using filter_entity_t = typename boost::unwrap_reference< typename filter_iterator_t< IteratorType >::value_type >::type
template<typename IteratorType >
using filter_enum_t = typename boost::tuples::element< 0, typename meta::remove_all< IteratorType >::type >::type
template<typename IteratorType >
using filter_iterator_t = typename boost::tuples::element< 1, typename meta::remove_all< IteratorType >::type >::type
typedef int64_type flag_type
template<typename FE1 , typename VectorType = typename Backend<typename functionspace_type<FE1>::value_type>::vector_type, typename ElemContType = VectorType>
using form1_space_t = typename form1_t< FE1, VectorType, ElemContType >::space_type
provide the type of the space associated to the linear form
template<typename FE1 , typename VectorType = typename Backend<typename functionspace_type<FE1>::value_type>::vector_type, typename ElemContType = VectorType>
using form1_t = form1_type< FE1, VectorType, ElemContType >
provide the type of the linear form
template<typename FE1 , typename VectorType = typename Backend<typename functionspace_type<FE1>::value_type>::vector_type, typename ElemContType = VectorType>
using form1_type = Feel::vf::detail::LinearForm< FE1, VectorType, ElemContType >
provide the type of the linear form
template<typename ElementT >
using functionspace_element_type = typename mpl::if_< is_functionspace_element< decay_type< ElementT > >, mpl::identity< decay_type< ElementT > >, mpl::identity< void > >::type::type
provides the function space type if FESpace is a shared_ptr of a function space then provides the function space type
typedef parameter::parameters< parameter::required< tag::mesh_type, boost::is_base_and_derived< MeshBase<>, _ > >, parameter::optional< parameter::deduced< tag::bases_list >, boost::is_base_and_derived< Feel::detail::bases_base, _ > >, parameter::optional< parameter::deduced< tag::value_type >, boost::is_floating_point< _ > >, parameter::optional< parameter::deduced< tag::mortar_type >, boost::is_base_and_derived< Feel::detail::mortar_base, _ > >, parameter::optional< parameter::deduced< tag::periodicity_type >, boost::is_base_and_derived< Feel::detail::periodicity_base, _ > > > functionspace_signature
template<typename FESpace >
using functionspace_type = typename mpl::if_< is_functionspace< decay_type< FESpace > >, mpl::identity< decay_type< FESpace > >, mpl::identity< void > >::type::type
provides the function space type if FESpace is a shared_ptr of a function space then provides the function space type
typedef GeoEntity< Simplex< 0, 1 > > GeoPoint
typedef Feel::Singleton< GinacExprManagerImpl > GinacExprManager
typedef Feel::Singleton< GinacExprManagerDefaultFileNameImpl > GinacExprManagerDefaultFileName
typedef Feel::Singleton< GinacExprManagerDefaultFileNameDeleterImpl > GinacExprManagerDefaultFileNameDeleter
typedef Feel::Singleton< GinacExprManagerDeleterImpl > GinacExprManagerDeleter
typedef std::shared_ptr< gmsh_type > gmsh_ptrtype
typedef Gmsh gmsh_type
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationGradient<nonconforming_t>>
using Grad_ptr_t = std::shared_ptr< Grad_t< DomainSpaceType, ImageSpaceType, IteratorRange, InterpType > >
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationGradient<nonconforming_t>>
using Grad_t = OperatorInterpolation< DomainSpaceType, ImageSpaceType, range_t< IteratorRange >, InterpType >
template<size_type Contextv, size_type Value>
using has_value = mpl::bool_<(Contextv &Value) !=0 >
typedef ublas::symmetric_matrix< double, ublas::lower, ublas::row_major, ublas::bounded_array< double, 9 > > hessian_node_type
hessian type
template<typename T >
using holo3_image = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor >
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationNonConforming>
using I_ptr_t = std::shared_ptr< I_t< DomainSpaceType, ImageSpaceType, IteratorRange, InterpType > >
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationNonConforming>
using I_t = operator_interpolation_t< DomainSpaceType, ImageSpaceType, IteratorRange, InterpType >
template<typename MeshType >
using idelements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using idfaces_t = faces_reference_wrapper_t< MeshType >
template<typename ConvexT , typename T = double>
using im_t = typename mpl::if_< mpl::bool_< ConvexT::is_simplex >, mpl::identity< IMGeneral< ConvexT::nDim, T, Simplex > >, mpl::identity< IMGeneral< ConvexT::nDim, T, Hypercube > > >::type::type
type of quadrature
template<typename T >
using IMFactory = Feel::Singleton< Feel::Factory< IMBase< T >, std::string > >
template<typename T >
using IMMaxOrderFactory = Feel::Singleton< std::map< std::string, IMMaxOrder< T > > >
template<typename MeshType >
using index_t = typename MeshType::index_type
using index_type = uint32_type
typedef boost::int16_t int16_type
typedef boost::int32_t int32_type
typedef boost::int64_t int64_type
typedef boost::int8_t int8_type
template<typename MeshType >
using internaledges_t = edges_reference_wrapper_t< MeshType >
template<typename MeshType >
using internalelements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using internalfaces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using internalpoints_t = points_reference_wrapper_t< MeshType >
using InterpolationConforme = InterpolationConforming
template<typename C >
using InterpolationID = typename mpl::if_< C, mpl::identity< InterpolationConforming >, mpl::identity< InterpolationNonConforming > >::type::type
using InterpolationNonConforme = InterpolationNonConforming
template<typename MeshType >
using interprocessfaces_t = faces_reference_wrapper_t< MeshType >
template<typename IteratorType , typename ... Args>
using intersect_t = ext_entities_from_iterator_t< IteratorType >
template<typename FuncSpaceType >
using is_functionspace = typename std::is_base_of< FunctionSpaceBase, FuncSpaceType >::type
if T has base class FunctionSpaceBase (hense if it is a function space) then provides the member constant value equal to true, false otherwise
template<typename ElementType >
using is_functionspace_element = typename std::is_base_of< FunctionSpaceBase::ElementBase, ElementType >::type
if T has base class ElementBase (hense if it is an element of a function space) then provides the member constant value equal to true, false otherwise
template<typename P >
using is_hcurl_conforming = boost::is_base_of< HCurlPolynomialSet, P >
type traits for hcurl conforming polynomialset
template<typename P >
using is_hcurl_conforming_t = boost::is_base_of< HCurlPolynomialSet, P >
template<typename P >
using is_hdiv_conforming = boost::is_base_of< HDivPolynomialSet, P >
type traits for hdiv conforming polynomialset
template<typename P >
using is_hdiv_conforming_t = boost::is_base_of< HDivPolynomialSet, P >
template<typename P >
using is_lagrange_polynomialset = std::is_base_of< fem::LagrangePolynomialSet, P >
template<typename T >
using is_matrix_polynomial = is_tensor2_polynomial< T >
template<typename MeshType >
using is_mesh = typename std::is_base_of< MeshBase<>, MeshType >::type
if T has base class MeshBase<> (hense if it is a function space) then provides the member constant value equal to true, false otherwise
template<typename T >
using is_scalar_field = typename std::is_base_of< ScalarBase, T >::type
if T has base class ScalarBase then
template<typename T >
using is_scalar_t = mpl::bool_< std::is_base_of_v< ScalarBase, T > >
template<class T >
using is_std_vector_t = is_std_vector< T >
template<typename T >
using is_tensor2_field = typename std::is_base_of< Tensor2Base, T >::type
if T has base class Tensor2Base then
template<typename T >
using is_tensor2_t = mpl::bool_< std::is_base_of_v< Tensor2Base, T > >
template<typename T >
using is_tensor2symm_field = typename std::is_base_of< Tensor2SymmBase, T >::type
if T has base class Tensor2SymmBase then
template<typename T >
using is_vector_field = typename std::is_base_of< VectorialBase, T >::type
if T has base class VectorialBase then
template<typename T >
using is_vectorial_polynomial = is_vector_polynomial< T >
template<typename T >
using is_vectorial_t = mpl::bool_< std::is_base_of_v< VectorialBase, T > >
typedef std::shared_ptr< iteration_type > iteration_ptrtype
typedef Iteration< double > iteration_type
typedef ublas::matrix< double, ublas::column_major, ublas::bounded_array< double, 9 > > lapack_matrix_type
typedef GeoEntity< Hypercube< 3, 1 > > LinearHexa
typedef GeoEntity< Simplex< 1, 1 > > LinearLine
typedef GeoEntity< Hypercube< 2, 1 > > LinearQuad
typedef GeoEntity< Simplex< 3, 1 > > LinearTetra
typedef GeoEntity< Simplex< 2, 1 > > LinearTriangle
template<typename T >
using local_interpolant_t = typename decay_type< T >::local_interpolant_type
template<typename T >
using local_interpolants_t = typename T::local_interpolants_type
template<int Dim, int GeoOrder = 1, template< uint16_type, uint16_type, uint16_type > class Convex = Simplex>
using ls_element_type = typename ls_space_type< Dim, GeoOrder, Convex >::element_type
template<int Dim, int GeoOrder = 1, template< uint16_type, uint16_type, uint16_type > class Convex = Simplex>
using ls_mesh_ptrtype = std::shared_ptr< Feel::Mesh< Convex< Dim, GeoOrder, Dim > > >
template<int Dim, int GeoOrder = 1, template< uint16_type, uint16_type, uint16_type > class Convex = Simplex>
using ls_mesh_type = Feel::Mesh< Convex< Dim, GeoOrder, Dim > >
template<int Dim, int GeoOrder = 1, template< uint16_type, uint16_type, uint16_type > class Convex = Simplex>
using ls_space_ptrtype = Pch_ptrtype< ls_mesh_type< Dim, GeoOrder, Convex >, 1 >
template<int Dim, int GeoOrder = 1, template< uint16_type, uint16_type, uint16_type > class Convex = Simplex>
using ls_space_type = Pch_type< ls_mesh_type< Dim, GeoOrder, Convex >, 1 >
template<int Dim, int GeoOrder = 1>
using lsh_element_type = ls_element_type< Dim, GeoOrder, Hypercube >
template<int Dim, int GeoOrder = 1>
using lsh_mesh_type = ls_mesh_type< Dim, GeoOrder, Hypercube >
template<int Dim, int GeoOrder = 1>
using lsh_space_type = ls_space_type< Dim, GeoOrder, Hypercube >
template<typename MeshType >
using marked2elements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using marked2faces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using marked3elements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using marked3faces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using markededges_t = edges_reference_wrapper_t< MeshType >
template<typename MeshType >
using markedelements_t = elements_reference_wrapper_t< MeshType >
template<typename MeshType >
using markedfaces_t = faces_reference_wrapper_t< MeshType >
template<typename MeshType >
using markedpoints_t = points_reference_wrapper_t< MeshType >
typedef std::shared_ptr< Material > material_ptrtype
typedef Material material_type
typedef Singleton< Feel::Factory< Material, std::string > > MaterialFactory
using matricial_t = rank_t< 2 >
using matrixN_type = Eigen::MatrixXd
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
using mesh_t = decay_type< MeshType >
provides the mesh type if MeshType is a shared_ptr of a Mesh then provides the mesh type
using microseconds_t = double
using multiple_space_t = hana::integral_constant< int, 2 >
using multiple_spaces_t = multiple_space_t
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using NChv_ptrtype = typename meta::NChv< MeshType, Order, Pts, Tag >::ptrtype
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using NChv_type = typename meta::NChv< MeshType, Order, Pts, Tag >::type
template<typename MeshType , int Order>
using Ned1h_ptrtype = typename meta::Ned1h< MeshType, Order >::ptrtype
template<typename MeshType , int Order>
using Ned1h_type = typename meta::Ned1h< MeshType, Order >::type
template<typename T = double, uint16_type S = 3>
using node_t = typename node< T, S >::type
using nonconforming_t = mpl::bool_< false >
template<typename MeshType , int Order, int Tag = 0>
using Odh_ptrtype = typename meta::Odh< MeshType, Order, Tag >::ptrtype
template<typename MeshType , int Order, int Tag = 0>
using Odh_type = typename meta::Odh< MeshType, Order, Tag >::type
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationNonConforming>
using operator_interpolation_t = OperatorInterpolation< DomainSpaceType, ImageSpaceType, range_t< IteratorRange >, InterpType >
get the type of an OperatorInterpolation
using optimizable_t = mpl::bool_< true >
using optional_double_t = boost::optional< double >
using ParameterSpaceX = ParameterSpace<>
dynamic parameter space type definition
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pch_element_t = typename Pch_type< MeshType, Order, T, Pts, Tag >::element_type
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pch_element_type = Pch_element_t< MeshType, Order, T, Pts, Tag >
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pch_ptrtype = typename meta::Pch< MeshType, Order, T, Pts, Tag >::ptrtype
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pch_type = typename meta::Pch< MeshType, Order, T, Pts, Tag >::type
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchm_ptrtype = typename meta::Pchm< MeshType, Order, T, Pts, Tag >::ptrtype
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchm_type = typename meta::Pchm< MeshType, Order, T, Pts, Tag >::type
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchms_ptrtype = typename meta::Pchms< MeshType, Order, T, Pts, Tag >::ptrtype
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchms_type = typename meta::Pchms< MeshType, Order, T, Pts, Tag >::type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pchv_element_t = typename Pchv_type< MeshType, Order, Pts >::element_type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pchv_element_type = Pchv_element_t< MeshType, Order, Pts >
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchv_ptrtype = typename meta::Pchv< MeshType, Order, Pts, Tag >::ptrtype
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pchv_type = typename meta::Pchv< MeshType, Order, Pts, Tag >::type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdh_element_t = typename Pdh_type< MeshType, Order, Pts >::element_type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdh_element_type = Pdh_element_t< MeshType, Order, Pts >
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdh_ptrtype = std::shared_ptr< Pdh_type< MeshType, Order, Pts > >
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdh_type = FunctionSpace< MeshType, bases< Lagrange< Order, Scalar, Discontinuous, Pts > >>
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhm_ptrtype = typename meta::Pdhm< MeshType, Order, T, Pts, Tag >::ptrtype
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhm_type = typename meta::Pdhm< MeshType, Order, T, Pts, Tag >::type
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhms_ptrtype = typename meta::Pdhms< MeshType, Order, T, Pts, Tag >::ptrtype
template<typename MeshType , int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhms_type = typename meta::Pdhms< MeshType, Order, T, Pts, Tag >::type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdhv_element_t = typename Pdhv_type< MeshType, Order, Pts >::element_type
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced>
using Pdhv_element_type = Pdhv_element_t< MeshType, Order, Pts >
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhv_ptrtype = typename meta::Pdhv< MeshType, Order, Pts, Tag >::ptrtype
template<typename MeshType , int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, int Tag = 0>
using Pdhv_type = typename meta::Pdhv< MeshType, Order, Pts, Tag >::type
template<typename MeshType >
using pid_edges_t = edges_reference_wrapper_t< MeshType >
typedef Geo0D< 3 > Point
template<typename MeshType >
using points_pid_t = points_reference_wrapper_t< MeshType >
template<typename MeshType >
using points_reference_wrapper_t = boost::tuple< mpl::size_t< MESH_POINTS >, typename MeshTraits< MeshType >::point_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::point_reference_wrapper_const_iterator, typename MeshTraits< MeshType >::points_reference_wrapper_ptrtype >
typedef std::shared_ptr< Preconditioner< double, uint32_type > > preconditioner_ptrtype
typedef Preconditioner< double, uint32_type > preconditioner_type
template<typename... SpaceList>
using product_spaces_element_ptr_t = typename ProductSpaces< SpaceList... >::element_ptrtype
template<typename... SpaceList>
using product_spaces_element_t = typename ProductSpaces< SpaceList... >::element_type
template<typename... SpaceList>
using product_spaces_t = ProductSpaces< SpaceList... >
template<class DomainSpace , class DualImageSpace >
using projector_ptrtype = std::shared_ptr< Projector< DomainSpace, DualImageSpace > >
template<class DomainSpace , class DualImageSpace >
using projector_type = Projector< DomainSpace, DualImageSpace >
typedef uint16_type quad_order_type
quadrature order type
typedef GeoEntity< Hypercube< 3, 2 > > QuadraticHexa
typedef GeoEntity< Simplex< 1, 2 > > QuadraticLine
typedef GeoEntity< Hypercube< 2, 2 > > QuadraticQuad
typedef GeoEntity< Simplex< 3, 2 > > QuadraticTetra
typedef GeoEntity< Simplex< 2, 2 > > QuadraticTriangle
template<typename RangeType >
using range_t = typename mpl::if_< boost::is_std_list< RangeType >, mpl::identity< RangeType >, mpl::identity< std::list< RangeType > > >::type::type::value_type
a RangeType can be one or more filter/range objects of the same type, we extract the underlying type by first casting everything to a list and then retrieving consistently the type.
template<int r>
using rank_t = mpl::int_< r >
typedef uint16_type rank_type
type for mpi rank ids
template<typename T >
using rankdown_t = typename RankDown< T >::type
typedef float real32_type
typedef double real64_type
typedef std::shared_ptr< region_tree_type > region_tree_ptrtype
typedef RegionTree region_tree_type
template<typename T >
using remove_shared_ptr_type = typename remove_shared_ptr< T >::type
template<typename T >
using remove_std_vector_t = typename remove_std_vector< T >::type
using scalar_t = rank_t< 0 >
using seconds_t = double
template<size_type Contextv, size_type Value>
using set_value = mpl::size_t<(Contextv|Value)>
typedef Singleton< Factory< Simget, std::string > > SimgetFactory
Simget factory.
using single_space_t = hana::integral_constant< int, 1 >
using single_spaces_t = single_space_t
using size_type = size_t
Indices (starting from 0)
typedef std::shared_ptr< d_sparse_matrix_type > sparse_matrix_ptrtype
typedef Feel::Singleton< StencilManagerImpl > StencilManager
template<typename... T>
using strongest_numeric_type = std::common_type_t< T... >
template<typename IteratorRangeT >
using submeshrange_t = typename Feel::detail::submeshrangetype< IteratorRangeT >::type
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
using support_mesh_t = typename unwrap_ptr_t< MeshSupportType >::mesh_type
typedef ublas::symmetric_adaptor< lapack_matrix_type, ublas::lower > symmetric_matrix_type
template<typename value_type = double>
using tensor1_map_t = Eigen::TensorMap< Eigen::Tensor< const value_type, 1 > >
template<int M, int N, typename value_type = double>
using tensor2_fixed_size_t = Eigen::TensorFixedSize< value_type, Eigen::Sizes< M, N > >
template<typename value_type = double>
using tensor2_map_t = Eigen::TensorMap< Eigen::Tensor< const value_type, 2 > >
using tensor2symm_false = std::integral_constant< bool, false >
using tensor2symm_true = std::integral_constant< bool, true >
template<int M, int N, int P, typename value_type = double>
using tensor3_fixed_size_t = Eigen::TensorFixedSize< value_type, Eigen::Sizes< M, N, P > >
template<typename value_type = double>
using tensor_eigen_ublas_type = Eigen::TensorMap< Eigen::Tensor< const value_type, 2 > >
Tensor map to a ublas_type.
template<int M, int N, typename value_type = double>
using tensor_map_fixed_size_matrix_t = Eigen::TensorMap< Eigen::TensorFixedSize< const value_type, Eigen::Sizes< M, N > >>
Tensor Maps.
template<int N, typename value_type = double>
using tensor_map_t = Eigen::TensorMap< Eigen::Tensor< const value_type, N > >
template<typename SpaceType >
using Test = BasisFunctions< SpaceType, 0 >
using time_point = std::chrono::high_resolution_clock::time_point
using time_quantum_t = uint64_type
typedef lapack_matrix_type transformation_matrix_type
template<typename SpaceType >
using Trial = BasisFunctions< SpaceType, 1 >
template<typename T >
using type_identity_t = typename type_identity< T >::type
typedef boost::uint16_t uint16_type
typedef boost::uint32_t uint32_type
typedef boost::uint64_t uint64_type
typedef boost::uint8_t uint8_type
template<typename Key , int N, int P, typename T = double>
using unordered_map_eigen_matrix_type = std::unordered_map< Key, eigen_matrix_type< N, P, T >, boost::hash< Key >, std::equal_to< Key >, allocator_matrix_t< Key, N, P, T > >
template<typename T >
using unwrap_ptr_t = remove_shared_ptr_type< T >
template<typename MeshType >
using value_t = typename MeshType::value_type
template<int N, int P, typename T = double>
using vector_eigen_matrix_type = std::vector< eigen_matrix_type< N, P, T >, Eigen::aligned_allocator< eigen_matrix_type< N, P, T > >>
template<int Dim, typename T = double>
using vector_eigen_vector_type = std::vector< eigen_vector_type< Dim, T >, Eigen::aligned_allocator< eigen_vector_type< Dim, T > >>
typedef std::shared_ptr< vector_type > vector_ptrtype
template<int M, int N, typename value_type = double>
using vector_tensor2_fixed_size_t = std::vector< tensor2_fixed_size_t< M, N, value_type > >
template<int M, int N, int P, typename value_type = double>
using vector_tensor3_fixed_size_t = std::vector< tensor3_fixed_size_t< M, N, P, value_type > >
typedef Vector< double > vector_type
typedef std::unique_ptr< vector_type > vector_uptrtype
using vectorial_t = rank_t< 1 >
using vectorN_type = Eigen::VectorXd
using worldcomm_ptr_t = std::shared_ptr< WorldComm >
using worldcomm_t = WorldComm
using worldscomm_ptr_t = std::vector< worldcomm_ptr_t >
Enumerations
enum {
lvl_info = google::GLOG_INFO, lvl_warn = google::GLOG_WARNING, lvl_debug = google::GLOG_INFO, lvl_error = google::GLOG_ERROR,
lvl_fatal = google::GLOG_FATAL
}
enum {
TimeIndependent =0, TimeDependent = 0x1, Linear = 0, NonLinear = 0x2,
Coercive = 0, InfSup = 0x4, Mono = 0, UseBlock =0x8
}
enum { FUNCTIONAL = 0, EQUALITIES, INEQUALITIES }
enum { INTERPOLATE_DIFFERENT_MESH =0, INTERPOLATE_SAME_MESH = 1 }
enum {
STEP_NEW = (1<<0), STEP_HAS_DATA = (1<<1), STEP_ON_DISK = (1<<2), STEP_IN_MEMORY = (1<<3),
STEP_IGNORED = (1<<4), STEP_OVERWRITE = (1<<10)
}
enum AitkenType { AITKEN_STANDARD =0, AITKEN_METHOD_1 =1, FIXED_RELAXATION_METHOD =2 }
enum BackendType {
BACKEND_NONE = -1, BACKEND_GMM, BACKEND_TRILINOS, BACKEND_EIGEN,
BACKEND_EIGEN_DENSE
}
Backend types.
enum BDFTimeScheme {
BDF_ORDER_ONE =1, BDF_ORDER_TWO, BDF_ORDER_THREE, BDF_ORDER_FOUR,
BDF_MAX_ORDER = 4
}
enum BFGSType { BFGS = 0, DFP }
BFGS algorithm (Broyden, Fletcher, Goldfarb, Shanno) Quasi Newton method for optimization problems.
enum Checks { NONE =0, EXACT, CONVERGENCE_ORDER }
enum ComponentType {
NO_COMPONENT = -1, X = 0, Y, Z,
NX, NY, NZ, TX,
TY, TZ
}
enum CRBErrorType { CRB_RESIDUAL = 0, CRB_RESIDUAL_SCM =1, CRB_NO_RESIDUAL =2, CRB_EMPIRICAL =3 }
CRBErrorType Determine the type of error estimation used.
enum CRBModelMode {
PFEM = 0, SCM = 1, CRB = 2, SCM_ONLINE =3,
CRB_ONLINE =4
}
enum DirichletType { STRONG =0, WEAK =1 }
enum EigenProblemType {
NHEP =0, HEP, GNHEP, GHEP,
PGNHEP, INVALID_EIGENPROBLEMTYPE
}
Defines an enum for eigenproblem types.
enum EigenSolverType {
POWER =0, LAPACK, SUBSPACE, ARNOLDI,
LANCZOS, KRYLOVSCHUR, ARPACK, INVALID_EIGENSOLVER
}
Defines an enum for iterative eigenproblem solver types.
enum ElementsType {
MESH_ELEMENTS = 0, MESH_FACES = 1, MESH_INTERNAL_FACES = 2, MESH_EDGES = 3,
MESH_INTERNAL_EDGES = 4, MESH_POINTS = 5
}
entity identifier for mesh iterators
enum EntityProcessType { LOCAL_ONLY, GHOST_ONLY, ALL, IGNORE_ENTITY_ON_INTERPROCESS_FACE }
enum EnumIndex {
GLOBAL_COMPONENT, COMPONENT_IN_COMPONENT, GLOBAL_FUNCTION_INDEX, PER_COMPONENT_FUNCTION_INDEX,
COMPONENT_IN_COMPONENT_FUNCTION_INDEX, FUNCTION_INDEX
}
enum ExporterGeometry { EXPORTER_GEOMETRY_STATIC = 0, EXPORTER_GEOMETRY_CHANGE_COORDS_ONLY = 1, EXPORTER_GEOMETRY_CHANGE = 2 }
enum ExtrapolationType_P1 { zero =0, constant, extrapol }
enum ExtrapolationType_spline { natural =0, clamped }
enum FaceLocation { INTERNAL = false, ON_BOUNDARY = true }
enum FieldSplitType { ADDITIVE =0, MULTIPLICATIVE, SCHUR }
Defines an enum for field split types.
enum FileType { ASCII = 0, BINARY = 1, UNDEFINED }
enum FluidMechanicsModel { STOKES = 0, NAVIER_STOKES }
enum FluidMechanicsOptions { FM_STEADY =0x1, FM_UNSTEADY =0x2, FM_LINEARIZED =0x3, FM_FULLY_IMPLICIT =0x4 }
enum FunctionSpaceType { SCALAR = 0, VECTORIAL = 1, TENSOR2, TENSOR2_SYMM }
enum GeoEntityContext { MESH_ENTITY_INTERNAL = (1<<0), MESH_ENTITY_BOUNDARY = (1<<1) }
enum GeomapStrategyType { GEOMAP_OPT = 0, GEOMAP_O1 = 1, GEOMAP_HO = 2 }
enum GMSH_ALGORITHM_2D {
MESHADAPT =1, AUTO =2, DELAUNAY =5, FRONTAL =6,
BAMG =7, FRONTAL_QUAD =8, PACK_PRLGRMS =9, PACK_PRLGRMS_CSTR =10
}
enum GMSH_ALGORITHM_3D {
DELAUNAY =1, FRONTAL =4, MMG3D =7, RTREE =9,
HXT =10
}
enum GMSH_ENTITY {
GMSH_LINE = 1, GMSH_TRIANGLE = 2, GMSH_QUADRANGLE = 3, GMSH_TETRAHEDRON = 4,
GMSH_HEXAHEDRON = 5, GMSH_PRISM = 6, GMSH_PYRAMID = 7, GMSH_LINE_2 = 8,
GMSH_TRIANGLE_2 = 9, GMSH_QUADRANGLE_2 = 10, GMSH_TETRAHEDRON_2 = 11, GMSH_HEXAHEDRON_2 = 12,
GMSH_PRISM_2 = 13, GMSH_PYRAMID_2 = 14, GMSH_POINT = 15, GMSH_TRIANGLE_INCOMPLETE_3 =20,
GMSH_TRIANGLE_3 =21, GMSH_TRIANGLE_INCOMPLETE_4 =22, GMSH_TRIANGLE_4 =23, GMSH_TRIANGLE_INCOMPLETE_5 =24,
GMSH_TRIANGLE_5 =25, GMSH_LINE_3 =26, GMSH_LINE_4 =27, GMSH_LINE_5 =28,
GMSH_TETRAHEDRON_3 =29, GMSH_TETRAHEDRON_4 =30, GMSH_TETRAHEDRON_5 =31
}
enum GMSH_FORMAT { GMSH_FORMAT_ASCII = 0, GMSH_FORMAT_BINARY = 1 }
enum GMSH_ORDER {
GMSH_ORDER_ONE = 1, GMSH_ORDER_TWO = 2, GMSH_ORDER_THREE = 3, GMSH_ORDER_FOUR = 4,
GMSH_ORDER_FIVE = 5
}
enum GMSH_PARTITIONER { GMSH_PARTITIONER_CHACO = 1, GMSH_PARTITIONER_METIS = 2 }
enum IntegrationFaceEnum {
ALL_FACES = -1, FACE_0 = 0, FACE_1 = 1, FACE_2,
FACE_3, FACE_4, FACE_5, FACE_6,
FACE_7, FACE_8
}
enum interpolation_operand_type {
ID = 0, GRADIENT, CURL, DIV,
EXPR
}
enum InterpolationType { P0 =0, P1, Spline, Akima }
enum InterpolationType_P0 { left =0, right, center }
enum IOStatus { isLoading, isSaving }
enum MatrixProperties
enum MatrixStructure {
SAME_NONZERO_PATTERN, DIFFERENT_NONZERO_PATTERN, SAME_PRECONDITIONER, SUBSET_NONZERO_PATTERN,
INVALID_STRUCTURE
}
indicates the structure of the matrix versus preconditioner
enum MatrixTranspose { MATRIX_TRANSPOSE_ASSEMBLED = 0x1, MATRIX_TRANSPOSE_UNASSEMBLED = 0x2, MATRIX_TRANSPOSE_CHECK = 0x4 }
enum MatSolverPackageType {
MATSOLVER_NONE =-1, MATSOLVER_SPOOLES, MATSOLVER_SUPERLU, MATSOLVER_SUPERLU_DIST,
MATSOLVER_UMFPACK, MATSOLVER_ESSL, MATSOLVER_LUSOL, MATSOLVER_MUMPS,
MATSOLVER_MKL_PARDISO, MATSOLVER_MKL_CPARDISO, MATSOLVER_PASTIX, MATSOLVER_DSCPACK,
MATSOLVER_MATLAB, MATSOLVER_PLAPACK, MATSOLVER_BAS, MATSOLVER_BOOMERAMG,
MATSOLVER_AMS, MATSOLVER_EUCLID, MATSOLVER_PILUT
}
enum MESH_CHANGES { MESH_CHANGES_POINTS_COORDINATES = 0, MESH_CHANGES_CONNECTIVITY = 1, MESH_CHANGES_PARTITION = 2 }
enum MeshComponents {
MESH_UPDATE_EDGES = (1 << 0), MESH_UPDATE_FACES = (1 << 1), MESH_CHECK = (1 << 2), MESH_PARTITION = (1 << 3),
MESH_RENUMBER = (1 << 4), MESH_ADD_ELEMENTS_INFO = (1 << 5), MESH_PROPAGATE_MARKERS = (1 << 6), MESH_REMOVE_PERIODIC_FACES_FROM_BOUNDARY = (1 << 7),
MESH_NO_UPDATE_MEASURES = (1 << 8), MESH_UPDATE_ELEMENTS_ADJACENCY = (1 << 9), MESH_UPDATE_FACES_MINIMAL = (1 << 10), MESH_GEOMAP_NOT_CACHED = (1 << 11),
MESH_DO_NOT_UPDATE = (1 << 16)
}
Mesh components enum.
enum MeshFormat {
MESHPP, INRIA, GMSH, NETGEN,
GAMBIT, ACUSIM
}
Mesh Formats that can be read and/or written.
enum ModelProperty { AXISYMM =1 }
enum NedelecKind { NED1, NED2 }
enum Pattern {
DEFAULT = 1 << 0, EXTENDED = 1 << 1, COUPLED = 1 << 2, PATTERN_SYMMETRIC = 1 << 3,
ZERO = 1 << 4, HAS_NO_BLOCK_PATTERN = 1 << 5, HDG = 1 << 6, NONE = 1<<7,
NONE =0
}
enum PositionOfSpectrum {
LARGEST_MAGNITUDE =0, SMALLEST_MAGNITUDE, LARGEST_REAL, SMALLEST_REAL,
LARGEST_IMAGINARY, SMALLEST_IMAGINARY, INVALID_Postion_of_Spectrum
}
Defines an enum for the position of the spectrum, i.e.
enum PreconditionerType {
IDENTITY_PRECOND =0, JACOBI_PRECOND, BLOCK_JACOBI_PRECOND, SOR_PRECOND,
SSOR_PRECOND, EISENSTAT_PRECOND, ASM_PRECOND, GASM_PRECOND,
CHOLESKY_PRECOND, ICC_PRECOND, ILU_PRECOND, LU_PRECOND,
AMG_PRECOND, USER_PRECOND, SHELL_PRECOND, FIELDSPLIT_PRECOND,
LSC_PRECOND, LSC2_PRECOND, PMM_PRECOND, PCD_PRECOND,
FEELPP_BLOCKNS_PRECOND, FEELPP_BLOCKMS_PRECOND, ML_PRECOND, GAMG_PRECOND,
BOOMERAMG_PRECOND, AMS_PRECOND, REDUNDANT_PRECOND, NONE_PRECOND,
INVALID_PRECONDITIONER
}
Defines an enum for preconditioner types.
enum ProjectorType {
NODAL =-1, L2 =0, L2, H1 =1,
DIFF =2, HDIV =3, HCURL =4, LIFT =5,
CIP =6
}
enum ReferenceGeometry {
GEOMETRY_POINT = (1<<0), GEOMETRY_LINE = (1<<1), GEOMETRY_SURFACE = (1<<2), GEOMETRY_VOLUME = (1<<3),
GEOMETRY_4 = (1<<4), GEOMETRY_5 = (1<<5)
}
enum ReferenceShapes {
SHAPE_LINEAR = (1<<0), SHAPE_BILINEAR = (1<<1), SHAPE_QUADRATIC = (1<<2), SHAPE_NONE = (1<<3),
SHAPE_POINT = (1<<4), SHAPE_LINE = (1<<5), SHAPE_TRIANGLE = (1<<6), SHAPE_QUAD = (1<<7),
SHAPE_HEXA = (1<<8), SHAPE_PRISM = (1<<9), SHAPE_TETRA = (1<<10), SHAPE_SP4 = (1<<11),
SHAPE_SP5 = (1<<12)
}
enum ReinitializerType { FM, HJ }
enum SamplingMode { RANDOM = 0, EQUIDISTRIBUTED = 1, LOGEQUIDISTRIBUTED = 2, READFROMCOMMANDLINE = 3 }
enum scstate { none =0, scstate::updated, modified }
describe the state of local matrix/vector in static condensation
enum solution_t { unique, up_to_a_constant }
enum SolverNonLinearLineSearchType {
BT = 0, NLEQERR, BASIC, L2,
CP
}
enum SolverNonLinearType {
SELECT_IN_ARGLIST =0, LINE_SEARCH, TRUST_REGION, NRICHARDSON,
NKSPONLY, VINEWTONRSLS, VINEWTONRSTR, NGMRES,
QN, NSHELL, GS, NCG,
FAS, MS, NASM, ANDERSON,
ASPIN
}
Define an enum for non linear solver type if SELECT_IN_ARGLIST the choice is done by the arguments in the line command.
enum SolverPackage {
SOLVERS_FEEL =0, SOLVERS_GMM, SOLVERS_EIGEN, SOLVERS_TRILINOS,
SOLVERS_SLEPC, SOLVER_INVALID_PACKAGE
}
Defines an enum for various linear solver packages.
enum SolverType {
CG =0, CGN, CGS, CR,
QMR, TCQMR, TFQMR, BICG,
BICGSTAB, MINRES, GMRES, FGMRES,
LSQR, JACOBI, SOR_FORWARD, SOR_BACKWARD,
SSOR, RICHARDSON, CHEBYSHEV, PREONLY,
GCR, INVALID_SOLVER
}
Defines an enum for iterative solver types.
enum SpectralTransformType { SHIFT =0, SINVERT, FOLD, CAYLEY }
Spectral transform type.
enum StabilizationMethods {
NO, CIP =6, SGS, SUPG,
GALS
}
enum TheShape { LINE = 1, TRIANGLE = 2, TETRAHEDRON = 3 }
enum TSState { TS_UNITIALIZED = 0, TS_RUNNING, TS_STOPPED }
enum TSStragegy { TS_STRATEGY_DT_CONSTANT, TS_STRATEGY_DT_ADAPTATIVE }
enum Zone { LOCAL, GLOBAL, NEIGHBORHOOD }
A Zone can be LOCAL or GLOBAL, NEIGHBORHOOD.
Functions
std::string _o (std::string const &prefix, std::string const &opt)
template<class Expr >
ADExpr< AdFuncAbs< ADExpr< Expr > > > abs (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< AdFuncAbs< ADType< T, Nvar, Order, Var > > > abs (const ADType< T, Nvar, Order, Var > &x)
template<class T >
T Abs (const T &a)
Feel::po::options_description advection_options (std::string const &prefix)
po::options_description aitken_options (std::string const &prefix="")
template<typename SpaceType >
std::shared_ptr< Aitken< SpaceType > > aitkenImpl (std::shared_ptr< SpaceType > const &_space, std::string _type, double _init_theta, double _tol, double _minParam, size_type _maxit)
Feel::po::options_description alemesh_options (std::string const &prefix="fsi")
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
allelements_t< MeshType > allelements (MeshType const &mesh)
po::options_description ams_options (std::string const &prefix="")
FEELPP_EXPORT std::string askPassword (std::string const &message)
Ask the user to fill a password. The password is hidden with asterisks.
po::options_description backend_options (std::string const &prefix="")
po::options_description backendeigen_options (std::string const &prefix="")
po::options_description backendpetsc_options (std::string const &prefix="")
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const bdf (order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time
po::options_description bdf_options (std::string const &prefix="")
template<size_t S, class ITERATOR >
ITERATOR begin (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR > &range)
template<size_t S, class ITERATOR >
ITERATOR begin (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR > const &range)
template<size_t S, class ITERATOR , class CONTAINER >
ITERATOR begin (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > &range)
template<size_t S, class ITERATOR , class CONTAINER >
ITERATOR begin (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > const &range)
template<class ITERATOR >
ITERATOR begin (std::pair< ITERATOR, ITERATOR > &range)
po::options_description benchmark_options (std::string const &prefix="")
add benchmark options to feel++ applications
template<typename FUNCTION , typename DERIVATIVE , typename VECTOR , typename IterationBFGS >
void bfgs (FUNCTION f, DERIVATIVE grad, VECTOR &x, int restart, IterationBFGS &iter, BFGSType version=BFGS, float lambda_init=0.001, float=1.0)
template<typename PS >
BlocksBaseVector< double, uint32_type > blockElement (PS &&ps, backend_ptrtype b=backend(), std::enable_if_t< std::is_base_of< ProductSpaceBase, std::remove_reference_t< PS >>::value > *=nullptr)
template<typename PS >
BlocksBaseVector< double, uint32_type > blockElement (PS &&ps, backend_ptrtype b=backend(), std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< PS >>::value > *=nullptr)
template<typename PS >
BlockLinearForm< PS > blockform1 (PS &&ps)
template<typename PS , typename BackendT >
BlockLinearForm< PS > blockform1 (PS &&ps, BackendT &&b)
template<typename PS , typename T >
BlockLinearForm< PS > blockform1 (PS &&ps, condensed_vector_ptr_t< T > v)
template<typename PS , typename BackendT >
BlockLinearForm< PS > blockform1 (PS &&ps, solve::strategy s, BackendT &&b)
template<typename PS >
BlockBilinearForm< PS > blockform2 (PS &&ps)
template<typename PS , typename BackendT >
BlockBilinearForm< PS > blockform2 (PS &&ps, BackendT &&b)
template<typename PS , typename T >
BlockBilinearForm< PS > blockform2 (PS &&ps, condensed_matrix_ptr_t< T > &m)
template<typename PS , typename BackendT >
BlockBilinearForm< PS > blockform2 (PS &&ps, solve::strategy s, BackendT &&b, size_type pattern=Pattern::COUPLED)
template<typename PS , typename BackendT >
BlockBilinearForm< PS > blockform2 (PS &&ps, solve::strategy s, BackendT &&b, std::vector< size_type > const &patterns)
template<typename PS , typename BackendT >
BlockBilinearForm< PS > blockform2 (PS const &ps, solve::strategy s, BackendT &&b, size_type pattern=Pattern::COUPLED)
template<typename PS , typename BackendT >
BlockBilinearForm< PS > blockform2 (PS const &ps, solve::strategy s, BackendT &&b, std::vector< size_type > const &patterns)
po::options_description blockms_options (std::string const &prefix="")
po::options_description blockns_options (std::string const &prefix="")
template<typename PS >
BlocksBaseVector< double, uint32_type > blockVector (PS &&ps, backend_ptrtype b=backend(), std::enable_if_t< std::is_base_of< ProductSpaceBase, std::remove_reference_t< PS >>::value > *=nullptr)
template<typename PS >
BlocksBaseVector< double, uint32_type > blockVector (PS &&ps, backend_ptrtype b=backend(), std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< PS >>::value > *=nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 * boost::is_convertible< mpl::_, std::shared_ptr< BackendBase > > (optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false)))(BOOST_PP_SEQ_FOLD_LEFT_I_2
template<class ResultType , class Args BOOST_PP_IIF_0>
ResultType boost_param_default_461preconditioner (ResultType(*)(), Args const &, int BOOST_PP_IIF_0(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~,) BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))(nil)(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~, BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))))
template<class ResultType , class Args BOOST_PP_IIF_0>
ResultType boost_param_default_564eigs (ResultType(*)(), Args const &, int BOOST_PP_IIF_0(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~,) BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))(nil)(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~, BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))))
template<class ResultType , class Args BOOST_PP_IIF_0>
ResultType boost_param_default_926bdf (ResultType(*)(), Args const &, int BOOST_PP_IIF_0(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~,) BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))(nil)(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION_ARG, ~, BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_TUPLE_ELEM, BOOST_PP_TUPLE_EAT_3)(2, 0,(BOOST_PP_SEQ_SPLIT_BOOST_PP_VARIADIC_ELEM_2 BOOST_PP_VARIADIC_ELEM_3))))
template<class Args >
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const boost_param_result_926bdf< Args >::type boost_param_implbdf (Args const &args)
template<class Args >
boost_param_result_926bdf< Args >::type boost_param_implbdf (Args const &args)
template<class Args >
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_0 boost_param_result_564eigs< Args >::type boost_param_impleigs (Args const &args)
template<class Args >
boost_param_result_564eigs< Args >::type boost_param_impleigs (Args const &args)
template<class Args >
boost_param_result_461preconditioner< Args >::type boost_param_implpreconditioner (Args const &args)
template<class Args >
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_0 boost_param_result_461preconditioner< Args >::type boost_param_implpreconditioner (Args const &args)
BOOST_PARAMETER_FUNCTION ((AboutData), about, tag,(required(name, *))(optional(author, *, "Feel++ Consortium")(task, *, "developer")(email, *, "feelpp-devel@feelpp.org")(desc, *, "Feel++ application")(license,(int), AboutData::License_GPL_V3)(copyright, *, "Copyright (C) Feel++ Consortium")(home, *, "http://www.feelpp.org")(bugs, *, "feelpp-devel@feelpp.org")(version, *, Feel::Info::versionString())))
BOOST_PARAMETER_FUNCTION ((backend_ptrtype), backend, tag,(optional(name,(std::string), "")(kind,(std::string), soption(_prefix=name, _name="backend"))(rebuild,(bool), boption(_prefix=name, _name="backend.rebuild"))(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
BOOST_PARAMETER_FUNCTION ((bool), boption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((c_backend_ptrtype), cbackend, tag,(optional(name,(std::string), "")(kind,(std::string), soption(_prefix=name, _name="backend"))(rebuild,(bool), boption(_prefix=name, _name="backend.rebuild"))(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
BOOST_PARAMETER_FUNCTION ((Checker), checker, tag,(required(name,(std::string))(solution_key,(std::string)))(optional(inputs,(std::map< std::string, std::string >),(std::map< std::string, std::string >{}))(solution,(std::string), inputs.count(solution_key)?inputs.at(solution_key):soption("checker.solution"))(gradient_key,(std::string), std::string{"grad_"}+solution_key)(gradient,(std::string), inputs.count(gradient_key)?inputs.at(gradient_key):soption("checker.gradient"))(script,(std::string), soption("checker.script"))(compute_pde_coefficients,(bool), boption("checker.compute-pde-coefficients"))(prefix,(std::string), "")(verbose,(bool), boption(_prefix=prefix, _name="checker.verbose"))))
check create function
BOOST_PARAMETER_FUNCTION ((double), doption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((double), measure, tag,(required(range, *))(optional(expr, *, cst(1.0))(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)))
BOOST_PARAMETER_FUNCTION ((double), normH1, tag,(required(range, *)(expr, *)(grad_expr, *))(optional(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)))
BOOST_PARAMETER_FUNCTION ((double), normL2, tag,(required(range, *)(expr, *))(optional(parallel,(bool), true)(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)))
BOOST_PARAMETER_FUNCTION ((double), normL2Squared, tag,(required(range, *)(expr, *))(optional(parallel,(bool), true)(quad, *, typename vf::detail::integrate_type< Args >::_quad_type(vf::detail::integrate_type< Args >::exprOrder))(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, typename vf::detail::integrate_type< Args >::_quad1_type(vf::detail::integrate_type< Args >::exprOrder_1))(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)))
BOOST_PARAMETER_FUNCTION ((double), normSemiH1, tag,(required(range, *)(grad_expr, *))(optional(parallel,(bool), true)(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)))
BOOST_PARAMETER_FUNCTION ((gmsh_ptrtype), convert2msh, tag,(required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(dim, *(boost::is_integral< mpl::_ >), 3)(order, *(boost::is_integral< mpl::_ >), 1)))
convert to gmsh format
BOOST_PARAMETER_FUNCTION ((gmsh_ptrtype), geo, tag,(required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(desc, *(boost::is_convertible< mpl::_, std::string >), std::string())(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(geo_parameters, *(boost::icl::is_map< mpl::_ >), Gmsh::gpstr2map(soption(_prefix=prefix, _name="gmsh.geo-variables-list", _vm=vm)))(dim, *(boost::is_integral< mpl::_ >), 3)(order, *(boost::is_integral< mpl::_ >), 1)(files_path, *(boost::is_convertible< mpl::_, std::string >), Environment::localGeoRepository())(depends, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.depends", _vm=vm))(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
geo return a gmsh_ptrtype of a .geo mesh
BOOST_PARAMETER_FUNCTION ((int), countoption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((int), ioption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((po::variable_value), option, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((std::string), img2msh, tag,(required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), fs::path(filename).stem())))
convert to msh format
BOOST_PARAMETER_FUNCTION ((std::string), soption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((std::vector< double >), vdoption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((std::vector< std::string >), vsoption, tag,(required(name,(std::string)))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((typename compute_aitken_return< Args >::ptrtype), aitkenPtr, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(prefix, *,"")(type, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="aitken.type"))(initial_theta, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.initial_theta"))(min_theta, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.min_theta"))(tolerance, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.tol"))(maxit,(size_type), ioption(_prefix=prefix, _name="aitken.maxit"))))
BOOST_PARAMETER_FUNCTION ((typename compute_aitken_return< Args >::type), aitken, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(prefix, *,"")(type, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="aitken.type"))(initial_theta, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.initial_theta"))(min_theta, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.min_theta"))(tolerance, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="aitken.tol"))(maxit,(size_type), ioption(_prefix=prefix, _name="aitken.maxit"))))
BOOST_PARAMETER_FUNCTION ((typename compute_form1_return< Args >::type), form1, tag,(required(test, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, Feel::backend())(in_out(vector), *, backend->newVector(test))(init, *(boost::is_integral< mpl::_ >), false)(do_threshold, *(boost::is_integral< mpl::_ >), bool(false))(threshold, *(boost::is_floating_point< mpl::_ >), type_traits< double >::epsilon())(rowstart, *(boost::is_integral< mpl::_ >), 0)(name,(std::string), std::string("linearform.f"))))
BOOST_PARAMETER_FUNCTION ((typename compute_form1_return< Args >::type), form1_mean, tag,(required(test, *)(range, *)(expr, *))(optional(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)(parallel, *(boost::is_integral< mpl::_ >), 1)(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
BOOST_PARAMETER_FUNCTION ((typename compute_form1_return< Args >::type), lform, tag,(required(test, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(in_out(vector), *(Feel::detail::is_vector_ptr< mpl::_ >)))(optional(init, *(boost::is_integral< mpl::_ >), false)(do_threshold, *(boost::is_integral< mpl::_ >), bool(false))(threshold, *(boost::is_floating_point< mpl::_ >), type_traits< double >::epsilon())(rowstart, *(boost::is_integral< mpl::_ >), 0)))
BOOST_PARAMETER_FUNCTION ((typename compute_form2_return< Args, mpl::bool_< boost::is_same< typename parameter::value_type< Args, tag::trial >::type, boost::parameter::void_ >::value > >::type), form2, tag,(required(test, *)(trial, *))(deduced(optional(init, *(boost::is_integral< mpl::_ >), false)(properties,(size_type), NON_HERMITIAN)(pattern, *(boost::is_integral< mpl::_ >), size_type(Pattern::COUPLED))(backend, *, Feel::backend())(in_out(matrix), *(boost::is_convertible< mpl::_, std::shared_ptr< MatrixSparse< double >>>), backend->newMatrix(_test=test, _trial=trial, _pattern=pattern, _properties=properties))(rowstart, *(boost::is_integral< mpl::_ >), 0)(colstart, *(boost::is_integral< mpl::_ >), 0)(name,(std::string), std::string("bilinearform.a")))))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args >::ptrtype), IPtr, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, InterpolationNonConforming())(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args >::ptrtype), opInterpolation, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, InterpolationNonConforming())(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args >::type), I, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, InterpolationNonConforming())(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args, InterpolationCurl< nonconforming_t >>::type), Curl, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, makeCurlInterpolation< nonconforming_t >(nonconforming_t()))(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args, InterpolationDiv< nonconforming_t >>::type), Div, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, makeDivInterpolation< nonconforming_t >(nonconforming_t()))(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opInterpolation_return< Args, InterpolationGradient< nonconforming_t >>::type), Grad, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(range, *, elements(imageSpace->mesh()))(backend, *, Backend< typename compute_opInterpolation_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(type, *, makeGradientInterpolation< nonconforming_t >(nonconforming_t()))(ddmethod,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename compute_opLagrangeP1_return< Args >::type), lagrangeP1, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, Backend< typename compute_opLagrangeP1_return< Args >::space_type::value_type >::build(soption(_name="backend")))(path, *(boost::is_convertible< mpl::_, std::string >), std::string("."))(prefix, *(boost::is_convertible< mpl::_, std::string >), std::string(""))(rebuild, *(boost::is_integral< mpl::_ >), 1)(parallel, *(boost::is_integral< mpl::_ >), 1)(update, *(boost::is_integral< mpl::_ >), MESH_RENUMBER|MESH_UPDATE_EDGES|MESH_UPDATE_FACES|MESH_CHECK)))
BOOST_PARAMETER_FUNCTION ((typename compute_opLinear_return< Args >::type), opLinear, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, Backend< typename compute_opLinear_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))(pattern, *,(size_type) Pattern::COUPLED)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_deim_return< Args >::ptrtype), deim, tag,(required(in_out(model), *))(optional(sampling, *, nullptr)(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(filename, *(boost::is_convertible< mpl::_, std::string >), "")(directory, *(boost::is_convertible< mpl::_, std::string >), "")(tag, *(boost::is_convertible< mpl::_, int >), 0)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_eim_return< Args >::ptrtype), eim, tag,(required(in_out(model), *)(in_out(element), *)(in_out(parameter), *)(in_out(expr), *)(name, *)(space, *))(optional(in_out(element2), *, element)(sampling, *, model->parameterSpace() ->sampling())(verbose,(int), 0)(filename, *(boost::is_convertible< mpl::_, std::string >), "")(directory, *(boost::is_convertible< mpl::_, std::string >), "")(prefix,(std::string), "")))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_exporter_return< Args >::ptrtype), exporter, tag,(required(mesh, *))(optional(fileset, *, boption(_name="exporter.fileset"))(order, *, mpl::int_< 1 >())(name, *, Environment::about().appName())(geo, *, soption(_name="exporter.geometry"))(path, *(boost::is_convertible< mpl::_, std::string >),(fs::path(Environment::exportsRepository())/fs::path(soption("exporter.format"))/name).string())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_functionalLinear_return< Args >::ptrtype), functionalLinear, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, Backend< typename Feel::detail::compute_functionalLinear_return< Args >::domain_space_type::value_type >::build(soption(_name="backend")))))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_functionalLinearComposite_return< Args >::ptrtype), functionalLinearComposite, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, backend())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_functionalLinearFree_return< Args >::ptrtype), functionalLinearFree, tag,(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(expr, *))(optional(backend, *, backend())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_mdeim_return< Args >::ptrtype), mdeim, tag,(required(in_out(model), *))(optional(sampling, *, nullptr)(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(filename, *(boost::is_convertible< mpl::_, std::string >), "")(directory, *(boost::is_convertible< mpl::_, std::string >), "")(tag, *(boost::is_convertible< mpl::_, int >), 0)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_opLinearComposite_return< Args >::ptrtype), opLinearComposite, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(backend, *, backend())(pattern, *,(size_type) Pattern::COUPLED)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_opLinearFree_return< Args >::ptrtype), opLinearFree, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(expr, *))(optional(backend, *, backend())(pattern, *,(size_type) Pattern::COUPLED)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::compute_stencil_type< Args >::ptrtype), stencil, tag,(required(test, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(trial, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(pattern,(uint32_type), Pattern::COUPLED)(pattern_block, *, default_block_pattern)(diag_is_nonzero,(bool), false)(collect_garbage,(bool), true)(close,(bool), true)(range, *(boost::is_convertible< mpl::_, stencilRangeMapTypeBase >), stencilRangeMap0Type())(range_extended, *(boost::is_convertible< mpl::_, stencilRangeMapTypeBase >), stencilRangeMap0Type())(quad, *(boost::is_convertible< mpl::_, stencilQuadSetBase >), stencilQuadSet<>())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::convolve_type< Args >::element_type), convolve, tag,(required(range, *)(expr, *)(space, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)(quadptloc, *, typename vf::detail::integrate_type< Args >::_quadptloc_ptrtype())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::createSubmesh< Args >::ptrtype), createSubmesh, tag,(required(mesh, *)(range, *))(optional(worldcomm, *, mesh->worldCommPtr())(context, *(boost::is_integral< mpl::_ >), EXTRACTION_KEEP_MESH_RELATION|EXTRACTION_KEEP_MARKERNAMES_ONLY_PRESENT)(update, *(boost::is_integral< mpl::_ >), MESH_CHECK|MESH_UPDATE_FACES|MESH_UPDATE_EDGES)(only_on_boundary_faces,(bool), false)(view,(bool), false)))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::lift_args< Args >::lift_return_type), opLift, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(type,(DirichletType), WEAK)(penaldir, *(boost::is_arithmetic< mpl::_ >), 20.)(backend, *, Backend< double >::build(soption(_name="backend")))))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype), createGMSHMesh, tag,(required(mesh, *)(desc, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(format, *, ioption(_prefix=prefix, _name="gmsh.format", _vm=vm))(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(parametricnodes, *(boost::is_integral< mpl::_ >), 0)(in_memory, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.in-memory", _vm=vm))(straighten, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(structured, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.structured", _vm=vm))(update, *(boost::is_integral< mpl::_ >), MESH_RENUMBER|MESH_UPDATE_EDGES|MESH_UPDATE_FACES|MESH_CHECK)(force_rebuild, *(boost::is_integral< mpl::_ >), 0)(physical_are_elementary_regions, *, boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(periodic, *, PeriodicEntities())(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *(boost::is_convertible< mpl::_, std::string >), "")(worldcomm,(worldcomm_ptr_t), mesh->worldCommPtr())(partitions, *(boost::is_integral< mpl::_ >), worldcomm->localSize())(partition_file, *(boost::is_integral< mpl::_ >), 0)(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))(directory,(std::string), "")))
create a mesh data structure (hold in a shared_ptr<>) using GMSH
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype), loadGMSHMesh, tag,(required(mesh, *)(filename, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(straighten, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(update, *(boost::is_integral< mpl::_ >), 0)(physical_are_elementary_regions, *, boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(worldcomm,(worldcomm_ptr_t), mesh->worldCommPtr())(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *, "")(partitions, *(boost::is_integral< mpl::_ >), worldcomm->globalSize())(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(partition_file, *(boost::is_integral< mpl::_ >), 0)(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))))
load a mesh data structure (hold in a shared_ptr<>) using GMSH
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype), loadMesh, tag,(required(mesh, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(filename, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.filename", _vm=vm))(desc, *, std::shared_ptr< gmsh_type >())(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(straighten,(bool), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(update, *(boost::is_integral< mpl::_ >), MESH_CHECK|MESH_UPDATE_FACES|MESH_UPDATE_EDGES)(physical_are_elementary_regions,(bool), boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(worldcomm, *, mesh->worldCommPtr())(force_rebuild, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.rebuild", _vm=vm))(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *(boost::is_convertible< mpl::_, std::string >), "")(partitions, *(boost::is_integral< mpl::_ >),(worldcomm)?worldcomm->globalSize():1)(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(savehdf5, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.savehdf5", _vm=vm))(partition_file, *(boost::is_integral< mpl::_ >), 0)(depends, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.depends", _vm=vm))(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))))
load a mesh data structure (hold in a shared_ptr<>) using GMSH
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::option< Args >::type), optionT, tag,(required(name,(std::string))(in_out(opt), *))(optional(sub,(std::string),"")(prefix,(std::string),"")(vm,(po::variables_map const &), Environment::vm())))
BOOST_PARAMETER_FUNCTION ((typename Feel::detail::projector_args< Args >::return_type), opProjection, tag,(required(domainSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >))(imageSpace, *(boost::is_convertible< mpl::_, std::shared_ptr< FunctionSpaceBase > >)))(optional(type,(ProjectorType), L2)(penaldir, *(boost::is_arithmetic< mpl::_ >), 20.)(backend, *, Backend< double >::build(soption(_name="backend")))))
BOOST_PARAMETER_FUNCTION ((typename meta::blockms< typename parameter::value_type< Args, tag::space >::type::element_type >::ptrtype), blockms, tag,(required(space, *)(matrix, *)(model, *))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "blockms")))
BOOST_PARAMETER_FUNCTION ((typename vf::detail::integrate_type< Args >::expr_type), integrate, tag,(required(range, *)(expr, *))(optional(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)(quadptloc, *, typename vf::detail::integrate_type< Args >::_quadptloc_ptrtype())))
BOOST_PARAMETER_FUNCTION ((typename vf::detail::integrate_type< Args >::expr_type::expression_type::matrix_type), mean, tag,(required(range, *)(expr, *))(optional(quad, *, quad_order_from_expression)(geomap, *, GeomapStrategyType::GEOMAP_OPT)(quad1, *, quad_order_from_expression)(use_tbb,(bool), false)(use_harts,(bool), false)(grainsize,(int), 100)(partitioner, *, "auto")(verbose,(bool), false)(parallel, *(boost::is_integral< mpl::_ >), 1)(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
BOOST_PARAMETER_FUNCTION ((void), saveGeoEntityAsGMSHMesh, tag,(required(geoentity, *)(filename, *))(optional(pointset, *, typename Feel::detail::meshFromGeoEntity< Args >::pointset_type())))
BOOST_PARAMETER_FUNCTION ((void), saveGMSHMesh, tag,(required(mesh, *)(filename, *))(optional(parametricnodes, *(boost::is_integral< mpl::_ >), 0)))
save a mesh data structure (hold in a shared_ptr<>) in the GMSH format
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_FUNCTION_SPLIT_ARG_BOOST_PP_REM (0, BOOST_PP_SEQ_NIL, 0, BOOST_PP_SEQ_NIL)
BOOST_PARAMETER_MEMBER_FUNCTION ((typename meta::blockas< typename parameter::value_type< Args, tag::space >::type::element_type, typename parameter::value_type< Args, tag::space2 >::type::element_type >::ptrtype), blockas, tag,(required(space, *)(space2, *)(matrix, *))(optional(type, *, "AS")(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(bc, *,(BoundaryConditions()))(h,(double), doption("parameters.k"))))
BOOST_PARAMETER_MEMBER_FUNCTION ((typename meta::blockns< typename parameter::value_type< Args, tag::space >::type::element_type, typename parameter::value_type< Args, tag::properties_space >::type::element_type >::ptrtype), blockns, tag,(required(space, *)(matrix, *)(type, *))(optional(properties_space, *,(Pdh< 0 >(space->mesh())))(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(bc, *,(BoundaryConditions()))(mu, *, cst(doption("mu")))(rho, *, cst(doption("rho")))(alpha, *, cst(0.))))
BOOST_PARAMETER_NAME (initMesh) BOOST_PARAMETER_NAME(geofile) BOOST_PARAMETER_NAME(adaptType) BOOST_PARAMETER_NAME(var) BOOST_PARAMETER_NAME(metric) BOOST_PARAMETER_NAME(hMin) BOOST_PARAMETER_NAME(hMax) BOOST_PARAMETER_NAME(tol) template< int Dim
BOOST_PARAMETER_NAME (keyword) BOOST_PARAMETER_NAME(repository) namespace FeelModels
BOOST_PARAMETER_NAME (thickness) BOOST_PARAMETER_NAME(use_adaptive_thickness) BOOST_PARAMETER_NAME(impl) BOOST_PARAMETER_NAME(imorder) namespace FeelModels
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_1 (BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_SEQ_FOLD_LEFT_F (BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))))(BOOST_PP_WHILE_2
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_SEQ_FOLD_LEFT_F (BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))))(BOOST_PP_WHILE_2
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_SEQ_FOLD_LEFT_F (BOOST_PARAMETER_FUNCTION_SPLIT_ARG, BOOST_PARAMETER_FUNCTION_SPLIT_ARG_BOOST_PP_REM(0, BOOST_PP_SEQ_NIL, 0, BOOST_PP_SEQ_NIL), BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))))
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_SEQ_FOLD_LEFT_F (BOOST_PARAMETER_FUNCTION_SPLIT_ARG, BOOST_PARAMETER_FUNCTION_SPLIT_ARG_BOOST_PP_REM(0, BOOST_PP_SEQ_NIL, 0, BOOST_PP_SEQ_NIL), BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))))
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_SEQ_FOR_EACH_I_DETAIL_CHECK_EMPTY (BOOST_PARAMETER_FUNCTION_FWD_COMBINATION, ~, BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))))
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_SEQ_FOR_EACH_I_DETAIL_CHECK_EMPTY (BOOST_PARAMETER_FUNCTION_FWD_COMBINATION, ~, BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))))
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_TUPLE_EAT_2 (2,(1 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))), BOOST_PP_IIF_0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose"))))(BOOST_PP_SEQ_FOLD_LEFT_I_2, BOOST_PP_SEQ_FOLD_LEFT_F)(BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose")))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(matrixA,(d_sparse_matrix_ptrtype))(matrixB,(d_sparse_matrix_ptrtype)))(optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose"))))))))(BOOST_PP_REPEAT_FROM_TO_M_1
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_TUPLE_EAT_2 (2,(1 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))), BOOST_PP_IIF_0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false)))(BOOST_PP_SEQ_FOLD_LEFT_I_2, BOOST_PP_SEQ_FOLD_LEFT_F)(BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(pc,(PreconditionerType))(backend, *(boost::is_convertible< mpl::_, std::shared_ptr< BackendBase >>)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), "")(matrix,(d_sparse_matrix_ptrtype), d_sparse_matrix_ptrtype())(pcfactormatsolverpackage,(MatSolverPackageType), MATSOLVER_DEFAULT)(rebuild,(bool), false)))))))(BOOST_PP_REPEAT_FROM_TO_M_1
FEELPP_TRAITS_OP_CODE BOOST_PP_TUPLE_REVERSE_1 ((float, float, 1, 0, 7, std::numeric_limits< float >::epsilon() *factor_from_eps_fl, 0)) FEELPP_TRAITS_OP_CODE BOOST_PP_TUPLE_REVERSE_1((double
Generate the type traits.
FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(0, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(0, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(0, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(1, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(1, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(1, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(2, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(2, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 1,(3, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(0, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(0, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(0, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(1, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(1, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(1, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(2, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(2, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 2,(3, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(0, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(0, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(0, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(1, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(1, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(1, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(2, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(2, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 3,(3, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(0, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(0, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(0, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(1, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(1, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(1, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(2, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(2, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 4,(3, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(0, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(0, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(0, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(1, 1), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(1, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(1, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(2, 2), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(2, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY Lagrange FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4 (Simplex, 5,(3, 3), Lagrange) FEELPP_GT_FACTORY BOOST_PP_TUPLE_REVERSE_4(Hypercube
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const boption (_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse
template<typename MeshType >
boundaryedges_t< MeshType > boundaryedges (MeshType const &mesh)
template<typename MeshType >
ext_elements_t< MeshType > boundaryelements (MeshType const &imesh, EntityProcessType entity)
template<typename MeshType >
boundaryelements_t< MeshType > boundaryelements (MeshType const &mesh, uint16_type entity_min_dim=0, uint16_type entity_max_dim=2)
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
faces_reference_wrapper_t< support_mesh_t< MeshSupportType > > const & boundaryfaces (MeshSupportType const &imesh)
template<typename MeshType >
ext_faces_t< MeshType > boundaryfaces (MeshType const &imesh, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
boundaryfaces_t< MeshType > boundaryfaces (MeshType const &mesh)
template<typename MeshType >
boundarypoints_t< MeshType > boundarypoints (MeshType const &mesh)
po::options_description case_options (int default_dim, std::string const &default_discr, std::string const &prefix="")
case options
template<typename CheckerT , typename ElementT , typename = std::enable_if_t<is_scalar_field_v<ElementT> || is_vector_field_v<ElementT> || is_matrix_field_v<ElementT> >>
int check (CheckerT &&thechecker, ElementT const &u, solution_t s=solution_t::unique)
po::options_description checker_options (std::string const &prefix="")
checker class options prefix to create new checkers when there is a need for several checkers in an application
po::options_description cnab2_options (std::string const &prefix="")
Feel::po::options_description coefficientformpde_options (std::string const &prefix)
Feel::po::options_description coefficientformpdes_options (std::string const &prefix)
template<typename MeshType >
std::map< int, markedelements_t< MeshType > > collectionOfMarkedelements (MeshType const &mesh, std::any const &collectionOfMarkersFlag)
template<typename IteratorType , typename Predicate >
ext_entities_from_iterator_t< IteratorType > complement (IteratorType &&it, Predicate pred)
Provides the complement of the set of entities given by [begin(it),end(it)] with respect to the negation of predicate pred.
template<typename Op1Type , typename Op2Type >
std::shared_ptr< OperatorCompose< Op1Type, Op2Type > > compose (std::shared_ptr< Op1Type > op1, std::shared_ptr< Op2Type > op2)
template<typename IteratorType , typename... Args>
FEELPP_EXPORT Feel::concatenate_t< IteratorType > concatenate (IteratorType &&it, Args &&... args)
this function takes a set of iterators over geometrical entities of the same type (e.g.
template<class Expr >
ADExpr< ADFuncCos< ADExpr< Expr > > > cos (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< ADFuncCos< ADType< T, Nvar, Order, Var > > > cos (const ADType< T, Nvar, Order, Var > &x)
po::options_description crbAeroOptions (std::string const &prefix="")
po::options_description crbBlockOptions (int const &n_block=3)
po::options_description crbOptions (std::string const &prefix="")
po::options_description crbPluginOptions (std::string const &prefix="")
command line options for plugins
po::options_description crbSaddlePointOptions (std::string const &prefix="", int const &n_block=2)
po::options_description crbSCMOptions (std::string const &prefix="")
po::options_description crbSEROptions (std::string const &prefix="")
template<typename T , typename IndexT >
ublas::vector< double > cross (Geo0D< 3, T, IndexT > p1, Geo0D< 3, T, IndexT > p2)
template<typename E1 , typename E2 >
ublas::vector< double > cross (ublas::vector_expression< E1 > _p1, ublas::vector_expression< E2 > _p2)
template<typename PS >
BlocksBaseGraphCSR csrGraphBlocks (PS &&ps, uint32_type pattern=Pattern::COUPLED, std::enable_if_t< std::is_base_of< ProductSpaceBase, std::remove_reference_t< PS >>::value > *=nullptr)
template<typename PS >
BlocksBaseGraphCSR csrGraphBlocks (PS &&ps, uint32_type pattern=Pattern::COUPLED, std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< PS >>::value > *=nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
template<typename Poly >
Polynomial< Poly, Vectorial > curl (Polynomial< Poly, Vectorial > const &p)
compute the curl of a vectorial polynomial p
template<typename Poly >
PolynomialSet< Poly, Vectorial > curl (PolynomialSet< Poly, Vectorial > const &p)
compute the curl of a vectorial polynomial set p
template<typename Poly >
Polynomial< Poly, Vectorial > curlt (Polynomial< Poly, Vectorial > const &p)
compute the transpose of the curl of a vectorial polynomial p
template<typename Poly >
PolynomialSet< Poly, Vectorial > curlt (PolynomialSet< Poly, Vectorial > const &p)
compute the transpose of the curl of a vectorial polynomial p
holo3_image< float > cutHbf (holo3_image< float > const &im, int n, int start)
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 d_sparse_matrix_ptrtype (optional(nev,(int), ioption(_name="solvereigen.nev"))(ncv,(int), ioption(_name="solvereigen.ncv"))(mpd,(int), ioption(_name="solvereigen.mpd"))(interval_a,(double), doption("solvereigen.interval-a"))(interval_b,(double), doption("solvereigen.interval-b"))(backend,(BackendType), BACKEND_DEFAULT)(solver,(EigenSolverType), KRYLOVSCHUR)(problem,(EigenProblemType), GHEP)(transform,(SpectralTransformType), SHIFT)(spectrum,(PositionOfSpectrum), LARGEST_MAGNITUDE)(maxit,(int), ioption(_name="solvereigen.maxiter"))(tolerance,(double), doption(_name="solvereigen.tolerance"))(verbose,(bool), boption(_name="solvereigen.verbose"))))(BOOST_PP_SEQ_FOLD_LEFT_I_2
detail void default_prepost_solve (vector_ptrtype rhs, vector_ptrtype sol)
!
po::options_description deimOptions (std::string const &prefix="")
Feel::po::options_description densityviscosity_options (std::string const &prefix)
template<int Dim, typename Matrix >
Matrix::value_type det (Matrix const &M)
template<typename FUNCTION , typename DERIVATIVE , typename VECTOR , typename IterationBFGS >
void dfp (FUNCTION f, DERIVATIVE grad, VECTOR &x, int restart, IterationBFGS &iter, BFGSType version=DFP)
template<int Order, typename MeshType >
dh_ptrtype< Order, MeshType > Dh (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
template<int Order, typename MeshType >
std::shared_ptr< FunctionSpace< MeshType, bases< RaviartThomas< Order >, Lagrange< Order, Scalar, Discontinuous > > > > DhPdh (std::shared_ptr< MeshType > mesh, std::vector< bool > buildExtendedDofTable=std::vector< bool >(2, false))
template<typename OpType >
std::shared_ptr< OperatorDiag< OpType > > diag (std::shared_ptr< OpType > M)
template<typename T >
constexpr int dimension (T const &t)
template<typename T , typename IndexT >
T distance (Geo0D< 1, T, IndexT > const &p1, Geo0D< 1, T, IndexT > const &p2)
template<typename T , typename IndexT >
T distance (Geo0D< 2, T, IndexT > const &p1, Geo0D< 2, T, IndexT > const &p2)
template<typename T , typename IndexT >
T distance (Geo0D< 3, T, IndexT > const &p1, Geo0D< 3, T, IndexT > const &p2)
template<typename FunctionSpaceP0Type , typename FunctionSpaceP1Type >
std::shared_ptr< DistToCurve< FunctionSpaceP0Type, FunctionSpaceP1Type > > distToCurve (std::shared_ptr< FunctionSpaceP0Type > spaceP0, std::shared_ptr< FunctionSpaceP1Type > spaceP1)
template<typename SpaceType , typename RangeType , typename = std::enable_if_t<is_functionspace_v<SpaceType>>>
element_t< SpaceType > distToEntityRange (std::shared_ptr< SpaceType > const &Xh, RangeType const &r)
compute the distance field as element of Xh to boundary defined by range r
template<typename ElementType >
ElementType div (ElementType const &v1, ElementType const &v2, typename boost::enable_if< boost::is_base_of< FunctionSpaceBase::ElementBase, ElementType > >::type *dummy=0)
Computes the element wise division of two vectors and eventually in parallel.
template<typename Poly >
Polynomial< Poly, Scalar > divergence (Polynomial< Poly, Vectorial > const &p)
compute the divergence of a vectorial polynomial p
template<typename Poly >
PolynomialSet< Poly, Scalar > divergence (PolynomialSet< Poly, Vectorial > const &p)
compute the divergence of a vectorial polynomial set p
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const doption (_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final _time
template<typename T >
FEELPP_EXPORT type_traits< T >::real_type dot (std::shared_ptr< Vector< T > > const &v1, std::shared_ptr< Vector< T > > const &v2)
template<typename T >
FEELPP_EXPORT type_traits< T >::real_type dot (Vector< T > const &v1, Vector< T > const &v2)
template<typename Poly , template< uint16_type > class Type>
Polynomial< Poly, Type > dx (Polynomial< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial x}\) of a polynomial p
template<typename Poly , template< uint16_type > class Type>
PolynomialSet< Poly, Type > dx (PolynomialSet< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial x}\) of a polynomial set p
template<typename Poly , template< uint16_type > class Type>
Polynomial< Poly, Type > dy (Polynomial< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial y}\) of a polynomial p
template<typename Poly , template< uint16_type > class Type>
PolynomialSet< Poly, Type > dy (PolynomialSet< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial y}\) of a polynomial set p
template<typename SpaceT , bool same_mesh = true>
ProductSpace< SpaceT, same_mesh > dynProduct (int n, typename SpaceT::mesh_ptrtype mesh)
template<typename SpaceT , bool same_mesh = true>
std::shared_ptr< ProductSpace< SpaceT, same_mesh > > dynProductPtr (int n, std::shared_ptr< SpaceT > const &s)
template<typename SpaceT , bool same_mesh = true>
std::shared_ptr< ProductSpace< SpaceT, same_mesh > > dynProductPtr (int n, typename SpaceT::mesh_ptrtype mesh)
template<typename Poly , template< uint16_type > class Type>
Polynomial< Poly, Type > dz (Polynomial< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial z}\) of a polynomial p
template<typename Poly , template< uint16_type > class Type>
PolynomialSet< Poly, Type > dz (PolynomialSet< Poly, Type > const &p)
compute \(\frac{\partial \cdot}{\partial z}\) of a polynomial set p
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
pid_edges_t< MeshType > edges (MeshType const &mesh)
FEELPP_EXPORT void editPtreeFromOptions (pt::ptree &p, std::string const &prefix="")
template<int Rows, int Cols = Eigen::Dynamic, typename T >
auto eigenMap (ublas::matrix< T, ublas::column_major > const &m, int nRows=Rows, int cols=Cols)
template<int Rows, typename T >
auto eigenMap (ublas::vector< T > const &v, int nrows=Rows)
template<typename ModelType >
std::shared_ptr< EimFunctionNoSolve< ModelType > > eim_no_solve (std::shared_ptr< ModelType > model)
template<typename ExprType , typename EimType >
Expr< vf_div< Expr< vf_sub< ExprType, Expr< OpId< typename EimType::element_type, __VALUE > > > >, Cst< double > > > eimBasisExpression (int m, ExprType const &expr, EimType const &eim)
po::options_description eimOptions (std::string const &prefix="")
Feel::po::options_description electricity_options (std::string const &prefix)
template<typename ElementType >
boost::tuple< mpl::size_t< MESH_ELEMENTS >, typename std::list< ElementType >::const_iterator, typename std::list< ElementType >::const_iterator > element (ElementType const &elt)
template<typename T >
VectorEigen< T > element_product (std::shared_ptr< VectorEigen< T > > const &v1, std::shared_ptr< VectorEigen< T > > const &v2)
Computes the element wise product of two vectors and eventually in parallel.
template<typename T , typename Storage1 , typename Storage2 >
VectorUblas< T > element_product (std::shared_ptr< VectorUblas< T, Storage1 > > const &v1, std::shared_ptr< VectorUblas< T, Storage2 > > const &v2)
Computes the element wise product of two vectors and eventually in parallel.
template<typename T >
VectorEigen< T > element_product (VectorEigen< T > const &v1, VectorEigen< T > const &v2)
Computes the element wise product of two vectors and eventually in parallel.
template<typename T , typename Storage1 , typename Storage2 >
VectorUblas< T > element_product (VectorUblas< T, Storage1 > const &v1, VectorUblas< T, Storage2 > const &v2)
Computes the element wise product of two vectors and eventually in parallel.
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
elements_reference_wrapper_t< support_mesh_t< MeshSupportType > > elements (MeshSupportType const &imesh)
template<typename MeshType >
ext_elements_t< MeshType > elements (MeshType const &imesh, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, decay_type< std::remove_pointer_t< MeshType >>>, int > = 0>
elements_pid_t< MeshType > elements (MeshType const &mesh)
template<typename MeshType >
elements_pid_t< MeshType > elements (MeshType const &mesh, elements_reference_wrapper_t< MeshType > const &rangeElt, faces_reference_wrapper_t< MeshType > const &rangeFace, ElementsType type=ElementsType::MESH_POINTS)
template<typename MeshType >
elements_pid_t< MeshType > elements (MeshType const &mesh, faces_reference_wrapper_t< MeshType > const &rangeFace, ElementsType type=ElementsType::MESH_POINTS)
template<typename MeshType , typename ExprType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
elements_pid_t< MeshType > elements (MeshType const &mesh, vf::Expr< ExprType > const &expr)
template<typename MeshType >
ext_elements_t< MeshType > elementsWithMarkedFaces (MeshType const &imesh, boost::any const &flag, EntityProcessType entity=EntityProcessType::LOCAL_ONLY)
template<size_t S, class ITERATOR >
ITERATOR end (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR > &range)
template<size_t S, class ITERATOR >
ITERATOR end (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR > const &range)
template<size_t S, class ITERATOR , class CONTAINER >
ITERATOR end (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > &range)
template<size_t S, class ITERATOR , class CONTAINER >
ITERATOR end (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > const &range)
template<class ITERATOR >
ITERATOR end (std::pair< ITERATOR, ITERATOR > &range)
template<int EntityCoDim, typename ElementT >
std::optional< std::map< uint16_type, Marker1 > > entityMarkers (ElementT const &e, uint16_type f)
get the map of markers of a entity of a geoelement
po::options_description eq_options (std::string const &prefix="")
empirical quadrature options
po::options_description error_options (std::string const &prefix="")
template<typename MeshType >
Pdh_element_t< MeshType, 0 > etaQ (std::shared_ptr< MeshType > const &m)
Return default triangle/tetrahedra quality (eta) of a given cell.
template<class T >
void Exchange (T &a, T &b)
template<class Expr >
ADExpr< AdFuncExp< ADExpr< Expr > > > exp (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< AdFuncExp< ADType< T, Nvar, Order, Var > > > exp (const ADType< T, Nvar, Order, Var > &x)
template<typename T >
FEELPP_EXPORT std::vector< T > exp (std::vector< T > const &v)
compute the exp component wise of the vector v
template<typename ElementType , typename CoeffType >
Feel::remove_shared_ptr_type< ElementType > expansion (std::vector< ElementType > const &b, CoeffType const &c, int M=-1)
Given a set of coefficient c and a set of finite element function b, build.
template<typename ElementType , typename CoeffType >
void expansion (std::vector< ElementType > const &b, CoeffType const &c, Vector< typename Feel::remove_shared_ptr_type< ElementType >::value_type > &res, int M=-1)
Given a set of coefficient c and a set of finite element function b, build.
po::options_description exporter_options (std::string const &prefix="")
command line options for exporter
template<typename A00_t , typename A01_t , typename A10_t , typename M2 , typename E1 , typename E2 >
void extractBlock (A00_t const &a00, A01_t const &a01, A10_t const &a10, M2 &ak, E1 const &e1, E2 const &e2)
template<typename A00_t , typename A01_t , typename A10_t , typename M2 , typename E1 , typename E2 >
void extractBlock (A00_t const &a00, A01_t const &a01, A10_t const &a10, M2 &ak, E1 const &e1, E2 const &e2, tensor2symm_false)
template<typename A00_t , typename A01_t , typename A10_t , typename M2 , typename E1 , typename E2 >
void extractBlock (A00_t const &a00, A01_t const &a01, A10_t const &a10, M2 &ak, E1 const &e1, E2 const &e2, tensor2symm_true)
template<typename A02_t , typename A20_t , typename Key1_t , typename Key2_t , typename BK_t , typename CK_t , typename E1 , typename E3 >
void extractBlock (A02_t const &A02K, Key1_t const &key2, A20_t const &A20K, Key2_t const &key3, BK_t &BK, CK_t &CK, int n, E1 const &e1, E3 const &e3, int start=0, std::enable_if_t< is_tensor2symm_field_v< E1 >> *=nullptr)
template<typename A02_t , typename A20_t , typename Key1_t , typename Key2_t , typename BK_t , typename CK_t , typename E1 , typename E3 >
void extractBlock (A02_t const &A02K, Key1_t const &key2, A20_t const &A20K, Key2_t const &key3, BK_t &BK, CK_t &CK, int n, E1 const &e1, E3 const &e3, int start=0, std::enable_if_t<!is_tensor2symm_field_v< E1 >> *=nullptr)
template<typename F0K_t , typename FK_t , typename E1 >
void extractBlock (F0K_t const &F0K, size_type K, FK_t &FK, E1 const &e1, std::enable_if_t< is_tensor2symm_field_v< E1 >> *=nullptr)
template<typename F0K_t , typename FK_t , typename E1 >
void extractBlock (F0K_t const &F0K, size_type K, FK_t &FK, E1 const &e1, std::enable_if_t<!is_tensor2symm_field_v< E1 >> *=nullptr)
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
faces_reference_wrapper_t< support_mesh_t< MeshSupportType > > faces (MeshSupportType const &imesh)
template<typename MeshType >
ext_faces_t< MeshType > faces (MeshType const &imesh, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
faces_pid_t< MeshType > faces (MeshType const &mesh)
std::shared_ptr< CRBPluginAPI > factoryCRBPlugin (std::string const &n, std::string const &pluginlibname="", std::string const &dirname=Info::libdir())
create the plugin name from plugin library pluginlibname located in dirname
po::options_description feel_nooptions ()
po::options_description feel_options (std::string const &prefix="")
FieldSplitType fieldsplitTypeConvertStrToEnum (std::string const &type)
po::options_description file_options (std::string const &prefix)
bool filename_is_dot (fs::path const &p)
bool filename_is_dot_dot (fs::path const &p)
po::options_description fit_options (std::string const &prefix="")
command line for data interpolator
template<typename ExprT1 >
Expr< FlatExpr< ExprT1 > > flat (ExprT1 const &__e1)
precompute expression tensor
template<class Container >
auto floating_equal_range (Container &&container, double target, double epsilon=0.00001) -> decltype(container.equal_range(target))
template<typename Container >
auto floating_key_exists (Container const &container, double target, double epsilon=0.00001) -> decltype(std::make_pair(true, floating_equal_range(container, target, epsilon)))
Feel::po::options_description fluidMechanics_options (std::string const &prefix="fluid")
po::options_description fluidmechanics_options (std::string prefix)
Feel::po::options_description fluidStructInteraction_options (std::string const &prefix)
template<typename FunctionSpaceType , typename periodicity_type = NoPeriodicity>
std::shared_ptr< ReinitializerFMS< FunctionSpaceType, periodicity_type > > fms (std::shared_ptr< FunctionSpaceType > const &Xh, periodicity_type p=NoPeriodicity())
for (int q=1;q< Qa();++q)
template<typename Xs , typename F , std::enable_if_t< boost::hana::Foldable< Xs >::value, int > = 0>
void for_each (Xs &&xs, F &&f)
template<typename X1 , typename RepType >
vf::detail::LinearForm< X1, RepType, RepType > form (std::string name, std::shared_ptr< X1 > const &__X1, std::shared_ptr< RepType > __M, size_type rowstart=0, bool init=false, bool do_threshold=false, typename X1::value_type threshold=type_traits< typename RepType::value_type >::epsilon())
template<typename X1 , typename X2 >
vf::detail::BilinearForm< X1, X2 > form (std::string name, std::shared_ptr< X1 > const &__X1, std::shared_ptr< X2 > const &__X2, std::shared_ptr< MatrixSparse< double > > __M, size_type rowstart=0, size_type colstart=0, bool init=false, bool do_threshold=false, typename X1::value_type threshold=type_traits< double >::epsilon(), size_type pattern=Pattern::COUPLED)
po::options_description functions_options (std::string const &prefix="")
create new functions with a prefix
po::options_description functionspace_options (std::string const &prefix="")
po::options_description generic_options ()
template<typename BareItem >
size_type getId (std::pair< BareItem, size_type > const &i)
template<typename BareItem >
BareItem getItem (std::pair< BareItem, size_type > const &i)
FEELPP_EXPORT int getOneChar ()
Get a unique char (no return cariage requrired). This function is a custom getch.
template<typename T >
T getOption (std::string const &name, std::string const &prefix, std::string const &sub, std::vector< std::string > const &prefixOverwrite, po::variables_map vm=Environment::vm())
template<typename T >
std::pair< bool, T > getOptionIfAvalaibleOLD (std::string const &name, std::string const &prefix, std::string const &sub, std::vector< std::string > const &prefixOverwrite, po::variables_map vm=Environment::vm())
po::options_description ginac_options (std::string const &prefix="")
template<typename C >
auto globalRank (C const &c)
po::options_description gmsh_domain_options (std::string const &prefix="")
po::options_description gmsh_options (std::string const &prefix="")
template<typename Poly >
Polynomial< Poly, Vectorial > gradient (Polynomial< Poly, Scalar > const &p)
compute the gradient of a scalar polynomial p
template<typename Poly >
Polynomial< Poly, Tensor2 > gradient (Polynomial< Poly, Vectorial > const &p)
compute the gradient of a vectorial polynomial p
template<typename Poly >
PolynomialSet< Poly, Vectorial > gradient (PolynomialSet< Poly, Scalar > const &p)
compute the gradient of a scalar polynomial set
template<typename Poly >
PolynomialSet< Poly, Tensor2 > gradient (PolynomialSet< Poly, Vectorial > const &p)
compute the gradient of a vectorial polynomial set
template<typename EltType >
bool hasFaceWithMarker (EltType const &e, boost::any const &flag, std::enable_if_t<(dimension_v< EltType > > 0) &&is_geoelement_v< EltType >> *=nullptr)
template<size_type Contextv>
bool hasValue (size_type c)
bool hasValue (size_type c, size_type v)
template<typename SpaceType >
NullSpace< double > hdgNullSpace (SpaceType const &space, mpl::int_< 2 >)
template<typename SpaceType >
NullSpace< double > hdgNullSpace (SpaceType const &space, mpl::int_< 3 >)
Feel::po::options_description heat_options (std::string const &prefix="heat")
Feel::po::options_description heatFluid_options (std::string const &prefix)
template<typename Poly >
PolynomialSet< Poly, Tensor2 > hessian (PolynomialSet< Poly, Scalar > const &p)
compute the gradient of a vectorial polynomial set
template<typename MeshType , typename = std::enable_if_t<is_mesh_v<MeshType>>>
std::tuple< value_t< MeshType >, value_t< MeshType >, value_t< MeshType > > hMeasures (std::shared_ptr< MeshType > const &m)
compute h measures statistics over all elements of a mesh
template<typename MeshType , typename RangeType , typename = std::enable_if_t<is_mesh_v<MeshType>>>
std::tuple< value_t< MeshType >, value_t< MeshType >, value_t< MeshType > > hMeasures (std::shared_ptr< MeshType > const &m, RangeType r)
template<typename MeshType , typename RangeType , typename = std::enable_if_t<is_mesh_v<MeshType>>>
std::tuple< value_t< MeshType >, value_t< MeshType >, value_t< MeshType > > hMeasures (std::shared_ptr< MeshType > const &m, RangeType r, typename MeshType::size_type nEntityInRange)
compute h measure statistics over a range of elements or facets
template<typename MeshType >
idelements_t< MeshType > idedelements (MeshType const &mesh, flag_type flag)
template<typename MeshType >
idfaces_t< MeshType > idedfaces (MeshType const &mesh, size_type id)
template<typename MeshType , typename IteratorType >
ext_elements_t< MeshType > idelements (MeshType const &imesh, IteratorType begin, IteratorType end)
build a list of elements based on iterators [begin,end) from a mesh imesh
template<typename MeshType , typename T >
ext_elements_t< MeshType > idelements (MeshType const &imesh, std::vector< T > const &l)
build a list of elements based on a list of element ids l from a mesh imesh
template<typename IMT >
IMT && im (IMT &&the_im, std::enable_if_t< std::is_base_of< PointSetBase, IMT >::value > *=nullptr)
template<typename IMT >
IMT const & im (IMT const &the_im, std::enable_if_t< std::is_base_of< PointSetBase, IMT >::value > *=nullptr)
template<typename IMT , typename QT >
IMT im (QT the_q, std::enable_if_t< std::is_base_of< _QBase, QT >::value > *=nullptr)
template<typename MeshT , typename T = double>
im_t< typename MeshT::element_type, T > im (std::shared_ptr< MeshT > mesh, uint16_type O)
build a quadrature formula from a mesh and a polynomial order O to integrate exactly
template<typename ConvexT , typename T = double>
im_t< ConvexT, T > im (uint16_type O)
instantiate a quadrature on convex ConvexT to integrate up to order O
template<typename IMT >
IMT im (uint16_type O, std::enable_if_t< std::is_base_of< PointSetBase, IMT >::value > *=nullptr)
template<typename T >
FEELPP_EXPORT type_traits< T >::real_type inner_product (std::shared_ptr< Vector< T > > const &v1, std::shared_ptr< Vector< T > > const &v2)
Computes the inner product of two vectors and eventually in parallel.
template<typename T >
type_traits< T >::real_type inner_product (Vector< T > const &v1, Vector< T > const &v2)
Computes the inner product of two vectors and eventually in parallel.
template<typename Poly , template< uint16_type > class PsetType>
Poly::value_type integrate (Polynomial< Poly, PsetType > const &p)
integrate a polynomial over a convex
template<typename MeshType >
internaledges_t< MeshType > internaledges (MeshType const &mesh)
template<typename MeshType >
internalelements_t< MeshType > internalelements (MeshType const &mesh)
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
faces_reference_wrapper_t< support_mesh_t< MeshSupportType > > const & internalfaces (MeshSupportType const &imesh)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
internalfaces_t< MeshType > internalfaces (MeshType const &mesh)
template<typename MeshType >
internalpoints_t< MeshType > internalpoints (MeshType const &mesh)
template<typename SpaceType , typename FunctionType , typename InterpType >
void interpolate (std::shared_ptr< SpaceType > const &space, FunctionType const &f, InterpType &interp)
Given a space space using a lagrange basis, compute the interpolation interp of f belonging to another function space.
template<typename SpaceType , typename FunctionType >
bool interpolate_copy (std::shared_ptr< SpaceType > const &space, FunctionType const &f, typename SpaceType::element_type &interp)
template<typename InterpType , typename SizeT >
void interpolate_sync (InterpType &interp, bool hasMeshSupportPartialDomain, std::set< SizeT > const &dofUsedWithPartialMeshSupport)
template<typename MeshType >
ext_edges_t< MeshType > interprocessedges (MeshType const &imesh, rank_type neighbor_pid=invalid_rank_type_value, EntityProcessType entity=EntityProcessType::ALL)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
interprocessfaces_t< MeshType > interprocessfaces (MeshType const &mesh)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
interprocessfaces_t< MeshType > interprocessfaces (MeshType const &mesh, rank_type neighbor_pid)
template<typename IteratorType , typename... Args>
FEELPP_EXPORT Feel::intersect_t< IteratorType > intersect (IteratorType &&it, Args &&... args)
this function takes a set of iterators over geometrical entities of the same type (e.g.
template<typename OpType >
std::shared_ptr< OperatorInverse< OpType > > inv (std::shared_ptr< OpType > M)
template<int Dim, typename Matrix >
void inverse (Matrix const &__restrict__ M, Matrix &__restrict__ Minv, typename Matrix::value_type const &J)
template<int Dim, typename Matrix >
void inverse (Matrix const &M, Matrix &Minv)
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const ioption (_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady
constexpr int64_t ipow (int64_t base, int exp, int64_t result=1)
compute integer power
template<typename Derived >
bool is_finite (const Eigen::MatrixBase< Derived > &x)
template<typename Derived >
bool is_nan (const Eigen::MatrixBase< Derived > &x)
template<typename PS >
constexpr auto is_product_spaces (PS &&ps)
template<typename P >
constexpr bool isHCurlConforming ()
template<typename P >
constexpr bool isHDivConforming ()
template<typename T >
bool isMatrixInverseSymmetric (std::shared_ptr< MatrixSparse< T > > &A, std::shared_ptr< MatrixSparse< T > > &At, bool print=false)
template<uint16_type N, typename T >
ublas::matrix< T > JacobiBatchDerivation (T a, T b, ublas::vector< T > const &__pts)
template<uint16_type N, typename T >
void JacobiBatchDerivation (ublas::matrix< T > &, T, T, ublas::vector< T > const &, mpl::bool_< false >)
template<uint16_type N, typename T >
void JacobiBatchDerivation (ublas::matrix< T > &res, T a, T b, ublas::vector< T > const &__pts, mpl::bool_< true >)
template<uint16_type N, typename T >
ublas::matrix< T > JacobiBatchEvaluation (T a, T b, ublas::vector< T > const &__pts)
po::options_description journal_options (std::string const &prefix="")
Journal observer class options (benchmark system).
SolverType kspTypeConvertStrToEnum (std::string const &type)
template<class Convex , uint16_type Order, template< class, uint16_type, class > class PointSetType, typename value_type >
value_type lebesgueConstant ()
Feel::po::options_description levelset_options (std::string const &prefix)
template<typename ElementType >
auto levelsetDiracElementsGeneric (ElementType const &phi, double eps)
template<typename ElementType >
auto levelsetInterfaceElements (ElementType const &phi)
std::map< double, double > loadXYFromCSV (std::string const &filename, std::string const &abscissa, std::string const &ordinate)
load a XY dataset from a CSV file
template<class Expr >
ADExpr< AdFuncLog< ADExpr< Expr > > > log (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< AdFuncLog< ADType< T, Nvar, Order, Var > > > log (const ADType< T, Nvar, Order, Var > &x)
template<typename T >
FEELPP_EXPORT std::vector< T > log (std::vector< T > const &v)
compute the log (base e) component wise of the vector v
template<class Expr >
ADExpr< AdFuncLog10< ADExpr< Expr > > > log10 (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< AdFuncLog10< ADType< T, Nvar, Order, Var > > > log10 (const ADType< T, Nvar, Order, Var > &x)
template<typename T >
FEELPP_EXPORT std::vector< T > log10 (std::vector< T > const &v)
compute the log (base 10) component wise of the vector v
template<typename MeshType >
decltype(auto) make_elements_wrapper ()
FEELPP_EXPORT AboutData makeAboutDefault (std::string name)
std::pair< BareEdge, bool > makeBareEdge (size_type const i, size_type const j)
It creates a BareEdge end returns the orientation of the created edge with respect to the given data.
std::pair< BareFace, bool > makeBareFace (size_type i, size_type j, size_type k)
It creates Bare Face objects from three Point size_type's.
std::pair< BareFace, bool > makeBareFace (size_type i, size_type j, size_type k, size_type l)
It creates Bare Face objects from four Point size_type's.
std::pair< BareEdge, bool > makeBareItem (size_type i, size_type j)
std::pair< BareFace, bool > makeBareItem (size_type i, size_type j, size_type k)
std::pair< BareFace, bool > makeBareItem (size_type i, size_type j, size_type k, size_type l)
std::pair< BarePoint, bool > makeBarePoint (size_type const i)
template<typename C , typename ... Args>
InterpolationCurl< C > makeCurlInterpolation (C &&c, Args &&... args)
template<typename C , typename ... Args>
InterpolationDiv< C > makeDivInterpolation (C &&c, Args &&... args)
template<typename ExprType , typename C , typename ... Args>
InterpolationExpr< ExprType, C > makeExprInterpolation (ExprType const &expr, C &&c, Args &&... args)
template<typename Convex , typename T >
mpl::if_< Feel::is_simplex< Convex >, mpl::identity< std::shared_ptr< GT_Lagrange< Convex::nDim, 1, Convex::nDim, Simplex, T > > >, mpl::identity< std::shared_ptr< GT_Lagrange< Convex::nDim, 1, Convex::nDim, Hypercube, T > > > >::type::type makeGeometricTransformation ()
template<typename C , typename ... Args>
InterpolationGradient< C > makeGradientInterpolation (C &&c, Args &&... args)
template<typename C , typename ... Args>
InterpolationID< C > makeInterpolation (C &&c, Args &&... args)
template<class T , class... Args>
decltype(auto) makeMesh (Args &&... args)
template<typename Geo , uint16_type Dim = 1, uint16_type Order = 1, uint16_type RDim = Dim, typename T = double>
Reference< Geo, Geo::nDim, 1, Geo::nRealDim, T > makeReferenceConvex ()
template<class T , class... Args>
condensed_matrix_ptr_t< T > makeSharedMatrixCondensed (Args &&... args)
Create a shared pointer MatrixCondensed<T> from Args.
template<class T , class... Args>
std::shared_ptr< Mesh< T > > makeSharedMesh (Args &&... args)
Create a shared pointer Mesh<T> from Args.
template<class T , class... Args>
condensed_vector_ptr_t< T > makeSharedVectorCondensed (Args &&... args)
Create a shared pointer VectorCondensed<T> from Args.
template<class T , class... Args>
std::unique_ptr< Mesh< T > > makeUniqueMesh (Args &&... args)
Create a unique pointer Mesh<T> from Args.
worldscomm_ptr_t makeWorldsComm (int n, WorldComm &wc)
worldscomm_ptr_t makeWorldsComm (int n, worldcomm_ptr_t const &wc)
template<typename MeshType >
ext_elements_t< MeshType > marked2elements (MeshType const &imesh, boost::any const &flag, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked2elements_t< MeshType > marked2elements (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked2elements_t< MeshType > marked2elements (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
ext_faces_t< MeshType > marked2faces (MeshType const &imesh, boost::any flag, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked2faces_t< MeshType > marked2faces (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked2faces_t< MeshType > marked2faces (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked3elements_t< MeshType > marked3elements (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked3elements_t< MeshType > marked3elements (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked3faces_t< MeshType > marked3faces (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
marked3faces_t< MeshType > marked3faces (MeshType const &mesh, std::initializer_list< boost::any > markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
decltype(auto) markededges (MeshType const &mesh)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
decltype(auto) markededges (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
decltype(auto) markededges (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
markededges_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, boost::any const &__marker, typename std::enable_if< is_3d< MeshType >::value >::type *=nullptr)
template<typename MeshType >
markedfaces_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, boost::any const &markersFlag, typename std::enable_if< is_2d< MeshType >::value >::type *=nullptr)
template<typename MeshType >
markedfaces_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, std::initializer_list< boost::any > const &markersFlag, typename std::enable_if< is_2d< MeshType >::value >::type *=nullptr)
template<typename MeshType >
markededges_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, std::initializer_list< boost::any > const &markersFlag, typename std::enable_if< is_3d< MeshType >::value >::type *=nullptr)
template<typename MeshType >
markedfaces_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, typename std::enable_if< is_2d< MeshType >::value >::type *=nullptr)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markededges_t< MeshType > markededgesByType (MeshType const &mesh, uint16_type markerType, typename std::enable_if< is_3d< MeshType >::value >::type *=nullptr)
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
elements_reference_wrapper_t< support_mesh_t< MeshSupportType > > markedelements (MeshSupportType const &imesh, boost::any flag)
template<typename MeshType >
ext_elements_t< MeshType > markedelements (MeshType const &imesh, boost::any const &flag, EntityProcessType entity)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedelements_t< MeshType > markedelements (MeshType const &mesh)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedelements_t< MeshType > markedelements (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedelements_t< MeshType > markedelements (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
markedelements_t< MeshType > markedelementsByType (MeshType const &mesh, uint16_type markerType)
template<typename MeshType >
markedelements_t< MeshType > markedelementsByType (MeshType const &mesh, uint16_type markerType, boost::any const &markersFlag)
template<typename MeshType >
markedelements_t< MeshType > markedelementsByType (MeshType const &mesh, uint16_type markerType, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshSupportType , std::enable_if_t< std::is_base_of_v< MeshSupportBase, unwrap_ptr_t< MeshSupportType >>, int > = 0>
faces_reference_wrapper_t< support_mesh_t< MeshSupportType > > markedfaces (MeshSupportType const &imesh, boost::any flag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedfaces_t< MeshType > markedfaces (MeshType const &mesh)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedfaces_t< MeshType > markedfaces (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0>
markedfaces_t< MeshType > markedfaces (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
markedfaces_t< MeshType > markedfacesByType (MeshType const &mesh, uint16_type markerType)
template<typename MeshType >
markedfaces_t< MeshType > markedfacesByType (MeshType const &mesh, uint16_type markerType, boost::any const &__marker)
template<typename MeshType >
markedfaces_t< MeshType > markedfacesByType (MeshType const &mesh, uint16_type markerType, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
markedpoints_t< MeshType > markedpoints (MeshType const &mesh)
template<typename MeshType >
markedpoints_t< MeshType > markedpoints (MeshType const &mesh, boost::any const &markersFlag)
template<typename MeshType >
markedpoints_t< MeshType > markedpoints (MeshType const &mesh, std::initializer_list< boost::any > const &markersFlag)
template<typename MeshType >
markedpoints_t< MeshType > markedpointsByType (MeshType const &mesh, uint16_type markerType)
template<typename MeshType >
markedpoints_t< MeshType > markedpointsByType (MeshType const &mesh, uint16_type markerType, boost::any const &__marker)
template<typename MeshType >
markedpoints_t< MeshType > markedpointsByType (MeshType const &mesh, uint16_type markerType, std::initializer_list< boost::any > const &markersFlag)
std::vector< MeshMarkerName > markerMap (int Dim)
FEELPP_EXPORT ModelMaterial material (ModelMaterials::value_type const &m)
po::options_description material_options (std::string const &prefix="")
MatSolverPackageType matSolverPackageConvertStrToEnum (std::string const &type)
template<class T >
T Max (const T &a, const T &b)
template<class T >
T Max (const T &a, const T &b, const T &c)
Feel::po::options_description maxwell_options (std::string const &prefix)
template<typename MeshType >
auto measurePointElements (std::shared_ptr< FunctionSpace< MeshType, bases< Lagrange< MeshType::nOrder, Scalar > > > > &Xh) -> decltype(Xh->element())
Given a function space Xh, compute the sum of of the measure of the elements shared by a point in the mesh.
template<typename Shape , typename T , int Tag1, int Tag2 = Tag1, int TheTag = Tag1>
std::shared_ptr< Mesh< Shape, T, TheTag > > merge (std::shared_ptr< Mesh< Shape, T, Tag1 >> m1, std::shared_ptr< Mesh< Shape, T, Tag2 >> m2)
FEELPP_EXPORT void mergePtree (pt::ptree &pa, const pt::ptree &pb)
po::options_description mesh_options (int Dim, std::string const &prefix="")
po::options_description mesh_options (std::string const &prefix="")
template<typename MeshType , typename DisplType >
std::shared_ptr< MeshType > meshMove (std::shared_ptr< MeshType > &m, DisplType const &u)
template<typename C >
FEELPP_DEPRECATED auto meshrank (C const &c)
template<typename T , typename IndexT >
Geo0D< 1, T, IndexT > middle (Geo0D< 1, T, IndexT > const &p1, Geo0D< 1, T, IndexT > const &p2)
template<typename T , typename IndexT >
Geo0D< 2, T, IndexT > middle (Geo0D< 2, T, IndexT > const &p1, Geo0D< 2, T, IndexT > const &p2)
template<typename T , typename IndexT >
Geo0D< 3, T, IndexT > middle (Geo0D< 3, T, IndexT > const &p1, Geo0D< 3, T, IndexT > const &p2)
template<class T >
T Min (const T &a, const T &b)
template<class T >
T Min (const T &a, const T &b, const T &c)
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType >
std::shared_ptr< FunctionSpace< MeshType, bases< Lagrange< Order, Scalar, Continuous, Pts > >, Periodicity< NoPeriodicity >, mortars< Mortar > > > Moch (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
build a function space of continuous function which are piecewise polynomial of degree (total or in each variable) less than k.
Feel::po::options_description modelalgebraic_options (std::string const &prefix)
Feel::po::options_description modelbase_options (std::string const &prefix)
Feel::po::options_description modelnumerical_options (std::string const &prefix)
FEELPP_EXPORT std::string name (ModelMaterials::value_type const &m)
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
NChv_ptrtype< MeshType, Order, Pts, Tag > NChv (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
Given a mesh, build a function space of vectorial continuous function which are piecewise polynomial of degree (total or in each variable) less than k using Lagrange basis functions.
template<int Order, typename MeshType >
meta::Ned1h< MeshType, Order >::ptrtype Ned1h (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
template<typename MT , typename Iterator >
size_type nelements (boost::tuple< MT, Iterator, Iterator > const &its, bool global=false, worldcomm_t const &worldComm=Environment::worldComm())
template<typename MT , typename Iterator , typename Container >
size_type nelements (boost::tuple< MT, Iterator, Iterator, Container > const &its, bool global=false, worldcomm_t const &worldComm=Environment::worldComm())
template<typename MT , typename Iterator , typename Container >
size_type nelements (boost::tuple< MT, Iterator, Iterator, Container > const &its, Zone const &z, worldcomm_t const &worldComm=Environment::worldComm())
template<typename MT , typename Iterator >
size_type nelements (std::list< boost::tuple< MT, Iterator, Iterator > > const &its, bool global=false, worldcomm_t const &worldComm=Environment::worldComm())
template<typename MT , typename Iterator , typename Container >
size_type nelements (std::list< boost::tuple< MT, Iterator, Iterator, Container > > const &its, bool global=false, worldcomm_t const &worldComm=Environment::worldComm())
template<typename MT , typename Iterator , typename Container >
size_type nelements (std::list< boost::tuple< MT, Iterator, Iterator, Container >> const &its, Zone const &z, worldcomm_t const &worldComm=Environment::worldComm())
template<typename Arg1 , typename ... Args>
BlocksBaseVector< typename decay_type< Arg1 >::value_type > newVectorBlocks (const Arg1 &arg1, const Args &... args)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
po::options_description nlsolver_options ()
command line options for non linear solver
template<typename MeshType >
Pdh_element_t< MeshType, 0 > nsrQ (std::shared_ptr< MeshType > const &m)
Return the normalized shape ratio (NSR) for a given element.
template<typename SpaceType , typename ExprType >
void nullspace (NullSpace< double, typename SpaceType::size_type > &K, std::shared_ptr< SpaceType > Xh, ExprType &&e)
template<typename SpaceType , typename ExprType , typename... Args>
void nullspace (NullSpace< double, typename SpaceType::size_type > &K, std::shared_ptr< SpaceType > Xh, ExprType &&e, Args... args)
template<typename SpaceType , typename ExprType , typename... Args>
NullSpace< double, typename SpaceType::size_type > nullspace (std::shared_ptr< SpaceType > Xh, ExprType &&e, Args... args)
template<typename SpaceType , typename ExprType , typename... Args>
std::shared_ptr< NullSpace< double, typename SpaceType::size_type > > nullspace_ptr (std::shared_ptr< SpaceType > Xh, ExprType &&e, Args... args)
template<int Order, typename MeshType , int Tag = 0>
Odh_ptrtype< MeshType, Order, Tag > Odh (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
Given a mesh, build a function space of discontinuous function which are piecewise polynomial of degree and \(L_2\) Orthonormal.
po::options_description on_options (std::string const &prefix="")
command line options for BDF
po::options_description onelab_options (std::string const &prefix="")
command line options for Onelab interface
template<typename MatrixType >
std::shared_ptr< OperatorMatrix< typename MatrixType::value_type > > op (std::shared_ptr< MatrixType > M, std::string label, bool transpose=false)
bool operator!= (const BareEdge &p1, const BareEdge &p2)
bool operator!= (const BareFace &p1, const BareFace &p2)
bool operator!= (const TypeInfo &lhs, const TypeInfo &rhs)
template<typename X , bool SM>
bool operator!= (ProductSpace< X, SM > const &x, ProductSpace< X, SM > const &y)
template<typename T , typename... SList1, typename... SList2>
bool operator!= (ProductSpaces2< T, SList1... > const &x, ProductSpaces2< T, SList2... > const &y)
template<typename... SList1, typename... SList2>
bool operator!= (ProductSpaces< SList1... > const &x, ProductSpaces< SList2... > const &y)
template<class T >
ADExpr< ADUnaryPlus< ADExpr< T > > > operator+ (const ADExpr< T > &expr)
template<typename fs_type >
void operator++ (std::shared_ptr< Aitken< fs_type > > &aitk)
template<class T >
ADExpr< ADUnaryMinus< ADExpr< T > > > operator- (const ADExpr< T > &expr)
template<typename Poly , template< uint16_type > class PolySetType>
Polynomial< Poly, PolySetType > operator- (Polynomial< Poly, PolySetType > const &p1, Polynomial< Poly, PolySetType > const &p2)
bool operator< (const BareEdge &e1, const BareEdge &e2)
bool operator< (const TypeInfo &lhs, const TypeInfo &rhs)
template<class T , class U >
bool operator< (std::weak_ptr< T > const &a, std::weak_ptr< U > const &b)
template<typename T , int N1 = Eigen::Dynamic, int N2 = Eigen::Dynamic>
DebugStream & operator<< (DebugStream &__os, Eigen::Matrix< T, N1, N2 > const &__n)
template<uint16_type Dim, typename T , typename IndexT >
FEELPP_DEPRECATED DebugStream & operator<< (DebugStream &__os, Geo0D< Dim, T, IndexT > const &__n)
template<uint16_type Dim, typename GEOSHAPE , typename T , typename IndexT , typename POINTTYPE , bool UseMeasuresStorage>
FEELPP_DEPRECATED DebugStream & operator<< (DebugStream &__os, GeoND< Dim, GEOSHAPE, T, IndexT, POINTTYPE, UseMeasuresStorage > const &__n)
FEELPP_DEPRECATED DebugStream & operator<< (DebugStream &__os, node< real64_type >::type const &__n)
template<typename T , typename Orient >
FEELPP_DEPRECATED DebugStream & operator<< (DebugStream &__os, ublas::matrix< T, Orient > const &__n)
template<typename T >
FEELPP_DEPRECATED DebugStream & operator<< (DebugStream &__os, ublas::vector< T > const &__n)
template<typename T , int N1 = Eigen::Dynamic, int N2 = Eigen::Dynamic>
NdebugStream & operator<< (NdebugStream &__os, Eigen::Matrix< T, N1, N2 > const &)
template<uint16_type Dim, typename T , typename IndexT >
FEELPP_DEPRECATED NdebugStream & operator<< (NdebugStream &__os, Geo0D< Dim, T, IndexT > const &__n)
template<uint16_type Dim, typename GEOSHAPE , typename T , typename IndexT , typename POINTTYPE , bool UseMeasuresStorage>
NdebugStream &FEELPP_DEPRECATED operator<< (NdebugStream &__os, GeoND< Dim, GEOSHAPE, T, IndexT, POINTTYPE, UseMeasuresStorage > const &__n)
template<typename T , typename Orient >
FEELPP_DEPRECATED NdebugStream & operator<< (NdebugStream &__os, ublas::matrix< T, Orient > const &)
template<typename T >
FEELPP_DEPRECATED NdebugStream & operator<< (NdebugStream &__os, ublas::vector< T > const &)
FEELPP_DEPRECATED NdebugStream & operator<< (NdebugStream &os, node< real64_type >::type const &)
template<typename SizeT = uint32_type>
std::ostream & operator<< (std::ostream &__os, Dof< SizeT > const &__dof)
template<uint16_type Dim, typename T , typename IndexT >
std::ostream & operator<< (std::ostream &__os, Geo0D< Dim, T, IndexT > const &__n)
template<uint16_type Dim, typename GEOSHAPE , typename T , typename IndexT , typename POINTTYPE , bool UseMeasuresStorage>
std::ostream & operator<< (std::ostream &__os, GeoND< Dim, GEOSHAPE, T, IndexT, POINTTYPE, UseMeasuresStorage > const &__n)
template<int NC, typename SizeT = uint32_type>
std::ostream & operator<< (std::ostream &__os, LocalDof< NC, SizeT > const &__dof)
FEELPP_EXPORT std::ostream & operator<< (std::ostream &os, AboutData const &about)
outpout stream an AboutData structure
template<typename T >
std::ostream & operator<< (std::ostream &os, const MatrixSparse< T > &m)
template<typename T , int M, int N>
std::ostream & operator<< (std::ostream &os, Feel::detail::ID< T, M, N > const &id)
template<typename A0 , typename A1 , typename A2 , typename A3 , typename A4 >
std::ostream & operator<< (std::ostream &os, FunctionSpace< A0, A1, A2, A3, A4 > const &Xh)
iostream operator to print some information about the function space Xh
std::ostream & operator<< (std::ostream &os, interpolation_operand_type const &o)
std::ostream & operator<< (std::ostream &os, ModelMaterial const &m)
std::ostream & operator<< (std::ostream &os, ModelOutput const &o)
template<typename Geo , uint16_type Dim, uint16_type Order, uint16_type RDim, typename T >
std::ostream & operator<< (std::ostream &os, Reference< Geo, Dim, Order, RDim, T > const &ref)
bool operator<= (const BareEdge &e1, const BareEdge &e2)
bool operator<= (const TypeInfo &lhs, const TypeInfo &rhs)
bool operator== (const BareEdge &p1, const BareEdge &p2)
bool operator== (const BareFace &p1, const BareFace &p2)
bool operator== (const TypeInfo &lhs, const TypeInfo &rhs)
template<typename X , bool SM>
bool operator== (ProductSpace< X, SM > const &x, ProductSpace< X, SM > const &y)
template<typename T , typename... SList1, typename... SList2>
bool operator== (ProductSpaces2< T, SList1... > const &x, ProductSpaces2< T, SList2... > const &y)
template<typename... SList1, typename... SList2>
bool operator== (ProductSpaces< SList1... > const &x, ProductSpaces< SList2... > const &y)
bool operator> (const BareEdge &e1, const BareEdge &e2)
bool operator> (const TypeInfo &lhs, const TypeInfo &rhs)
bool operator>= (const BareEdge &e1, const BareEdge &e2)
bool operator>= (const TypeInfo &lhs, const TypeInfo &rhs)
template<typename space_type >
std::shared_ptr< OperatorSteklovPc< space_type > > operatorSteklPc (std::shared_ptr< space_type > const &space, typename OperatorSteklovPc< space_type >::backend_ptrtype const &backend=Backend< double >::build(BACKEND_PETSC))
this function returns a OperatorSteklovPc shared_ptr with
template<typename self_type >
std::shared_ptr< OperatorTrace< self_type > > operatorTrace (std::shared_ptr< self_type > const &domainspace)
this function returns a OperatorTrace shared_ptr with
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange , typename InterpType >
decltype(auto) opInterp (std::shared_ptr< DomainSpaceType > const &domainspace, std::shared_ptr< ImageSpaceType > const &imagespace, IteratorRange const &r, typename OperatorInterpolation< DomainSpaceType, ImageSpaceType, typename Feel::detail::opinterprangetype< IteratorRange >::type, InterpType >::backend_ptrtype const &backend, InterpType const &interptype, bool ddmethod)
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange , typename InterpType >
decltype(auto) opInterpPtr (std::shared_ptr< DomainSpaceType > const &domainspace, std::shared_ptr< ImageSpaceType > const &imagespace, IteratorRange const &r, typename OperatorInterpolation< DomainSpaceType, ImageSpaceType, typename Feel::detail::opinterprangetype< IteratorRange >::type, InterpType >::backend_ptrtype const &backend, InterpType const &interptype, bool ddmethod)
template<typename space_type >
std::shared_ptr< OperatorLagrangeP1< space_type > > opLagrangeP1_impl (std::shared_ptr< space_type > const &Xh, typename OperatorLagrangeP1< space_type >::backend_ptrtype const &backend, std::string pathMeshLagP1, std::string prefix, bool rebuild, bool parallel, size_type meshUpdate)
po::options_description opusapp_options (std::string const &prefix)
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const order (BOOST_PP_REPEAT_FROM_TO_M_1,(1, BOOST_PP_IIF_0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))(BOOST_PP_SEQ_FOLD_LEFT_I_2, BOOST_PP_SEQ_FOLD_LEFT_F)(BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))), BOOST_PARAMETER_FUNCTION_FWD_FUNCTION,((std::shared_ptr< Bdf< typename meta::remove_all< typename parameter::binding< Args, tag::space >::type >::type::element_type > >), bdf, 0, BOOST_PP_IIF_0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))(nil)(BOOST_PP_SEQ_FOR_EACH_I_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_I_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FUNCTION_FWD_COMBINATION, ~, BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))), 1 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))))) BOOST_PP_REPEAT_1_BOOST_PP_INC_BOOST_PP_VARIADIC_ELEM_2(BOOST_PP_REPEAT_FROM_TO_M_1
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const order (BOOST_PP_SEQ_FOLD_LEFT_I_2, BOOST_PP_SEQ_FOLD_LEFT_F)(BOOST_PARAMETER_ARITY_RANGE_M
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const order (BOOST_PP_SUB_O, BOOST_PP_NIL BOOST_PP_TUPLE_EAT_2)(2
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const order (BOOST_PP_WHILE_2,(1 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order))), BOOST_PP_IIF_0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order)))(BOOST_PP_SEQ_FOLD_LEFT_I_2, BOOST_PP_SEQ_FOLD_LEFT_F)(BOOST_PARAMETER_ARITY_RANGE_M, BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III, BOOST_PP_SEQ_TAIL_I BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order))), 0 BOOST_PP_IIF_1(BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EXEC, BOOST_PP_SEQ_FOR_EACH_DETAIL_CHECK_EMPTY)(BOOST_PARAMETER_FLATTEN_SPEC,(3, 2, 3),(required(space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm,(po::variables_map const &), Environment::vm())(prefix, *,"")(name, *,"bdf")(order, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.order", _vm=vm))(initial_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-initial", _vm=vm))(final_time, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-final", _vm=vm))(time_step, *(boost::is_floating_point< mpl::_ >), doption(_prefix=prefix, _name="bdf.time-step", _vm=vm))(strategy, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.strategy", _vm=vm))(steady, *(bool), boption(_prefix=prefix, _name="bdf.steady", _vm=vm))(reverse, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.reverse", _vm=vm))(restart, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart", _vm=vm))(restart_path, *, soption(_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.restart.at-last-save", _vm=vm))(save, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.save", _vm=vm))(freq, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="bdf.save.freq", _vm=vm))(format, *, soption(_prefix=prefix, _name="bdf.file-format", _vm=vm))(rank_proc_in_files_name, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="bdf.rank-proc-in-files-name", _vm=vm))(n_consecutive_save, *(boost::is_integral< mpl::_ >), order))))) BOOST_PP_TUPLE_EAT_3)(BOOST_PP_SUB_P
po::options_description oseen_options (std::string const &prefix="", OseenDefaults defaults=OseenDefaults())
po::options_description parallel_options (std::string const &prefix="")
command line options for multithreading and GPU parallelization
po::options_description parameters_options (std::string const &prefix="")
create new parameters with a prefix
template<typename MeshType >
void partition (std::string const &partitioner, std::shared_ptr< MeshType > mesh, int n_parts)
template<typename MeshType >
std::unique_ptr< MeshPartitionSet< MeshType > > partitionMesh (std::shared_ptr< MeshType > mesh, rank_type nGlobalParts, std::vector< elements_reference_wrapper_t< MeshType >> partitionByRange=std::vector< elements_reference_wrapper_t< MeshType >>())
partition a mesh and provide a helper data struct navigate in the newly partitioned mesh
po::options_description pcd_options (std::string const &prefix="")
command line options for specific preconditionner
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pch_ptrtype< MeshType, Order, T, Pts, Tag > Pch (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pch_ptrtype< MeshType, Order, T, Pts, Tag > Pch (std::shared_ptr< MeshType > mesh, elements_reference_wrapper_t< MeshType > const &rangeElt, bool buildExtendedDofTable=false, size_type components=0)
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pchm_ptrtype< MeshType, Order, T, Pts, Tag > Pchm (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pchms_ptrtype< MeshType, Order, T, Pts, Tag > Pchms (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
build a function space of continuous symmetric matrix fields which are piecewise polynomial of degree (total or in each variable) less than k.
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pchv_ptrtype< MeshType, Order, Pts, Tag > Pchv (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
Given a mesh, build a function space of vectorial continuous function which are piecewise polynomial of degree (total or in each variable) less than k using Lagrange basis functions.
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pchv_ptrtype< MeshType, Order, Pts, Tag > Pchv (std::shared_ptr< MeshType > mesh, elements_reference_wrapper_t< MeshType > const &rangeElt, bool buildExtendedDofTable=false)
Given a mesh, build a function space of vectorial continuous function which are piecewise polynomial of degree (total or in each variable) less than k using Lagrange basis functions.
PreconditionerType pcTypeConvertStrToEnum (std::string const &type)
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType >
Pdh_ptrtype< MeshType, Order, Pts > Pdh (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
Given a mesh, build a function space of discontinuous function which are piecewise polynomial of degree (total or in each variable) less than k.
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType >
Pdh_ptrtype< MeshType, Order, Pts > Pdh (std::shared_ptr< MeshType > mesh, elements_reference_wrapper_t< MeshType > const &rangeElt, bool buildExtendedDofTable=false)
Given a mesh, build a function space of discontinuous function which are piecewise polynomial of degree (total or in each variable) less than k.
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pdhm_ptrtype< MeshType, Order, T, Pts, Tag > Pdhm (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
template<int Order, typename T = double, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pdhms_ptrtype< MeshType, Order, T, Pts, Tag > Pdhms (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
build a function space of discontinuous symmetric matrix fields which are piecewise polynomial of degree (total or in each variable) less than k.
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pdhv_ptrtype< MeshType, Order, Pts, Tag > Pdhv (std::shared_ptr< MeshType > mesh, bool buildExtendedDofTable=false)
Given a mesh, build a function space of vectorial discontinuous function which are piecewise polynomial of degree (total or in each variable) less than k using Lagrange basis functions.
template<int Order, template< class, uint16_type, class > class Pts = PointSetEquiSpaced, typename MeshType , int Tag = 0>
Pdhv_ptrtype< MeshType, Order, Pts, Tag > Pdhv (std::shared_ptr< MeshType > mesh, elements_reference_wrapper_t< MeshType > const &rangeElt, bool buildExtendedDofTable=false)
Given a mesh, build a function space of vectorial discontinuous function which are piecewise polynomial of degree (total or in each variable) less than k using Lagrange basis functions.
template<typename A0 >
Periodicity< A0 > periodicity (A0 const &a0)
template<typename A0 , typename A1 >
Periodicity< A0, A1 > periodicity (A0 const &a0, A1 const &a1)
template<typename A0 , typename A1 , typename A2 >
Periodicity< A0, A1, A2 > periodicity (A0 const &a0, A1 const &a1, A2 const &a2)
po::options_description pfemapp_options (std::string const &prefix)
po::options_description podOptions (std::string const &prefix="")
template<typename MeshType >
points_pid_t< MeshType > points (MeshType const &mesh)
template<typename T >
FEELPP_EXPORT std::vector< T > polyfit (const std::vector< T > &xv, const std::vector< T > &yv, int order=1)
compute least square (or interpolation) fitting polynomial
std::string prefixvm (std::string const &prefix, std::string const &opt, std::string const &sep=".")
template<typename MeshT >
void print (MeshT *m)
template<typename ElementType >
ElementType prod (ElementType const &v1, ElementType const &v2, typename boost::enable_if< boost::is_base_of< FunctionSpaceBase::ElementBase, ElementType > >::type *dummy=0)
Computes the element wise product of two vectors and eventually in parallel.
template<typename... SpaceList>
ProductSpaces< SpaceList... > product (SpaceList... spaces)
compile time product of function spaces
template<typename T , typename... SpaceList>
ProductSpaces2< T, SpaceList... > product2 (SpaceList... spaces, std::shared_ptr< ProductSpace< T, true >> const &ps)
mixed compile time and runtime product of function space
template<typename T , typename... SpaceList>
ProductSpaces2< T, SpaceList... > product2 (std::shared_ptr< ProductSpace< T, true >> const &ps, SpaceList... spaces)
mixed compile time and runtime product of function space
template<typename... SpaceList>
std::unique_ptr< ProductSpaces< SpaceList... > > productPtr (SpaceList... spaces)
template<typename Pset , typename Func , typename IM >
Polynomial< Pset, Scalar > project (Pset const &pset, Func const &f, IM const &im)
\(L_2\) Projection over the associated convex of a function f onto a scalar polynomial set.
template<typename TDomainSpace , typename TDualImageSpace >
std::shared_ptr< Projector< TDomainSpace, TDualImageSpace > > projector (std::shared_ptr< TDomainSpace > const &domainspace, std::shared_ptr< TDualImageSpace > const &imagespace, typename Projector< TDomainSpace, TDualImageSpace >::backend_ptrtype const &abackend=Backend< double >::build(soption(_name="backend")), ProjectorType proj_type=L2, double epsilon=0.01, double gamma=20, DirichletType dirichlet_type=WEAK)
this function returns a Projector shared_ptr with
po::options_description ptree_options (std::string const &prefix="")
ptree options
std::map< std::string, std::string > pyexpr (std::string const &pycode, std::vector< std::string > const &vars, std::map< std::string, std::string > const &locals)
evaluate python code pycode and retrieve dictionary of Feel++ expressions expressions are of the form : f(x,y,z):x:y:z
void pyexprFromFile (std::string const &pyfilename, std::map< std::string, std::map< std::string, std::string >> &locals)
void pyexprFromFile (std::string const &pyfilename, std::map< std::string, std::string > &locals)
evaluate python code from file pyfilename using local variables locals and retrieve dictionary of Feel++ expressions expressions are of the form : f(x,y,z):x:y:z
template<typename MeshTestType , typename IteratorRange , typename Im , typename Expr >
std::shared_ptr< QuadPtLocalization< typename Feel::detail::quadptlocrangetype< IteratorRange >::type, Im, Expr > > quadPtLocPtr (std::shared_ptr< MeshTestType > meshTest, IteratorRange const &elts, Im const &im, Expr const &expr)
template<typename MeshTestType , typename MeshTrialType , typename IteratorRange , typename Im , typename Expr >
std::shared_ptr< QuadPtLocalization< typename Feel::detail::quadptlocrangetype< IteratorRange >::type, Im, Expr > > quadPtLocPtr (std::shared_ptr< MeshTestType > meshTest, std::shared_ptr< MeshTrialType > meshTrial, IteratorRange const &elts, Im const &im, Expr const &expr)
template<typename T >
FEELPP_EXPORT std::vector< T > randint (int N, T min, T max)
template<typename T >
std::vector< T > range (T &&beg, T &&end)
template<typename T >
std::vector< T > range (T &&beg, T &&end, T &&step)
template<typename T >
std::vector< T > range (T &&end)
template<typename C >
auto rank (C const &c)
template<typename SpaceType >
std::shared_ptr< ReducedBasisSpace< SpaceType > > RbSpacePch (std::shared_ptr< SpaceType > const &Xh)
template<int Order, typename SpaceType >
std::shared_ptr< ReducedBasisSpace< SpaceType > > RbSpacePchv (std::shared_ptr< SpaceType > const &Xh)
FEELPP_EXPORT std::string readFromFile (std::string const &filename)
helper function that read a file filename and store its contents into a std::string
template<typename T >
holo3_image< T > readHBF (std::string const &s)
read an HBF file containing an array of floats
std::tuple< int32_t, int32_t, std::string > readHBFHeaderAndSizes (std::ifstream &in)
Given a std::ifstream, read the header and return the sizes of the HBF and the type of data.
std::tuple< int32_t, int32_t, std::string > readHBFHeaderAndSizes (std::string const &s)
Given a std::string path to a file, read the header and return the sizes of the HBF and the type of data.
template<typename T >
constexpr int real_dimension (T const &t)
template<typename MeshType , typename = std::enable_if_t<is_mesh_v<MeshType>>>
constexpr int realdim (std::shared_ptr< MeshType > const &m)
Feel::po::options_description redistanciation_fm_options (std::string const &prefix, bool addProjectorsOpts=true)
Feel::po::options_description redistanciation_hj_options (std::string const &prefix)
template<typename SpaceType , typename Expr >
SpaceType::element_type region (std::shared_ptr< SpaceType > const &space, Expr const &expr)
template<typename SpaceType >
SpaceType::element_type regionMarker (std::shared_ptr< SpaceType > const &space)
template<typename SpaceType >
SpaceType::element_type regionMarker2 (std::shared_ptr< SpaceType > const &space)
template<typename SpaceType >
SpaceType::element_type regionMarker3 (std::shared_ptr< SpaceType > const &space)
template<typename SpaceType >
SpaceType::element_type regionProcess (std::shared_ptr< SpaceType > const &space)
template<typename SpaceType , typename Expr >
SpaceType::element_type regionv (std::shared_ptr< SpaceType > const &space, Expr const &expr)
template<typename MeshType >
std::map< std::string, std::unique_ptr< Partitioner< MeshType > > > registerPartitioner ()
template<typename MeshType >
Remesh< MeshType > remesher (std::shared_ptr< MeshType > const &m, boost::any required_element_markers=std::vector< int >{}, boost::any required_facet_markers=std::vector< int >{})
template<typename T >
decltype(auto) remove_shared_ptr_f (T &&e)
FEELPP_EXPORT std::string removeComments (std::string str_with_comments)
remove c and c++ comments from string str_with_comments if any
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 required (matrixA,(d_sparse_matrix_ptrtype))(matrixB
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 required (pc,(PreconditionerType))(backend
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 required (space, *(boost::is_convertible< mpl::_, std::shared_ptr< Feel::FunctionSpaceBase > >)))(optional(vm
std::string sanitize (std::string const &s)
trim string to remove special characters
std::vector< std::string > sanitize (std::vector< std::string > const &s)
trim a vector of strings removing all leading and trailing spaces and replace all special characters " ;:," inside the block by a _
po::options_description sc_options (std::string const &prefix="")
template<typename OpType >
std::shared_ptr< OperatorScale< OpType > > scale (std::shared_ptr< OpType > M, typename OpType::value_type s)
A scale (this->thetaq(0))
template<class Archive , class SpaceType , typename RbType >
void serializeByBlock (Archive &ar, std::vector< int > const &n, SpaceType const &Rh, RbType &rb, typename std::enable_if< SpaceType::element_type::is_composite >::type *=nullptr)
template<class Archive , class SpaceType , typename RbType >
void serializeByBlock (Archive &ar, std::vector< int > const &n, SpaceType const &Rh, RbType &rb, typename std::enable_if<!SpaceType::element_type::is_composite >::type *=nullptr)
BareEdge setBareEdge (size_type const i, size_type const j)
It creates a BareEdge, ignoring orientation.
BareEdge setBareEdgeNo (size_type const i, size_type const j)
It creates a non-standard BareEdge.
template<class BoostParameterDummy >
eigen setEigenProblemType ((EigenProblemType) EigenMap[problem])
eigen setInterval (interval_a, interval_b)
eigen setMapCol (formA.matrixPtr() ->mapColPtr())
eigen setMapRow (formA.matrixPtr() ->mapRowPtr())
eigen setMaximumProjectedDimension ((mpd >0)?mpd:invalid_v< size_type >)
eigen setMaxIterations (maxit)
eigen setNumberOfEigenValues (nev)
eigen setNumberOfEigenValuesConverged (ncv)
eigen setPositionOfSpectrum ((PositionOfSpectrum) EigenMap[spectrum])
eigen setSpectralTransform ((SpectralTransformType) EigenMap[transform])
eigen setTolerance (tolerance)
template<class Expr >
ADExpr< ADFuncSin< ADExpr< Expr > > > sin (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< ADFuncSin< ADType< T, Nvar, Order, Var > > > sin (const ADType< T, Nvar, Order, Var > &x)
SolverNonLinearLineSearchType snesLineSearchTypeConvertStrToEnum (std::string const &type)
std::string snesTypeConvertEnumToStr (SolverNonLinearType type)
SolverNonLinearType snesTypeConvertStrToEnum (std::string const &type)
Feel::po::options_description solidMechanics_options (std::string const &prefix="struct")
po::options_description solidmechanics_options (std::string prefix)
po::options_description solvereigen_options (std::string const &prefix="")
defines solver eigen options
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const soption (_prefix=prefix, _name="bdf.restart.path", _vm=vm))(restart_at_last_save
template<typename MatrixType >
void spy (MatrixType const &__m, std::string const &filename)
Dump vector to file in Matlab format and spy.
template<class Expr >
ADExpr< ADFuncSqrt< ADExpr< Expr > > > sqrt (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< ADFuncSqrt< ADType< T, Nvar, Order, Var > > > sqrt (const ADType< T, Nvar, Order, Var > &x)
po::options_description stabilization_options (std::string const &prefix="")
void stencilManagerAdd (StencilManagerImpl::key_type const &key, StencilManagerImpl::graph_ptrtype graph)
function that add an entry in the StencilManager
void stencilManagerGarbage (StencilManagerImpl::key_type const &key)
function that cleans up one entry the StencilManager
void stencilManagerGarbageCollect ()
function that cleans up the StencilManager any time stencil() is called
void stencilManagerPrint ()
print entries stored in stencil manager
template<int I, int J, typename IteratorRange >
fusion::pair< fusion::pair< mpl::int_< I >, mpl::int_< J > >, typename stencilrangetype< IteratorRange >::list_type > stencilRange (IteratorRange const &r)
stencilRangeMap0Type stencilRangeMap ()
template<typename ThePair1Type >
stencilRangeMap1Type< ThePair1Type > stencilRangeMap (ThePair1Type const &p)
template<typename ThePair1Type , typename ThePair2Type >
stencilRangeMap2Type< ThePair1Type, ThePair2Type > stencilRangeMap (ThePair1Type const &p1, ThePair2Type const &p2)
template<typename MeshType >
std::shared_ptr< MeshType > straightenMesh (std::shared_ptr< MeshType > mesh, worldcomm_ptr_t const &worldcomm, bool refine, bool save)
straighten the internal faces of a high order mesh
template<typename EltType >
fusion::result_of::accumulate< typename EltType::functionspace_type::functionspace_vector_type, fusion::vector<>, Feel::detail::CreateElementVector< EltType > >::type subelements (EltType const &e, std::vector< std::string > const &n)
extract subelements from an element of a product of spaces
template<typename SpaceT , typename = std::enable_if_t<is_functionspace_v<SpaceT>>>
constexpr SpaceT::template GetMeshSupport< typename SpaceT::mesh_ptrtype, 0 >::ptrtype support (std::shared_ptr< SpaceT > const &X)
template<int Dim>
std::vector< symbol > symbols ()
std::vector< symbol > symbols (std::initializer_list< std::string > l)
std::vector< symbol > symbols (std::vector< std::string > const &symbNames, std::vector< GiNaC::symbol > const &symbExisting)
std::vector< symbol > symbols (std::vector< std::string > l)
template<>
std::vector< symbol > symbols< 1 > ()
template<>
std::vector< symbol > symbols< 2 > ()
template<>
std::vector< symbol > symbols< 3 > ()
template<typename T , typename SizeT >
FEELPP_EXPORT void sync (Vector< T, SizeT > &v, Feel::detail::syncOperator< T, SizeT > const &opSync)
template<typename T , typename SizeT >
FEELPP_EXPORT void sync (Vector< T, SizeT > &v, std::string const &opSyncStr, std::set< SizeT > const &dofGlobalProcessPresent)
template<typename T , typename SizeT >
FEELPP_EXPORT void sync (Vector< T, SizeT > &v, std::string const &opSyncStr="=")
template<typename ElementType , typename RangeType , typename FunctionType >
void syncDofs (ElementType &phi, RangeType const &range, FunctionType const &func)
template<typename VectorType , typename DofTableType , typename RangeType , typename FunctionType >
void syncDofs (VectorType &phi, DofTableType const &dofTable, RangeType const &range, FunctionType const &func)
template<class Expr >
ADExpr< ADFuncTan< ADExpr< Expr > > > tan (const ADExpr< Expr > &expr)
template<class T , int Nvar, int Order, int Var>
ADExpr< ADFuncTan< ADType< T, Nvar, Order, Var > > > tan (const ADType< T, Nvar, Order, Var > &x)
template<typename SpaceType >
Test< SpaceType > test (std::shared_ptr< SpaceType > const &X)
Feel::po::options_description thermoElectric_options (std::string const &prefix)
static const std::string timerDefaultInstanceName ()
template<typename SizeT >
std::shared_ptr< NullSpace< double, SizeT > > toBackend (std::shared_ptr< Backend< double, SizeT >> const &b, std::shared_ptr< NullSpace< double, SizeT >> const &Kspace, bool redoOrtho=false)
Feel::po::options_description toolboxes_options (std::string const &type)
Feel::po::options_description toolboxes_options (std::string const &type, std::string const &prefix)
template<typename T , typename SizeT = uint32_type>
std::shared_ptr< BackendPetsc< T, SizeT > > toPETSc (std::shared_ptr< Backend< T, SizeT >> const &b)
returns a BackendPetsc shared_ptr from a Backend.
template<typename T >
std::shared_ptr< MatrixPetsc< T > > toPETSc (std::shared_ptr< MatrixSparse< T >> const &m)
returns a MatrixPetsc shared_ptr from a Matrix if it was a MatrixPetsc if the cast fails then it is a null shared_ptr
template<typename T >
std::shared_ptr< PreconditionerPetsc< T > > toPETSc (std::shared_ptr< Preconditioner< T >> const &p)
returns a PreconditionerPetsc shared_ptr from a Preconditioner if it was a PreconditionerPetsc if the cast fails then it is a null shared_ptr
template<typename T >
std::shared_ptr< VectorPetsc< T > > toPETSc (std::shared_ptr< Vector< T >> const &v)
returns a VectorPetsc shared_ptr from a Vector if it was a VectorPetsc if the cast fails then it is a null shared_ptr
template<typename MeshType , typename = std::enable_if_t<is_mesh_v<MeshType>>>
constexpr int topodim (std::shared_ptr< MeshType > const &m)
template<typename RefEntity >
void toPython (RefEntity const &e, std::string str="simplex")
template<typename SpaceType >
Trial< SpaceType > trial (std::shared_ptr< SpaceType > const &X)
po::options_description ts_options (std::string const &prefix="")
template<typename T >
constexpr hana::integral_constant< int,(decay_type< T >::nSpaces==1)?1:2 > type_space_t (T &&t)
template<typename T1 , typename T2 >
constexpr hana::integral_constant< int,(decay_type< T1 >::nSpaces==1 &&decay_type< T2 >::nSpaces==1)?1:2 > type_spaces_t (T1 &&t1, T2 &&t2)
template<int Ngeo = 1>
std::shared_ptr< Mesh< Simplex< 2, Ngeo > > > unitCircle (double h=doption(_name="gmsh.hsize"))
build a mesh of the unit circle using triangles
std::shared_ptr< Mesh< Simplex< 3 > > > unitCube (double h=option(_name="gmsh.hsize").as< double >())
build a mesh of the unit square [0,1]^3 using tetrahedrons
template<typename P , template< uint16_type > class Type, template< class, template< uint16_type > class > class Poly1, template< class, template< uint16_type > class > class Poly2>
PolynomialSet< P, Type > unite (Poly1< P, Type > const &pset1, Poly2< P, Type > const &pset2)
union of two polynomial sets P1 and P2 : \(P_1 \oplus P_2\)
template<int Dim, typename Convex = Simplex<Dim>>
std::shared_ptr< Mesh< Convex > > unitHypercube (double h=doption(_name="gmsh.hsize"))
Generate the mesh of an hypercube.
std::shared_ptr< Mesh< Simplex< 1 > > > unitSegment (double h=option(_name="gmsh.hsize").as< double >(), std::string prefix="", worldcomm_ptr_t const &c=Environment::worldCommPtr())
build a mesh of the unit segment [0,1]
template<int Ngeo = 1>
std::shared_ptr< Mesh< Simplex< 3, Ngeo > > > unitSphere (double h=doption(_name="gmsh.hsize"))
build a mesh of the unit circle using triangles
std::shared_ptr< Mesh< Simplex< 2 > > > unitSquare (double h=option(_name="gmsh.hsize").as< double >(), PeriodicEntities pe=PeriodicEntities())
build a mesh of the unit square [0,1]^2 using triangles
template<typename C >
unwrap_ptr_t< C > & unwrap_ptr (C &c)
template<typename C >
unwrap_ptr_t< C > & unwrap_ptr (C *c)
template<typename C >
unwrap_ptr_t< C > const & unwrap_ptr (C const &c)
template<typename Arg >
BlocksBaseVector< typename decay_type< Arg >::value_type > vectorBlocks (const Arg &arg, std::enable_if_t< std::is_base_of< ProductSpaceBase, std::remove_reference_t< Arg >>::value > *=nullptr)
template<typename Arg1 , typename ... Args>
BlocksBaseVector< typename decay_type< Arg1 >::value_type > vectorBlocks (const Arg1 &arg1, const Args &... args, std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< Arg1 >>::value > *=nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
template<size_t S, class ITERATOR , class CONTAINER >
WorldComm const & worldComm (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > const &range)
FEELPP_DEPRECATED worldscomm_ptr_t worldsComm (worldcomm_ptr_t const &wc)
template<typename T >
void writeHBF (std::string const &s, holo3_image< T > const &x)
write a HBF file containing an array of floats
template<typename ItT1 , typename ItT2 >
static auto zip (ItT1 &&itBegin, ItT2 &&itEnd)
template<typename F , typename ItT1 , typename ItT2 >
static auto zip_with (F &&f, ItT1 &&itBegin, ItT2 &&itEnd)
Variables
* A = *M_Aq[0]
const BackendType BACKEND_DEFAULT =BACKEND_EIGEN
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const po::variables_map const BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const po::variables_map const bdf
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const * bool
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PARAMETER_FUNCTION_DEFAULT_FUNCTION
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PARAMETER_FUNCTION_FWD_FUNCTION
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_ELEM_III
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_SUB_O
template<size_type Contextv, size_type Value>
constexpr size_type clear_value_v = clear_value<Contextv,Value>::value
std::map< std::string, size_type > ContextOnMap
BlocksStencilPattern default_block_pattern
template<typename T >
constexpr uint16_type dimension_v = dimension_t<T>::value
FEELPP_TRAITS_OP_CODE double
std::map< std::string, size_type > EigenMap
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 eigs
solve for \(A x =\lambda B x\)
const size_type EXTRACTION_KEEP_ALL_IDS
const size_type EXTRACTION_KEEP_EDGES_IDS = (1 << 1)
const size_type EXTRACTION_KEEP_FACES_IDS = (1 << 2)
const size_type EXTRACTION_KEEP_MARKERNAMES_ONLY_PRESENT = (1 << 5)
const size_type EXTRACTION_KEEP_MESH_RELATION = (1 << 4)
const size_type EXTRACTION_KEEP_POINTS_IDS = (1 << 0)
const size_type EXTRACTION_KEEP_VOLUMES_IDS = (1 << 3)
const double factor_from_eps = 50
const float factor_from_eps_fl = 50
const char * FEELPP_GMSH_FORMAT_VERSION
const GMSH_PARTITIONER GMSH_PARTITIONER_DEFAULT
template<size_type Contextv, size_type Value>
constexpr bool has_value_v = has_value<Contextv,Value>::value
const mpl::int_< COMPONENT_IN_COMPONENT > INDEX_COMPONENT_IN_COMPONENT = mpl::int_<COMPONENT_IN_COMPONENT>()
const mpl::int_< COMPONENT_IN_COMPONENT_FUNCTION_INDEX > INDEX_COMPONENT_IN_COMPONENT_FUNCTION_INDEX = mpl::int_<COMPONENT_IN_COMPONENT_FUNCTION_INDEX>()
const mpl::int_< FUNCTION_INDEX > INDEX_FUNCTION_INDEX = mpl::int_<FUNCTION_INDEX>()
const mpl::int_< GLOBAL_COMPONENT > INDEX_GLOBAL_COMPONENT = mpl::int_<GLOBAL_COMPONENT>()
const mpl::int_< GLOBAL_FUNCTION_INDEX > INDEX_GLOBAL_FUNCTION_INDEX = mpl::int_<GLOBAL_FUNCTION_INDEX>()
const mpl::int_< PER_COMPONENT_FUNCTION_INDEX > INDEX_PER_COMPONENT_FUNCTION_INDEX = mpl::int_<PER_COMPONENT_FUNCTION_INDEX>()
std::map< std::string, InterpolationType > InterpolationTypeMap
const int64_type invalid_flag_type_value = std::numeric_limits<int32_type>::min()
template<typename C >
constexpr bool is_conforming = C::value
template<typename... T>
constexpr bool is_filter_v = is_filter<T...>::value
template<typename ElementType >
constexpr bool is_functionspace_element_v = is_functionspace_element<ElementType>::value
helper variable template for is_functionspace_element
template<typename FuncSpaceType >
constexpr bool is_functionspace_v = is_functionspace<FuncSpaceType>::value
helper variable template for is_functionspace
template<typename... T>
constexpr bool is_geoelement_v = is_geoelement<T...>::value
Helper variable template.
template<typename P >
constexpr bool is_hcurl_conforming_v = boost::is_base_of<HCurlPolynomialSet,P>::value
template<typename P >
constexpr bool is_hdiv_conforming_v = boost::is_base_of<HDivPolynomialSet,P>::value
template<typename T , typename V >
constexpr bool is_iterable_of_v = is_iterable_of<T, V>::value
template<typename T >
constexpr bool is_iterable_v = is_iterable<T>::value
template<typename P >
constexpr bool is_lagrange_polynomialset_P0d_v = is_lagrange_polynomialset_v<P> && (P::nOrder == 0) && !P::continuity_type::is_continuous
template<typename P >
constexpr bool is_lagrange_polynomialset_v = boost::is_base_of<fem::LagrangePolynomialSet,P>::value
template<typename T >
constexpr bool is_linear_polynomial_v = is_linear_polynomial<T>::value
template<typename T >
constexpr bool is_matrix_field_v = is_tensor2_field_v<T> || is_tensor2symm_field_v<T>
helper variable template,
template<typename MeshType >
constexpr bool is_mesh_v = is_mesh<MeshType>::value
helper variable template for is_mesh
template<typename... T>
constexpr bool is_reference_convex_v = is_reference_convex<T...>::value
Helper variable template.
template<typename T >
constexpr bool is_scalar_field_v = is_scalar_field<T>::value
helper variable template for is_scalar_field
template<typename T >
constexpr bool is_scalar_v = std::is_base_of_v<ScalarBase,T>
template<class T >
constexpr bool is_shared_ptr_v = is_shared_ptr<T>::value
template<typename T >
constexpr bool is_simplex_v = is_simplex<T>::value
template<class T >
constexpr bool is_std_vector_v = is_std_vector_t<T>::value
template<typename T >
constexpr bool is_symm_v = std::is_base_of_v<Tensor2SymmBase,T>
helper constant that is true if the T derives from Tensor2SymmBase, false orherwise
template<typename T >
constexpr bool is_tensor2_field_v = is_tensor2_field<T>::value
helper variable template for is_tensor2_field
template<typename T >
constexpr bool is_tensor2_v = std::is_base_of_v<Tensor2Base,T>
template<typename T >
constexpr bool is_tensor2symm_field_v = is_tensor2symm_field<T>::value
helper variable template for is_tensor2symm_field
template<typename T >
constexpr bool is_vector_field_v = is_vector_field<T>::value
helper variable template for is_vector_field
template<typename T >
constexpr bool is_vectorial_v = std::is_base_of_v<VectorialBase,T>
constexpr auto is_void = hana::integral(hana::metafunction<std::is_void>)
const auto MATSOLVER_DEFAULT = MATSOLVER_NONE
const uint16_type MESH_ALL_COMPONENTS = MESH_UPDATE_EDGES | MESH_UPDATE_FACES | MESH_CHECK | MESH_PARTITION | MESH_RENUMBER
const uint16_type MESH_COMPONENTS_DEFAULTS = MESH_RENUMBER | MESH_CHECK
constexpr multiple_space_t multiple_space_c {}
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const name
std::map< std::string, nlopt::algorithm > nloptAlgoMap
std::map< nlopt::result, std::string > nloptResultMap
int Order
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 po::variables_map const BOOST_PARAMETER_ARITY_RANGE_M_BOOST_PP_REM BOOST_PP_SEQ_TAIL_I po::variables_map const order
const double Pi = 3.14159265358979323846264338328
const double pi = constants::pi<double>()
template<typename T >
constexpr bool polynomial_order_v = polynomial_order<T>::value
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 preconditioner
template<typename T >
constexpr uint16_type real_dimension_v = real_dimension_t<T>::value
template<size_type Contextv, size_type Value>
constexpr size_type set_value_v = set_value<Contextv,Value>::value
constexpr single_space_t single_space_c {}
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_0 tag
const double TGV = 1e20
static uint16_type TIMERDATA_INSTANCE_NUMBER = 0
const double two_pi = constants::two_pi<double>()
Constants
template<typename T >
const T invalid_v = T(-1)
get invalid value from type T
const uint8_type invalid_uint8_type_value = uint8_type(-1)
Invalid uint8_type value.
const uint16_type invalid_uint16_type_value = uint16_type(-1)
Invalid uint16_type value.
const uint32_type invalid_uint32_type_value = uint32_type(-1)
Invalid uint32_type value.
const uint64_type invalid_uint64_type_value = uint64_type(-1)
Invalid uint64_type value.
const dim_type invalid_dim_type_value = dim_type(-1)
Invalid dim type value.
const rank_type invalid_rank_type_value = rank_type(-1)
Invalid dim type value.
const size_type invalid_size_type_value = size_type(-1)
Invalid size type value.
const uint16_type quad_order_from_expression = invalid_uint16_type_value
Quadrature order deduced from the expression to integrate.
template<typename E >
constexpr auto to_underlying (E e) noexcept
get the underlying value of an enum class entry
template<typename E , typename T >
constexpr std::enable_if< std::is_enum< E >::value &&std::is_integral< T >::value, E >::type to_enum (T value) noexcept
Constructors, destructor
Elements (worldcomm_ptr_t const &worldComm=Environment::worldCommPtr())
Elements (Elements const &f)
virtual ~Elements ()
void clear ()
Operator overloads
Elements & operator= (Elements const &e)
copy operator
Accessors
elements_type const & elements () const
virtual bool isEmpty () const
WorldComm & worldCommElements ()
bool isBoundaryElement (element_type const &e) const
bool isBoundaryElement (size_type const &id) const
element_const_iterator elementIterator (size_type i) const
FEELPP_DEPRECATED element_const_iterator elementIterator (size_type i, rank_type p) const
element_const_iterator elementIterator (element_type const &elt) const
element_type const & element (size_type i) const
FEELPP_DEPRECATED element_type const & element (size_type i, rank_type p) const
bool hasElement (size_type i) const
bool hasElement (size_type i, rank_type p) const
element_iterator beginElement ()
element_iterator endElement ()
ordered_element_reference_wrapper_iterator beginOrderedElement ()
ordered_element_reference_wrapper_iterator endOrderedElement ()
parts_const_iterator_type beginParts () const
parts_const_iterator_type endParts () const
parts_map_type const & parts () const
std::pair< element_iterator, element_iterator > elementsRange ()
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithId (size_type m) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarkerByType (uint16_type markerType, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarkerByType (uint16_type markerType, std::set< flag_type > const &markerFlags, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarkerByType (uint16_type markerType, flag_type m, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarker (flag_type m=invalid_flag_type_value, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarker2 (flag_type m, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithMarker3 (flag_type m, rank_type p=invalid_rank_type_value) const
std::map< int, std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > > collectionOfElementsWithMarkerByType (uint16_type markerType, std::map< int, std::set< flag_type >> const &collectionOfMarkerFlagSet, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > elementsWithProcessId (rank_type p=invalid_rank_type_value) const
element_const_iterator firstElementIteratorWithProcessId (rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > boundaryElements (uint16_type entity_min_dim, uint16_type entity_max_dim, rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > boundaryElements (rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > internalElements (rank_type p=invalid_rank_type_value) const
std::tuple< element_reference_wrapper_const_iterator, element_reference_wrapper_const_iterator, elements_reference_wrapper_ptrtype > ghostElements () const
Methods
void reserveNumberOfElement (size_type nElt)
reserve size of container
std::pair< element_iterator, bool > addElement (element_type &f, bool setid=true)
add a new element in the mesh
std::pair< element_iterator, bool > addElement (element_type &&f)
move an element into the mesh
element_iterator eraseElementOnly (element_iterator it)
template<typename ElementVecType >
void updateMarker (uint16_type markerType, ElementVecType const &evec)
template<typename ElementVecType >
void updateMarker2 (ElementVecType const &evec)
template<typename ElementVecType >
void updateMarker3 (ElementVecType const &evec)
template<typename IteratorRange >
void updateMarkerWithRangeElements (uint16_type markerType, IteratorRange const &range, flag_type flag)
template<typename IteratorRange >
void updateMarkerWithRangeElements (IteratorRange const &range, flag_type flag)
template<typename IteratorRange >
void updateMarker2WithRangeElements (IteratorRange const &range, flag_type flag)
template<typename IteratorRange >
void updateMarker3WithRangeElements (IteratorRange const &range, flag_type flag)
void updateMarkersFromFaces (std::initializer_list< uint16_type > const &markersType)
update the elements markers by setting them from the face markers associated to the elements if 2 several markers are find in elt, the element take the last find as marker
void updateMarkersFromFaces ()
void setWorldCommElements (worldcomm_ptr_t const &_worldComm)
void updateOrderedElement ()
void addParts (std::set< int > const &someParts)
Detailed Description
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*-
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*- vim:fenc=utf-8:ft=cpp:et:sw=4:ts=4:sts=4
allow automatic type naming of complex expression
include linear algebra backend
file GeoEntity.h
Special routines to read meshes and special structures for sides and faces handling.
big changes : handle parallel and a lot of code simplifications Vincent Doyeux 2014-01-10
Namespace for general FEEL functions.
This file is part of the Feel++ library
Author(s): Christophe Prud'homme chris.nosp@m.toph.nosp@m.e.pru.nosp@m.dhom.nosp@m.me@fe.nosp@m.elpp.nosp@m..org Date: 27 Nov 2016
Copyright (C) 2016 Feel++ Consortium
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
This file is part of the Feel library Author(s): Christophe Prud'homme chris.nosp@m.toph.nosp@m.e.pru.nosp@m.dhom.nosp@m.me@fe.nosp@m.elpp.nosp@m..org Date: 2011-12-23 Copyright (C) 2011 Universit Joseph Fourier (Grenoble I) Copyright (C) 2011-2016 Feel++ Consortium This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Classes BareFace and BareEdge have been created to give an UNIQUE Representation for mesh faces and edges and thus allow the construction of global tables or Fields.
include function space class include gmsh mesh importer include the header for the variational formulation language (vf) aka FEEL++
This file is part of the Feel++ library
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Typedef Documentation
is_hcurl_conforming
template<typename P > using Feel::is_hcurl_conforming = typedef boost::is_base_of<HCurlPolynomialSet,P>
type traits for hcurl conforming polynomialset
Returns
true_type if hcurl conforming polynomialset, false_type otherwise
is_hdiv_conforming
template<typename P > using Feel::is_hdiv_conforming = typedef boost::is_base_of<HDivPolynomialSet,P>
type traits for hdiv conforming polynomialset
Returns
true_type if hdiv conforming polynomialset, false_type otherwise
operator_interpolation_t
template<typename DomainSpaceType , typename ImageSpaceType , typename IteratorRange = elements_pid_t<typename ImageSpaceType::mesh_type>, typename InterpType = InterpolationNonConforming> using Feel::operator_interpolation_t = typedef OperatorInterpolation<DomainSpaceType, ImageSpaceType, range_t<IteratorRange>, InterpType>
get the type of an OperatorInterpolation
operator_interpolation_t<space_1_type,space_2_type,elements_pid_t<typename space_2_type::mesh_type>, >
region_tree_ptrtype
std::shared_ptr< RegionTree > Feel::region_tree_ptrtype
pointer type for Region Tree.
region_tree_type
RegionTree Feel::region_tree_type
an alias for RegionTree
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TimeIndependent
TimeIndependent.
TimeDependent
TimeDependent.
Coercive
Coercive PDE.
InfSup
Inf-Sup PDE.
Mono
Monolithic.
UseBlock
By block.
anonymous enum
anonymous enum
Enumerator
FUNCTIONAL
functional identifier
EQUALITIES
equalities identifier
INEQUALITIES
inequalities identifier
BackendType
enum Feel::BackendType
Backend types.
At the moment, we support GMM(serial), PETSC and TRILINOS(serial and parallel)
BFGSType
enum Feel::BFGSType
BFGS algorithm (Broyden, Fletcher, Goldfarb, Shanno) Quasi Newton method for optimization problems.
with Wolfe Line search.
Ripped from getfem++ by Y. Renard
CRBErrorType
enum Feel::CRBErrorType
CRBErrorType Determine the type of error estimation used.
CRB_RESIDUAL : use the residual error estimation without algorithm SCM
CRB_RESIDUAL_SCM : use the residual error estimation and also algorithm SCM
CRB_NO_RESIDUAL : in this case we don't compute error estimation
CRB_EMPIRICAL : compute |S_n - S_{n-1}| where S_n is the output obtained by using a reduced basis with n elements
EigenProblemType
enum Feel::EigenProblemType
Defines an enum for eigenproblem types.
This can be Hermitian (HEP), generalized Hermitian (GHEP), non-Hermitian (NHEP), generalized non-Hermitian (GNHEP) and Generalized Non-Hermitian GNHEP with positive (semi-)definite B
ElementsType
enum Feel::ElementsType
entity identifier for mesh iterators
Enumerator
MESH_ELEMENTS
elements
MESH_FACES
faces
MESH_INTERNAL_FACES
internal faces
MESH_EDGES
edges
MESH_INTERNAL_EDGES
internal edges
MESH_POINTS
points
GeoEntityContext
enum Feel::GeoEntityContext
Enumerator
MESH_ENTITY_INTERNAL
internal entity
MESH_ENTITY_BOUNDARY
boundary entity
GMSH_ENTITY
enum Feel::GMSH_ENTITY
enumerate the various elements available in gmsh
Enumerator
GMSH_LINE
Line (2 nodes).
GMSH_TRIANGLE
Triangle (3 nodes).
GMSH_QUADRANGLE
Quadrangle (4 nodes).
GMSH_TETRAHEDRON
Tetrahedron (4 nodes).
GMSH_HEXAHEDRON
Hexahedron (8 nodes).
GMSH_PRISM
Prism (6 nodes).
GMSH_PYRAMID
Pyramid (5 nodes).
GMSH_LINE_2
Second order line (3 nodes: 2 associated.
GMSH_TRIANGLE_2
Second order triangle (6 nodes: 3.
GMSH_QUADRANGLE_2
Second order quadrangle (9 nodes: 4.
GMSH_TETRAHEDRON_2
Second order tetrahedron (10 nodes:
GMSH_HEXAHEDRON_2
Second order hexahedron (27 nodes: 8.
GMSH_PRISM_2
Second order prism (18 nodes: 6 associated.
GMSH_PYRAMID_2
Second order pyramid (14 nodes: 5.
GMSH_POINT
Point (1 node).
GMSH_TRIANGLE_INCOMPLETE_3
triangle of order 3
GMSH_TRIANGLE_3
triangle of order 3
GMSH_TRIANGLE_INCOMPLETE_4
triangle of order 4
GMSH_TRIANGLE_4
triangle of order 4
GMSH_TRIANGLE_INCOMPLETE_5
triangle of order 5
GMSH_TRIANGLE_5
triangle of order 5
GMSH_LINE_3
line of order 3
GMSH_LINE_4
line of order 4
GMSH_LINE_5
line of order 5
GMSH_TETRAHEDRON_3
tetra of order 3
GMSH_TETRAHEDRON_4
tetra of order 4
GMSH_TETRAHEDRON_5
tetra of order 5
NedelecKind
enum Feel::NedelecKind strong
NED1 H(curl) Nedelec finite element of the first kind
NED2 H(curl) Nedelec finite element of the second kind (full polynomial space)
PositionOfSpectrum
enum Feel::PositionOfSpectrum
Defines an enum for the position of the spectrum, i.e.
the eigenvalues to be computed.
ReferenceGeometry
enum Feel::ReferenceGeometry
Enumerator
GEOMETRY_POINT
point entity
GEOMETRY_LINE
line entity
GEOMETRY_SURFACE
surface entity
GEOMETRY_VOLUME
volume entity
GEOMETRY_4
hypercube entity
GEOMETRY_5
hypercube entity
scstate
enum Feel::scstate strong
describe the state of local matrix/vector in static condensation
Enumerator
updated
no initialized
SolverPackage
enum Feel::SolverPackage
Defines an enum for various linear solver packages.
This allows for run-time switching between solver packages
Function Documentation
addElement() [1/2]
std::pair<element_iterator,bool> Feel::addElement (element_type && f)
move an element into the mesh
Parameters
f a new point
Returns
the new point from the list
addElement() [2/2]
std::pair<element_iterator,bool> Feel::addElement (element_type & f, bool setid = true)
add a new element in the mesh
Parameters
f a new point
Returns
the new point from the list
allelements()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> allelements_t<MeshType> Feel::allelements (MeshType const & mesh)
Returns
a pair of iterators to iterate over elements with pid flag
Referenced by Feel::PartitionerMetis< MeshType >::partitionImpl().
askPassword()
FEELPP_EXPORT std::string Feel::askPassword (std::string const & message)
Ask the user to fill a password. The password is hidden with asterisks.
Parameters
message a message to display to the user
Returns
The (clear) password in a string.
Note
: This function is unix specific.
backend_options()
po::options_description Feel::backend_options (std::string const & prefix = "")
Parameters
prefix prefix given to the backend option
Returns
backend command line options description
blockVector()
template<typename PS > BlocksBaseVector<double,uint32_type> Feel::blockVector (PS && ps, backend_ptrtype b = backend(), std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< PS >>::value > * = nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
Variadic template is used to handle an arbitrary number of function spaces. The blocks are organized then matrix wise with the stencil associated of pairs of function spaces in (arg1,...,argn)
BOOST_PARAMETER_FUNCTION() [1/8]
Feel::BOOST_PARAMETER_FUNCTION ((Checker) , checker , tag , (required(name,(std::string))(solution_key,(std::string)))(optional(inputs,(std::map< std::string, std::string >),(std::map< std::string, std::string >{}))(solution,(std::string), inputs.count(solution_key)?inputs.at(solution_key):soption("checker.solution"))(gradient_key,(std::string), std::string{"grad_"}+solution_key)(gradient,(std::string), inputs.count(gradient_key)?inputs.at(gradient_key):soption("checker.gradient"))(script,(std::string), soption("checker.script"))(compute_pde_coefficients,(bool), boption("checker.compute-pde-coefficients"))(prefix,(std::string), "")(verbose,(bool), boption(_prefix=prefix, _name="checker.verbose"))))
check create function
Parameters
c_name name of the checker
solution to pass to checker and check the numerical results, if empty use checker.solution
gradient optional expression for the gradient, if empty use checker.gradient if gradient and option checker.gradient are empty then we do not set the gradient expression
BOOST_PARAMETER_FUNCTION() [2/8]
Feel::BOOST_PARAMETER_FUNCTION ((gmsh_ptrtype) , convert2msh , tag , (required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(dim, *(boost::is_integral< mpl::_ >), 3)(order, *(boost::is_integral< mpl::_ >), 1)))
convert to gmsh format
filename
dim (optional, default = 3)
order (optional, default = 1)
BOOST_PARAMETER_FUNCTION() [3/8]
Feel::BOOST_PARAMETER_FUNCTION ((gmsh_ptrtype) , geo , tag , (required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(desc, *(boost::is_convertible< mpl::_, std::string >), std::string())(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(geo_parameters, *(boost::icl::is_map< mpl::_ >), Gmsh::gpstr2map(soption(_prefix=prefix, _name="gmsh.geo-variables-list", _vm=vm)))(dim, *(boost::is_integral< mpl::_ >), 3)(order, *(boost::is_integral< mpl::_ >), 1)(files_path, *(boost::is_convertible< mpl::_, std::string >), Environment::localGeoRepository())(depends, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.depends", _vm=vm))(worldcomm,(worldcomm_ptr_t), Environment::worldCommPtr())))
geo return a gmsh_ptrtype of a .geo mesh
filename
dimension
order (optional, default = 1)
h (optional, default = 0.1)
References Feel::Environment::findFile(), and Feel::Environment::geoPathList().
BOOST_PARAMETER_FUNCTION() [4/8]
Feel::BOOST_PARAMETER_FUNCTION ((std::string) , img2msh , tag , (required(filename, *(boost::is_convertible< mpl::_, std::string >)))(optional(prefix, *(boost::is_convertible< mpl::_, std::string >), fs::path(filename).stem())))
convert to msh format
filename
BOOST_PARAMETER_FUNCTION() [5/8]
Feel::BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype) , createGMSHMesh , tag , (required(mesh, *)(desc, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(format, *, ioption(_prefix=prefix, _name="gmsh.format", _vm=vm))(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(parametricnodes, *(boost::is_integral< mpl::_ >), 0)(in_memory, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.in-memory", _vm=vm))(straighten, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(structured, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.structured", _vm=vm))(update, *(boost::is_integral< mpl::_ >), MESH_RENUMBER|MESH_UPDATE_EDGES|MESH_UPDATE_FACES|MESH_CHECK)(force_rebuild, *(boost::is_integral< mpl::_ >), 0)(physical_are_elementary_regions, *, boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(periodic, *, PeriodicEntities())(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *(boost::is_convertible< mpl::_, std::string >), "")(worldcomm,(worldcomm_ptr_t), mesh->worldCommPtr())(partitions, *(boost::is_integral< mpl::_ >), worldcomm->localSize())(partition_file, *(boost::is_integral< mpl::_ >), 0)(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))(directory,(std::string), "")))
create a mesh data structure (hold in a shared_ptr<>) using GMSH
mesh mesh data structure
descprition
h (float, optional, default = 0.1)
order (integer, optional, default = 1)
parametricnodes (boolean, optional, default = 0)
refine (boolean, optional, default = 0)
update (boolean, optional, default = 0)
force_rebuild boolean (boolean, optional, default = 0)
physical_are_elementary_regions change file format (optional, default = false)
BOOST_PARAMETER_FUNCTION() [6/8]
Feel::BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype) , loadGMSHMesh , tag , (required(mesh, *)(filename, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(straighten, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(update, *(boost::is_integral< mpl::_ >), 0)(physical_are_elementary_regions, *, boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(worldcomm,(worldcomm_ptr_t), mesh->worldCommPtr())(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *, "")(partitions, *(boost::is_integral< mpl::_ >), worldcomm->globalSize())(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(partition_file, *(boost::is_integral< mpl::_ >), 0)(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))))
load a mesh data structure (hold in a shared_ptr<>) using GMSH
mesh mesh data structure
filename filename string (with extension)
refine optionally refine with refine levels the mesh (default: 0)
update update the mesh data structure (build internal faces and edges) (default : true)
physical_are_elementary_regions boolean to load specific meshes formats (default : false)
BOOST_PARAMETER_FUNCTION() [7/8]
Feel::BOOST_PARAMETER_FUNCTION ((typename Feel::detail::mesh< Args >::ptrtype) , loadMesh , tag , (required(mesh, *))(optional(prefix,(std::string), "")(vm,(po::variables_map const &), Environment::vm())(filename, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.filename", _vm=vm))(desc, *, std::shared_ptr< gmsh_type >())(h, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="gmsh.hsize", _vm=vm))(scale, *(boost::is_arithmetic< mpl::_ >), doption(_prefix=prefix, _name="mesh.scale", _vm=vm))(straighten,(bool), boption(_prefix=prefix, _name="gmsh.straighten", _vm=vm))(refine, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.refine", _vm=vm))(update, *(boost::is_integral< mpl::_ >), MESH_CHECK|MESH_UPDATE_FACES|MESH_UPDATE_EDGES)(physical_are_elementary_regions,(bool), boption(_prefix=prefix, _name="gmsh.physical_are_elementary_regions", _vm=vm))(worldcomm, *, mesh->worldCommPtr())(force_rebuild, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.rebuild", _vm=vm))(respect_partition,(bool), boption(_prefix=prefix, _name="gmsh.respect_partition", _vm=vm))(rebuild_partitions,(bool), boption(_prefix=prefix, _name="gmsh.partition", _vm=vm))(rebuild_partitions_filename, *(boost::is_convertible< mpl::_, std::string >), "")(partitions, *(boost::is_integral< mpl::_ >),(worldcomm)?worldcomm->globalSize():1)(partitioner, *(boost::is_integral< mpl::_ >), ioption(_prefix=prefix, _name="gmsh.partitioner", _vm=vm))(savehdf5, *(boost::is_integral< mpl::_ >), boption(_prefix=prefix, _name="gmsh.savehdf5", _vm=vm))(partition_file, *(boost::is_integral< mpl::_ >), 0)(depends, *(boost::is_convertible< mpl::_, std::string >), soption(_prefix=prefix, _name="gmsh.depends", _vm=vm))(verbose,(int), ioption(_prefix=prefix, _name="gmsh.verbosity", _vm=vm))))
load a mesh data structure (hold in a shared_ptr<>) using GMSH
mesh mesh data structure
filename filename string (with extension)
refine optionally refine with refine levels the mesh (default: 0)
update update the mesh data structure (build internal faces and edges) (default : true)
physical_are_elementary_regions boolean to load specific meshes formats (default : false)
References Feel::Environment::expand(), Feel::Environment::findFile(), scale(), straightenMesh(), and Feel::Environment::vm().
BOOST_PARAMETER_FUNCTION() [8/8]
Feel::BOOST_PARAMETER_FUNCTION ((void) , saveGMSHMesh , tag , (required(mesh, *)(filename, *))(optional(parametricnodes, *(boost::is_integral< mpl::_ >), 0)))
save a mesh data structure (hold in a shared_ptr<>) in the GMSH format
mesh mesh data structure
filename filename string (with extension)
References Feel::ExporterGmsh< MeshType, N >::saveMesh().
boundaryedges()
template<typename MeshType > boundaryedges_t<MeshType> Feel::boundaryedges (MeshType const & mesh)
Returns
a pair of iterators to iterate over all boundary edges of the mesh
boundaryelements()
template<typename MeshType > boundaryelements_t<MeshType> Feel::boundaryelements (MeshType const & mesh, uint16_type entity_min_dim = 0, uint16_type entity_max_dim = 2)
Returns
a pair of iterators to iterate over elements of the mesh which share a face with the boundary
boundaryElements() [1/2]
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::boundaryElements (rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the boundary element on processor p
References boundaryElements(), invalid_rank_type_value, and Feel::WorldComm::localRank().
boundaryElements() [2/2]
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::boundaryElements (uint16_type entity_min_dim, uint16_type entity_max_dim, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the boundary element on processor p which share a subentity of minDim<= dim <= maxDim on boundary
References invalid_rank_type_value, and Feel::WorldComm::localRank().
Referenced by boundaryElements().
boundaryfaces()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> boundaryfaces_t<MeshType> Feel::boundaryfaces (MeshType const & mesh)
Returns
a pair of iterators to iterate over all boundary faces of the mesh
boundarypoints()
template<typename MeshType > boundarypoints_t<MeshType> Feel::boundarypoints (MeshType const & mesh)
Returns
the range of iterators [begin,end] over the boundary points of the mesh
Warning
this filter is not parallelized
References unwrap_ptr().
Referenced by nelements().
collectionOfElementsWithMarkerByType()
std::map<int, std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> > Feel::collectionOfElementsWithMarkerByType (uint16_type markerType, std::map< int, std::set< flag_type >> const & collectionOfMarkerFlagSet, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker1 markerFlags on processor p
References invalid_rank_type_value, and Feel::WorldComm::localRank().
collectionOfMarkedelements()
template<typename MeshType > std::map<int,markedelements_t<MeshType> > Feel::collectionOfMarkedelements (MeshType const & mesh, std::any const & collectionOfMarkersFlag)
Returns
a mapping between a id and pair of iterators to iterate over elements of the mesh with marker flag
complement()
template<typename IteratorType , typename Predicate > ext_entities_from_iterator_t<IteratorType> Feel::complement (IteratorType && it, Predicate pred)
Provides the complement of the set of entities given by [begin(it),end(it)] with respect to the negation of predicate pred.
// get all faces not marked by marker1 "R"
auto set = complement(faces(mesh), [&mesh](auto const& e) { return e.marker() == mesh->markerName("R"); });
compose()
template<typename Op1Type , typename Op2Type > std::shared_ptr<OperatorCompose<Op1Type,Op2Type> > Feel::compose (std::shared_ptr< Op1Type > op1, std::shared_ptr< Op2Type > op2)
Parameters
op1 an operator
op2 an operator
Returns
the operator which is the composition of op1 with op2
References Feel::OperatorBase< op1_type::value_type >::label().
concatenate()
template<typename IteratorType , typename... Args> FEELPP_EXPORT Feel::concatenate_t<IteratorType> Feel::concatenate (IteratorType && it, Args &&... args)
this function takes a set of iterators over geometrical entities of the same type (e.g.
faces, volumes, edges, points) and generate a data structure that will hold the corresponding reference of mesh elements. This data structure can then be used to iterate over meshes like other mesh filters.
// the following code below merges internal faces with inlet faces
auto subset = concatenate(internalfaces(mesh), markedfaces(mesh,"inlet"));
// it can then be used eg to create a submesh
auto submesh = createSubmesh(mesh, subset);
csrGraphBlocks()
template<typename PS > BlocksBaseGraphCSR Feel::csrGraphBlocks (PS && ps, uint32_type pattern = Pattern::COUPLED, std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< PS >>::value > * = nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
Variadic template is used to handle an arbitrary number of function spaces. The blocks are organized then matrix wise with the stencil associated of pairs of function spaces in (arg1,...,argn)
curl() [1/2]
template<typename Poly > Polynomial<Poly, Vectorial> Feel::curl (Polynomial< Poly, Vectorial > const & p)
compute the curl of a vectorial polynomial p
Returns
the curl of the vectorial polynomial
curl() [2/2]
template<typename Poly > PolynomialSet<Poly, Vectorial> Feel::curl (PolynomialSet< Poly, Vectorial > const & p)
compute the curl of a vectorial polynomial set p
Returns
the curl of the vectorial polynomial
curlt() [1/2]
template<typename Poly > Polynomial<Poly, Vectorial> Feel::curlt (Polynomial< Poly, Vectorial > const & p)
compute the transpose of the curl of a vectorial polynomial p
Note
swap the signs of the curl matrix operator
Returns
the transpose of the curl of the vectorial polynomial
curlt() [2/2]
template<typename Poly > PolynomialSet<Poly, Vectorial> Feel::curlt (PolynomialSet< Poly, Vectorial > const & p)
compute the transpose of the curl of a vectorial polynomial p
Note
swap the signs of the curl matrix operator
Returns
the transpose of the curl of the vectorial polynomial
default_prepost_solve()
detail void Feel::default_prepost_solve (vector_ptrtype rhs, vector_ptrtype sol)
!
default pre/post solve function, a no-op
DhPdh()
template<int Order, typename MeshType > std::shared_ptr<FunctionSpace<MeshType,bases<RaviartThomas<Order>,Lagrange<Order,Scalar,Discontinuous> > > > Feel::DhPdh (std::shared_ptr< MeshType > mesh, std::vector< bool > buildExtendedDofTable = std::vector<bool>(2,false))
#include <feel/feeldiscr/dhpdh.hpp>
auto Xh = DhPdh<2>(mesh);
diag()
template<typename OpType > std::shared_ptr<OperatorDiag<OpType> > Feel::diag (std::shared_ptr< OpType > M)
Parameters
op an operator
s a scalar
Returns
the operator which is the scaling of op by s
dimension()
template<typename T > constexpr int Feel::dimension (T const & t) constexpr
Returns
topological dimension of a type T
distToEntityRange()
template<typename SpaceType , typename RangeType , typename = std::enable_if_t<is_functionspace_v<SpaceType>>> element_t<SpaceType> Feel::distToEntityRange (std::shared_ptr< SpaceType > const & Xh, RangeType const & r)
compute the distance field as element of Xh to boundary defined by range r
// distance to boundary faces
auto phi = distToEntityRange(Xh, boundaryfaces(Xh->mesh()));
// distance to faces marked moving
auto phi = distToEntityRange(Xh, markedfaces(Xh->mesh(), "moving"));
Note
Xh must be Lagrange P1
References elements().
div()
template<typename ElementType > ElementType Feel::div (ElementType const & v1, ElementType const & v2, typename boost::enable_if< boost::is_base_of< FunctionSpaceBase::ElementBase, ElementType > >::type * dummy = 0)
Computes the element wise division of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the element wise division product of v1 and v2
divergence() [1/2]
template<typename Poly > Polynomial<Poly, Scalar> Feel::divergence (Polynomial< Poly, Vectorial > const & p)
compute the divergence of a vectorial polynomial p
Returns
the divergence of the vectorial polynomial
divergence() [2/2]
template<typename Poly > PolynomialSet<Poly, Scalar> Feel::divergence (PolynomialSet< Poly, Vectorial > const & p)
compute the divergence of a vectorial polynomial set p
Returns
the divergence of the vectorial polynomial set
dx() [1/2]
template<typename Poly , template< uint16_type > class Type> Polynomial<Poly, Type> Feel::dx (Polynomial< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial x}\) of a polynomial p
Returns
the gradient of the scalar polynomial
dx() [2/2]
template<typename Poly , template< uint16_type > class Type> PolynomialSet<Poly, Type> Feel::dx (PolynomialSet< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial x}\) of a polynomial set p
Returns
the gradient of the scalar polynomial
dy() [1/2]
template<typename Poly , template< uint16_type > class Type> Polynomial<Poly, Type> Feel::dy (Polynomial< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial y}\) of a polynomial p
Returns
the gradient of the scalar polynomial
dy() [2/2]
template<typename Poly , template< uint16_type > class Type> PolynomialSet<Poly, Type> Feel::dy (PolynomialSet< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial y}\) of a polynomial set p
Returns
the gradient of the scalar polynomial
dz() [1/2]
template<typename Poly , template< uint16_type > class Type> Polynomial<Poly, Type> Feel::dz (Polynomial< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial z}\) of a polynomial p
Returns
the gradient of the scalar polynomial
dz() [2/2]
template<typename Poly , template< uint16_type > class Type> PolynomialSet<Poly, Type> Feel::dz (PolynomialSet< Poly, Type > const & p)
compute \(\frac{\partial \cdot}{\partial z}\) of a polynomial set p
Returns
the gradient of the scalar polynomial
edges()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> pid_edges_t<MeshType> Feel::edges (MeshType const & mesh)
Returns
a pair of iterators to iterate over edges of the mesh on processor __pid
Parameters
mesh a mesh data structure
__pid process id
Returns
a pair of edge iterators (begin,end)
Referenced by worldComm().
element_product() [1/4]
template<typename T > VectorEigen<T> Feel::element_product (std::shared_ptr< VectorEigen< T > > const & v1, std::shared_ptr< VectorEigen< T > > const & v2)
Computes the element wise product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the inner product of v1 and v2
element_product() [2/4]
template<typename T , typename Storage1 , typename Storage2 > VectorUblas<T> Feel::element_product (std::shared_ptr< VectorUblas< T, Storage1 > > const & v1, std::shared_ptr< VectorUblas< T, Storage2 > > const & v2)
Computes the element wise product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the inner product of v1 and v2
element_product() [3/4]
template<typename T > VectorEigen<T> Feel::element_product (VectorEigen< T > const & v1, VectorEigen< T > const & v2)
Computes the element wise product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the element product of v1 and v2
element_product() [4/4]
template<typename T , typename Storage1 , typename Storage2 > VectorUblas<T> Feel::element_product (VectorUblas< T, Storage1 > const & v1, VectorUblas< T, Storage2 > const & v2)
Computes the element wise product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the element product of v1 and v2
References project(), range(), and Feel::vf::vec().
elements() [1/5]
elements_type const& Feel::elements () const
Returns
the elements container
Referenced by Feel::TwoSpacesMap< SpaceType >::build(), distToEntityRange(), elements(), etaQ(), hMeasures(), Feel::CNAB2< FieldType >::l2Error(), nsrQ(), Feel::Mesh0D< Shape, T, IndexT >::numLocalVertices(), Feel::PartitionerLinear< MeshType >::partitionImpl(), Feel::Partitioner< MeshType >::singlePartition(), Feel::SolidMechanics< DisplSpaceType >::updateCoefflame1(), Feel::SolidMechanics< DisplSpaceType >::updateCoefflame2(), and Feel::Mesh< Hypercube< 2 > >::updateMarker3WithRange().
elements() [2/5]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, decay_type< std::remove_pointer_t< MeshType >>>, int > = 0> elements_pid_t<MeshType> Feel::elements (MeshType const & mesh)
Returns
a pair of iterators to iterate over elements with pid flag
References elements().
elements() [3/5]
template<typename MeshType > elements_pid_t<MeshType> Feel::elements (MeshType const & mesh, elements_reference_wrapper_t< MeshType > const & rangeElt, faces_reference_wrapper_t< MeshType > const & rangeFace, ElementsType type = ElementsType::MESH_POINTS)
Returns
a pair of iterators to iterate over a range of elements 'rangeElt' which touch the range of faces rangeFace by a point/edge/faces (with respect to type arg)
elements() [4/5]
template<typename MeshType > elements_pid_t<MeshType> Feel::elements (MeshType const & mesh, faces_reference_wrapper_t< MeshType > const & rangeFace, ElementsType type = ElementsType::MESH_POINTS)
Returns
a pair of iterators to iterate over all elements (not ghost) which touch the range of faces rangeFace by a point/edge/faces (with respect to type arg)
elements() [5/5]
template<typename MeshType , typename ExprType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> elements_pid_t<MeshType> Feel::elements (MeshType const & mesh, vf::Expr< ExprType > const & expr)
Returns
a pair of iterators to iterate over elements with pid flag and verified expr > 0 for all nodes of the element
elementsRange()
std::pair<element_iterator, element_iterator> Feel::elementsRange ()
Returns
the range of iterator (begin,end) over the elements with marker m on processor p
elementsWithId()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithId (size_type m) const
Returns
the range of iterator (begin,end) over the elements with Id m
References hasElement().
elementsWithMarker()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarker (flag_type m = invalid_flag_type_value, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker1 m on processor p
References elementsWithMarkerByType().
elementsWithMarker2()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarker2 (flag_type m, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker2 m on processor p
References elementsWithMarkerByType().
elementsWithMarker3()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarker3 (flag_type m, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker3 m on processor p
References elementsWithMarkerByType().
elementsWithMarkerByType() [1/3]
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarkerByType (uint16_type markerType, flag_type m, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker1 m on processor p
References elementsWithMarkerByType().
elementsWithMarkerByType() [2/3]
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarkerByType (uint16_type markerType, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with any Marker1 on processor p
References invalid_rank_type_value, and Feel::WorldComm::localRank().
Referenced by elementsWithMarker(), elementsWithMarker2(), elementsWithMarker3(), and elementsWithMarkerByType().
elementsWithMarkerByType() [3/3]
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithMarkerByType (uint16_type markerType, std::set< flag_type > const & markerFlags, rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements with Marker1 markerFlags on processor p
References invalid_rank_type_value, and Feel::WorldComm::localRank().
elementsWithProcessId()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::elementsWithProcessId (rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the elements on processor p
References invalid_rank_type_value, and Feel::WorldComm::localRank().
entityMarkers()
template<int EntityCoDim, typename ElementT > std::optional<std::map<uint16_type,Marker1> > Feel::entityMarkers (ElementT const & e, uint16_type f)
get the map of markers of a entity of a geoelement
Parameters
e element id to get face markers from
f entity id in the element
Returns
an optional map of markers for the entity f of the element e
etaQ()
template<typename MeshType > Pdh_element_t<MeshType,0> Feel::etaQ (std::shared_ptr< MeshType > const & m)
Return default triangle/tetrahedra quality (eta) of a given cell.
The quality measure relates the area of the triangle (a) to its edge lengths (l1, l2, l3). \(\eta = \frac{4\sqrt{3}a}{l_1^2 + l_2^2 + l_3^2} \)
References elements().
expansion() [1/2]
template<typename ElementType , typename CoeffType > Feel::remove_shared_ptr_type<ElementType> Feel::expansion (std::vector< ElementType > const & b, CoeffType const & c, int M = -1)
Given a set of coefficient c and a set of finite element function b, build.
\[ w = \sum_{i=1}^{M} c_i b_i \]
The last argument M allows to build only a subset of the expansion
References expansion(), and unwrap_ptr().
expansion() [2/2]
template<typename ElementType , typename CoeffType > void Feel::expansion (std::vector< ElementType > const & b, CoeffType const & c, Vector< typename Feel::remove_shared_ptr_type< ElementType >::value_type > & res, int M = -1)
Given a set of coefficient c and a set of finite element function b, build.
\[ w = \sum_{i=1}^{M} c_i b_i \]
The last argument M allows to build only a subset of the expansion
References unwrap_ptr().
Referenced by Feel::DEIMModel< ModelType, Backend< ModelType::value_type >::sparse_matrix_type >::deimExpansion(), and expansion().
faces()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> faces_pid_t<MeshType> Feel::faces (MeshType const & mesh)
Returns
a pair of iterators to iterate over faces of the mesh on processor __pid
Parameters
mesh a mesh data structure
__pid process id
Returns
a pair of face iterators (begin,end)
References markedelementsByType().
Referenced by Feel::Partitioner< MeshType >::singlePartition().
factoryCRBPlugin()
std::shared_ptr<CRBPluginAPI> Feel::factoryCRBPlugin (std::string const & n, std::string const & pluginlibname = "", std::string const & dirname = Info::libdir())
create the plugin name from plugin library pluginlibname located in dirname
Parameters
n name of the plugin
pluginlibname name of the plugin library
dirname location of the plugin library
firstElementIteratorWithProcessId()
element_const_iterator Feel::firstElementIteratorWithProcessId (rank_type p = invalid_rank_type_value) const
Returns
the first iterator over the elements on processor p if exist else return endElement iterator
References invalid_rank_type_value, and Feel::WorldComm::localRank().
flat()
template<typename ExprT1 > Expr<FlatExpr<ExprT1> > Feel::flat (ExprT1 const & __e1)
precompute expression tensor
This allows for more efficient bi/linear form assembly
ghostElements()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::ghostElements () const
Returns
the range of iterator (begin,end) over the internal element on processor p
globalRank()
template<typename C > auto Feel::globalRank (C const & c)
Returns
the global MPI rank of the data structure c
Referenced by Feel::TwoSpacesMap< SpaceType >::clusterToSequential().
gradient() [1/4]
template<typename Poly > Polynomial<Poly, Vectorial> Feel::gradient (Polynomial< Poly, Scalar > const & p)
compute the gradient of a scalar polynomial p
Returns
the gradient of the scalar polynomial
gradient() [2/4]
template<typename Poly > Polynomial<Poly, Tensor2> Feel::gradient (Polynomial< Poly, Vectorial > const & p)
compute the gradient of a vectorial polynomial p
Returns
the gradient of the vectorial polynomial
gradient() [3/4]
template<typename Poly > PolynomialSet<Poly, Vectorial> Feel::gradient (PolynomialSet< Poly, Scalar > const & p)
compute the gradient of a scalar polynomial set
Returns
the gradient of the scalar polynomial set
gradient() [4/4]
template<typename Poly > PolynomialSet<Poly, Tensor2> Feel::gradient (PolynomialSet< Poly, Vectorial > const & p)
compute the gradient of a vectorial polynomial set
Returns
the gradient of the vectorial polynomial set
hasElement()
bool Feel::hasElement (size_type i) const
Returns
true if element with id i is found, false otherwise
Referenced by elementsWithId().
hasFaceWithMarker()
template<typename EltType > bool Feel::hasFaceWithMarker (EltType const & e, boost::any const & flag, std::enable_if_t<(dimension_v< EltType > > 0) &&is_geoelement_v< EltType >> * = nullptr)
Returns
true if the element e has a face with flag, false otherwise
References Feel::GeoElement3D< Dim, GEOSHAPE, T, IndexT, UseMeasuresStorage >::id(), and Feel::GeoElement3D< Dim, GEOSHAPE, T, IndexT, UseMeasuresStorage >::numLocalFaces.
hessian()
template<typename Poly > PolynomialSet<Poly, Tensor2> Feel::hessian (PolynomialSet< Poly, Scalar > const & p)
compute the gradient of a vectorial polynomial set
Returns
the gradient of the vectorial polynomial set
idedelements()
template<typename MeshType > idelements_t<MeshType> Feel::idedelements (MeshType const & mesh, flag_type flag)
Returns
a pair of iterators to iterate over elements with id flag
References markedelementsByType().
idedfaces()
template<typename MeshType > idfaces_t<MeshType> Feel::idedfaces (MeshType const & mesh, size_type id)
Returns
a pair of iterators to iterate over elements with id id
References rank(), and unwrap_ptr().
inner_product() [1/2]
template<typename T > FEELPP_EXPORT type_traits<T>::real_type Feel::inner_product (std::shared_ptr< Vector< T > > const & v1, std::shared_ptr< Vector< T > > const & v2)
Computes the inner product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the inner product of v1 and v2
References Feel::Vector< T, SizeT >::localSize(), and Feel::Vector< T, SizeT >::size().
inner_product() [2/2]
template<typename T > type_traits<T>::real_type Feel::inner_product (Vector< T > const & v1, Vector< T > const & v2)
Computes the inner product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the inner product of v1 and v2
integrate()
template<typename Poly , template< uint16_type > class PsetType> Poly::value_type Feel::integrate (Polynomial< Poly, PsetType > const & p)
integrate a polynomial over a convex
since we use a L2 orthonormal basis, the integral of the polynomial is equal to the first first coefficient of the polynomial
internaledges()
template<typename MeshType > internaledges_t<MeshType> Feel::internaledges (MeshType const & mesh)
Returns
a pair of iterators to iterate over all internal edges of the mesh
References unwrap_ptr().
Referenced by markedpoints().
internalelements()
template<typename MeshType > internalelements_t<MeshType> Feel::internalelements (MeshType const & mesh)
Returns
a pair of iterators to iterate over elements of the mesh which are stricly within the domain that is to say they do not share a face with the boundary
internalElements()
std::tuple<element_reference_wrapper_const_iterator,element_reference_wrapper_const_iterator,elements_reference_wrapper_ptrtype> Feel::internalElements (rank_type p = invalid_rank_type_value) const
Returns
the range of iterator (begin,end) over the internal element on processor p
References invalid_rank_type_value, and Feel::WorldComm::localRank().
internalfaces()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> internalfaces_t<MeshType> Feel::internalfaces (MeshType const & mesh)
Returns
a pair of iterators to iterate over all internal faces of the mesh belong to process domain __pid
internalpoints()
template<typename MeshType > internalpoints_t<MeshType> Feel::internalpoints (MeshType const & mesh)
Returns
the range of iterators [begin,end] over the internal(not on the boundary) points of the mesh
Warning
this filter is not parallelized
interpolate()
template<typename SpaceType , typename FunctionType , typename InterpType > void Feel::interpolate (std::shared_ptr< SpaceType > const & space, FunctionType const & f, InterpType & interp)
Given a space space using a lagrange basis, compute the interpolation interp of f belonging to another function space.
FunctionSpace<mesh_type,fusion::vector<Whatever> > Yh;
FunctionSpace<mesh_type,fusion::vector<Whatever> >::element_type f;
FunctionSpace<mesh_type,fusion::vector<Lagrange<> > > Xh;
FunctionSpace<mesh_type,fusion::vector<Lagrange<> > >::element_type u;
interpolate(Xh, f, u);
References intersect().
interprocessfaces() [1/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> interprocessfaces_t<MeshType> Feel::interprocessfaces (MeshType const & mesh)
Returns
a pair of iterators to iterate over all interprocess faces of the mesh belonging to process __pid
interprocessfaces() [2/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> interprocessfaces_t<MeshType> Feel::interprocessfaces (MeshType const & mesh, rank_type neighbor_pid)
Returns
a pair of iterators to iterate over all interprocess faces of the mesh belonging to process __pid
intersect()
template<typename IteratorType , typename... Args> FEELPP_EXPORT Feel::intersect_t<IteratorType> Feel::intersect (IteratorType && it, Args &&... args)
this function takes a set of iterators over geometrical entities of the same type (e.g.
faces, volumes, edges, points) and generate a data structure that will hold the corresponding reference of mesh elements. This data structure can then be used to iterate over meshes like other mesh filters.
// the following code below intersection of internal elements with marked elements omega
auto subset = intersect(internalelements(mesh), markedelements(mesh,"omega"));
// it can then be used eg to create a submesh
auto submesh = createSubmesh(mesh, subset);
Referenced by interpolate().
inv()
template<typename OpType > std::shared_ptr<OperatorInverse<OpType> > Feel::inv (std::shared_ptr< OpType > M)
Parameters
op an operator
l label of the operator
transpose boolean to say wether we want the matrix or its transpose
Returns
the Operator associated to the matrix M
References Feel::OperatorBase< operator_type::value_type >::setLabel().
ipow()
constexpr int64_t Feel::ipow (int64_t base, int exp, int64_t result = 1) constexpr
compute integer power
uint64_t i = ipow(2, 3);
References exp().
is_finite()
template<typename Derived > bool Feel::is_finite (const Eigen::MatrixBase< Derived > & x)
Returns
true is the matrix has no Inf, false otherwise
Referenced by is_nan().
is_nan()
template<typename Derived > bool Feel::is_nan (const Eigen::MatrixBase< Derived > & x)
Returns
true is matrix has no NaN, false otherwise
References is_finite().
isEmpty()
virtual bool Feel::isEmpty () const virtual
Returns
true if the container is empty, false otherwise
Referenced by Feel::Mesh2D< Shape, T, IndexT >::numElements(), Feel::Mesh3D< Shape, T, IndexT >::numElements(), Feel::Mesh1D< Shape, T, IndexT >::numElements(), and Feel::Mesh0D< Shape, T, IndexT >::numElements().
loadXYFromCSV()
std::map<double,double> Feel::loadXYFromCSV (std::string const & filename, std::string const & abscissa, std::string const & ordinate)
load a XY dataset from a CSV file
Parameters
filename name of the CSV file
abscissa name of the column to be used as X
ordinate name of the column to be used as Y
Returns
the map<key,value> {X,Y} here is an example
// load the columns "time" and "ft" into a map<>
auto m = loadXYFromCSV("data.csv", "time", "ft");
makeMesh()
template<class T , class... Args> decltype(auto) Feel::makeMesh (Args &&... args)
See also
makeSharedMesh
makeSharedMatrixCondensed()
template<class T , class... Args> condensed_matrix_ptr_t<T> Feel::makeSharedMatrixCondensed (Args &&... args)
Create a shared pointer MatrixCondensed<T> from Args.
// create a MatrixCondensed std::shared_ptr
auto mc = makeSharedMatrixCondensed<double>();
makeSharedMesh()
template<class T , class... Args> std::shared_ptr<Mesh<T> > Feel::makeSharedMesh (Args &&... args)
Create a shared pointer Mesh<T> from Args.
// create a tetrahedron mesh std::shared_ptr
auto mesh = makeSharedMesh<Simplex<3>>();
makeSharedVectorCondensed()
template<class T , class... Args> condensed_vector_ptr_t<T> Feel::makeSharedVectorCondensed (Args &&... args)
Create a shared pointer VectorCondensed<T> from Args.
// create a VectorCondensed std::shared_ptr
auto mc = makeSharedVectorCondensed<double>();
makeUniqueMesh()
template<class T , class... Args> std::unique_ptr<Mesh<T> > Feel::makeUniqueMesh (Args &&... args)
Create a unique pointer Mesh<T> from Args.
// create a tetrahedron mesh std::unique_ptr
auto mesh = makeUniqueMesh<Simplex<3>>();
marked2elements()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> marked2elements_t<MeshType> Feel::marked2elements (MeshType const & mesh, boost::any const & markersFlag)
Returns
a pair of iterators to iterate over elements of the mesh with Marker2 string
marked3elements()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> marked3elements_t<MeshType> Feel::marked3elements (MeshType const & mesh, boost::any const & markersFlag)
Returns
a pair of iterators to iterate over elements of the mesh with Marker3 string
markededgesByType()
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> markededges_t<MeshType> Feel::markededgesByType (MeshType const & mesh, uint16_type markerType, typename std::enable_if< is_3d< MeshType >::value >::type * = nullptr)
Returns
a pair of iterators to iterate over edges of the mesh marked with __marker
Parameters
mesh a mesh data structure
__marker a marker that identifies edges
__pid process id
Returns
a pair of iterators (begin,end) for the set of marked edges
markedelements() [1/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> markedelements_t<MeshType> Feel::markedelements (MeshType const & mesh)
Returns
a pair of iterators to iterate over elements of the mesh with marker
markedelements() [2/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> markedelements_t<MeshType> Feel::markedelements (MeshType const & mesh, boost::any const & markersFlag)
Returns
a pair of iterators to iterate over elements of the mesh with marker flag
markedelementsByType() [1/3]
template<typename MeshType > markedelements_t<MeshType> Feel::markedelementsByType (MeshType const & mesh, uint16_type markerType)
Returns
a pair of iterators to iterate over elements of the mesh with marker flag
Referenced by faces(), and idedelements().
markedelementsByType() [2/3]
template<typename MeshType > markedelements_t<MeshType> Feel::markedelementsByType (MeshType const & mesh, uint16_type markerType, boost::any const & markersFlag)
Returns
a pair of iterators to iterate over elements of the mesh with marker flag
markedelementsByType() [3/3]
template<typename MeshType > markedelements_t<MeshType> Feel::markedelementsByType (MeshType const & mesh, uint16_type markerType, std::initializer_list< boost::any > const & markersFlag)
Returns
a pair of iterators to iterate over elements of the mesh with marker flag
markedfaces() [1/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> markedfaces_t<MeshType> Feel::markedfaces (MeshType const & mesh)
Returns
a pair of iterators to iterate over faces of the mesh marked
Parameters
mesh a mesh data structure
__pid process id
Returns
a pair of iterators (begin,end) for the set of marked faces
markedfaces() [2/2]
template<typename MeshType , std::enable_if_t< std::is_base_of_v< MeshBase<>, unwrap_ptr_t< MeshType >>, int > = 0> markedfaces_t<MeshType> Feel::markedfaces (MeshType const & mesh, boost::any const & markersFlag)
Returns
a pair of iterators to iterate over faces of the mesh marked with __marker
Parameters
mesh a mesh data structure
markersFlag a marker that identifies faces
Returns
a pair of iterators (begin,end) for the set of marked faces
markedpoints() [1/2]
template<typename MeshType > markedpoints_t<MeshType> Feel::markedpoints (MeshType const & mesh)
Returns
a pair of iterators to iterate over points of the mesh marked
Parameters
mesh a mesh data structure
__pid process id
Returns
a pair of iterators (begin,end) for the set of marked points
References internaledges().
markedpoints() [2/2]
template<typename MeshType > markedpoints_t<MeshType> Feel::markedpoints (MeshType const & mesh, boost::any const & markersFlag)
Parameters
mesh a mesh data structure
markersFlag a marker that identifies points
Returns
the range of iterators [begin,end,container] over the marked points with flag of the mesh
measurePointElements()
template<typename MeshType > auto Feel::measurePointElements (std::shared_ptr< FunctionSpace< MeshType, bases< Lagrange< MeshType::nOrder, Scalar > > > > & Xh) -> decltype(Xh->element())
Given a function space Xh, compute the sum of of the measure of the elements shared by a point in the mesh.
This is helfpul for example for a posteriori error estimation.
nelements() [1/4]
template<typename MT , typename Iterator > size_type Feel::nelements (boost::tuple< MT, Iterator, Iterator > const & its, bool global = false, worldcomm_t const & worldComm = Environment::worldComm())
Returns
the number of elements given element iterators constructed using the mesh filters
Parameters
its the mesh iterators
global all reduce number of elements if set to true
The following code prints in the logfile the number of elements in the mesh that are marked with marker1 equal to 1:
LOG(INFO) << "number of elements = " << nelements(markedelements(mesh,1)) << "\n";
nelements() [2/4]
template<typename MT , typename Iterator , typename Container > size_type Feel::nelements (boost::tuple< MT, Iterator, Iterator, Container > const & its, bool global = false, worldcomm_t const & worldComm = Environment::worldComm())
Returns
the number of elements given element iterators constructed using custom range
Parameters
its the mesh iterators
global all reduce number of elements if set to true
The following code prints in the logfile the number of elements in the mesh that are marked with marker1 equal to 1:
LOG(INFO) << "number of elements = " << nelements(myCustomRange) << "\n";
References worldComm().
nelements() [3/4]
template<typename MT , typename Iterator > size_type Feel::nelements (std::list< boost::tuple< MT, Iterator, Iterator > > const & its, bool global = false, worldcomm_t const & worldComm = Environment::worldComm())
Returns
the number of elements given element iterators constructed using the mesh filters
Parameters
a list of mesh iterators
global all reduce number of elements if set to true
The following code prints in the logfile the number of elements in the mesh that are marked with marker1 equal to 1:
LOG(INFO) << "number of elements = " << nelements(markedelements(mesh,{1,2,3})) << "\n";
References boundarypoints().
nelements() [4/4]
template<typename MT , typename Iterator , typename Container > size_type Feel::nelements (std::list< boost::tuple< MT, Iterator, Iterator, Container > > const & its, bool global = false, worldcomm_t const & worldComm = Environment::worldComm())
Returns
the number of elements given element iterators constructed using custom range
Parameters
a list of mesh iterators
global all reduce number of elements if set to true
The following code prints in the logfile the number of elements in the mesh that are marked with marker1 equal to 1:
LOG(INFO) << "number of elements = " << nelements(markedelements(mesh,{1,2,3})) << "\n";
newVectorBlocks()
template<typename Arg1 , typename ... Args> BlocksBaseVector<typename decay_type<Arg1>::value_type> Feel::newVectorBlocks (const Arg1 & arg1, const Args &... args)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
Variadic template is used to handle an arbitrary number of function spaces. The blocks are organized then matrix wise with the stencil associated of pairs of function spaces in (arg1,...,argn)
nsrQ()
template<typename MeshType > Pdh_element_t<MeshType,0> Feel::nsrQ (std::shared_ptr< MeshType > const & m)
Return the normalized shape ratio (NSR) for a given element.
it is referred as the radius ratio, as it is described by the ratio between the inradius (r) and the circumradius (R). \(\rho = \frac{dr}{R}\) where d is the dimension
References elements().
op()
template<typename MatrixType > std::shared_ptr<OperatorMatrix<typename MatrixType::value_type> > Feel::op (std::shared_ptr< MatrixType > M, std::string label, bool transpose = false)
Parameters
M matrix
l label of the operator
transpose boolean to say wether we want the matrix or its transpose
Returns
the Operator associated to the matrix M
operator<<() [1/2]
FEELPP_EXPORT std::ostream& Feel::operator<< (std::ostream & os, AboutData const & about)
outpout stream an AboutData structure
Parameters
os ostream to use to stream the about data
about data to stream
Returns
the ostream
operator<<() [2/2]
template<typename A0 , typename A1 , typename A2 , typename A3 , typename A4 > std::ostream& Feel::operator<< (std::ostream & os, FunctionSpace< A0, A1, A2, A3, A4 > const & Xh)
iostream operator to print some information about the function space Xh
auto Xh = Pch<2>(mesh);
// Xh is a pointer
std::cout << "Xh:" << *Xh << "\n";
operatorSteklPc()
template<typename space_type > std::shared_ptr< OperatorSteklovPc<space_type> > Feel::operatorSteklPc (std::shared_ptr< space_type > const & space, typename OperatorSteklovPc< space_type >::backend_ptrtype const & backend = Backend<double>::build(BACKEND_PETSC))
this function returns a OperatorSteklovPc shared_ptr with
Parameters
pace
backend
operatorTrace()
template<typename self_type > std::shared_ptr< OperatorTrace<self_type> > Feel::operatorTrace (std::shared_ptr< self_type > const & domainspace)
this function returns a OperatorTrace shared_ptr with
Parameters
traceSpace
References Feel::vf::trace().
opLagrangeP1_impl()
template<typename space_type > std::shared_ptr<OperatorLagrangeP1<space_type> > Feel::opLagrangeP1_impl (std::shared_ptr< space_type > const & Xh, typename OperatorLagrangeP1< space_type >::backend_ptrtype const & backend, std::string pathMeshLagP1, std::string prefix, bool rebuild, bool parallel, size_type meshUpdate)
Returns
the P1 Lagrange adaptor associated to the space Xh
partitionMesh()
template<typename MeshType > std::unique_ptr<MeshPartitionSet<MeshType> > Feel::partitionMesh (std::shared_ptr< MeshType > mesh, rank_type nGlobalParts, std::vector< elements_reference_wrapper_t< MeshType >> partitionByRange = std::vector<elements_reference_wrapper_t<MeshType>>())
partition a mesh and provide a helper data struct navigate in the newly partitioned mesh
Returns
a std::unique_ptr to a MeshPartitionSet
References Feel::Partitioner< MeshType >::partition().
points()
template<typename MeshType > points_pid_t<MeshType> Feel::points (MeshType const & mesh)
Returns
the range of iterators [begin,end] over the points of the mesh
Warning
this filter is not parallelized
Referenced by Feel::PointSetQuadrature< Hypercube< 2, 1 >, T >::fpoint(), and Feel::GeoMap< Dim, Order, RealDim, T, Entity, PP >::transform().
polyfit()
template<typename T > FEELPP_EXPORT std::vector<T> Feel::polyfit (const std::vector< T > & xv, const std::vector< T > & yv, int order = 1)
compute least square (or interpolation) fitting polynomial
Parameters
xv x parameter values
yv y parameter values
order order of the least square (or interpolation) fitting polynomial
Note: . xv.size() == order+1 then it is interpolation, . xv.size() > order+1 then it is least square fitting
prod()
template<typename ElementType > ElementType Feel::prod (ElementType const & v1, ElementType const & v2, typename boost::enable_if< boost::is_base_of< FunctionSpaceBase::ElementBase, ElementType > >::type * dummy = 0)
Computes the element wise product of two vectors and eventually in parallel.
Parameters
v1 vector (eventually distributed)
v2 vector (eventually distributed)
Returns
the element wise product of v1 and v2
Referenced by Feel::CRB< TruthModelType >::printErrorsDuringRbConstruction().
product()
template<typename... SpaceList> ProductSpaces<SpaceList...> Feel::product (SpaceList... spaces)
compile time product of function spaces
Parameters
spaces expansion of arbitrary number of spaces
Returns
the compile time product
product2() [1/2]
template<typename T , typename... SpaceList> ProductSpaces2<T,SpaceList...> Feel::product2 (SpaceList... spaces, std::shared_ptr< ProductSpace< T, true >> const & ps)
mixed compile time and runtime product of function space
Parameters
spaces expansion of arbitrary number of function spaces
ps dynamic product of function spaces of the same type
Returns
the space product
product2() [2/2]
template<typename T , typename... SpaceList> ProductSpaces2<T,SpaceList...> Feel::product2 (std::shared_ptr< ProductSpace< T, true >> const & ps, SpaceList... spaces)
mixed compile time and runtime product of function space
Parameters
spaces expansion of arbitrary number of function spaces
ps dynamic product of function spaces of the same type
Returns
the space product
project()
template<typename Pset , typename Func , typename IM > Polynomial<Pset, Scalar> Feel::project (Pset const & pset, Func const & f, IM const & im)
\(L_2\) Projection over the associated convex of a function f onto a scalar polynomial set.
Returns
the polynomial with the same basis as the polynomial set and with coeff \(\sum_q w_q f_q \phi_q \)
Referenced by Feel::VectorUblas< double >::add(), element_product(), Feel::PolynomialSet< Poly, PolySetType >::polynomialsRange(), and Feel::PolynomialSet< Poly, PolySetType >::polynomialsUpToDimension().
projector()
template<typename TDomainSpace , typename TDualImageSpace > std::shared_ptr< Projector<TDomainSpace, TDualImageSpace> > Feel::projector (std::shared_ptr< TDomainSpace > const & domainspace, std::shared_ptr< TDualImageSpace > const & imagespace, typename Projector< TDomainSpace, TDualImageSpace >::backend_ptrtype const & abackend = Backend<double>::build(soption(_name="backend")), ProjectorType proj_type = L2, double epsilon = 0.01, double gamma = 20, DirichletType dirichlet_type = WEAK)
this function returns a Projector shared_ptr with
Parameters
domainSpace
imageSpace
backend
pyexprFromFile()
void Feel::pyexprFromFile (std::string const & pyfilename, std::map< std::string, std::string > & locals)
evaluate python code from file pyfilename using local variables locals and retrieve dictionary of Feel++ expressions expressions are of the form : f(x,y,z):x:y:z
locals allows to set some input variables for the python code and stores the output variables that are required by the c++ code.
Note
that if the python expression to be retrieved is a sympy expression then the expression is transformed into an expression that is then compiled and loaded as a plugin.
we start with ta test without any input variable (eg locals is empty)
// no locals
std::map<std::string,string> locals={};
pyexprFromFile(filename, locals);
We define now some input data
// no locals
std::map<std::string,string> locals={{"dim","3"}};
pyexprFromFile(filename, locals);
for(auto d : locals) cout << d.first << ":" << d.second << std::endl;
randint()
template<typename T > FEELPP_EXPORT std::vector<T> Feel::randint (int N, T min, T max)
Returns
a vector of N random integers between [min and max], min and max included
rank()
template<typename C > auto Feel::rank (C const & c)
Returns
the local MPI rank of the data structure c
Referenced by Feel::DofTable< MeshType, FEType, PeriodicityType, MortarType >::buildGhostDofMap(), idedfaces(), and Feel::PolynomialSet::PreCompute::PreCompute().
readHBF()
template<typename T > holo3_image<T> Feel::readHBF (std::string const & s)
read an HBF file containing an array of floats
Parameters
s file name
Returns
eigen array of type T
real_dimension()
template<typename T > constexpr int Feel::real_dimension (T const & t) constexpr
Returns
real dimension of a type T
Referenced by Feel::Hypercube< Dim, Order, RDim >::dimension(), and Feel::Simplex< 1, Dim >::dimension().
reserveNumberOfElement()
void Feel::reserveNumberOfElement (size_type nElt)
reserve size of container
Parameters
nElt : the size reserved
sanitize()
std::vector<std::string> Feel::sanitize (std::vector< std::string > const & s)
trim a vector of strings removing all leading and trailing spaces and replace all special characters " ;:," inside the block by a _
Parameters
s a vector of strings
scale()
template<typename OpType > std::shared_ptr<OperatorScale<OpType> > Feel::scale (std::shared_ptr< OpType > M, typename OpType::value_type s)
Parameters
op an operator
s a scalar
Returns
the operator which is the scaling of op by s
Referenced by BOOST_PARAMETER_FUNCTION(), and Feel::VectorUblas< double >::operator*=().
solvereigen_options()
po::options_description Feel::solvereigen_options (std::string const & prefix = "")
defines solver eigen options
The prefix parameter allows to set different eigensolver options for different eigensolver. It allows to distinguish between these options
// register two slepc eigensolver options
add_options(solvereigen_options("eigen1")).add_options(solvereigen_options("eigen2"));
// build an eigen solver associated with option set eigen1
SolverEigen<double>::build(vm, "eigen1");
Parameters
prefix prefix allows to prefix options
spy()
template<typename MatrixType > void Feel::spy (MatrixType const & __m, std::string const & filename)
Dump vector to file in Matlab format and spy.
straightenMesh()
template<typename MeshType > std::shared_ptr<MeshType> Feel::straightenMesh (std::shared_ptr< MeshType > mesh, worldcomm_ptr_t const & worldcomm, bool refine, bool save)
straighten the internal faces of a high order mesh
mesh mesh data structure
Referenced by BOOST_PARAMETER_FUNCTION().
subelements()
template<typename EltType > fusion::result_of::accumulate<typename EltType::functionspace_type::functionspace_vector_type, fusion::vector<>, Feel::detail::CreateElementVector<EltType> >::type Feel::subelements (EltType const & e, std::vector< std::string > const & n)
extract subelements from an element of a product of spaces
Parameters
e an element of a product of spaces
n a vector of string to name the sub elements
Returns
a vector of subelements
support()
template<typename SpaceT , typename = std::enable_if_t<is_functionspace_v<SpaceT>>> constexpr SpaceT::template GetMeshSupport<typename SpaceT::mesh_ptrtype,0>::ptrtype Feel::support (std::shared_ptr< SpaceT > const & X) constexpr
Returns
the support of a function space
toPETSc() [1/4]
template<typename T , typename SizeT = uint32_type> std::shared_ptr<BackendPetsc<T,SizeT> > Feel::toPETSc (std::shared_ptr< Backend< T, SizeT >> const & b)
returns a BackendPetsc shared_ptr from a Backend.
if the cast fails then it is a null shared_ptr
here is a sample code:
auto b = backend(); // default backend is petsc type
if (auto bp = toPETSc(b)) // bp is BackendPetsc
{
  // use BackendPetsc interface
}
else // bp is a null shared_ptr and evaluates to false in the if above
{
  // it was not a BackendPetsc
}
toPETSc() [2/4]
template<typename T > std::shared_ptr<MatrixPetsc<T> > Feel::toPETSc (std::shared_ptr< MatrixSparse< T >> const & m)
returns a MatrixPetsc shared_ptr from a Matrix if it was a MatrixPetsc if the cast fails then it is a null shared_ptr
here is a sample code:
auto b = backend(); // default backend is petsc type
auto v = b->newMatrix();
if (auto vp = toPETSc(v)) // bp is MatrixPetsc
{
  // use MatrixPetsc interface
}
else // bp is a null shared_ptr and evaluates to false in the if above
{
  // it was not a MatrixPetsc
}
toPETSc() [3/4]
template<typename T > std::shared_ptr<PreconditionerPetsc<T> > Feel::toPETSc (std::shared_ptr< Preconditioner< T >> const & p)
returns a PreconditionerPetsc shared_ptr from a Preconditioner if it was a PreconditionerPetsc if the cast fails then it is a null shared_ptr
here is a sample code:
auto b = backend(); // default backend is petsc type
 if ( auto vp = toPETSc( b->preconditioner() ) ) // vp is PreconditionerPetsc
{
  // use PreconditionerPetsc interface
}
else // bp is a null shared_ptr and evaluates to false in the if above
{
  // it was not a PreconditionerPetsc
}
toPETSc() [4/4]
template<typename T > std::shared_ptr<VectorPetsc<T> > Feel::toPETSc (std::shared_ptr< Vector< T >> const & v)
returns a VectorPetsc shared_ptr from a Vector if it was a VectorPetsc if the cast fails then it is a null shared_ptr
here is a sample code:
auto b = backend(); // default backend is petsc type
auto v = b->newVector();
if (auto vp = toPETSc(v)) // bp is VectorPetsc
{
  // use VectorPetsc interface
}
else // bp is a null shared_ptr and evaluates to false in the if above
{
  // it was not a VectorPetsc
}
type_space_t()
template<typename T > constexpr hana::integral_constant<int,(decay_type<T>::nSpaces == 1)?1:2> Feel::type_space_t (T && t) constexpr
Returns
single_space_t if the space is not a cartesian product, multiple_space_t otherwise
type_spaces_t()
template<typename T1 , typename T2 > constexpr hana::integral_constant<int,(decay_type<T1>::nSpaces == 1 && decay_type<T2>::nSpaces == 1)?1:2> Feel::type_spaces_t (T1 && t1, T2 && t2) constexpr
Returns
single_spaces_t if the spaces aren't cartesian products, multiple_space_t otherwise
unite()
template<typename P , template< uint16_type > class Type, template< class, template< uint16_type > class > class Poly1, template< class, template< uint16_type > class > class Poly2> PolynomialSet<P, Type> Feel::unite (Poly1< P, Type > const & pset1, Poly2< P, Type > const & pset2)
union of two polynomial sets P1 and P2 : \(P_1 \oplus P_2\)
Returns
the union of the two sets by appending the coefficient and computing the range of the resulting set
unwrap_ptr()
template<typename C > unwrap_ptr_t<C> const& Feel::unwrap_ptr (C const & c)
Returns
the c++ objet pointed by c++ pointer or shared_ptr or same object otherwise
Referenced by boundarypoints(), expansion(), idedfaces(), internaledges(), Feel::DEIMBase< ModelType::parameterspace_type, ModelType::space_type, TensorType >::saveDB(), and worldComm().
vectorBlocks()
template<typename Arg1 , typename ... Args> BlocksBaseVector<typename decay_type<Arg1>::value_type> Feel::vectorBlocks (const Arg1 & arg1, const Args &... args, std::enable_if_t< std::is_base_of< ProductSpacesBase, std::remove_reference_t< Arg1 >>::value > * = nullptr)
Build blocks of CSR graphs with function spaces (args1,args2,argn).
Variadic template is used to handle an arbitrary number of function spaces. The blocks are organized then matrix wise with the stencil associated of pairs of function spaces in (arg1,...,argn)
worldComm()
template<size_t S, class ITERATOR , class CONTAINER > WorldComm const& Feel::worldComm (boost::tuple< mpl::size_t< S >, ITERATOR, ITERATOR, CONTAINER > const & range)
Returns
the worldcomm associated to the mesh stored in the range
References edges(), invalid_rank_type_value, and unwrap_ptr().
Referenced by Feel::Exporter< mesh_t >::addPath(), Feel::StaticCondensation< T, IndexT >::block(), Feel::DofTable< MeshType, FEType, PeriodicityType, MortarType >::buildGhostDofMap(), Feel::ExporterEnsight< MeshType, N >::ExporterEnsight(), Feel::ExporterEnsightGold< MeshType, N >::ExporterEnsightGold(), Feel::Bdf< fluid_space_type >::initialize(), nelements(), Feel::Mesh< Hypercube< 2 > >::numGlobalEdges(), and Feel::Exporter< mesh_t >::setOptions().
writeHBF()
template<typename T > void Feel::writeHBF (std::string const & s, holo3_image< T > const & x)
write a HBF file containing an array of floats
Parameters
s file name
x eigen array of type T
Variable Documentation
eigs
BOOST_PP_REPEAT_1_BOOST_PP_REM BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_IIF_0 BOOST_PP_IIF_BOOST_PP_BOOL_BOOST_PP_IIF_0 BOOST_PP_NIL BOOST_PP_IIF_0 BOOST_PP_IIF_0 Feel::eigs
solve for \(A x =\lambda B x\)
Parameters
A sparse matrix
B sparse matrix
ncv number of converged eigen values (dimension of Krylov space)
nev number of eigen values
backend type of backend (default BACKEND_PETSC)
solver type of solver (default KRYLOVSCHUR)
problem type of problem (default GHEP)
transform type of spectral transform (default SHIFT)
spectrum type of eigenvalue (default LARGEST_MAGNITUDE)
maxit number of maximum iterations
tolerance tolerance for the eigenvalue solver (default 1e-11)
Returns
eigen modes
EXTRACTION_KEEP_ALL_IDS
const size_type Feel::EXTRACTION_KEEP_ALL_IDS
Initial value:
= (EXTRACTION_KEEP_POINTS_IDS |
                                            EXTRACTION_KEEP_EDGES_IDS |
                                            EXTRACTION_KEEP_FACES_IDS |
                                            EXTRACTION_KEEP_VOLUMES_IDS )
is_geoelement_v
template<typename... T> constexpr bool Feel::is_geoelement_v = is_geoelement<T...>::value constexpr
Helper variable template.
Returns
true is T is a GeoElement<n>D at compilation time, false otherwise
is_reference_convex_v
template<typename... T> constexpr bool Feel::is_reference_convex_v = is_reference_convex<T...>::value constexpr
Helper variable template.
Returns
true is T is a Reference convex at compilation time, false otherwise