Feel++: /nvme0/prudhomm/actions-runner/_work/feelpp/feelpp/feelpp/feel/feelvf/norm.hpp File Reference
norm.hpp File Reference
Namespaces
namespace Feel
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*-
Functions
template<typename ExprL , typename ExprR >
auto Feel::vf::ddot (ExprL l, ExprR r) -> decltype(trace(trans(l) *r))
double dot product of the left and right expressions
template<typename ExprL , typename ExprR >
auto Feel::vf::outer_prod (ExprL l, ExprR r) -> decltype(l *trans(r))
inner product of the left and right expressions
Detailed Description
Author
Christophe Prud'homme chris.nosp@m.toph.nosp@m.e.pru.nosp@m.dhom.nosp@m.me@fe.nosp@m.elpp.nosp@m..org
Date
2010-04-17
Function Documentation
ddot()
template<typename ExprL , typename ExprR > auto Feel::vf::ddot (ExprL l, ExprR r) -> decltype(trace(trans(l) * r))
double dot product of the left and right expressions
Note
it handles matricial(rank 2 tensors) expressions
Returns
the double dot product \((l : r)\)
References Feel::vf::ddot(), Feel::vf::trace(), and Feel::vf::trans().
Referenced by Feel::vf::ddot().
outer_prod()
template<typename ExprL , typename ExprR > auto Feel::vf::outer_prod (ExprL l, ExprR r) -> decltype(l * trans(r))
inner product of the left and right expressions
Note
it handles vectorial expressions
Returns
the inner product \((l * r^T)\)
References Feel::vf::outer_prod(), and Feel::vf::trans().
Referenced by Feel::vf::outer_prod().