Feel++: nlohmann::json_sax< BasicJsonType > Struct Template Reference
nlohmann::json_sax< BasicJsonType > Struct Template Reference abstract
Description
template<typename BasicJsonType>
struct nlohmann::json_sax< BasicJsonType >
SAX interface.
This class describes the SAX interface used by nlohmann::json::sax_parse. Each function is called in different situations while the input is parsed. The boolean return value informs the parser whether to continue processing the input.
Public Types
using binary_t = typename BasicJsonType::binary_t
using number_float_t = typename BasicJsonType::number_float_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using string_t = typename BasicJsonType::string_t
Public Member Functions
virtual bool binary (binary_t &val)=0
a binary value was read
virtual bool boolean (bool val)=0
a boolean value was read
virtual bool end_array ()=0
the end of an array was read
virtual bool end_object ()=0
the end of an object was read
json_sax (const json_sax &)=default
json_sax (json_sax &&) noexcept=default
virtual bool key (string_t &val)=0
an object key was read
virtual bool null ()=0
a null value was read
virtual bool number_float (number_float_t val, const string_t &s)=0
a floating-point number was read
virtual bool number_integer (number_integer_t val)=0
an integer number was read
virtual bool number_unsigned (number_unsigned_t val)=0
an unsigned integer number was read
json_sax & operator= (const json_sax &)=default
json_sax & operator= (json_sax &&) noexcept=default
virtual bool parse_error (std::size_t position, const std::string &last_token, const detail::exception &ex)=0
a parse error occurred
virtual bool start_array (std::size_t elements)=0
the beginning of an array was read
virtual bool start_object (std::size_t elements)=0
the beginning of an object was read
virtual bool string (string_t &val)=0
a string value was read
Member Function Documentation
binary()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::binary (binary_t & val) pure virtual
a binary value was read
Parameters
[in] val binary value
Returns
whether parsing should proceed
Note
It is safe to move the passed binary value.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
boolean()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::boolean (bool val) pure virtual
a boolean value was read
Parameters
[in] val boolean value
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
end_array()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::end_array () pure virtual
the end of an array was read
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
end_object()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::end_object () pure virtual
the end of an object was read
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
key()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::key (string_t & val) pure virtual
an object key was read
Parameters
[in] val object key
Returns
whether parsing should proceed
Note
It is safe to move the passed string.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
null()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::null () pure virtual
a null value was read
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
number_float()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::number_float (number_float_t val, const string_t & s) pure virtual
a floating-point number was read
Parameters
[in] val floating-point value
[in] s raw token value
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
number_integer()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::number_integer (number_integer_t val) pure virtual
an integer number was read
Parameters
[in] val integer value
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
number_unsigned()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::number_unsigned (number_unsigned_t val) pure virtual
an unsigned integer number was read
Parameters
[in] val unsigned integer value
Returns
whether parsing should proceed
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
parse_error()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::parse_error (std::size_t position, const std::string & last_token, const detail::exception & ex) pure virtual
a parse error occurred
Parameters
[in] position the position in the input where the error occurs
[in] last_token the last read token
[in] ex an exception object describing the error
Returns
whether parsing should proceed (must return false)
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
start_array()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::start_array (std::size_t elements) pure virtual
the beginning of an array was read
Parameters
[in] elements number of array elements or -1 if unknown
Returns
whether parsing should proceed
Note
binary formats may report the number of elements
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
start_object()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::start_object (std::size_t elements) pure virtual
the beginning of an object was read
Parameters
[in] elements number of object elements or -1 if unknown
Returns
whether parsing should proceed
Note
binary formats may report the number of elements
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().
string()
template<typename BasicJsonType > virtual bool nlohmann::json_sax< BasicJsonType >::string (string_t & val) pure virtual
a string value was read
Parameters
[in] val string value
Returns
whether parsing should proceed
Note
It is safe to move the passed string value.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::__attribute__().