Feel++: /nvme0/prudhomm/actions-runner/_work/feelpp/feelpp/feelpp/feel/feelvf/time.hpp File Reference
time.hpp File Reference
Classes
class Feel::vf::TimeExpr< TimeExprT >
struct Feel::vf::TimeExpr< TimeExprT >::HasTestFunction< Func >
struct Feel::vf::TimeExpr< TimeExprT >::HasTrialFunction< Func >
struct Feel::vf::TimeExpr< TimeExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >
struct Feel::vf::TimeExpr< TimeExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >::is_zero
struct Feel::vf::TimeExpr< TimeExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >::sig< Args >
Namespaces
namespace Feel
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*-
Functions
template<typename ExprT >
Expr< TimeExpr< ExprT > > Feel::vf::time (ExprT v, std::string t="")
time an expression during evaluation.
Detailed Description
Author
Christophe Prud'homme chris.nosp@m.toph.nosp@m.e.pru.nosp@m.dhom.nosp@m.me@fe.nosp@m.elpp.nosp@m..org
Date
2014-05-13
Function Documentation
time()
template<typename ExprT > Expr< TimeExpr< ExprT > > Feel::vf::time (ExprT v, std::string t = "")
time an expression during evaluation.
This function is typically used for debugging purposes and it allows to check the numerical results of expressions and sub-expressions.
The following code times the intermediary results of the evaluation of \(\int_\Omega x y\)
auto e = Px()*Py();
std::cout << integrate(_range=elements(mesh), _expr=time(e,"e=")).evaluate();
Returns
the expression that was timeed.
Referenced by Feel::Bdf< SpaceType >::poly(), Feel::FeelModels::ModelMeasuresStorage::restart(), and Feel::FeelModels::ModelMeasuresStorage::save().