Feel++: /nvme0/prudhomm/github-actions/actions-runner-3/_work/feelpp/feelpp/feelpp/feel/feelvf/trans.hpp File Reference
trans.hpp File Reference
Classes
class Feel::vf::Trans< ExprT >
Transpose an scalar, vectorial or matricial expression.
struct Feel::vf::Trans< ExprT >::HasTestFunction< Func >
struct Feel::vf::Trans< ExprT >::HasTrialFunction< Func >
struct Feel::vf::Trans< ExprT >::Lambda< TheExpr >
struct Feel::vf::Trans< ExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >
struct Feel::vf::Trans< ExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >::is_zero
struct Feel::vf::Trans< ExprT >::tensor< Geo_t, Basis_i_t, Basis_j_t >::sig< Args >
Namespaces
namespace Feel
-*- mode: c++; coding: utf-8; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4; show-trailing-whitespace: t -*-
Functions
template<typename ExprT >
Expr< Trans< ExprT > > Feel::vf::trans (ExprT v)
Transpose an expression v.
Detailed Description
Author
Christophe Prud'homme chris.nosp@m.toph.nosp@m.e.pru.nosp@m.dhom.nosp@m.me@fe.nosp@m.elpp.nosp@m..org
Date
2014-05-13
Function Documentation
trans()
template<typename ExprT > Expr< Trans< ExprT > > Feel::vf::trans (ExprT v)
Transpose an expression v.
The expression can be scalar (no-op), vectorial or matricial.
// define a column vector of two element
auto e = vec(Px(),Py());
// transpose it and get a row vector expression of two elements
auto eT = trans(e);
Returns
the transposed expression
References Feel::vf::trans().
Referenced by Feel::vf::ddot(), Feel::vf::outer_prod(), and Feel::vf::trans().