Defining and using expressions
==============================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

The next step is to construct a function space over the mesh. 

== Step by step explanations 

- We start by loading a Mesh in 2D.

[source,c++]
----
auto mesh = loadMesh( _mesh=new Mesh<Simplex<2>> );
----  

- then we define some expression through the command line of config file: `g` is a scalar field and `f` is a vector field, here is an example how to enter them :

[source,bash]
----
./feelpp_tut_myexpression --a=3 --functions.g="a*x*y:x:y:a" --functions.f="{sin(pi*x),cos(pi*y)}:x:y"   
----

You can print back the expression to the screen to check that everything is ok. You want to use as expression `a*x+b*y`, you have to define `a` and `b` as option (either in your code, either in the library).   

- then we compute the gradient of `g` and `f`.   

[source,c++]
----
auto grad_g=grad<2>(g);  
auto grad_f=grad(f);
----    

Notice that template argument are given to `grad`  to specify the shape of the gradient: in the case of $$\nabla g$$, it is $$1\times2$$ and  $$2\times 2$$ for $$\nabla f$$ since we are in 2D.

- then we compute the laplacian of `g`  and `f`.  

[source,c++]
----
auto laplacian_g=laplacian(g);
auto laplacian_f=laplacian(f);
---- 

- then we compute the divergence of `f`.  

[source,c++]
----
auto div_f=div(f);
----  

- and the curl of `f`   

[source,c++]
----
auto curl_f=curl(f);
---- 

- Finally we evaluate these expressions at one point given by the option `x` and `y`.  

== Code

=== Source code

[source,c++]
----
{% include "code/04-myexpression.cpp" %}
----

=== Config file

[source,c++]
----
{% include "code/04-myexpression.cfg" %}
----

=== Compilation and execution

To compile, just use the `make` command in your compilation directory

[source,bash]
----
make feelpp_tut_myexpression   
./feelpp_tut_myexpression  
----

or

[source,c++]
----
./feelpp_tut_myexpression --a=3 --functions.g="<your_function>" --functions.f="<your_function>"
----

== Some results 

We start with the following function $$g=1$$ and $$f=(1,1)$$.

[source,bash]
----
 ./feelpp_tut_myexpression --functions.g=1:x:y --functions.f="{1,1}:x:y"  

g=1
f={1,1}
i=(x-aVal)*y
grad(g)=[[0,0]]
grad(f)=[[0,0],[0,0]]
laplacian(g)=[[0]]
laplacian(f)=[[0],[0]]
div(f)=[[0]]
curl(f)=[[0]]
Evaluation  at  (0,0):
           g(x,y)=1
           f(x,y)=1
1
           i(x,y)=-0
Gradient:
     grad(g)(x,y)=0 0
     grad(f)(x,y)=0 0
0 0
Divergence:
      div(f)(x,y)=0
Curl:
     curl(f)(x,y)=0
Laplacian:
laplacian(g)(x,y)=0
laplacian(f)(x,y)=0
0
----

The symbolic calculus system worked as expected.



