Before reading the following, it is recommended to have a look at:

- link:../GettingStarted/download.adoc[Install Feel++]

- link:../GettingStarted/compiling.adoc[Using Feel++]

Examples, configuration files and geometries can be found https://github.com/feelpp/feelpp-book/tree/master/Tutorial/code[on the github repository].

To try it on your machine, you have to do:

[source,sh]
----
cd your_feelpp_root_source/research
git clone https://github.com/feelpp/feelpp-book
cd your_build_dir
cmake your_feelpp_root_source/ -DFEELPP_ENABLE_RESEARCH_FEELPP-BOOK=ON
cd your_build_dir/research/feelpp-book/Tutorial/code
make 
----


The step by step tutorial is decomposed into :   

- link:01-OutputDirectories.adoc[General information about directories management]

- link:02-SettingUpEnvironment.adoc[Setting up the Feel++ environment]

- link:03-LoadingMesh.adoc[How to handle a mesh]

- link:04-UsingExpressions.adoc[How to manage expressions]

- link:05-EvaluatingFunctions.adoc[Functions evaluation]

- link:06-VisualizingFunctions.adoc[Visualization]

- link:07-SpaceElements.adoc[Functions Spaces]

- link:08-ComputingIntegrals.adoc[Computing integrals]

- link:11-SolveAnEquation.adoc[Solving a partial differential equation]

- link:09-UsingBackend.adoc[Using a backend]

- link:10-Model.adoc[Creating a model]

