ISO 10211:2007 Thermal bridges in building construction
=======================================================

== Introduction

ISO 10211:2007 sets out the specifications for a three-dimensional and a
two-dimensional geometrical model of a thermal bridge for the numerical
calculation of:

 . heat flows, in order to assess the overall heat loss from a building or part of it;
 . minimum surface temperatures, in order to assess the risk of surface condensation.
 
These specifications include the geometrical boundaries and subdivisions of the
model, the thermal boundary conditions, and the thermal values and relationships
to be used.

ISO 10211:2007 is based upon the following assumptions:

 . all physical properties are independent of temperature;
 . there are no heat sources within the building element.
 
ISO 10211:2007 can also be used for the derivation of linear and point thermal
transmittances and of surface temperature factors.

more information link:http://www.iso.org/iso/catalogue_detail.htm?csnumber=40967[here].

== Implementation

Only the 2D specifications have been implemented.

== Running the testcase

[source,sh]
----
$ mpirun -np 4 /usr/local/bin/feelpp_toolbox_heat_2d --config-file thermo2dCase2.cfg
----
