# -*- mode: makefile -*-

all:
	aclocal -I admin
#	autoheader
	automake
	autoconf
	-test -d meta_life_ifp/ && ( cd meta_life_ifp && make -f Makefile.dist)
	-test -d crb/ && ( cd crb && make -f Makefile.dist)

