#!/bin/sh
aclocal -I config --output=config/aclocal.m4
cp -f config/aclocal.m4 .
cp -f config/install-sh .
autoheader
autoconf -I config
#pas de ./ devant les noms des makefiles !!!
automake --gnu --verbose `find . -name Makefile.am | sed -e 's@\./\(.*\)\.am@\1@g'`


