:feelpp: Feel++
= feelpp_mesh_partitioner(1)
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>; Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: feelpp_mesh_partitioner
:man-linkstyle: pass:[blue R < >]


== NAME

{manmanual} - a mesh partitioner for {feelpp}


== SYNOPSIS

{manmanual} --part num [num2...] --ifile file [--dim d] [--json file.json] [--shape s] [--order num] [--by-markers] [--by-markers-desc markers] [--ofile file] [--odir dir]

== DESCRIPTION

{manmanual} is a simple application which can generate a partitioned mesh and
save it in a {feelpp} specific `json+hdf5` file format.

The generated mesh can then be loaded very efficiently in parallel.

=== Options

{manmanual} requires some options.

.Table of command-line {manmanual} options
|===
| Name | Description | Default value

| dim | dimension of the mesh | 3
| shape| shape of the mesh elements | Simplex
| order | mesh geometric order | 1
| by-markers | partitioning on each marker |
| by-markers-desc | partitioning by specifying the markers |
| part | number of desired partitions |
| ifile | name or path to the mesh |
| ofile | output filename prefix (without extension) |
| odir | output directory |
| json | json file that describes the partitioning |
|===

== EXAMPLES

We are now using the `feelpp/feelpp-toolboxes:latest` docker images as described in link:http://book.feelpp.org/user-manual/#getting_started[] to demonstrate {manmanual} usage.
We use the meshes in `src/feelpp/data/gmsh/primitives` in the docker image.
[source,shell]
.Starting the docker `feelpp/feelpp-toolboxes:latest`
----
docker run --rm -ti -v $HOME/feel:/feel feelpp/feelpp-toolboxes
----

=== Generating a single mesh partitioning

We generate a mesh partitioned on 4 cores with the following command

[source,shell]
----
feelpp_mesh_partitioner --part 4  --ifile /usr/share/feelpp/data/geo/torus.geo --odir torus_partitioning   
----

You should have in the current directory 4 files

[source,shell]
----
ls torus_partitioning/
torus_p4.h5  torus_p4.json
----

Now the file `torus_p4.json` can be loaded in a Feel++ application distributed on 4 cores.

NOTE: Others file generated by the application (msh file from geo, log, ...) are located into the app directory (which is controled by `directory` option)

=== Generating multiple mesh partitioning

Often we are interested in a set of partitioned meshes in order to do a speed-up study.
`feelpp_mesh_partitioner` is the right tool for that. Let's consider a set of partitions stem:[\mathcal{P}=\{2, 4, 8, 16, 32 \}].

[source,shell]
----
feelpp_mesh_partitioner --part 2 4 8 16 32  --ifile  /usr/share/feelpp/data/geo/torus.geo --odir torus_partitioning   
----

You should have in the  directory `torus-mesh` (thanks to the `odir` option) 5 partitioned meshes

[source,shell]
----
ls torus_partitioning
torus_p16.h5  torus_p16.json  torus_p2.h5  torus_p2.json  torus_p32.h5  torus_p32.json  torus_p4.h5  torus_p4.json  torus_p8.h5  torus_p8.json
----

NOTE: The mesh filenames contain the partition information.

NOTE: If you want a different prefix than `torus`, like `torus-coarse`, you can use the `--ofile torus-coarse` option and you will have a set of files named `torus-coarse_p*.*` in the `torus_partitioning` directory.

=== Generating a mesh partitioning by markers
1) partitioning of each marker present in the mesh :
[source,shell]
----
feelpp_mesh_partitioner --ifile  toto.geo --by-markers --part 4 8 15 --odir hola
----

2) partitioning of ```marker1``` and partitioning of the union of ```marker2 and marker3``` :
[source,shell]
----
feelpp_mesh_partitioner --ifile toto.geo --by-markers-desc marker1:marker2,marker3 --part 4 8 15  --odir hola
----
In ```by-markers-desc``` option, the ```,``` keyword create an union of the markers and ```:``` keyword allow to split the partitioning regions.

=== Aggregating elements of a mesh

For some numerical methods, it is necessary to aggregate elements that share faces marked with a specific marker.
This is done to 

* avoid these faces are also interprocess faces 
* avoid having degrees of freedom split over different processes

To do so we use the `--json` option to specify the partitioning.

The following code will aggregate the elements of the spheres marked with `CenterSphere`, `LeftSphere` and `RightSphere` in the mesh on the same processor.
The aggregation is done by adding weights to the elements sharing the same face marked with the same marker which then force the graph partitioner to put them on the same processor.

[source,json]
----
{
    "partitioner":
    {
        "aggregates":
        {
            "spheres":{
                "type": "faces",
                "markers": ["CenterSphere","LeftSphere","RightSphere"]
            }
        }
    }
}
----


== SEE ALSO

*{feelpp} Book:* http://book.feelpp.org

== COPYING

Copyright \(C) 2017-2024 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

