:feelpp: Feel++
= feelpp_remotedata(1)
Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: feelpp_remotedata
:man-linkstyle: pass:[blue R < >]


== NAME

{manmanual} - manage remotedata for {feelpp}


== SYNOPSIS

{manmanual} is a simple application which can download data, upload data and print remote data listing.


== DESCRIPTION



== OPTIONS

=== Options

{manmanual} requires some options.

.Table of command-line {manmanual} options
|===
| Name | Description | Default value

| upload | specify the remote server and the location of uploaded files on remote server |
| download | specify remote data to download |
| data a|

* with upload mode : datas path (file or dir) to upload,
* with download mode : the path of downloaded datas
|
| contents | specify data contents to print in the terminal |
|===

== EXAMPLES

=== Download mode

* Download file from an url

[source,shell]
----
feelpp_remotedata --download https://raw.githubusercontent.com/feelpp/feelpp/develop/README.adoc
----

* Download file/folder from Github

[source,shell]
----
feelpp_remotedata --download "github:{repo:feelpp,path:README.adoc}"
----

* Download file/folder from Girder

[source,shell]
----
feelpp_remotedata --download "girder:{file:5b1f8707b0e9570499f66bd0}"
----

* Download into a specific directory

[source,shell]
----
feelpp_remotedata --download "girder:{file:5b1f8707b0e9570499f66bd0}" --data $HOME/mydir
----

=== Upload mode

* Upload file/folder on Girder (require an authentication)

[source,shell]
----
feelpp_remotedata --upload "girder:{folder:<a folder id>}" --data $HOME/mydata
----


=== Contents mode

* With Girder

[source,shell]
----
feelpp_remotedata --contents "girder:{folder:5ac72871b0e9574027047894}"
feelpp_remotedata --contents "girder:{file:5b1f8707b0e9570499f66bd0}"
feelpp_remotedata --contents "girder:{folder:[5ac72871b0e9574027047894,5ad4b75db0e9574027047d70],file:5b1f8707b0e9570499f66bd0}"
----

== REMOTE STORAGE DESCRIPTION

=== Github

|===
| Option | Default value | Description

| `owner` | feelpp | the github organization
| `repo` | feelpp | the github repository in organization
| `branch` | <default in github> | the branch in the git repository
| `path` |  <root of repository> | the path in the git repository
| `token` | <no default value> | an authentication token
|===

=== Girder

|===
| Option | Default value | Description

| `url` | https://girder.math.unistra.fr | url of a Girder platform
| `file` | <no default value> | one or several file id(s)
| `folder` | <no default value> | one or several folder id(s)
| `api_key` | <no default value> | an authentication key
|===


== AUTHENTICATION

=== Github
You need to give a token for access to private repository or increase the for example. Two ways to specify the token :

* Define the environment variable FEELPP_GITHUB_TOKEN.
+
[source,shell]
----
export FEELPP_GITHUB_TOKEN=xxxxx
----
* Add token option in the github description.
+
[source,shell]
----
github:{repo:feelpp,path:README.adoc,token:xxxx}
----

=== Girder
You need to give an api key for access to private data or upload data. Two ways to specify the token :

* Define the environment variable FEELPP_GIRDER_API_KEY.
+
[source,shell]
----
export FEELPP_GIRDER_API_KEY=xxxxx
----
* Add api_key option in the girder description.
+
[source,shell]
----
girder:{folder:5ac72871b0e9574027047894,api_key:xxxx}
----

Remark: another possibility for is to give directly the token generated from an api key (replace api_key by token).
But it's quite difficult to get a token from the web interface of Girder, and you a responsible to delete the token.
With the api key system, the remotedata apps generate and delete token automatically.


== COPYING

Copyright \(C) 2017-2024 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

