:feelpp: Feel++
= feelpp_mesh_partitioner(1)
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>; Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: feelpp_mesh_partitioner
:man-linkstyle: pass:[blue R < >]


== NAME

{manmanual} - a mesh partitioner for {feelpp}


== SYNOPSIS

{manmanual} is a simple application which can generate a partitioned mesh and
save it in a Feel++ specific `json+hdf5` file format.

The generated mesh can then be loaded very efficiently in parallel.


== DESCRIPTION



== OPTIONS

=== Options

{manmanual} requires some options.                                                                                                                                  
.Table of command-line {manmanual} options                                                                                                                          
|===                                                                                                                                                                              
| Name | Description | Default value                                                                                                                                              
| dim | dimension of the mesh | 3                                                                                              
| shape| shape of the mesh elements | Simplex
| part | number of desired partitions |
| ifile | name or path to the mesh |
| ofile | output filename prefix (without extension) |
| odir | output directory |                                                                                                                                                     
|===  

== EXAMPLES

We are now using the `feelpp/toolboxes:latest` docker images as described in link:http://book.feelpp.org/user-manual/#getting_started[] to demonstrate {manmanual} usage.               
We use the meshes in `src/feelpp/data/gmsh/primitives` in the docker image.                                                                                                       
[source,shell]
.Starting the docker `feelpp/toolboxes:latest`
----
docker run --rm -ti -v $HOME/feel:/feel feelpp/toolboxes:latest
----

=== Generating a single mesh partitioning

We generate a mesh partitioned on 4 cores with the following command

[source,shell]
----
feelpp_mesh_partitioner --part 4  --ifile src/feelpp/data/gmsh/primitives/torus.geo --ofile torus
----

You should have in the current directory 4 files

[source,shell]
----
ls torus*
torus.geo  torus.h5  torus.json  torus.msh
----

Now the file `torus.json` can be loaded in a Feel++ application distributed on 4 cores. 

== SEE ALSO

*{feelpp} Book:* http://book.feelpp.org

== COPYING

Copyright \(C) 2017 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

