= {feelpp}partitioner(1)
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>; Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:feelpp: Feel++
:feelpp_: feelpp_
:manmanual: {feelpp}partitioner
:mansource: {feelpp}partitioner
:man-linkstyle: pass:[blue R < >]


== NAME

{feelpp_}partitioner - a mesh partitioner for {feelpp}


== SYNOPSIS

{manmanual} is a simple application which can generate a partitioned mesh and
save it in a Feel++ specific `json+hdf5` file format.

The generated mesh can then be loaded very efficiently in parallel.


== DESCRIPTION



== OPTIONS


== EXAMPLES

We are now using the `feelpp/apps:latest` docker images
as described in link:/GettingStarted/README.adoc[Getting Started] to demonstrate `feelpp_mesh_partitioner` usage.
We use the meshes in `src/feelpp/data/gmsh/primitives` in the docker image.

[source,shell]
.Starting the docker `feelpp/apps:latest`
----
docker run -ti -v $HOME/feel:/feel feelpp/apps:latest
----

=== Generating a single mesh partitioning

We generate a mesh partitioned on 4 cores with the following command

[source,shell]
----
feelpp_mesh_partitioner --part 4  --ifile src/feelpp/data/gmsh/primitives/torus.geo --ofile torus
----

You should have in the current directory 4 files

[source,shell]
----
ls torus*
torus.geo  torus.h5  torus.json  torus.msh
----

Now the file `torus.json` can be loaded in a Feel++ application distributed on 4 cores. 

== SEE ALSO


