:feelpp: Feel++
= {{ toolbox_app }}(1)
Christophe Prud'homme <https://github.com/prudhomm[@prudhomm]>; Vincent Chabannes <https://github.com/vincentchabannes[@vincentchabannes]>
:manmanual: {{ toolbox_app }}
:man-linkstyle: pass:[blue R < >]
v{{ version_string }}: 


== NAME

{{ toolbox_app }} - {{ toolbox_desc }} toolbox application


== SYNOPSIS

----
{{ toolbox_app }} 
  [--{{ toolbox}}.filename  <path to .json specification file>]
  [--config-file <path to .cfg file]
  [--case <directory to model case>] 
  [--case.dim {{ toolbox_default_option_values[0] }}]
  [--case.discretization {{ toolbox_default_option_values[1] }}]
  [--{{ toolbox }}.ksp-monitor=<0,1>]
  [--{{ toolbox }}.ksp-view=<0,1>]
  [--{{ toolbox }}.ksp-type=<see below>]
  [--{{ toolbox }}.pc-view=<0,1>]
  [--{{ toolbox }}.pc-type=<see below>]
  [--{{ toolbox }}.snes-monitor=<0,1>]
  [--{{ toolbox }}.ksp-type=<see below>]
----

== DESCRIPTION

{{ toolbox_app }} is an application which can run {{ toolbox_desc }} model defined by a set of files : a geometry or mesh, a config file(`.cfg`) and  a model file(`.json`)

The execution steps are as follows:

* load the model
* load the mesh
* setup model (materials, initial and boundary condition)
* execute the steady or unsteady simulation
* post-process the results, viewable in paraview or ensight 

=== Options

{{ toolbox_app }} requires some options.

.Table of command-line {{ toolbox_app }} options
|===
| Name | Description | Default value | Possible Values

| case.dim | dimension of problem  | {{ toolbox_default_option_values[0] }} | {{ toolbox_possible_option_values[0] }}
| case.discretization | discretization of problem  | {{ toolbox_default_option_values[1] }} | {{ toolbox_possible_option_values[1] }}
| {{ toolbox }}.filename | path to the .json specification case file  | *no default value* | *required from user*
| {{ toolbox }}.ksp-monitor | monitor the Krylov Subspace iterations  | 0 | 0,1
| {{ toolbox }}.ksp-view | view the Krylov Subspace structure  | 0 | 0,1
| {{ toolbox }}.ksp-type | change the Krylov Subspace method  | `gmres` | link:https://www.mcs.anl.gov/petsc/documentation/linearsolvertable.html[see PETSc documentation]
| {{ toolbox }}.pc-view | view the Krylov Subspace structure  | 0 | 0,1
| {{ toolbox }}.pc-type | change the Krylov Subspace strategy  | `lu` | link:https://www.mcs.anl.gov/petsc/documentation/linearsolvertable.html[see PETSc documentation]
| {{ toolbox }}.snes-monitor | if applicable, monitor the non-linear solver iterations  | 0 | 0,1
| {{ toolbox }}.snes-type | if applicable, change the non-linear solver iterations  | `newtonls` | link:https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESType.html[see PETSc documentation]

|===

NOTE:: 0 as option value means that the option is not enabled, 1 means it is enabled.

== EXAMPLES

We are now using the `feelpp/feelpp-toolboxes:latest` docker images as described in link:http://docs.feelpp.org/user/{{ version_string }}/install/containers/#_docker[] to demonstrate {{ toolbox_app }} usage.

[source,shell]
.Starting the docker `feelpp/feelpp-toolboxes:latest`
----
docker run --rm -ti -v $HOME/feel:/feel ghcr.io/feelpp/feelpp-toolboxes:v{{ version_string }} 
----

[source,shell]
.Explanations about the command line
----
docker run <1>
--rm <2>
-ti <3>
-v $HOME/feel:/feel <4>
feelpp/feelpp-toolboxes <5>
----
<1> run docker executable
<2> remove container from docker once execution is done
<3> run in interactive mode and enter the docker container
<4> mount `$HOME/feel` on host to `/feel/` in docker: the results will be exported there
<5> the docker container to execute, by default it uses the `latest` tag


.Example of a command line to execute {{ toolbox_app }}
----
mpirun --bind-to core -np 10 {{ toolbox_app }} --case {{ toolbox_default_case }}
----

.Explantion of the command line to execute {{ toolbox_app }}
----
mpirun --bind-to core <1>
  -np 10 <2>
 {{ toolbox_appp }} <3>
  --case {{ toolbox_default_case }} <4>
----
<1> execute in parallel using MPI with processes bound to cores
<2> execute in parallel usisng 10 processes
<3> the name of the toolbox application
<4> case directory containing the model files (geometry, config and json). This case file is available remotely on github.

Other test cases can be found

- locally in /usr/share/feelpp/data/testcases/toolboxes/{{ toolbox }}.
- on-line http://docs.feelpp.org/cases/{{ version_doc }}/{{ toolbox_docs }}/README


== RESOURCES

{feelpp} Docs::
http://docs.feelpp.org/toolboxes/{{ version_doc }}/

{feelpp} Cases for {{ toolbox_app }}::
http://docs.feelpp.org/cases/{{ version_doc }}/{{ toolbox_docs }}/README

{feelpp} Toolbox Docs for {{ toolbox_app }}::
http://docs.feelpp.org/toolboxes/{{ version_doc }}/{{ toolbox_docs }}/

== SEE ALSO

{feelpp} Mesh Partitioner::
Mesh partitioner for {feelpp} Toolboxes
http://docs.feelpp.org/user/{{ version_doc }}/using/mesh_partitioner/


{feelpp} Remote Tool::
Access remote data(model cases, meshes) on Github and Girder in {feelpp} applications.
http://docs.feelpp.org/user/{{ version_doc }}/using/remotedata/


== COPYING

Copyright \(C) 2020 {feelpp} Consortium. +
Free use of this software is granted under the terms of the GPLv3 License.

