#!/bin/bash

# Building ParaView 5.0.0 (Enable latest OpenGL backend)

cmake $1 -DBUILD_TESTING=OFF -DVTK_RENDERING_BACKEND=OpenGL2 -DPARAVIEW_ENABLE_CATALYST=ON -DPARAVIEW_ENABLE_PYTHON=ON -DPARAVIEW_INSTALL_DEVELOPMENT_FILES=ON -DPARAVIEW_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=$2
make -j $3
