# -*- Mode: python coding: latin-1 -*-
###  SConscript ---

#  Author(s): Christophe Prud'homme <christophe.prudhomme@ujf-grenoble.fr>
#       Date: 2007-05-25
#
#  Copyright (C) 2007 Université Joseph Fourier (Grenoble I)
#
# Distributed under the GPL(GNU Public License):
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#

Import('env')

SOURCES=['oseen.cpp',
         ]

if env['static']:
    env.StaticLibrary('lifediscr', source=SOURCES)

if env['shared']:
    env.SharedLibrary('lifediscr', source=SOURCES,LIBS=['lifecore'],LIBPATH=['../lifecore'])

