= Glossary

== boundaryelements

Free-function to apply to a mesh to retrieve the iterators over  elements touching the boundary of the mesh stored on the current processor with an face, edge or point.

== boundaryfaces

Free-function to apply to a mesh to retrieve the iterators over boundary faces of the mesh stored on the current processor.

== Cmake

The tool that configures Feel++ build environment and generate Makefiles by default.

== edges

Free-function to apply to a mesh to retrieve the iterators over the edges of the mesh stored on the current processor

== Eigen3

Eigen is a C++ template library for linear algebra: matrices, vectors, numerical solvers, and related algorithms.

== elements

Free-function to apply to a mesh to retrieve the iterators over the elements of the mesh stored on the current processor

== faces

Free-function to apply to a mesh to retrieve the iterators over the faces of the mesh stored on the current processor

== globalRank

MPI global rank of a data structure

== integrate

Free-function to define integral expressions entering the definition of integrals, linear and bi-linear forms.

== internalelements

Free-function to apply to a mesh to retrieve the iterators over  elements which are not touching with a point, edge or face the boundary of the mesh stored on the current processor

== Make

A tool that builds Feel++ code from Makefiles generated by Cmake.

== marked2elements

Free-function to apply to a mesh to retrieve the iterators over marked elements (by a string or an integer id) with marker2 of the mesh stored on the current processor

== marked3elements

Free-function to apply to a mesh to retrieve the iterators over marked elements (by a string or an integer id) with marker3 of the mesh stored on the current processor

== markededges

Free-function to apply to a mesh to retrieve the iterators over marked edges (by a string or an integer id) of the mesh stored on the current processor

== markedelements

Free-function to apply to a mesh to retrieve the iterators over marked elements (by a string or an integer id) of the mesh stored on the current processor

== markedfaces

Free-function to apply to a mesh to retrieve the iterators over marked faces (by a string or an integer id) of the mesh stored on the current processor

== marker

Marker for mesh element, faces, edges or point. Element marker are often associated to material properties

== marker2

Marker for mesh element, faces, edges or point. It is used for example to iterate over element thanks to a particular piecewise constant field

== marker3

Marker for mesh element, faces, edges or point. It is used for example to iterate over element thanks to a particular piecewise constant field

== mean

Free-function to compute the average value of a function.

== MUMPS

A parallel sparse direct solvers 

== normH1

Free-function to compute the $$H^1$$ norm of an expression

== normL2

Free-function to compute the $$L^2$$ norm of an expression

== normLinf

Free-function to compute the $$L^{\infty}$$ norm of an expression

== Pastix

PaStiX (Parallel Sparse matriX package) is a scientific library that provides a high performance parallel solver for very large sparse linear systems based on direct methods.  Numerical algorithms are implemented in single or double precision (real or complex) using LLt, LDLt and LU with static pivoting (for non symmetric matrices having a symmetric pattern).  This solver provides also an adaptive blockwise iLU(k) factorization that can be used as a parallel preconditioner using approximated supernodes to build a coarser block structure of the incomplete factors. See http://pastix.gforge.inria.fr/.

== PETSc

A library for High Performance Computing providing parallel data structures and numerical methods linear and non-linear algebraic problems arising for example PDE discretisation. PETSc is the main solver strategy provider for FEEL++.

== project

Free-function to project an expression $$e$$ over a nodal function space $$X_h$$. It would typically return the interpolant $$\Pi_h e \in X_h$$ of the expression in the function space.

== rank

MPI local rank of a data structure

== SLEPc

A library based on PETSc providing a framework to solve eigenvalue problems.

== SPD

Symmetric Positive Definite

== UMFPACK

UMFPACK /ˈʌmfpæk/ is a set of routines for solving sparse linear systems of the form Ax=b, using the Unsymmetric MultiFrontal method (Matrix A is not required to be symmetric) [source: https://en.wikipedia.org/wiki/UMFPACK]