Feel++
======

Finite Element Embedded Library in C++
--------------------------------------

Feel\++ is a unified C++ implementation of Galerkin methods (finite and spectral element methods) in 1D, 2D and 3D to solve partial differential equations.

Feel++ is

 . a versatile mathematical kernel solving easily problems using
   different techniques thus allowing testing and comparing methods, e.g. cG versus dG.
   
 . a *small* and *manageable* library which nevertheless            encompasses a wide range of numerical methods and techniques     and in particular reduced order methods such as the reduced      basis method.
   
 . a software that follows closely the mathematical abstractions
   associated with partial differential equations (PDE) and in
   particular the finite element mathematical framework and
   variational formulations.
   
 . a library that offers solving strategies that scales up to
   thousands and even tens of thousands of cores.
   
 . a library entirely in `C++` allowing to create `C++` complex
   and typically non-linear multi-physics applications currently in industry, physics and health-care.

=== Help and Support

We're always happy to help out with Feel\++ or any other questions you might have. You can ask a question or signal an issue at the Gitter Feel++ salon.

https://gitter.im/feelpp/feelpp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge[
image:https://badges.gitter.im/Join%20Chat.svg[Join the chat at https://gitter.im/feelpp/feelpp]]


=== Contribute to this documentation

You can contribute to improve this documentation on
https://github.com/feelpp/feelpp-book[GitHub].



