function(feelpp_python_normalize_module_path)
  set(_FEELPP_PYTHON_PATH_SCRIPT "\nimport os, site, sys, sysconfig\nbase = os.path.normpath('${CMAKE_INSTALL_PREFIX}')\npyver = str(sys.version_info.major) + '.' + str(sys.version_info.minor)\nplatlib = sysconfig.get_path('platlib', vars={'base': base, 'platbase': base})\ncands = []\nif platlib:\n    cands.append(platlib)\ntry:\n    cands += site.getsitepackages()\nexcept Exception:\n    pass\nseen = set()\nnorm_cands = []\nfor p in cands:\n    if not p:\n        continue\n    p = os.path.normpath(p)\n    if p in seen:\n        continue\n    seen.add(p)\n    norm_cands.append(p)\ncands = norm_cands\npreferred = [\n    os.path.normpath(base + '/lib/python3/dist-packages'),\n    os.path.normpath(base + '/lib/python' + pyver + '/dist-packages'),\n    os.path.normpath(base + '/lib/python' + pyver + '/site-packages'),\n]\nlocal_base = os.path.normpath(base + '/local')\nchoice = None\nfor pref in preferred:\n    for p in cands:\n        if p == pref or p.startswith(pref + os.sep):\n            choice = p\n            break\n    if choice:\n        break\nif choice is None:\n    for p in cands:\n        if not (p == base or p.startswith(base + os.sep)):\n            continue\n        if p == local_base or p.startswith(local_base + os.sep):\n            continue\n        choice = p\n        break\nif choice is None and platlib:\n    choice = os.path.normpath(platlib)\nif choice is None and cands:\n    choice = cands[0]\nprint(choice)\n")
  # Honor an explicit override first
  if (DEFINED PYTHON_SITE_PACKAGES)
    set(_REQ_PY_SITE "${PYTHON_SITE_PACKAGES}")
    set(_USE_REQ_PATH ON)
    if (IS_ABSOLUTE "${_REQ_PY_SITE}")
      string(FIND "${_REQ_PY_SITE}" "${CMAKE_INSTALL_PREFIX}/" _req_prefix_pos)
      if (_req_prefix_pos EQUAL -1)
        set(_USE_REQ_PATH OFF)
      else()
        set(_LOCAL_PREFIX "${CMAKE_INSTALL_PREFIX}/local/")
        string(FIND "${_REQ_PY_SITE}" "${_LOCAL_PREFIX}" _req_local_pos)
        if (_req_local_pos EQUAL 0)
          set(_USE_REQ_PATH OFF)
        endif()
      endif()
    endif()
    if (_USE_REQ_PATH)
      set(FEELPP_PYTHON_MODULE_PATH "${_REQ_PY_SITE}" PARENT_SCOPE)
      set(FEELPP_PYTHON_MODULE_PATH "${_REQ_PY_SITE}" CACHE STRING "Python module install path" FORCE)
      return()
    endif()
  endif()

  # If a value exists but points under a different prefix or under ".../local/...",
  # recompute using Python's sysconfig for the current CMAKE_INSTALL_PREFIX.
  set(_RECOMPUTE OFF)
  if (DEFINED FEELPP_PYTHON_MODULE_PATH)
    if (FEELPP_PYTHON_MODULE_PATH MATCHES "^local/")
      set(_RECOMPUTE ON)
    elseif (FEELPP_PYTHON_MODULE_PATH MATCHES "^\\.\\./")
      set(_RECOMPUTE ON)
    elseif (IS_ABSOLUTE "${FEELPP_PYTHON_MODULE_PATH}")
      string(FIND "${FEELPP_PYTHON_MODULE_PATH}" "${CMAKE_INSTALL_PREFIX}/" _prefix_pos)
      if (_prefix_pos EQUAL -1)
        set(_RECOMPUTE ON)
      else()
        set(_LOCAL_PREFIX "${CMAKE_INSTALL_PREFIX}/local/")
        string(FIND "${FEELPP_PYTHON_MODULE_PATH}" "${_LOCAL_PREFIX}" _local_pos)
        if (_local_pos EQUAL 0)
          set(_RECOMPUTE ON)
        endif()
      endif()
    endif()
  else()
    set(_RECOMPUTE ON)
  endif()

  if (_RECOMPUTE)
    if (NOT Python3_EXECUTABLE)
      # Try to find Python3 if not already available
      find_package(Python3 COMPONENTS Interpreter QUIET)
    endif()
    if (Python3_EXECUTABLE)
      execute_process(
        COMMAND ${Python3_EXECUTABLE} -c "${_FEELPP_PYTHON_PATH_SCRIPT}"
        OUTPUT_VARIABLE _ABS_PYTHON_MODULE_PATH
        OUTPUT_STRIP_TRAILING_WHITESPACE)
      if (NOT "${_ABS_PYTHON_MODULE_PATH}" STREQUAL "")
        get_filename_component(_ABS_PYTHON_MODULE_PATH "${_ABS_PYTHON_MODULE_PATH}" ABSOLUTE)
        file(RELATIVE_PATH FEELPP_PYTHON_MODULE_PATH "${CMAKE_INSTALL_PREFIX}" "${_ABS_PYTHON_MODULE_PATH}")
        set(FEELPP_PYTHON_MODULE_PATH "${FEELPP_PYTHON_MODULE_PATH}" PARENT_SCOPE)
        set(FEELPP_PYTHON_MODULE_PATH "${FEELPP_PYTHON_MODULE_PATH}" CACHE STRING "Python module install path" FORCE)
      endif()
    endif()
  endif()
endfunction()
