function(feelpp_python_normalize_module_path)
  # Honor an explicit override first
  if (DEFINED PYTHON_SITE_PACKAGES)
    set(_REQ_PY_SITE "${PYTHON_SITE_PACKAGES}")
    set(_USE_REQ_PATH ON)
    if (IS_ABSOLUTE "${_REQ_PY_SITE}")
      string(FIND "${_REQ_PY_SITE}" "${CMAKE_INSTALL_PREFIX}/" _req_prefix_pos)
      if (_req_prefix_pos EQUAL -1)
        set(_USE_REQ_PATH OFF)
      else()
        set(_LOCAL_PREFIX "${CMAKE_INSTALL_PREFIX}/local/")
        string(FIND "${_REQ_PY_SITE}" "${_LOCAL_PREFIX}" _req_local_pos)
        if (_req_local_pos EQUAL 0)
          set(_USE_REQ_PATH OFF)
        endif()
      endif()
    endif()
    if (_USE_REQ_PATH)
      set(FEELPP_PYTHON_MODULE_PATH "${_REQ_PY_SITE}" PARENT_SCOPE)
      set(FEELPP_PYTHON_MODULE_PATH "${_REQ_PY_SITE}" CACHE STRING "Python module install path" FORCE)
      return()
    endif()
  endif()

  # If a value exists but points under a different prefix or under ".../local/...",
  # recompute using Python's sysconfig for the current CMAKE_INSTALL_PREFIX.
  set(_RECOMPUTE OFF)
  if (DEFINED FEELPP_PYTHON_MODULE_PATH)
    if (FEELPP_PYTHON_MODULE_PATH MATCHES "^local/")
      set(_RECOMPUTE ON)
    elseif (IS_ABSOLUTE "${FEELPP_PYTHON_MODULE_PATH}")
      string(FIND "${FEELPP_PYTHON_MODULE_PATH}" "${CMAKE_INSTALL_PREFIX}/" _prefix_pos)
      if (_prefix_pos EQUAL -1)
        set(_RECOMPUTE ON)
      else()
        set(_LOCAL_PREFIX "${CMAKE_INSTALL_PREFIX}/local/")
        string(FIND "${FEELPP_PYTHON_MODULE_PATH}" "${_LOCAL_PREFIX}" _local_pos)
        if (_local_pos EQUAL 0)
          set(_RECOMPUTE ON)
        endif()
      endif()
    endif()
  else()
    set(_RECOMPUTE ON)
  endif()

  if (_RECOMPUTE)
    if (NOT Python3_EXECUTABLE)
      # Try to find Python3 if not already available
      find_package(Python3 COMPONENTS Interpreter QUIET)
    endif()
    if (Python3_EXECUTABLE)
      execute_process(
        COMMAND ${Python3_EXECUTABLE} -c "\nimport sys, sysconfig, site, os\nbase='${CMAKE_INSTALL_PREFIX}'\ncands=[]\ntry:\n    cands+=site.getsitepackages()\nexcept Exception:\n    pass\ncands.append(sysconfig.get_path('platlib', vars={'base': base, 'platbase': base}))\npreferred=[base + '/lib/python3/dist-packages']\nchoice=None\nfor p in cands:\n    if not p: continue\n    if any(p.startswith(pr) for pr in preferred):\n        choice=p; break\nif choice is None:\n    for p in cands:\n        if p.startswith(base+os.sep) and not p.startswith(base+os.sep+'local'+os.sep):\n            choice=p; break\nif choice is None:\n    choice=cands[0]\nprint(choice)\n"
        OUTPUT_VARIABLE _ABS_PYTHON_MODULE_PATH
        OUTPUT_STRIP_TRAILING_WHITESPACE)
      if (NOT "${_ABS_PYTHON_MODULE_PATH}" STREQUAL "")
        get_filename_component(_ABS_PYTHON_MODULE_PATH "${_ABS_PYTHON_MODULE_PATH}" ABSOLUTE)
        file(RELATIVE_PATH FEELPP_PYTHON_MODULE_PATH "${CMAKE_INSTALL_PREFIX}" "${_ABS_PYTHON_MODULE_PATH}")
        set(FEELPP_PYTHON_MODULE_PATH "${FEELPP_PYTHON_MODULE_PATH}" PARENT_SCOPE)
        set(FEELPP_PYTHON_MODULE_PATH "${FEELPP_PYTHON_MODULE_PATH}" CACHE STRING "Python module install path" FORCE)
      endif()
    endif()
  endif()
endfunction()
