== CMAKE
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

CMake is a tool that helps simplifying the build process for development projects across different platforms. CMake automates the generation of buildsystems such as _**Makefiles**_ and Visual Studio project files.

=== Building with CMake   
Setting up CMakeLists.txt files will not immediately allow you to build your project. CMake is just a cross platform wrapper around more traditional build systems. In the case of linux, this means make. A quick preprocessing step will convert your CMakeLists.txt description into a traditional make build system automatically. One nice and highly recommended feature of CMake is the ability to do out of source builds. This way you can build all your object files (.o), various temporary files, and even the binary executables without cluttering up your source tree.   

Below is a CMakeLists.txt file for our simple project.
[source,sh]
----
#set(CMAKE_CXX_COMPILER /usr/bin/clag++ 3.6.0)
cmake_minimum_required(VERSION 2.8.9 FATAL_ERROR)
project(operation)

# Create a library called "operationlib" which includes the source file "operation.cxx".
# The extension is already found. Any number of sources could be listed here.

option(USE_SHARED "use a shared library" OFF)
            
if(USE_SHARED)
add_library(operationlib SHARED operation.cpp operation.h)  
# Make sure the compiler can find include files for our operation library
# when other libraries or executables link to operation
target_include_directories (operationlib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

else()
add_library(operationlib STATIC operation.cpp operation.h)
target_include_directories (operationlib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
endif()

# Add executable called "operation" that is built from the source files "operation.cxx"". The extensions are automatically found.
add_executable(operation main.cpp)

# Link the executable to the operation library. Since the operation library has public include directories we will use those link directories when building operation
target_link_libraries(operation LINK_PUBLIC operationlib)   
----

To use out of source builds, create a build directory (technically, this can be anywhere, but for the sake of simplicity, we will use the top-level project folder). Next, go into your build directory and run cmake pointing it to the directory of the top-level CMakeLists.txt. For example, for our simple project: 

`cd src`: Takes us to the src directory (containing the source code). +
`mkdir build`: Creates the build directory. +   
`cd build`: Takes us to build directory. +   
`cmake ..`: Runs cmake pointing it to the src directory.

Then run the command. 
[source,sh]
----
make
----

Remember to be in your build directory and point cmake only to the directory containing the top-level CMakeLists.txt file (not the file itself). If aeverything goes well, cmake will process your CMakeLists.txt files, find the location of all libraries and include paths, and display information about the configuration including a traditional _**Makefile**_ in your build directory.

This only touches the surface of what CMake can do. Check out the link:http://www.cmake.org/Wiki/CMake[CMake Wiki] for more info.
