:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Git

Git is the open source distributed version control system that facilitates GitHub activities on your laptop or desktop. The basic commands to get started with git are: 

Clone an existing repository:
```
$ git clone ssh://user@domain.com/repository_name.git
```

Create a new local repository : 
```
$ git init
```   

Add a new file:
```
$ git add <file>
```  

Download changes and directly merge/integrate into HEAD:    
```
$ git pull
```   

Publish local changes on a remote: 
```
$ git push
```   

Click link:http://www.git-tower.com/blog/git-cheat-sheet/[here] for more information about git commands.

== Github

GitHub is a web-based Git repository hosting service. It offers all of the distributed revision control and source code management (SCM) functionality of Git as well as adding its own features.

If you are new to github, these are the basic things you need to know to get started with GitHub:
   
 -  Creating a personal account: +
The first step to using GitHub is to set up a personal link:https://help.github.com/articles/signing-up-for-a-new-github-account/[GitHub account]. If you already have an account, visit link:https://github.com/[github.com] and sign in.
 
 - Creating a new repository: +
In your account page of Github, the Repositories tab allows you to create a new repository with the `New` button. Once you have created it, you can clone it locally using the `git clone` command. 

- Adding files +
Now that we have a Git repo up and running, we need to add some files for it to track. Now remember, git doesn't just automatically track every file in the directory as soon as you put it there. It only tracks the files that you tell it to, a file can be either tracked or untracked. Since a commit is not automatically done as soon as we add files to this folder, they will be marked as untracked files. To add files to a repository, type the following command: 
[source,sh]
----
git add file_Name
----
   
- Making a commit: +
After having added files to our empty Git repo (we used the `git add` command to stage those files), the next step is to commit them. When committing, an important step is to add a meaningful description of the changes done to the files. To add a commit message, in the command line, write: 

[source,sh]
----
git commit -m "Added a new file"
----   

- Checking differences: +
Most of the time, you will be adding all of your modified files to your next commit. But there are times when you might want to check what has changed before you commit the files:

[source,sh]
----
git diff
----

Inside the index file, it will show you the changes in two ways.

If you have a branch set up to track a remote branch, you can use the `git pull` command to automatically fetch and merge a remote branch into your current branch. 

- Pushing to Your Remotes: +
When you want to share your modifications, you can push them upstream. The command for this is simple: 

[source,sh]
----
git push [remote-name] [branch-name].    
----

> **NOTE:** `git remote rename file_name` and `git remote rm file_name` will rename and remove the given file respectively from a repo.


- Pull requests: +
Pull requests let you tell others	about changes you've pushed to a repository on GitHub. The request, printed to the standard output, summarizes the changes and indicates from where they can	be pulled.

[source,sh]
----
git request-pull [-p] <start> <url> [<end>]
----

The upstream project is expected to have the commit named by `<start>` and the output asks it to integrate the changes you made since that commit, up to the commit named by `<end>`, by visiting the repository named by `<url>`.     

* Issues: +
Issues are a way to keep track of tasks, enhancements, and bugs for your projects. They can be shared and discussed with the rest of your team. Most software projects have a bug trackers. The GitHub equivalent is called Issues, and has its own section in every repository. See how to create an issue link:https://help.github.com/articles/creating-an-issue/[here]. A title and description describe what the issue is all about.


* Notifications: +
Notifications are the way GitHub uses to keep up to date with your Issues. You can use them to find out about new issues on repositories, or just to know when someone needs your input to move forward on an issue. There are two ways to receive notifications: via email, and via the web. You can link:https://help.github.com/articles/configuring-notification-emails/[configure] how you receive notifications in your settings. If you plan on receiving a lot of notifications, we like to recommend that you receive web + email notifications for Participating and web notifications for Watching.   

* Milestones: +
Milestones are used to track the progress of similar issues and pull requests as they are opened and closed over time. At a glance, you can easily see the progress of work in a the lifetime of a milestone. Once you have collected a lot of issues, you may find it hard to find the important ones. link:https://guides.github.com/features/issues/[Milestones, labels, and assignees] are great features to filter and categorize issues.

For quick reference, visit link:https://guides.github.com/[GitHub guides]. This will give you the basic knowledge to get started into GitHub.