== MAKEFILES
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

=== Compiling by hand 

The initial command to compile our files and obtain an executable is the following:

[source,sh]
----
g++ main.cpp operation.cpp -o operation
----

To simplify the compilation of several source files, project developers generally use Makefiles. They are specially formatted files that you can use with the make utility. They will help in automating the build steps of your projects.

It is recommended (actually mandatory for Feel++) to separate source code and build directory.

=== Creating a Makefile

A typical *Makefile* is laid out as follows:
[source,makefile]
----
target: dependencies
[tab] system command
----

Here is a simple Makefile to compile the files from our simple project:
[source,makefile]
----
all: operation 
operation: main.o operation.o
	g++ main.o operation.o -o operation 

main.o: main.cpp
	g++ -c main.cpp

operation.o: operation.cpp
	g++ -c operation.cpp

clean:
	rm -rf *.o 
----

==== The make utility
The `make`
command will look for a file named `Makefile` in the current directory, and execute the `all` target.

If you have several makefiles, then you can execute them with the command:   
[source,makefile]
----
make -f MyMakefile
----

There are several other switches to the make utility. For more information, please refer to the manual of `make`:
```
man make
```


Visit link:http://www.gnu.org/software/make/manual/make.html[GNU make] for more informations about makefile.

