#!/bin/bash
ARCH=`uname -m`
SITE=`hostname`
OS_VERSION=debian-sid
WORK_DIR=$HOME/sources/
MAKE_ARGS="-j5"
PARALLEL="5"
COMMON="ctest -VV -S $HOME/Devel/FEEL/feelpp.git/cmake/dashboard/testsuite.cmake,FEELPP_CTEST_CONFIG=feelpp.site.$site.cmake,FEELPP_WORK_DIR=$WORK_DIR,FEELPP_ENABLE_CRB_ALL=ON,FEELPP_MAKE_ARGS=$MAKE_ARGS,CTEST_BUILD_FLAGS=-j$PARALLEL,CTEST_PARALLEL_LEVEL=$PARALLEL,FEELPP_SITE=$SITE,FEELPP_MODE=$1,FEELPP_BUILD_STRING=$OS_VERSION-$ARCH"
#$COMMON-gcc-4.4.6,FEELPP_CXX=g++-4.4,FEELPP_EXPLICIT_VECTORIZATION=novec
#$COMMON-gcc-4.4.6,FEELPP_CXX=g++-4.4,FEELPP_EXPLICIT_VECTORIZATION=SSE2
#$COMMON-gcc-4.5.2,FEELPP_CXX=g++-4.5,FEELPP_EXPLICIT_VECTORIZATION=novec
if [ -x /usr/bin/g++-4.5 ]; then
    $COMMON-gcc-4.5.3,FEELPP_CXX=g++-4.5,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=OFF
#    $COMMON-gcc-4.5.3-mpi,FEELPP_CXX=g++-4.5,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=ON
fi
if [ -x /usr/bin/g++-4.6 ]; then
    $COMMON-gcc-4.6.2,FEELPP_CXX=g++-4.6,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=OFF
    $COMMON-gcc-4.6.2-mpi,FEELPP_CXX=g++-4.6,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=ON
fi
if [ -x /usr/bin/g++-4.7 ]; then
    $COMMON-gcc-4.7.0,FEELPP_CXX=g++-4.7,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=OFF
    $COMMON-gcc-4.7.0-mpi,FEELPP_CXX=g++-4.7,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=ON
fi

if [ -x /usr/bin/clang-3.1 ]; then
#    $COMMON-gcc-4.7.0,FEELPP_CXX=clang-3.1,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=OFF
    $COMMON-clang-3.1-mpi,FEELPP_CXX=clang-3.1,FEELPP_EXPLICIT_VECTORIZATION=SSE2,FEELPP_ENABLE_MPI_MODE=ON
fi
