name: Deploy Doxygen 

on: 
  workflow_dispatch:
  push:
    branches:
      - develop 

jobs:
#  docs:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: buildkite/trigger-pipeline-action@v1.2.0
#      env:
#        BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
#        PIPELINE: "feelpp/cemosis-docs"
#        COMMIT: "HEAD"
#        BRANCH: "master"
#        MESSAGE: ":github: Triggered from a GitHub Action by Holo3 Project"
  build:
    runs-on: self-ubuntu-24.04
    if: "github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'doc skip')"
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: false
        lfs: 'true'
    - name: Initialize submodules
      run: git submodule update --init --recursive
#    - name: Update Dependencies
#      run: |
#        sudo apt install -y gpg
#        wget -qO - http://apt.feelpp.org/apt.gpg | gpg --dearmor > feelpp.gpg
#        sudo install -o root -g root -m 644 feelpp.gpg /etc/apt/trusted.gpg.d
#        echo "deb [signed-by=/etc/apt/trusted.gpg.d/feelpp.gpg] http://apt.feelpp.org/ubuntu focal latest" | sudo tee -a /etc/apt/sources.list.d/feelpp.list
#        rm -f feelpp.gpg 
#        sudo apt update
#        sudo apt --reinstall install -y libfeelpp1 libfeelpp-dev feelpp-tools doxygen graphviz
    - name: Configure Doxygen Preset
      run: cmake --preset doxygen -DDOXYGEN=/nvme0/prudhomm/local/doxygen/bin/doxygen -DDOXYGEN_EXECUTABLE=/nvme0/prudhomm/local/doxygen/bin/doxygen
    - name: Build Doxygen
      run: cmake --build --preset doxygen --target doxygen
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/doxygen/doc/api/html # The folder the action should deploy.
