name: Feelpp PKG Containers
run-name: "PKG Containers Feel++ [ ${{ inputs.flavor }}/${{ inputs.dist }} ]"
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Flavor to build'
        required: true
        default: 'ubuntu'
        type: choice
        options:
        - 'ubuntu'
        - 'debian'
        - 'spack'
      dist:
        description: 'Distribution to build'
        required: true
        default: 'jammy'
        type: choice
        options:
        - 'jammy'
        - 'focal'
        - 'noble'
        - 'bullseye'
        - 'bookworm'
        - 'testing'
        - 'sid'
        - 'openmpi'
        - 'mpich'
      version:
        description: 'Version of Feel++ packages'
        required: false
        type: string
        default: ''
      docker:
        description: 'Build docker image'
        required: false
        default: "true"
        type: choice
        options:
        - 'true'
        - 'false'
      apptainer:
        description: 'Build apptainer image'
        required: false
        default: "1.3.3"
        type: choice
        options:
        - '1.2.2'
        - '1.3.3'
        - 'false'
      parallel:
        description: 'Number of parallel jobs'
        required: false
        default: "20"
        type: string
      skip:
        description: 'Skip build'
        required: false
        default: ""
        type: string
      continue-on-error:
        description: 'Continue on error'
        required: false
        default: "false"
        type: string


env:
  DEB_BUILD_OPTIONS: parallel=${{ inputs.parallel || 20 }}
  CXX: clang++
  CC: clang

jobs:
    version:
        uses: ./.github/workflows/version.yml
        with:
            continue-on-error: "false"
        secrets: inherit

    pkg-docker:
        if: ${{ inputs.docker == 'true' }}
        needs: version
        uses: ./.github/workflows/pkg-docker.yml
        with:
          dist: ${{ inputs.dist }}
          flavor: ${{ inputs.flavor }}
          parallel: ${{ inputs.parallel }}
          skip: ${{ inputs.skip }}
          version: ${{ inputs.version || needs.version.outputs.version }}

          continue-on-error: ${{ inputs.continue-on-error }}
        secrets: inherit

    pkg-apptainer:
        if: ${{ inputs.apptainer != 'false' }}
        needs: [pkg-docker,version]
        uses: ./.github/workflows/pkg-apptainer.yml
        with:
          dist: ${{ inputs.dist }}
          flavor: ${{ inputs.flavor }}
          parallel: ${{ inputs.parallel }}
          docker: ${{ needs.pkg-docker.outputs.image }}
          docker-dev: ${{ needs.pkg-docker.outputs.image-dev }}
          apptainer: ${{ inputs.apptainer }}
          skip: ${{ inputs.skip }}
          version: ${{ inputs.version || needs.version.outputs.version }}
          continue-on-error: ${{ inputs.continue-on-error }}
        secrets: inherit