name: Feelpp PKG CI

on:
  push:
    branches:
 #      - develop
     - 2259-add-script-to-get-feelpp-version
  workflow_dispatch:
    inputs:
      parallel:
        description: 'Number of parallel jobs'
        required: false
        default: "20"
        type: string
      skip:
        description: 'Skip build'
        required: false
        default: ""
        type: string
      enable-debian:
        description: 'Enable debian distros'
        required: false
        default: 'none'
        type: choice
        options:
        - 'all'
        - 'bookworm'
        - 'testing'
        - 'sid'
        - 'none'
      enable-ubuntu:
        description: 'Enable ubuntu distros'
        required: false
        default: 'noble'
        type: choice
        options:
        - 'all'
        - 'noble'
        - 'jammy'
        - 'focal'
        - 'none'
      enable-spack:
        description: 'Enable spack distros'
        required: false
        default: 'none'
        type: choice
        options:
        - 'all'
        - 'mpich'
        - 'openmpi'
        - 'none'
      enable-apptainer:
        description: 'Enable apptainer distros'
        required: false
        default: 'apptainer'
        type: choice
        options:
        - 'apptainer'
        - 'none'
      enable-docker:
        description: 'Enable docker distros'
        required: false
        default: 'docker'
        type: choice
        options:
        - 'docker'
        - 'none'

jobs:
  version:
    uses: ./.github/workflows/version.yml
    with:
        continue-on-error: "false"
    secrets: inherit

  version-print:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Print outputs from version workflow
        run: |
          echo "Feel++ Main Version: ${{ needs.version.outputs.main_version }}"
          echo "Feel++ Extra Version: ${{ needs.version.outputs.extra_version }}"
          echo "Feel++ Version: ${{ needs.version.outputs.version }}"
  pkg-factory:
    uses: ./.github/workflows/pkg-factory.yml
    with:
        parallel: "${{ inputs.parallel || '20' }}"
        enable-debian: "${{ inputs.enable-debian || 'all' }}"
        enable-ubuntu: "${{ inputs.enable-ubuntu || 'all' }}"
        enable-spack: "${{ inputs.enable-spack || 'none' }}"
        enable-apptainer: "${{ inputs.enable-apptainer || 'apptainer' }}"
        enable-docker: "${{ inputs.enable-docker || 'docker' }}"
        skip: "${{ inputs.skip || '' }}"
    secrets: inherit

  pkg-factory-2:
    name: Packaging Factory 2
    runs-on: ubuntu-latest
    needs: pkg-factory
    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          console.log(${{ toJson(needs.pkg-factory.outputs.matrix) }});

  build:
    needs: [pkg-factory,version]
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.pkg-factory.outputs.matrix) }}
    uses: ./.github/workflows/pkg-dist.yml
    with:
        dist: "${{ matrix.dist }}"
        flavor: "${{ matrix.flavor }}"
        parallel: "${{ inputs.parallel || '20' }}"
        skip: "${{ inputs.skip || '' }}"
        docker: "${{ matrix.docker }}"
        apptainer: "${{ matrix.apptainer }}"
        continue-on-error: "${{ matrix.continue-on-error }}"
        version: "${{ matrix.version }}"
        feelpp-version: "${{ needs.version.outputs.version }}"
        feelpp-main-version: "${{ needs.version.outputs.main_version }}"
        feelpp-extra-version: "${{ needs.version.outputs.extra_version }}"
    secrets: inherit

