Download Feel++ sources
=======================
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Getting the source via an archive

Feel++ is distributed as tarballs following each major release. The tarballs are available at:

https://github.com/feelpp/feelpp/releases

Download the latest tarball, then uncompress it with:

----
tar -xzf feelpp-X.YY.0.tar.gz
cd feelpp-X.YY.0
----

Eventually, you can move to the compilation and installation step via the CMake procedure.

## Getting the source via Git

Alternatively, you can download the sources of Feel++ directly from https://github.com/feelpp/feelpp[the source repository], thanks to Git.

You can either download them anonymously or with your
Github account. As an open-source project, we strongly suggest you to create an account and take part of the project by sharing your ideas, developments or suggestions. For now, if you want to get the sources without an account, open a command-line and type:

----
git clone --depth=xx https://github.com/feelpp/feelpp.git
----

with `xx` the number of last commits you want to save.
`xx=1` will allow you to reduce the time to clone.
Then you can go to the Feel++ top directory with:

----
  cd feel
----

You should obtain a directory tree such as:

----
applications/   # functional applications
benchmarks/  # applications under test
cmake/   # do not touch, used for compilation
contrib/
data/   # geometric data
doc/   # tutorial and examples
feel/   # Feel++ library
ports/   # used for Mac OS X installation
quickstart/   # basic examples
research/   # research projects using Feel++
scripts/ # various scripts
testsuite/ # Feel++ unit tests testsuite
CMakeLists.txt   # the file for cmake to build, do not modify
...
----
