Feel++ on Linux
===============
:toc:
:toc-placement: macro
:toclevels: 2

toc::[]

== Debian

Debian is the platform of choice for Feel+\+, it was developed mainly on it. The commands to install Feel++ on Debian are:

----
  sudo apt-get update
  sudo apt-get install feel++-apps libfeel++-dev feel++-doc
----

The interested user is encouraged to follow the Feel\++ PTS page:

* Feel++, http://packages.qa.debian.org/f/feel%2B%2B.html[Debian Packages Tracking System]

At the moment Feel++ compiles and is available on the following Debian platforms:

* Feel++: https://buildd.debian.org/status/package.php?p=feel%2b%2b[Build results]

##  Ubuntu
Feel++ has its own PPA, checkout https://launchpad.net/~feelpp/+archive/ppa[feelpp ppa for Trusty, Saucy and Precise].

The interested user might want to look at the following Ubuntu Launchpad Feel\++ page: https://launchpad.net/ubuntu/\+source/feel++[Ubuntu Source
  Page for all Ubuntu versions].

=== Ubuntu 12.04 - Precise Pangolin

This section is outdated.

----
	sudo add-apt-repository -y ppa:feelpp/ppa
	sudo add-apt-repository -y ppa:feelpp/petsc
	sudo add-apt-repository -y ppa:mapnik/boost-backports-1-54
	sudo add-apt-repository -y ppa:kalakris/eigen
	sudo apt-get -qq update
	sudo apt-get install -qq libboost1.54-all-dev mpi-default-dev mpi-default-bin libeigen3-dev libpetsc3.4.2-dev libcln-dev petsc-dev libxml2-dev gmsh bison flex doxygen doxygen-latex transfig imagemagick libtbb-dev libann-dev libglpk-dev automake libtool
	sudo apt-get install feel++-apps libfeel++-dev
----

It allows us also to provide a recent version to compile the Feel++ projects on https://travis-ci.org/feelpp/feelpp[Travis-ci], which is a continuous integration tool. The installation procedure is currently https://github.com/feelpp/feelpp/blob/develop/.travis.yml[as follows].

=== Ubuntu 14.04 - Trusty Tahr

----
	sudo add-apt-repository ppa:feelpp/ppa
	sudo apt-get -qq update
	sudo apt-get install feel++-apps libfeel++-dev
----

Ubuntu 14.04 does not support C+\+14 at this time, however a ppa providing clang and gcc versions that do support C++14, is available.

[source,sh]
----
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install g++-4.9
----

=== Configuration

First of all, you have to install dependencies:

----
 sudo apt-get install git libboost1.55-all-dev petsc-dev libgmsh2 libgmsh-dev paraview gcc-4.9 clang-3.6  libopenmpi1.6 libopenmpi-dev libcln-dev libxml2-dev automake libtool cmake cmake-curses-gui libgoogle-glog-dev libeigen3-dev
----

=== Cmake

Then, in your chosen build directory, you have to run the cmake command: 
[source,sh]
----
cmake /where/is/feelpp/ -DCMAKE_CXX_COMPILER=`which clang++-3.6` -DCMAKE_C_COMPILER=`which clang-3.6` -DFEELPP_MINIMAL_CONFIGURATION=ON -DFEELPP_ENABLE_NLOPT=OFF
----

=== Compilation

And evntually compile the library and sample applications:
[source,sh]
----
make
----

You should consider running parallel compilation (`make -j 12` for example).

==== Installation
You can then install Feel++ in your system. By default, the target directory will be `/usr/local`, be sure to change it with the `-DCMAKE_INSTALL_PREFIX=...` option if you do not have administration rights. +
To perform the installation, you have several options listed below:
```
# Only builds and install the feelpp library
make install-feelpp-lib

# Builds and install the feelpp library and sample applications
make install-feelpp-base

# Builds and install the feelpp library and all the applications (This might take some time)
make install
```